### ISSUE TITLE
Update SA1004 (DocumentationLinesMustBeginWithSingleSpace) to support multi-line comments

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1001]
SA1004 was enabled as part of #983, but support for multi-line comments such as the following is not tested:

```csharp
/**
 *<summary>
 *text
 *</summary>
 */
```

Tests should be added for this functionality, which will likely reveal bugs in the current handling of these comments.

**Comment by vweijsters** [comment]
Grabbing this
