### ISSUE TITLE
GeneratedCodeAnalysisExtensions.IsGeneratedDocument: Filename matching is done other then in summary documented

### ISSUE THREAD

**Issue by StefanSchoof** [DotNetAnalyzers/StyleCopAnalyzers#1021]
The documentation of GeneratedCodeAnalysisExtensions.IsGeneratedDocument says:
The code is contained in a file with a name matching certain patterns (case-insensitive):
 * service.cs
 * TemporaryGeneratedFile_*.cs
 * assemblyinfo.cs
 * assemblyattributes.cs
 * *.g.cs
 * *.g.i.cs
 * *.designer.cs
 * *.generated.cs
 * *.assemblyattributes.cs

see https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers/GeneratedCodeAnalysisExtensions.cs#L76

But the regex in the IsGeneratedFileName does only check for *.designer.cs https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers/GeneratedCodeAnalysisExtensions.cs#L185

**Comment by sharwell** [comment]
Looks like we failed to update the comment when we merged #874. Definitely my fault on this one!
