### ISSUE TITLE
Empty files should not be analyzed

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1040]
Currently some files are being analyzed when they are completely empty (an example appears in #1039).

If a file consists of nothing but whitespace and/or newlines, no warnings should be reported.

**Comment by pdelvo** [comment]
grabbed

**Comment by sharwell** [comment]
@pdelvo This is as good a time as any to move this analysis up into `DiagnosticVerifier`.

**Comment by pdelvo** [comment]
I'm going to add a few tests for auto generated files

**Comment by sharwell** [comment]
I'm thinking if `VerifyCSharpDiagnosticAsync` is called and the expected results contain one or more diagnostic starting with `SA` or `SX`, we could automatically run a second test on the same input with `/// <auto-generated>` added to the beginning and ensure that the result:

1. Does not include anything from the expected results which starts with `SA` or `SX`.
2. Does include everything else from the expected results, but with the locations incremented by one line.
