### ISSUE TITLE
SA1513 is unaware of expression-bodied functions

### ISSUE THREAD

**Issue by RalfKoban** [DotNetAnalyzers/StyleCopAnalyzers#1049]
Hi,

when I use the StyleCop.Analyzers (1.0.0-beta001), I get an SA1513 for expression-bodied funcions, e.g. as following:

        protected override IEnumerable<AttributeTargets> ValidAttributeTargets() => new[]
                                                                                        {
                                                                                            AttributeTargets.Assembly,
                                                                                            AttributeTargets.Class,
                                                                                            AttributeTargets.Struct,
                                                                                            AttributeTargets.Constructor,
                                                                                            AttributeTargets.Method,
                                                                                            AttributeTargets.Property,
                                                                                            AttributeTargets.Event
                                                                                        };

**Comment by sharwell** [comment]
You are on a good roll of reporting issues you noticed. This is a big help to us. :+1: 

:bulb: If this is a case where a diagnostic was reported but you didn't expect it, can you include the location of the reported diagnostic?

:bulb: If this is a case where a diagnostic should be reported but isn't, can you include a description of the location where you expected to see it?

:bulb: If this is a code fix that changed code in a way you didn't expect, can you include a sample showing the expected output of the code fix, and another showing the actual output of the code fix?

**Comment by RalfKoban** [comment]
Hi, the issue here is that I get the SA1513 for that semicolon on the closing } brace. I would not expect to get that, because an empty line follows that };

**Comment by sharwell** [comment]
Thanks! :smile:
