### ISSUE TITLE
New rule proposal: Documentation output should be enabled

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1053]
**Category:** Documentation
**Title:** Documentation output should be enabled (could change)
**Description:** When a project is configured to not produce an XML documentation file with the output (this is the default), the semantics of documentation comments are not checked. This quickly results in several other problems, including the following:

* #1012 
* #1050 
* dotnet/roslyn#2773

**Comment by pdelvo** [comment]
Sounds like a good idea. And enabling documentation does not have any negative sideaffect you cant easily suppress.
