### ISSUE TITLE
Proposal: Permanently disable rule SA1409

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1058]
Rule SA1409 (RemoveUnnecessaryCode) has two characteristics which make it a particularly poor rule for StyleCopAnalyzers:

* It is poorly defined (what is or is not "necessary"?)
* It is largely a semantic rule as opposed to a syntax-based style rule

I propose rule SA1409 be permanently disabled, and allow other tools which focus on semantics (e.g. a future "FxCopAnalyzers") to pick up this diagnostic at a later time.

**Comment by Noryoko** [comment]
I agree. This should be handled by something like FxCopAnalyzers.

**Comment by pdelvo** [comment]
:+1:
