### ISSUE TITLE
SA1402 does not check file name

### ISSUE THREAD

**Issue by pdelvo** [DotNetAnalyzers/StyleCopAnalyzers#1072]
SA1402 should not only check that only one class is in a file but it should also verify that the name of the class matches the file name. We actually do have a [violation](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers/Helpers/DocumentationCommentExtensions.cs) ourself.

**Comment by sharwell** [comment]
This is closely related to #953.

**Comment by sharwell** [comment]
I'm going to close this as a duplicate of #169, #158, #157, and/or #153.

It might make sense to propose a new rule as a more direct approach to catching this problem.
