### ISSUE TITLE
SA1515 fires after some directives when it shouldn't

### ISSUE THREAD

**Issue by bmenees** [DotNetAnalyzers/StyleCopAnalyzers#1083]
The following code raises SA1515 (Single-line comment must be preceded by blank line) errors when it shouldn't.  It raises them for the "// Inside region", "// After region", and "// After pragma" comments even though there are blank lines before them.  It's interesting that it does _not_ have this problem for the "// After if" and "// After endif" comments.

```C#
#region Test

// Inside region
using System;

#endregion

// After region
#pragma warning restore 1234

// After pragma
using System.Reflection;

#if DEBUG

// After if
using System.Resources;

#endif

// After endif
using System.Runtime.InteropServices;

**Comment by sharwell** [comment]
Hi @bmenees, welcome to the project and to GitHub! :smile: 

This should be pretty easy to reproduce with that example. I've marked it **up for grabs**.

**Comment by bmenees** [comment]
Thanks for the quick turnaround on this!

And separately, thanks for your work on ANTLR 4 and its C# target.  I use and enjoy those too!  :-)
