### ISSUE TITLE
QUESTION: Can I configure a report to be generated after build with list of violations?

### ISSUE THREAD

**Issue by gep13** [DotNetAnalyzers/StyleCopAnalyzers#1090]
Similar to what could be done with standalone StyleCop?

**Comment by sharwell** [comment]
Right now you cannot directly do this. If you create a custom build logger, you can present the errors in a customized manner. For example, here's how [AppVeyor presents style violations](https://ci.appveyor.com/project/sharwell/stylecopanalyzers/build/1.0.1082/messages).

**Comment by sharwell** [comment]
I'm closing this, since even if it were a new feature it would be independent of this project (it would be a generalized reporting tool for MSBuild output, which supported filtering by the warning/error ID).

**Comment by gep13** [comment]
@sharwell thanks for getting back to me!  I am a little unclear though...

Are you saying that AppVeyor has created a custom build logger, and is extracting the messages that are part of the build log, or that you have added something into the AppVeyor build to extract these?

Can you point me in a direction of where to start with a custom build logger?  Thanks!

**Comment by roadz99** [comment]
Tfs build can do this too (report all build warnings).

**Comment by sharwell** [comment]
@gep13 AppVeyor created their own build logger. I'm not sure if it's open source or not.

**Comment by gep13** [comment]
@FeodorFitsner can you comment on this? Thanks!

**Comment by FeodorFitsner** [comment]
Right, AppVeyor has its own custom MSBuild event logger [using this API](http://www.appveyor.com/docs/build-worker-api).

**Comment by gep13** [comment]
@FeodorFitsner gotcha.  Is the custom logger that you have written open source, i.e. the actual parsing of the MSBuild Log?

**Comment by FeodorFitsner** [comment]
It's not open-source, but it's trivial. You don't have to parse anything - the process is described in details here: https://msdn.microsoft.com/en-us/library/ms171471.aspx

Let me know if you have any questions.

**Comment by gep13** [comment]
@FeodorFitsner thank you, I will take a look.
