### ISSUE TITLE
Namespace ordering w.r.t. `global::`

### ISSUE THREAD

**Issue by tristal** [DotNetAnalyzers/StyleCopAnalyzers#1092]
Hi,

The latest release changed the order convention for namespaces using the `global::` prefix.  Previously the order was based as if the `global::` did not exist -- e.g.

```
using System;

using Newtonsoft.Json;

using global::OpenSource.Stuff;
```

After updating to the latest (beta3), the ordering now takes into account `global::`, thus is now requiring:

```
using System;

using global::OpenSource.Stuff;

using Newtonsoft.Json;
```

Before I go ahead and update our codebase to adhere to this change, is this an expected change -- or an overlooked case for the rule?

**Comment by sharwell** [comment]
This was an expected change, which was discussed in a [comment thread in the diff for #896](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/pull/896#discussion_r32060359). It was essentially decided based on the fact that Visual Studio's organize usings feature uses the order that we are now enforcing.

**Comment by tristal** [comment]
:+1:
