### ISSUE TITLE
GeneratedCodeAttribute

### ISSUE THREAD

**Issue by mudnug** [DotNetAnalyzers/StyleCopAnalyzers#1094]
Is there any intention to ignore classes decorated with System.CodeDom.Compiler.GeneratedCode? I think CodeAnalysis will "suppress results from generated code" but it seems StyleCopAnalyzer's isn't setup to do the same.

**Comment by sharwell** [comment]
As of right now, there is not. We considered it as part of #792 (and that pull request originally did skip them). However, this exclusion results in a tremendous performance impact on analyzers that run all the time as opposed to running only at build time.

The current file-header-based exclusion mechanism is extremely efficient (it doesn't even appear in profiler traces), so the only way we would look back at attribute-based exclusions is if someone proves that such an exclusion could offer similar performance characteristics as what we have now.
