### ISSUE TITLE
Namespace rules

### ISSUE THREAD

**Issue by paulomorgado** [DotNetAnalyzers/StyleCopAnalyzers#1097]
This code:

    using System.Globalization; // SA1200
    using System.Threading; // SA1200
    namespace Nbsi.Dei.Goit.Web // SA1516
    {
        using System;
        using System.Diagnostics.CodeAnalysis;
        using System.Linq;
        using System.Web;
        using System.Web.Http;
        using System.Web.Mvc;
        using System.Web.Optimization;
        using System.Web.Routing;

reports warnings as stated in the comments.

However, there's no fix offered for SA1200.

**Comment by Maxwe11** [comment]
And what wrong here?

**Comment by sharwell** [comment]
Closing as a duplicate :smile:
