### ISSUE TITLE
Code fix: SA1203 (ConstantsMustAppearBeforeFields)

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1104]
Implement a code fix for #63.

**Comment by hvanbakel** [comment]
Grabbed

**Comment by sharwell** [comment]
:+1: If you aren't familiar with the details of this rule already, make sure to read through the comments in #1123. I can say the actual StyleCop rules surprised me. :ghost:

**Comment by hvanbakel** [comment]
Thats about SA1204, I'm implementing SA1203? That's just, a const field should be defined before any non const fields? That's also how the diagnostic is implemented?

**Comment by sharwell** [comment]
It turned out several rules were affected. The details are in the comments of #1123 and you can see the overall impact in #1128.
