### ISSUE TITLE
SA1202 (Public methods must come before private) conflicts with SA1204 (Static methods must appear before instance methods)

### ISSUE THREAD

**Issue by oatkins** [DotNetAnalyzers/StyleCopAnalyzers#1117]
The following code produces either SA1202 or SA1204 depending on the order of the two methods.

    public void A()
    {
    }

    private static void B()
    {
    }

This appears to be an error with SA1204, since its precedence should be lower than that of SA1202.

**Comment by Noryoko** [comment]
Looks like a problem in SA1202 not separating static elements from instance ones. I'll get this fixed. Thanks for catching this! :smile:
