### ISSUE TITLE
SA1204 (Static fields must appear before instance fields) conflicts with SA1203 (Constants must appear before fields)

### ISSUE THREAD

**Issue by oatkins** [DotNetAnalyzers/StyleCopAnalyzers#1119]
The following two fields give either SA1204 or SA1203 depending on their order:

```csharp
private const char ReportDelimiterCharacter = ';';

private static readonly string A = "Haddock";
```

The above order is, I think, the correct one. It gives SA1204, which therefore seems to be in error.

**Comment by sharwell** [comment]
You are correct, the expected order is:

1. `const` fields
2. `static readonly` fields
3. `static` fields
4. `readonly` fields
5. Other instance fields

**Comment by Noryoko** [comment]
I'll get this fixed. Thanks for catching it!
