### ISSUE TITLE
Implement SA1413: UseTrailingCommasInMultiLineInitializers

### ISSUE THREAD

**Issue by otac0n** [DotNetAnalyzers/StyleCopAnalyzers#1121]
**Category:** Maintainability?
**Rule:** Trailing commas are required for multi-line initializers.
**Description:** All elements in object initializers and array initializers that span multiple lines must be followed by a comma.
**Rationale:** For multi-line object initializers and array initializers, requiring a trailing comma for each element has some advantages:

* Elements can be reordered easily (Alt + Up/Down in most cases).
* Adding a new element at the end doesn't change unrelated lines.

This rule would fire for the following:

    var x = new Barnacle
    {
        Age = 100,
        Height = 0.2M,
        Weight = 0.88M
    };

    var x = new []
    {
        Tuple.Create("A", 1),
        Tuple.Create("B", 2),
        Tuple.Create("C", 3)
    };

The rule would not fire for the following (although other rules might):

    var x = new Barnacle
    {
        Age = 100,
        Height = 0.2M,
        Weight = 0.88M,
    };

    var x = new { Min = 0, Max = 0 };

    var x = new [] { Tuple.Create("A", 1), Tuple.Create("B", 2), Tuple.Create("C", 3) };

**Comment by sharwell** [comment]
I think it makes sense. If we implement it, I'd like to see it paired with a rule that trailing commas shouldn't be included in single-line initializers.

**Comment by vweijsters** [comment]
:+1: I think this is a good proposal

**Comment by Maxwe11** [comment]
:+1:

**Comment by nbarbettini** [comment]
Grabbing this :+1:

**Comment by sharwell** [comment]
@nbarbettini Sounds good. I'm not planning to include any other rules for RC 1 other than the three that are already assigned to that milestone, but we can include it afterwards.

**Comment by nbarbettini** [comment]
@sharwell Cool. I'll PR to master when I'm done.

> I'd like to see it paired with a rule that trailing commas shouldn't be included in single-line initializers.

Still want to do this as well, as a separate rule?

**Comment by sharwell** [comment]
> Still want to do this as well, as a separate rule?

Not sure yet. I'll have to think about it some more after RC 1.
