### ISSUE TITLE
StyleCop.Analyzers work only if VS is installed

### ISSUE THREAD

**Issue by azabluda** [DotNetAnalyzers/StyleCopAnalyzers#1124]
I tried to set up a simple MSBuild environment on a clean Windows 7 PC without Visual Studio. So I went ahead and installed

* .NET Framework 4.6
* Microsoft Build Tools 2015 RC

Building a simple project with active StyleCop.Analyzers gave me the following error:

>   CSC : warning CS8032: An instance of analyzer StyleCop.Analyzers.NamingRules.SA1306FieldNamesMustBeginWithLowerCaseLetter cannot be created from F:\BuildNG\wcf-proto\packages\StyleCop.Analyzers.1.0
.0-beta003\analyzers\dotnet\cs\StyleCop.Analyzers.dll : Could not load file or assembly 'System.Collections.Immutable, Version=1.1.36.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of it
s dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040).

After I manually installed the 'System.Collections.Immutable, Version=1.1.36.0' assembly into GAC I received the new error:

> CSC : warning CS8032: An instance of analyzer StyleCop.Analyzers.SpacingRules.SA1004DocumentationLinesMustBeginWithSingleSpace cannot be created from F:\BuildNG\wcf-proto\packages\StyleCop.Analyzers.1.0.0-beta003\analyzers\dotnet\cs\StyleCop.Analyzers.dll : Method 'get_SupportedDiagnostics' in type 'StyleCop.Analyzers.SpacingRules.SA1004DocumentationLinesMustBeginWithSingleSpace' from assembly 'StyleCop.Analyzers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=97d9e3aa481481c8' does not have an implementation..

As per http://stackoverflow.com/a/31779752 it is likely another version conflict, which already goes a bit beyond my understanding. Had to give up at that point...

Do you confirm the StyleCop.Analyzers are only intended to run on the developers PCs? Are there any ways/plans to make it work also on the build machines?

Many thanks in advance,
AZ

**Comment by pdelvo** [comment]
The problem might be that you installed the RC version of the build tools which probably comes with an outdated version of the compiler. Can you try to uninstall it and install the [rtm version](https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs.aspx) instead?

**Comment by azabluda** [comment]
Thanks @pdelvo! I followed your link and (after some desperate search all over the page) found exactly what google failed to give me. The RTM version works like a charm!

An alternative (more direct) link is http://www.microsoft.com/en-in/download/details.aspx?id=48159, should anyone be interested...

**Comment by sharwell** [comment]
:+1:
