### ISSUE TITLE
SA1512 (A single line comment must not be followed by a blank line) should allow blank line between single line comments and documentation comments

### ISSUE THREAD

**Issue by oatkins** [DotNetAnalyzers/StyleCopAnalyzers#1130]
The following generates a warning for the SA1512 analyzer, but not in legacy StyleCop:

    // Some comments.

    /// <summary>Some summary.</summary>
    public void A()
    {
    }

Removing the space eliminates the warning. However, without the space, legacy StyleCop would report SA1514. (See issue #1131.)

These issues might seem unimportant, but I doubt that I am alone in having *many* classes that have code comments followed by documentation comments, following the SC rules.

**Comment by Noryoko** [comment]
Grabbing this.

**Comment by RalfKoban** [comment]
Hi,

using Beta 6, I'm experiencing a similar issue (SA1514) for following code snippet:

        public override bool SomeMethod() => true; // some comment

        /// <summary>
        /// ...
        /// </summary>
        public override void SomeOtherMethod()
        {
        }


Best regards,
Ralf

**Comment by sharwell** [comment]
@RalfKoban Can you open a new issue for that?

Thanks! :+1:

**Comment by RalfKoban** [comment]
@sharwell
Of course. Reported as issue #1215.
