### ISSUE TITLE
SA1514 (A documentation comment must be preceded by a blank line...) not reported when immediately preceded by a single line comment

### ISSUE THREAD

**Issue by oatkins** [DotNetAnalyzers/StyleCopAnalyzers#1131]
The following should, but does not, generate an analyzer warning. (It does in legacy StyleCop.)

    // Something in advance.
    /// <summary>
    /// The YetMore class.
    /// </summary>
    public static class YetMore { }

The above code should be "fixed" by inserting a blank line before the documentation comments, though this would currently add a violation of SA1512 without a fix for #1130.

**Comment by Noryoko** [comment]
Grabbing this.
