### ISSUE TITLE
SA1515 (Single line comment must be preceded by blank line) and SA1506 (A documentation header must not be followed by a blank line) require wrong spacing

### ISSUE THREAD

**Issue by oatkins** [DotNetAnalyzers/StyleCopAnalyzers#1132]
In legacy StyleCop, the following is correct:

    /// <summary>Some summary.</summary>
    // Some comment.
    public void A()
    {
    }

Introducing a space between the two comment lines would cause a violation of SA1506.

In this project, the above code gives SA1515. Introducing a space between the two comment lines, which is wrong by legacy StyleCop, removes the analyzer warning.

See also #1130 and #1131.

Incidentally, I don't really *like* this style, but I have *many* violations because of the new analyzer behaviour. The primary reason is that we have many comments like

    /// <summary>Doc comments here...</summary>
    // ReSharper disable once XXXX
    public void SomeMethodWithReSharperSuppression()
    {
    }

where the spacing has been chosen to avoid SC violations. It's a pain that these now give analyzer warnings.

**Comment by Noryoko** [comment]
Grabbing this.
