### ISSUE TITLE
SA1513: ClosingCurlyBracketMustBeFollowedByBlankLine

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#114]
http://www.stylecop.com/docs/SA1513.html

**Comment by vweijsters** [comment]
grabbing this.

**Comment by vweijsters** [comment]
I propose to make a change to the StyleCop behavior here. StyleCop mandates the following:

```C#
        switch (X)
        {
          case 1:
            {
              this.X = 2;
            }

            break;
        }
```

I intend to change the behavior so that the code below will not generate a diagnostic.
```C#
        switch (X)
        {
          case 1:
            {
              this.X = 2;
            }
            break;
        }
```

What are your thoughts on that?

**Comment by sharwell** [comment]
@vweijsters Move the `break` statement inside the braces.
