### ISSUE TITLE
New rule proposal: Store files as UTF-8 with byte order mark

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1142]
**Category:** Maintainability
**Name:** Store files as UTF-8 with byte order mark
**Description:** Source files should be saved using the UTF-8 encoding with a byte order mark
**Rationale:** Storing files in this encoding ensures that the files are always treated the same way by the compiler, even when compiled on systems with varying default system encodings. In addition, this encoding is the most widely supported encoding for features like visual diffs on GitHub and other tooling. This encoding is also the default encoding used when creating new C# source files within Visual Studio.

Related issue reports:

* https://github.com/dotnet/roslyn/pull/479#issuecomment-74431004
* dotnet/roslyn#4022
* dotnet/roslyn#4222
* dotnet/roslyn#4264
* dotnet/roslyn#4255
* dotnet/roslyn#4298
* dotnet/corefx#2346

**Comment by oatkins** [comment]
Yes please!

**Comment by pdelvo** [comment]
:+1: Im currently working on a prototype

**Comment by sharwell** [comment]
With three :+1: votes and a tested implementation with code fix, I'm promoting this one to tentative status as a new rule.
