### ISSUE TITLE
Respect ExcludeFromStyleCop in csproj

### ISSUE THREAD

**Issue by hickford** [DotNetAnalyzers/StyleCopAnalyzers#1145]
A feature of [StyleCop "classic"](https://stylecop.codeplex.com/) is that you can exclude files completely by editing the csproj project

    <Compile Include="Calculation\DataExtraction.cs">
      <ExcludeFromStyleCop>true</ExcludeFromStyleCop>
    </Compile>

StyleCop.Analyzers doesn't seem to respect this. This is a barrier to us upgrading. https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/1144

**Comment by sharwell** [comment]
Currently Roslyn doesn't provide us with that information (see dotnet/roslyn#2287). It might be possible to manually inject the project file into the build (see the comments in #422), but we'd still have to use the MSBuild APIs to locate the current file and get its metadata.

Right now the best way to handle this is put the following comment at the top of any such file:

```csharp
// <auto-generated/>
```

If the file isn't actually auto generated, you could put this:

```csharp
// This file isn't generated, but this comment is necessary to exclude it from StyleCop analysis.
// <auto-generated/>
```

**Comment by hickford** [comment]
Hi Sam, thanks for your reply. Ah, I thought something like that might be the problem. That's frustrating.

Cheers for the workaround.

**Comment by hickford** [comment]
See also https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/726

**Comment by sharwell** [comment]
Ah, I knew we had comments in code where exclusions are implemented, but I didn't realize we had an issue for it. :smile:

**Comment by peterjp80** [comment]
I can't exclude a file from Stylecop.  I tried regions ending in "generated code" and I've tried placing `// <auto-generated/>` at the top of the file, but neither works.  Is there something I need to configure in stylecop.json to ignore auto generated files?  I'm using .NET Core 1.1.2 and StyleCop.Analyzers 1.0.2.

**Comment by sharwell** [comment]
@peterjp80 Can you include an example of a specific warning ID which is getting reported?

**Comment by peterjp80** [comment]
@sharwell I'm getting CS1591 warnings.  However, I just noticed that these warnings (on files commented with // <auto-generated/>) appear on the first time any changes are built.  For example, I add a line break and run "Build Solution" and the auto-generated files are not ignored...but then I run "Build Solution" a 2nd time and they are ignored.  I repeated this multiple times and can reproduce each time.

**Comment by sharwell** [comment]
@peterjp80 CS1591 is reported by the compiler, not by StyleCop Analyzers. The documentation for [SA0001](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA0001.md#how-to-fix-violations) describes a couple ways to deal with that specific situation. :+1:

**Comment by peterjp80** [comment]
@sharwell I've suppressed those warnings. Thanks for your help!
