### ISSUE TITLE
SA1215: Incorrectly errors when constants are declared before readonly fields

### ISSUE THREAD

**Issue by FlatlinerDOA** [DotNetAnalyzers/StyleCopAnalyzers#1154]
Example:

    public class Test
    {
        private const string Test1 = "Test";
        private readonly string test2 = "Test";
    }

Is incorrectly identifying test2 as in error for SA1215 "All private readonly fields must be declared before private non-readonly fields".

**Comment by sharwell** [comment]
Hi @FlatlinerDOA and welcome!

This issue was actually reported in #1148, which is also the pull request that fixed it. :+1: It will be included in Beta 5 later today.
