### ISSUE TITLE
SA1516: ElementsMustBeSeparatedByBlankLine

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#117]
http://www.stylecop.com/docs/SA1516.html

**Comment by pdelvo** [comment]
grabbed

**Comment by pdelvo** [comment]
I implemented the diagnostic + code fix + tests, but Im waiting for #518. I used the mechanic to build the expected diagnostic result array I implemented in there. The more I use it the more I like it ;) It reduces the code to create the expected diagnostic array by about 90%
