### ISSUE TITLE
New rule proposal: Constructor initializer must appear on its own line

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1177]
**Category:** Readability
**Title:** Constructor initializer must appear on its own line
**Description:** A violation of this rule occurs when an instance constructor contains a constructor initializer, but the constructor initializer is not on its own line. For example:

```csharp
public class TypeName
{
    public TypeName() : this(0)
    {
    }

    public TypeName(int value)
    {
    }
}
```

To resolve a violation of this rule, move the constructor initializer to its own line, including the `:` character.

```csharp
public class TypeName
{
    public TypeName()
        : this(0)
    {
    }

    public TypeName(int value)
    {
    }
}
```

:thought_balloon: I'm thinking that violations of this rule could be specifically determined by the placement of the `:`, meaning the following would violate this as well. However, I'd be open to alternative views if people think this would be a major problem.

```csharp
public class TypeName
{
    public TypeName() :
        this(0)
    {
    }

    public TypeName(int value)
    {
    }
}
```

**Comment by hvanbakel** [comment]
This would be helpful since the constructor initializer can never be off screen, by having it on a new line this is really clearly specified.

**Comment by JohanLarsson** [comment]
I thought this was already a cop rule, it makes perfect sense to me.
Side note:
Is there a rule about the order of chained constructors and method overloads? Dunno if chained is the correct word.

**Comment by Noryoko** [comment]
:+1:  I think R# formats constructors like this by default.

**Comment by oatkins** [comment]
:+1:

**Comment by sharwell** [comment]
Moved this to **up for grabs**.

> Is there a rule about the order of chained constructors and method overloads? Dunno if chained is the correct word.

Not that I know of.

**Comment by JohanLarsson** [comment]
Would an ordering rule make sense?

**Comment by sharwell** [comment]
> Would an ordering rule make sense?

I'm finding the more I use the ordering rules, the more I dislike them. They encourage some very bad practices for teams using code review (small changes are forced to use large diffs).

Also, is one way really better than any other for chaining? It seems like each has different merits and use cases.

Also the order would be impacted by accessibility of constructors in the chain. This could add more confusion to the interaction between existing ordering rules.

**Comment by nbarbettini** [comment]
Taking the diagnostic side of this.
