### ISSUE TITLE
False positive of SA1601 on windows forms - if documentation build XML isn't eanbled.

### ISSUE THREAD

**Issue by alaendle** [DotNetAnalyzers/StyleCopAnalyzers#1190]
Just create a new windows forms project under VS2015 and add the StyleCop.Analyzers analyzer.
Resolve all warnings in the IDE by adaption of the code - but do not activate the documentation build.
If you now build the project you will face a additional warning like the following in the build output:

1>C:\temp\TestStyleCopAnalyzers\TestStyleCopAnalyzers\Form1.cs(14,24,14,29): warning SA1601: Partial elements must be documented

Also it seems that the missing documentation build raises a lot of other false positives.
If this is a know behavior please close this issue immediately - and maybe add this fact to the documentation more prominent.

**Comment by pdelvo** [comment]
The code behind class is a partial class so I think the reported diagnostic is correct. Is the original stylecop behaving differently?

**Comment by sharwell** [comment]
Many analyzers which examine documentation comments naturally do not run when documentation output is disabled. In cases where XML documentation output is disabled, the only reported diagnostic for documentation comments should be SA1652 (EnableXmlDocumentationOutput).

**Comment by sharwell** [comment]
Grabbed
