### ISSUE TITLE
Add ability to test performance of code fixes with StyleCopTester

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1199]
Currently StyleCopTester does a great job with performance testing analyzers, but it does not run any fixes. Since batch fixing is the most likely to cause problems in the IDE, it would be nice to have a `/fix` command line option which applies the fixes for reported diagnostics.

> :warning: Make sure to *not* write the changes to disk during the fix operation. The fixes should be fully applied, but only in memory.

**Comment by sharwell** [comment]
Tentatively assigning to @pdelvo as the likely implementer. :smile:

**Comment by robinsedlaczek** [comment]
:warning: Make sure to not write the changes to disk during the fix operation. The fixes should be fully applied, but only in memory.

Means, that the user has to save all documents at the end in Visual Studio? Are all affected documents opened (for review) then, or how could the workflow look like? When will the changed documents be saved?

Second, applying the changes on disk directly is the current implementation in Visual Studio 2015, is that correct? Is that the point, where all the SaveFile dialogs pop up?

Applying in memory sounds great, testing performance with StyleCopTester as well! Please consider undo operations in this context as well!

**Comment by robinsedlaczek** [comment]
Please let me back-link to /dotnet/roslyn/issues/2637 [https://github.com/dotnet/roslyn/issues/2637].

**Comment by sharwell** [comment]
@robinsedlaczek StyleCopTester is a tool this team uses to accurately profile the analyzers and code fixes we develop to ensure the best user experience possible. During these profiling passes, it's important that we be able to test the behavior on any number of projects without having to worry about it overwriting the project files on disk. Within Visual Studio, the code fixes will continue to automatically save the results when they are applied to a project or solution.

**Comment by robinsedlaczek** [comment]
@sharwell Thanks a lot for your explanation. Got it. :)

**Comment by sharwell** [comment]
Fixed in #1317
