### ISSUE TITLE
SA1500 (Curly brackets for multi-line statements must not share a line) wrongly raised for extension method on a collection with a collection initializer

### ISSUE THREAD

**Issue by oatkins** [DotNetAnalyzers/StyleCopAnalyzers#1202]
The following code gives SA1500 with the analyzer but not with legacy SC:

    public void Fish()
    {
        var someList = new List<int>
                       {
                           1,
                           2,
                           3
                       }.Select(x => x.ToString());
    }

**Comment by Noryoko** [comment]
Grabbing this.
