### ISSUE TITLE
SA1514 (A documentation comment must be preceded by a blank line...) should not be reported when immediately preceded by a single line comment on a method body

### ISSUE THREAD

**Issue by RalfKoban** [DotNetAnalyzers/StyleCopAnalyzers#1215]
Hi,

using Beta 6, I'm experiencing a similar issue (SA1514) for following code snippet:

    public override bool SomeMethod() => true; // some comment

    /// <summary>
    /// ...
    /// </summary>
    public override void SomeOtherMethod()
    {
    }

Best regards,
Ralf

**Comment by Noryoko** [comment]
Grabbing this.
