### ISSUE TITLE
SA1602: EnumerationItemsMustBeDocumented

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#122]
http://www.stylecop.com/docs/SA1602.html

**Comment by pdelvo** [comment]
grabbed

**Comment by pdelvo** [comment]
I think this issue can be closed.

**Comment by sharwell** [comment]
Yes. This one's on me; I should have closed the issue at the same time as I set the label to "fixed". In the future you can make sure all related issues get closed by using one "Fixed #xxx" line for each issue fixed by a pull request, as opposed to using a comma-separated list like #370 used.
