### ISSUE TITLE
SA1603: DocumentationMustContainValidXml

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#123]
http://www.stylecop.com/docs/SA1603.html

**Comment by pdelvo** [comment]
grabbed.

**Comment by sharwell** [comment]
Cool. I was just looking at this one actually.

Let me look at the updates to #370 and then I may have questions about the supporting API you're using here. There are some security and performance concerns that we'll have to be certain are properly addressed.

**Comment by pdelvo** [comment]
Okay. I am actually not using the supporting API for this.
