### ISSUE TITLE
SA1204 Conflict between private static and explicit interface methods

### ISSUE THREAD

**Issue by aboryczko** [DotNetAnalyzers/StyleCopAnalyzers#1230]
Hi,
There seems to be a bug with explicit interface method classification. The following code gives a violation for SA1204 (or SA1202 if you change the order):

```csharp
private static void ExampleMethod()
{
}

IEnumerator IEnumerable.GetEnumerator()
{
	return GetEnumerator();
}
```

Kind regards,
Artur

**Comment by sharwell** [comment]
Hi @aboryczko and welcome to the project. :smile: 

Sorry I didn't reply sooner, but I have some good news now. We've already fixed this issue in the code base (based on this bug report). In addition, we're trying very hard to get the next beta released today - there's one more bug we need to attend to but I don't think it will be a problem!
