### ISSUE TITLE
SA1514 seems to be unaware of regions

### ISSUE THREAD

**Issue by RalfKoban** [DotNetAnalyzers/StyleCopAnalyzers#1231]
Hi,

I'm using 1.0.0 Beta 7.
The SA1514 rule seems to be got unaware of regions, because I get a violation e.g. in following snippet:

        #region Fields

        /// <summary>
        /// Contains some data.
        /// </summary>
        private object someData;

        #endregion

In Beta 6 that was working.

Best regards,
Ralf

**Comment by sharwell** [comment]
I'm thinking for most cases of preprocessor directives, we need to avoid reporting this warning whether or not there is a blank line before the documentation comment. The exceptions are:

* Must have a blank line if preceded by:
  * `#endif`
  * `#region`
  * `#endregion`

**Comment by Noryoko** [comment]
Sounds good to me. :+1:
