### ISSUE TITLE
Add InternalsVisibleTo for the test project

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1242]
The main analyzers assembly needs an `InternalsVisibleTo` attribute for ease of testing features without making them public.

**Comment by vweijsters** [comment]
This will require signing the test assembly as well

**Comment by sharwell** [comment]
More than that, it will require signing the test assembly with its own key. The keys currently used by the main project change based on whether a release is a stable release or not - if the same pattern were used for the test assembly it would cause all the tests to fail when we tag the 1.0 stable release. :wink:

**Comment by vweijsters** [comment]
An update of the xunit packages is also required. The  `2.1.0-beta3-build3029` will not properly run signed assemblies. `2.1.0-beta4-build3109` works fine.
