### ISSUE TITLE
SA1027 (TabsMustNotBeUsed) code fix ignores trivia

### ISSUE THREAD

**Issue by Maxwe11** [DotNetAnalyzers/StyleCopAnalyzers#1246]
e.g. assume all lines indented by tabs

		/// <summary>
		/// foo bar
		/// </summary>
		public void FooBar()

after code fix we will receive:

		/// <summary>
		/// foo bar
		/// </summary>
        public void FooBar()

code indented by spaces but documentation still indented by tabs

**Comment by Maxwe11** [comment]
same issue with tabs inside comments

**Comment by robinsedlaczek** [comment]
Working on it! 

Question: which points from the contributing guide are important for bug fixes in existing analyzers and code fixes?

**Comment by sharwell** [comment]
@robinsedlaczek I wrote the contributing guide back when only I was working on the project. It could be entirely out of date now that the project took off. The comment you posted is enough to count as claiming it. Then there is a code review after you submit a pull request. :smile:

**Comment by robinsedlaczek** [comment]
@sharwell Cool, thanks!

**Comment by sharwell** [comment]
@robinsedlaczek I ended up fixing this as part of another efficiency change I was working on.

**Comment by robinsedlaczek** [comment]
@sharwell Oh, so I am too late. :) Great, that you fixed it. I'll have a look to learn. Thanks!
