### ISSUE TITLE
SA1018 errors on badly placed question mark

### ISSUE THREAD

**Issue by nbarbettini** [DotNetAnalyzers/StyleCopAnalyzers#1256]
I accidentally typed a stray `?` at the end of my class and noticed this bug:

```
namespace StyleCopAnalyzers_Test
{
    public class Class1
    {
        private void Test()
        {
            var hello = "world";
        }
    }
}
?
```

The question mark at the end of the class causes this banner to appear above the code editor:

> SA1018CodeFixProvider encountered an error and has been disabled.

In my real-world project, it seemed to happen as soon as I typed the question mark. In my repro example above, it didn't occur until I clicked on the lightbulb icon to view suggested improvements. Tested in beta008.

**Comment by sharwell** [comment]
Thanks for taking the time to report this. :+1:

**Comment by nbarbettini** [comment]
Wow, fast service. Thanks :+1:
