### ISSUE TITLE
Provide binary release via direct download

### ISSUE THREAD

**Issue by jimevans** [DotNetAnalyzers/StyleCopAnalyzers#1258]
There are legitimate reasons for projects to _not_ manage dependencies through NuGet. Forcing users to go through the NuGet package manager, then extract the contents for inclusion induces friction through the creation of an extra step. Please consider providing directly-downloadable releases.

**Comment by sharwell** [comment]
I updated all of the [releases](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/releases) to attach the build artifact.

**Comment by sharwell** [comment]
I'm going to close this as "addressed". Let me know if there is something specific we should be doing in addition to this.

Thanks for taking a look at our project, and we hope you stick around. :smile:
