### ISSUE TITLE
SA1609 - The most annoying new feature.

### ISSUE THREAD

**Issue by DarkBond** [DotNetAnalyzers/StyleCopAnalyzers#1262]
SA1609 was not turned on by default in the old StyleCop.  It is, without question, the most annoying new feature of the new StyleCop in that the value added is negligible vs. the amount of work needed for compliance.  All of my properties have a standard 'Gets or sets' documentation.  The 'Value' description is redundant.  Is there some justification for this rule being on be default or was it just turned on by mistake?

**Comment by sharwell** [comment]
There wasn't a specific decision to enable it by default as a difference from StyleCop "classic". It was simply enabled because enabling diagnostics is part of our default workflow to date and no one pointed out that it differs from StyleCop "classic".

:question: Have you checked out the automatic code fix for it by any chance? If so, what are your impressions of it?

**Comment by DarkBond** [comment]
1. For anyone who has a large code base and is converting from the old StyleCop, this jumps out as a major drain of energy.  Even to disable it in all your projects eats up a bunch of time and I'm trying to avoid (at all cost) any deviation from the out-of-the-box settings.
2. The automatic code fix is amazing.  I've run it a couple times on a Solution-wide setting.  (With the exception of 1609) it takes away one of the biggest obstacles to StyleCop compliance in that it makes making a large change in your code base as easy as Refactoring.

**Comment by sharwell** [comment]
Note that I'm specifically referring to the code fix for SA1609 in my previous question. :smile:

**Comment by DarkBond** [comment]
Yes.  I used the automatic code fix for that one as well.  It works great except that I have to delete the <placeholder> tags.  The biggest issue I have is that __SA1609__ has no use: you have to work really, really hard to come up with a situation where the 'Gets or sets' description doesn't describe the value that's returned.

**Comment by DarkBond** [comment]
But I can't emphasis this enough: for someone who's been using the product to convert a large code base and make it compliant, the automatic code fixing is amazing.

**Comment by sharwell** [comment]
> Yes. I used the automatic code fix for that one as well. It works great except that I have to delete the  `<placeholder>` tags.

:bulb: There is a code fix for removing these as well. A fix-all for values followed by a fix-all for placeholders will typically get your project into the right state, provided you review the changes before committing them to source control.

**Comment by sharwell** [comment]
@oatkins @pdelvo @Noryoko @vweijsters How do y'all feel about enabling or disabling this rule by default?

**Comment by Noryoko** [comment]
Sounds good to me. Looks like SA1610 is also disabled by default in classic StyleCop.

**Comment by vweijsters** [comment]
I'm in favor of disabling by default.

**Comment by oatkins** [comment]
Also in favour of disabling it.
________________________________

**Comment by sharwell** [comment]
I'll go ahead and disable it by default. I'm leaving SA1610 enabled though; it only gets reported if you specifically include a `<value>` element but it doesn't have any content.
