### ISSUE TITLE
SA1119 reports incorrect unnecessary parenthesis in string interpolation

### ISSUE THREAD

**Issue by nbarbettini** [DotNetAnalyzers/StyleCopAnalyzers#1284]
This snippet triggers SA1119:
```
bool flag = false;
string data = $"{(flag ? "yep" : "nope")}";
```

But this is actually [correct syntax](http://stackoverflow.com/questions/31844058/how-to-use-the-ternary-operator-inside-interpolated-string) for using the ternary operator inside a C# 6.0 interpolated string; there's no way to write it without the parenthesis. The code fix (removing the parenthesis) causes the code to be uncompilable.

**Comment by pdelvo** [comment]
Nice catch! Im going to have a look at it

**Comment by nbarbettini** [comment]
Would take a look myself, but still at work! :smile:

**Comment by pdelvo** [comment]
If you want to fix it go ahead!

**Comment by nbarbettini** [comment]
I wouldn't be able to get to it until later, so unless I've specifically mentioned here that I'm looking at it, assume I haven't had time yet.

**Comment by sharwell** [comment]
So who took it? :smile:

**Comment by pdelvo** [comment]
Im going to fix this now

**Comment by nbarbettini** [comment]
Yeah, sorry... didn't have time to look at it yet. :disappointed: Go for it!
