### ISSUE TITLE
TriviaHelper.WithoutLeadingBlankLines bug

### ISSUE THREAD

**Issue by hvanbakel** [DotNetAnalyzers/StyleCopAnalyzers#1285]
In #1252 there's now a failing test as a result of TriviaHelper.WithoutLeadingBlankLines throwing an index out of range exception on line 299 with this code:
```CSharp
public class Foo
{
    private int i = 0;

    public int Prop
    {
        /// <summary>
        /// The setter documentation
        /// </summary>
        set
        {
            i = value;
        }

        /// <summary>
        /// The getter documentation
        /// </summary>
        get
        {
            return i;
        }
    }
}
```

**Comment by hvanbakel** [comment]
Checked with `//` as well, it does not crash but it leaves leading newlines in place. So both cases are a problem.

**Comment by sharwell** [comment]
I marked it **up for grabs**. Did you want to take a look at it?

I'm headed to bed so I won't be able to set the assignee until tomorrow, but I think everyone here looks for "Grabbed" comments first anyway. :smile:

**Comment by hvanbakel** [comment]
Not really. I did a quick scan but couldn't find it straight away. Might
also be related to the late hour :)

**Comment by pdelvo** [comment]
grabbed
