### ISSUE TITLE
stylecop.json needs a documentation page

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1289]
The documentation page should include the following:

* Explanation of the structure
* Link to the JSON schema
* Explanation of the fact that the code fix can automatically add this file to the project, but you still have to manually set it to the build action `AdditionalFiles` (with instructions)
  * This code fix is the recommended way to add the file to a project, because it adds the "$schema" property automatically, which gives IntelliSense functionality in Visual Studio.
* A link from the readme to this page (remove the old link to an issue talking about Settings.StyleCop).

**Comment by journeyman** [comment]
Hi, @sharwell 
maybe I'm dumb, but I still don't understand how to configure certain rules to be ignored?
example from old **Settings.StyleCop**:
```xml
<Rule Name="ElementsMustBeDocumented">
  <RuleSettings>
    <BooleanProperty Name="Enabled">False</BooleanProperty>
  </RuleSettings>
</Rule>
```
With CodeAnalysis **FxCop.ruleset** it will translate to:
```xml
<Rules AnalyzerId="StyleCop.Analyzers" RuleNamespace="StyleCop.Analyzers">
    <Rule Id="SA1000" Action="Hidden" />
</Rules>
```

How should it look like in new **stylecop.json**?
Also would be very cool to have a way to exclude certain file from analysis

**Comment by sharwell** [comment]
@journeyman **stylecop.json** cannot be used to exclude rules. That behavior is provided exclusively by the new rule sets functionality. The [configuration documentation](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md) should contain all the information you need. Please open a new issue if something in there is still unclear. :smile:

**Comment by journeyman** [comment]
Got it, I thought those "two separate mechanisms" can be used interchangeably. But now it makes sense, thanks!
Do you know any way to exclude particular file from analysis? Previously I could use:
```xml
<Compile Include="OpenSourceComponent.cs">
    <ExcludeFromStyleCop>True</ExcludeFromStyleCop>
</Compile>

**Comment by journeyman** [comment]
@sharwell found https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/1145 
sorry to disturb and thanks for help!

**Comment by sharwell** [comment]
No problem :smile:
