### ISSUE TITLE
SA1652 does not disable when suppressed via ruleset.

### ISSUE THREAD

**Issue by otac0n** [DotNetAnalyzers/StyleCopAnalyzers#1290]
Problem persists across rebuilds.  Fixed by restarting Visual Studio. Perhaps reloading the project would have worked.

**Comment by sharwell** [comment]
This is a bug in Roslyn. Can you file it there?

**Comment by sharwell** [comment]
Note that SA1652 should never be suppressed. Failing to correct this issue will cause Visual Studio itself to behave incorrectly with respect to commonly executed operations like Remove and Sort Usings.

XML documentation files are an essential output of any correct build, whether or not you plan to use them afterwards.
