### ISSUE TITLE
Proposal: Permanently disable rule SA1603 (DocumentationMustContainValidXml)

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1291]
This rule is a duplication of compiler warning [CS1570](https://msdn.microsoft.com/en-us/library/c20zzdxx.aspx), which means we're slowing down the build but not gaining any functionality from it.

**Comment by Noryoko** [comment]
Sounds good to me.  :+1:

**Comment by vweijsters** [comment]
:+1:
