### ISSUE TITLE
New rule proposal: VariableNamesMustBeginWithLowerCaseLetter

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1310]
**Category:** Naming
**Title:** Variable names must begin with lower case letter
**Description:** This is very similar to SA1306, but it applies specifically to non-`const` local variables.

This functionality is handled by SA1306 in StyleCop classic, but the commentary in #1307 suggests that we continue to implement SA1306 in a more strict manner here and report variables separately. One advantage of treating local variables separately from fields is renaming them is *always* a non-breaking change (they are not even exposed via Reflection), so the ability to "fix all" on these would be valuable and trusted provided it only touched local variables.

**Comment by otac0n** [comment]
:+1:

**Comment by test20150828** [comment]
:+1: The parameter names should be checked the same way like they were checked with old StyleCop.
