### ISSUE TITLE
New rule proposal: ParameterNamesMustBeginWithLowerCaseLetter

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1311]
**Category:** Naming
**Title:** Parameter names must begin with lower case letter
**Description:** This is very similar to SA1306, but it applies specifically to parameters of methods and delegates.

This proposal was created based on feedback in #1307. This proposal is separated from #1310 due to the fact that renaming a parameter is a source-breaking change (call sites using named arguments need to be updated).

**Comment by otac0n** [comment]
:+1: I like the idea of keeping the rules separate.

**Comment by test20150828** [comment]
:+1: The parameter names should be constrained. And it's ok if this check will be in a separate rule.
