### ISSUE TITLE
SA1028 code fix throws ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by pdelvo** [DotNetAnalyzers/StyleCopAnalyzers#1313]
Im currently implementing #1199 and while testing I discovered that [this](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/f1b19b9fc48b16165f2f995dad958aa2e9707da5/StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1028CodeFixProvider.cs#L123) line throws an ArgumentOutOfRangeException when trying to auto fix SA1028 on the roslyn codebase

**Comment by Noryoko** [comment]
Grabbing.

**Comment by pdelvo** [comment]
I just noticed I wrote NRE. It was actually an ArgumentOutOfRangeException.

**Comment by Noryoko** [comment]
Was about to ask. Thanks for clarifying.
