### ISSUE TITLE
SA1313 with underscore in lambda.

### ISSUE THREAD

**Issue by grokys** [DotNetAnalyzers/StyleCopAnalyzers#1343]
A common pattern when using LINQ etc with a parameter that you don't care about is to use the '_' character as the variable name, e.g.

    Observable.Interval(Tick, PerspexScheduler.Instance).Select(_ => Stopwatch.Elapsed)

However with beta 9, I'm getting the warning:

    Warning SA1313 Parameter '_' must begin with lower-case letter

Should this be special-cased?

**Comment by sharwell** [comment]
I thought about special-casing this, but I'm not convinced it's the most StyleCop-like approach. The `_` name does indicate that a variable is not used, but it also hides the meaning of a variable making it easy to later *use* this variable without renaming it. You can see one instance I fixed in commit 4785fee4c99ca4abafcb71ef276d20a71537b317.

I think this issue needs more discussion to figure out the final plan. :smile:

**Comment by grokys** [comment]
That's fair enough, but also consider that there are cases where the parameter *means nothing*, such as [Observable.Unit](https://msdn.microsoft.com/en-us/library/system.reactive.unit(v=vs.103).aspx).

**Comment by sharwell** [comment]
Would be interesting to exclude it *only* if it's not actually used.

**Comment by grokys** [comment]
Sorry, not sure I follow.

I've been thinking more about it, and I think it's such a common and useful pattern that it should be allowed, though obviously the decision is with you guys,

**Comment by grokys** [comment]
Also, looking to a future implementation of pattern matching - as far as I understand '_' is used in many languages (rust, scala are the ones that come to mind) as an ignored parameter. See also https://github.com/dotnet/roslyn/issues/206#issuecomment-72716510.

**Comment by sharwell** [comment]
> Sorry, not sure I follow.

I'm saying to only allow a parameter named `_` if it meets *all* of the following:

* It's the name of a parameter of a lambda or anonymous method.
* The parameter is declared, but never used.

**Comment by grokys** [comment]
Ah, ok. Yes, that sounds like a good idea.

**Comment by lowkay** [comment]
+1 for this, I agree with @grokys assertion that people would just use single-letter variables if it were disallowed (or disable the rule) leading to a degraded coding style.

**Comment by sharwell** [comment]
If @oatkins agrees I'll move this to **up for grabs**.

**Comment by oatkins** [comment]
:+1: Seems fine to me.

(Personally I don't see a great advantage in using `_` over `x`, etc., but it seems to be a popular suggestion and, with the limited scope of the change, it certainly doesn't do any harm.)

**Comment by otac0n** [comment]
:+1: I like the "if it is not used" addition.

**Comment by AArnott** [comment]
I agree. I like using underscore rather than x when I don't use the variable.

**Comment by nbarbettini** [comment]
+1. I really like the idea of having `_` only pass the check if it isn't used in the subsequent lambda. That enforces the best practice of this style.

To go a step further, a warning if you **do** name the variable `x` and then never use it (with a suggestion to rename to `_`) would be even more cool!

**Comment by sharwell** [comment]
> To go a step further, a warning if you **do** name the variable `x` and then never use it (with a suggestion to rename to `_`) would be even more cool!

@nbarbettini That would only work well if C# treated `_` like a special name that can be defined multiple times in the same context.

**Comment by nbarbettini** [comment]
Ah, my bad, you're right. Still +1 to the original suggestion. :+1:
