### ISSUE TITLE
MissingAnalyzerReference warning with alpha 9.

### ISSUE THREAD

**Issue by grokys** [DotNetAnalyzers/StyleCopAnalyzers#1344]
I'm getting the following warning with beta 9:

Warning MissingAnalyzerReference Analyzer assembly 'D:\projects\Perspex\packages\StyleCop.Analyzers.1.0.0-beta009\analyzers\dotnet\cs\Newtonsoft.Json.dll' depends on 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' but it was not found.

**Comment by sharwell** [comment]
Duplicate of #1345, which I typed out yesterday but forgot to hit submit. :expressionless:
