### ISSUE TITLE
File headers: leading spaces should be ignored in copyright messages on lines other than the first

### ISSUE THREAD

**Issue by oatkins** [DotNetAnalyzers/StyleCopAnalyzers#1356]
If the correct header for a file is

    // <copyright file="fish.cs" company="Face">
    //   Copyright (c) Face.
    //   All rights reserved.
    // </copyright>

Then the settings file must contain:

    "copyrightText": "Copyright (c) Face.\n   All rights reserved."

Note that, after the "\n" there must be exactly three spaces to match the indent of the second line of the message.

This was also true in legacy StyleCop, but it would be nicer if you could just have: 

    "copyrightText": "Copyright (c) Face.\nAll rights reserved."

**Comment by sharwell** [comment]
:memo: The code fix will insert exactly one space at the beginning of each line. If you plan to use the code fix and want more than one space, you'll still need to code them in.

**Comment by oatkins** [comment]
OK, though I don't think "exactly one space" will be helpful for most preexisting projects. For example, our own tests use three, and [this example](http://blogs.msdn.com/b/sourceanalysis/archive/2008/05/25/configuring-file-header-company-and-copyright.aspx) from the old StyleCop blog uses a whopping five!

**Comment by sharwell** [comment]
Exactly one space is the most flexible policy. It's easy to add spaces, but difficult to remove them. Zero spaces might even make sense but that would lead to violations of the "include a space in comments" rule.

**Comment by otac0n** [comment]
I would actually support treating all spans of whitespace `[\s\r\n]+` as a single space for validation purposes.

@sharwell Does it make sense for the code fix to introduce spacing for the first line, but none of the others?  Also, what if a user wants to switch away from XML comments?  Ideally this would not require changes to the copyright text configuration.

I would therefore recommend that the code fix introduce context-sensitive indentation for all lines in the copyright text.

    // <copyright ...>
    //   Line 1
    //   Line 2
    // </copyright>

And:

    // Line 1
    // Line 2

**Comment by sharwell** [comment]
@otac0n I discourage the indentation of content within XML tags. It cramps the right margin for and offers little to no benefit when syntax highlighting colors are updated to a more muted color for the XML tags.

**Comment by otac0n** [comment]
@sharwell All the more reason for SyleCop's Code Fix to apply the correct indentation automatically.

**Comment by vweijsters** [comment]
If I understand the @oatkins correctly, he is asking for the SA1636 analyzer to ignore any leading / trailing space on a line when checking it against the copyright text in the settings file. 
That was the way that I intended to implement that, so I think its a bug indeed.

@sharwell Assign it to me please, I'll fix the analyzer.
