### ISSUE TITLE
Image could not be loaded in SA1641 documentation page

### ISSUE THREAD

**Issue by NikolayIT** [DotNetAnalyzers/StyleCopAnalyzers#1358]
I've noticed that in https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1641.md the image `/documentation/Images/CompanyInformationSettings.JPG` is missing.

**Comment by sharwell** [comment]
This page was copied over from StyleCop "classic". The new instructions for configuring this information are available in [Configuration.md](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md), but we should update this page to be accurate too.
