### ISSUE TITLE
Code fix for SA1212 and SA1213 does not preserve blank lines between accessors

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1364]
#1363 introduces new unit tests for SA1212 and SA1313. In this code, the `fixedCode` for the following tests does not contain a blank line between the accessors after the code fix is run. However, in each of these cases a blank line is expected.

* `SA1212UnitTests.TestPropertyWithDocumentationAsync`
* `SA1212UnitTests.TestPropertyWithLineCommentAsync`
* `SA1212UnitTests.TestPropertyWithBlockCommentAsync`
* `SA1213UnitTests.TestAddAccessorAfterRemoveAccessorWithLineCommentAsync`
* `SA1213UnitTests.TestAddAccessorAfterRemoveAccessorWithBlockCommentAsync`

Currently blocked on #1363.

**Comment by hvanbakel** [comment]
Grabbed
