### ISSUE TITLE
Syntax tree analysis instead of raw text analysis in spacing analyzers

### ISSUE THREAD

**Issue by alxyr** [DotNetAnalyzers/StyleCopAnalyzers#1367]
Hi all,

I was researching StyleCop.Analyzers code as a reference for implementing my own custom analyzer and there is something that is not obvious to me.

Is there any reason that the complex token-level processing is used in spacing analyzers instead of simple parsing of raw text lines? For example, the analyzing code in SA1028CodeMustNotContainTrailingWhitespace class might look like the following:

```C#
SourceText sourceText = context.Tree.GetText(context.CancellationToken);
foreach (TextLine line in sourceText.Lines)
{
	if (line.Span.IsEmpty)
		continue;

	string text = line.ToString();
	int wsStart = FindTrailingWhitespace(text);

	if (wsStart >= 0)
	{
		Location diagnosticLocation = Location.Create(
			context.Tree, TextSpan.FromBounds(line.Start + wsStart, line.End));

		// TODO: report diagnostic for the location above
	}
}
```

This seems more simple and reliable than the current implementation.

**Comment by sharwell** [comment]
We don't examine text inside disabled text `#if false`, or within verbatim string literals. Also *many* of the spacing rules have special exceptions depending on where you are in the syntax tree (see #1191 for example).

**Comment by alxyr** [comment]
It makes sense to walk the syntax tree then. Thanks for the answer.
