### ISSUE TITLE
SA1501 (StatementMustNotBeOnASingleLine): allow writing do-while in two lines

### ISSUE THREAD

**Issue by alxyr** [DotNetAnalyzers/StyleCopAnalyzers#1368]
Hi,

Would it be possible to relax SA1501 so that it would allow writing do-while loops in two lines (when SA1503:CurlyBracketsMustNotBeOmitted is disabled)? For example:
```C#
do ++pos;
while (pos < str.Length && char.IsWhiteSpace(str[pos]));
```
vs.
```C#
do
	++pos;
while (pos < str.Length && char.IsWhiteSpace(str[pos]));
```
or:
```C#
if (cursor.MoveFirst())
{
	do cursor.UpdateData();
	while (cursor.MoveNext());
}
```
vs.
```C#
if (cursor.MoveFirst())
{
	do
		cursor.UpdateData();
	while (cursor.MoveNext());
}
```
I'm not sure that the short word `do` deserves it's own line.

And do-while written in three lines looks like VB `Do...Loop` which have no braces but may contain multiple statements inside. For those who writing in both C# and VB the three-line do-while may look confusing without braces.

**Comment by sharwell** [comment]
My vote is no; I feel this proposal runs counter to both #1175 and the general practices encouraged by StyleCop. I'll wait for others to chime in.

`do`...`while` is an interesting case. It's the only control flow construct that I find out of place with respect to SA1519 and SA1520. I don't see an advantage to ever omitting curly braces for this particular case.

**Comment by oatkins** [comment]
Me too :-1: 

Interestingly, IIRC legacy StyleCop required

    do
    {
        // ...
    }
    while (true)

which was fairly daft (prohibiting having the `while` immediately follow the closing brace).

**Comment by alxyr** [comment]
StyleCop.Analyzers prohibits `while` after closing brace too (raises SA1500).

**Comment by GregReddick** [comment]
:-1: I think the way we have it is right.
