### ISSUE TITLE
SA1600 (Elements must be documented) treats members that explicitly implement an interface differently from legacy StyleCop

### ISSUE THREAD

**Issue by oatkins** [DotNetAnalyzers/StyleCopAnalyzers#1370]
(I may have mentioned this before, but can't find the issue.)

Legacy StyleCop treats members that explicitly implement an interface member as if they were private. Since 0960dcd5b6f8551cefd5a7e87460455e92a408d2 we view them as public. (This isn't consistent with its ordering rules, which treat such members as being public.)

I don't know why SC had this behaviour, since it is easy to argue that such a member is usually a publicly accessible member of the type (assuming the interface itself is public). Maybe it's just a side-effect of the member not having an access modifier, which would usually imply private accessibility.

Alternatively—and this is the rationale that seems most reasonable to me—documentation comments are primarily intended to feed Intellisense. An explicitly implemented interface member is never visible in Intellisense except after casting the object to the interface type. Therefore, any documentation against the implementation is never used.

Even where XML comments are used to generate documentation, it would seem reasonable that comments for explicitly implemented interfaces could be obtained directly from the interface rather than its implementation.

**Comment by sharwell** [comment]
:memo: A code fix is provided for this in #1331.

**Comment by oatkins** [comment]
Fair enough. I do prefer the old behaviour, but if I'm on my own on this, then that's fine. The code fix makes it easy to tidy these up.

**Comment by sharwell** [comment]
> Therefore, any documentation against the implementation is never used.

This is a great point BTW. These comments would only ever be used when rendering the documentation with tools like Sandcastle. The only reason I lean away from changing it is it will be *so* easy to clean these up starting (ideally) with Beta 10.

**Comment by oatkins** [comment]
OK. I can live with that.

**Comment by oatkins** [comment]
One more thing to consider...

The compiler rule CS1591 (Missing comment for publicly visible type or member) seems to have similar logic to the old StyleCop behaviour. It is seemingly never reported for explicit interface implementations.
