### ISSUE TITLE
SA1028 does not appear to catch single space after final closing brace

### ISSUE THREAD

**Issue by jedidja** [DotNetAnalyzers/StyleCopAnalyzers#1373]
The following code will pass SA1028, where `·` is a space.

```c-sharp
namespace Foo
{
  public class Bar
  {
    ...
  }
}·
```
Adding multiple spaces will trigger SA1025, and 

```
  }
} // comments goes here·
```

will trigger SA1028. Is this as designed?

**Comment by pdelvo** [comment]
Hi!
Thanks for reporting this!
This looks like a bug to me. The analyzer is looking for a new line to determine if the whitespace is at the end of the line. if the whitespace is at the end if the file there is no new line.

**Comment by sharwell** [comment]
Thanks for the :bug: report!
