### ISSUE TITLE
Rewrite SA1025 code fix to use more efficient text manipulation

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1398]
The performance of the SA1025 code fix is already good, but it would be _even better_ if it performed the fixes using direct `TextChange` operations in the same way that the SA1028 code fix already does.

**Comment by bjornhellander** [comment]
Fixing this!

**Comment by sharwell** [comment]
Marking **wontfix** based on the performance evaluation in #2209.
