### ISSUE TITLE
SA1118 (ParameterMustNotSpanMultipleLines) should designate a span for the warning

### ISSUE THREAD

**Issue by AArnott** [DotNetAnalyzers/StyleCopAnalyzers#1404]
This analyzer does not provide a (non-empty) span for the error, I suppose, since it doesn't show any squiggly line. As a result, Roslyn doesn't give me an option to suppress it.

**Comment by sharwell** [comment]
Can you include a code snippet that reproduces this issue?

**Comment by AArnott** [comment]
Not repro.
My guess is it had something to do with #1391 that caused the problem.
