### ISSUE TITLE
SA1008 reports wrong warning in string interpolation

### ISSUE THREAD

**Issue by chrfin** [DotNetAnalyzers/StyleCopAnalyzers#1407]
If I have the following code:

    fileTitle = $"{fileName}{(FileContainer.HasContentChanged ? "*" : String.Empty)}";

I get a SA1008 warning at the `(` in front of the FileContainer which is wrong IMO.

**Comment by pdelvo** [comment]
Yes this looks like a bug to me. Its a very easy one to fix so Im going to send a PR in a few minutes
