### ISSUE TITLE
Move work out of DocumentBasedFixAllProvider.GetFixAsync

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1411]
As mentioned by @FrankBakkerNl in #947, the current implementation of `DocumentBasedFixAllProvider` performs a great deal of work in `GetFixAsync` which can be moved into the code action instead.

**Comment by FrankBakkerNl** [comment]
Nice and quick fix. I see you avoided adding a CancelationToken parameter to the abstract method FixAllInDocumentAsync() by adding it to the Context, I personally think however it is more clear if it is passed explicitly. 

That way you can also get warnings when you forget to pass it down, like in RemoveRegionFixAllProvider.when calling document.GetSyntaxRootAsync()

**Comment by sharwell** [comment]
@FrankBakkerNl It's important to only pass one `CancellationToken` to a method so it's clear which one is the correct one to use. This is the same reason we *never* pass a `CodeFixContext` to `GetTransformedDocumentAsync` in the various code fixes (`CodeFixContext` does not provide a `WithCancellationToken` method).

Since I couldn't be sure that users wouldn't need some of the other information available in `FixAllContext`, such as the `Scope` property, I decided to continue passing the `FixAllContext` with the correct `CancellationToken` rather than pass the information as individual parameters.
