### ISSUE TITLE
TriviaHelper HasLeadingBlankLines is misleading

### ISSUE THREAD

**Issue by hvanbakel** [DotNetAnalyzers/StyleCopAnalyzers#1418]
I suggest renaming this method to `IsPrecededByBlankLine` as it doesn't check if the token has a leading blank line but checks if it was directly prededed by a blank line.

**Comment by sharwell** [comment]
:+1: The documentation should be updated at the same time to clarify the precise behavior of the method.

Did you want to fix this?

**Comment by hvanbakel** [comment]
sure
