### ISSUE TITLE
SA1623: PropertySummaryDocumentationMustMatchAccessors

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#143]
http://www.stylecop.com/docs/SA1623.html

**Comment by fubar-coder** [comment]
It might be a dumb question, but how are languages other than english supported for this kind of analyzers? You wrote in #600 that the *.ruleset files don't allow custom rule configuration. However, there seems to be a way to show ruleset properties in the properties window, but I don't seem to able to see/change anything there. Maybe it's a not yet implemented feature?

**Comment by sharwell** [comment]
Right now other languages wouldn't be supported by this rule, but it could easily be disabled if you are wiring documentation in another language.

**Comment by Noryoko** [comment]
Grabbing this. I'm thinking this can be combined with SA1624 for one analyzer.
