### ISSUE TITLE
File header code fix should only replace the copyright element

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1434]
An XML file header may contain additional elements, including the following:

1. Horizontal bars (the series of `-----------------` characters)
2. A `<summary>` element
3. Other XML elements
4. Other text outside of XML elements

## Expected behavior

When the file header code fix corrects the `<copyright>` element, each of these other elements should be preserved.

## Actual behavior

When the file header code fix corrects the `<copyright>` element, the entire header is replaced (each of the items is lost).

**Comment by peteri** [comment]
Going to have a look at this as I got burnt by it today.

**Comment by peteri** [comment]
Fixed and pull request issued.
