### ISSUE TITLE
SA1028 falsely reports when [assembly: InternalsVisibleTo("...")] is used at the end of file

### ISSUE THREAD

**Issue by NikolayIT** [DotNetAnalyzers/StyleCopAnalyzers#1445]
I have this file:

    using System.Reflection;
    using System.Runtime.CompilerServices;

    [assembly: AssemblyVersion("1.0.0.0")]
    [assembly: AssemblyFileVersion("1.0.0.0")]

    [assembly: InternalsVisibleTo("SomeLibrary")]

StyleCopAnalyzers falsely reports 

    Warning	SA1028	Code must not contain trailing whitespace

on line 7 (`[assembly: InternalsVisibleTo("Santase.Logic.Tests")]`) character 10 (the space between `[assembly:` and `InternalsVisibleTo("SomeLibrary")]`)

![stylecopbug](https://cloud.githubusercontent.com/assets/3106986/9783014/3a7fb76e-57aa-11e5-9c85-9ee1a24de7b3.png)

**Comment by NikolayIT** [comment]
Adding new line at the end of file fixes the problem but it is a workaround not expected behavior.

**Comment by nbarbettini** [comment]
It's occurring for me as well in beta010. Always on the last line of `AssemblyInfo.cs`, regardless of whether it's an `InternalsVisibleToAttribute`.

**Comment by sharwell** [comment]
It affects any file which does not end with a new line, and which contains non-trailing whitespace on the last line.
