### ISSUE TITLE
Implement SA1130 (UseLambdaSyntax)

### ISSUE THREAD

**Issue by otac0n** [DotNetAnalyzers/StyleCopAnalyzers#1451]
**Category:** Readability
**Rule:** Use lambda syntax over delegate syntax.
**Description:** Replace usages of the `delegate` syntax with lambda expressions.
**Rationale:** Lamda syntax is used more widely and reads easier since it uses fewer characters.

These would yield a warning:

    foo += delegate { x = 0; };
    bar += delegate() { y = 0; };
    baz += delegate(int a, int b) { return a + b; };

This would not:

    var x = A(() => { }); // Expression
    var y = A(delegate { }); // Action

    private Expression<Action> A(Expression<Action> expression)
    {
        return expression;
    }

    private Action A(Action action)
    {
        return action;
    }

**Comment by sharwell** [comment]
:+1:

**Comment by ChrSteinert** [comment]
:+1:

**Comment by Maxwe11** [comment]
:+1:

**Comment by ChrSteinert** [comment]
Why would `var y = A(delegate { });` not yield a warning?

**Comment by Maxwe11** [comment]
@ChrSteinert what do you mean? This rule not implemented yet :smile:

**Comment by ChrSteinert** [comment]
I know, but I want to implement it ;) Sorry, for poor wording.
So the question is, why SHOULD mentioned snipped yield no warning. I'd argue that using delegate anywhere is not wanted. But the initial proposal says that this should be ok. So, why should this be ok?

**Comment by pdelvo** [comment]
Using a lambda expression would change the semantics because now you would call a different overload. The question is if we want to have an exception for these cases or if we want to fix the ambiguosity in a code fix by adding a cast.

**Comment by otac0n** [comment]
Because in that context, blindly converting to the lambda syntax would
change which overload gets called. This is the only case (as far as I was
able to work out) where the syntaxes are treated differently, and I expect
it to be exceedingly rare.

**Comment by ChrSteinert** [comment]
Ahhh of course, now I get it. 
An really ingesting exception for a possible rule.

**Comment by pdelvo** [comment]
Im grabbing this
