### ISSUE TITLE
Investigate failed build 1714

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1459]
It's unclear to me why [build 1714](https://ci.appveyor.com/project/sharwell/stylecopanalyzers/build/1.0.1714) failed. This could point to a bug in the code (or in Roslyn), or to a non-deterministic aspect of the test which just happened to fail this time.

**Comment by ChrSteinert** [comment]
Well, it runs perfectly on my machine (even multiple times). Digging into the supplied stack trace and exception info, I'd say there seemed to be some problem on the build server side. What seems to have failed is the determination of the correct diagnostic location. It says in the logs:
`Expected diagnostic to be in file "Test0.cs" was actually in file ""` so the actual file is empty. This can't be (assuming correct compiler and framework implementations). An exception message is given with `Cannot call Enqueue when the queue is already completed.` but the methods in the stacktrace don't use queues. But there is path matching with `Contains` and the likes with may use queues and may ran out of memory.

I'd say accept this as a hiccup, as the following build succeed and close this issue (for now).

**Comment by vweijsters** [comment]
I had a look around as well and the exception message `Cannot call Enqueue when the queue is already completed.` is generated in the `Enqueue` method of the internal `AsyncQueue` class of Roslyn.

The only code paths that I could find that would touch this method are within `GetAnalyzerDiagnosticsAsync` from `CompilationWithAnalyzers` (in Roslyn).

This method is called in `GetSortedDiagnosticsFromDocumentsAsync` in `DiagnosticVerifier.Helper`. 

Unfortunately there is not enough information available from the original exception (like a call stack) to further pinpoint it. Seems to me its a bug in Roslyn, but without a (semi-) reliable reproduction possibility nothing is sure. Might be a good idea to ask the Roslyn team to add a call stack to exception message for AD0001

**Comment by vweijsters** [comment]
no longer relevant
