### ISSUE TITLE
SA1627: DocumentationTextMustNotBeEmpty

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#147]
http://www.stylecop.com/docs/SA1627.html

**Comment by sharwell** [comment]
:bulb: The implementation of this issue could likely be modeled after SA1614 (#134, #632).

**Comment by pdelvo** [comment]
I think this can be tagged as easy.

**Comment by peteri** [comment]
I'm up for grabbing this.

**Comment by sharwell** [comment]
Go for it :smile:

**Comment by sharwell** [comment]
This was fixed in #1571.
