### ISSUE TITLE
SA1628: DocumentationTextMustBeginWithACapitalLetter

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#148]

**Comment by sharwell** [comment]
Marking **wontfix** based on #1057.

**Comment by dlemstra** [comment]
Woops. It seems I referenced the wrong issue in this pull request: #2242. It should be this one instead of #149. I can still work on #149 once my pull request has been reviewed and merged. You could remove the wontfix from this one if you plan to merge my pull request in the future?
