### ISSUE TITLE
Implementations of IDisposable should check private disposed field in public/internal/protected methods

### ISSUE THREAD

**Issue by jimmyheaddon** [DotNetAnalyzers/StyleCopAnalyzers#1484]
Possibly this falls under a different Analyzer, but it's currently not caught by Code Analysis or any other DotNetAnalyzers.

Essentially if a class correctly implements the IDisposable pattern, then public/internal/protected methods should throw ObjectDisposedException(this.GetType().FullName) as per the majority of .NET framework classes (e.g. Socket).

    if (this.disposed)
    {
        throw new ObjectDisposedException(this.GetType().FullName);
    }

Optionally an XML comment should be declared to reflect this:

    /// <exception cref="ObjectDisposedException">Thrown if this instance of <see cref="ClassName" /> has been disposed.</exception>

**Comment by sharwell** [comment]
This would be more of an FXCop rule than a StyleCop rule. It might make sense to suggest it in the [Proposals](https://github.com/DotNetAnalyzers/Proposals) repository for now. Another option is [dotnet/roslyn-analyzers](https://github.com/dotnet/roslyn-analyzers), which is currently the home of work on FXCop analyzers although I have suggested they be moved into their own repository.

**Comment by jimmyheaddon** [comment]
Thanks @sharwell, I've posted it in both and have linked the two.
