### ISSUE TITLE
SA1629: DocumentationTextMustEndWithAPeriod

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#149]
~~http://www.stylecop.com/docs/SA1629.html~~
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1629.md

**Comment by Noryoko** [comment]
:question: Should this be permanently disabled based on #1057?

**Comment by pdelvo** [comment]
I think it should.

**Comment by peteri** [comment]
Is this going ahead or not? Personally I like this rule (and SA1628) as they help make sandcastle documentation look consistent. But the discussion on #1057 suggests they won't be going in.
I'd guess if they were combined together then the other rules in #1057 wouldn't be too bad for performance (not sure about the spelling).

**Comment by sharwell** [comment]
@peteri I've never found this rule to be a burden. It's relatively easy to implement and provide a code fix for, and I believe complete sentences do help documentation readability.

**Comment by NikolayIT** [comment]
I can implement this if you decide to make it disabled by default but

**Comment by peteri** [comment]
I was going to do this but I've been so busy at work that I've not had time (and I'm unlikely to have much free time until early next year).

I suspect that the code I wrote for SA1627 (pull #1571) could be modified to support both this and SA1628 so the scan of the xml elements only happens once.

**Comment by sharwell** [comment]
It doesn't look like this rule will have a champion for the RC 1 release. Since it's a relatively minor rule, I'm moving it to the **Backlog** milestone to deal with after the 1.0 release.

**Comment by martincostello** [comment]
@sharwell Is there a plan for any further Release Candidates after rc1 before 1.0.0 in February (I'm going by the milestone dates in the Issues tab here)? I wouldn't mind whetting my beak trying to implement this for 1.0.0 if there's enough time left before 1.0.0 and at least one more RC to try it out in.

**Comment by sharwell** [comment]
We might have an RC 2, but we're feature frozen for the 1.0 release. This diagnostic will be in the first post-1.0 beta release at the earliest (which might actually occur before 1.0 stable ships).

**Comment by martincostello** [comment]
@sharwell Fair enough - it being a vNext feature seems reasonable. I'll take a go at picking it up though :)

**Comment by sharwell** [comment]
@martincostello I'm moving this back to **up for grabs**. Let me know if you plan on working on it. :smile:
