### ISSUE TITLE
The change of the version of StyleCop.Analyzers.dll assembly in beta12 forces to recompile dependent code

### ISSUE THREAD

**Issue by alxyr** [DotNetAnalyzers/StyleCopAnalyzers#1496]
The commit https://github.com/DotNetAnalyzers/StyleCopAnalyzers/commit/7228989026b4ecffde725e2ea1ca1edec06caa75 changed the version of StyleCop.Analyzers.dll from 1.0.0.0 to 1.0.0.23. This breaks our custom analyzers which reference StyleCop.Analyzers.dll (we use the helper method `StyleCop.Analyzers.AnalyzerExtensions.RegisterSyntaxTreeActionHonorExclusions` to exclude generated files from analysis).

The error message is `The User Diagnostic Analyzer 'xxxxx' threw an exception of type 'System.IO.FileNotFoundException' with message 'Could not load file or assembly 'StyleCop.Analyzers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=97d9e3aa481481c8' or one of its dependencies. The system cannot find the file specified.'.`

It's no problem to recompile our assembly once to reference the new assembly version but we would like to avoid doing it for each update of StyleCop.Analyzers (which are rather frequent).

**Comment by sharwell** [comment]
@alxyr There are no compatibility guarantees between preview releases. While I have not decided on a final breaking changes model for stable releases, it is likely to focus on other aspects such as stability of the **stylecop.json** format.

Based on the way we have to place **Newtonsoft.Json.dll** in the same folder as **StyleCop.Analyzers.dll**, it seems if another analyzer uses our code then the user no longer has control over which version of this project is used by a project. In the distribution of your custom analyzers, are you including **StyleCop.Analyzers.dll** in the NuGet package or are you simply declaring a dependency in the **.nuspec** file?

**Comment by alxyr** [comment]
@sharwell We just put all analyzer dlls in one folder (StyleCop.Analyzer.dll, Newtonsoft.Json.dll, OurOwnAnalyzer.dll) and reference them from <Analyzer> elements in csproj files. We don't use NuGet and simply replace 2 dlls in the analyzers' folder when need to upgrade StyleCop.Analyzers to a newer version (we have a really big number of csproj files and don't want them all to be modified by NuGet each time we upgrade the analyzers).

All worked perfectly while StyleCop.Analyzer.dll had fixed version number in all betas (1.0.0.0). Now we have to rebuild OurOwnAnalyzer.dll specifically for beta12 (1.0.0.23). If beta13 will change its version to 1.0.0.24, we will have to rebuild OurOwnAnalyzer.dll again.

I'm wondering if there's a way to somehow configure binding redirection in this case.

**Comment by sharwell** [comment]
@alxyr You're going to need to take additional steps when you update to Beta 13 as a result of #1502. However, this will be a one-time change as opposed to breaking with each update.

**Comment by alxyr** [comment]
@sharwell Does it mean (#1502) that won't be able to use 'StyleCop.Analyzers.AnalyzerExtensions.RegisterSyntaxTreeActionHonorExclusions' anymore?

**Comment by sharwell** [comment]
You will be able to, but you'll need to copy the source files which provide that feature into your own project as opposed to just referencing the compiled assembly from this project. This particular functionality should be fairly easy to incorporate. :smile:

**Comment by alxyr** [comment]
So no direct use. I would prefer rebuilding a dll than duplicate code :)
Anyway, thanks for answering.
