### ISSUE TITLE
SA1202 thrown an exception of type KeyNotFoundException

### ISSUE THREAD

**Issue by NikolayIT** [DotNetAnalyzers/StyleCopAnalyzers#1507]
I am not sure when exactly did that message show up but I've deleted a C# class file before the message and then rebuild.
![untitled](https://cloud.githubusercontent.com/assets/3106986/9976157/77159ece-5ee3-11e5-80f1-209de6016ec4.png)
Message text:
```Message	AD0001	The User Diagnostic Analyzer 'StyleCop.Analyzers.OrderingRules.SA1202ElementsMustBeOrderedByAccess' threw an exception of type 'System.Collections.Generic.KeyNotFoundException' with message 'The given key was not present in the dictionary.'.```
Restarting Visual Studio of course fixed the problem.

**Comment by bexxx** [comment]
I think I found a repro case. Took me a while staring at the screen :)

**Comment by bexxx** [comment]
Pull request for fix: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/pull/1740
