### ISSUE TITLE
stylecop rule that corresponds to the resharper namespace resolver

### ISSUE THREAD

**Issue by jimmymain** [DotNetAnalyzers/StyleCopAnalyzers#1522]
Hi,

Resharper already has a built in fix for [namespace and file locations](http://confluence.jetbrains.com/display/ReSharper/Namespace+does+not+correspond+to+file+location)
Stylecop should possibly have a similar enforceable rule?

**Comment by sharwell** [comment]
This looks like a duplicate of #1481. Can you confirm? :smile:

**Comment by Maxwe11** [comment]
it's dup
