### ISSUE TITLE
SA1600 is not working for private methods, fields?

### ISSUE THREAD

**Issue by knoxi** [DotNetAnalyzers/StyleCopAnalyzers#1527]
I have found private methods and fields in my code without comments, but the SA1600 has not detetcted a violation.

```code
        private void ViewerServiceOnProcessChanged(object sender, ProcessChangedEventArgs args)
        {
            ...
        }

        private IViewerDataViewModel viewerDataViewModel;
```

Is it part of the rule or a bug?

I have enabled the SA1652.

**Comment by pdelvo** [comment]
Hi,
by default SA1600 does not enforce documentation on private members but you can enable it in the settings file. See https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md.

**Comment by sharwell** [comment]
Hi @knoxi,

Please let us know if the linked documentation doesn't get things working the way you expect. :smile:

**Comment by knoxi** [comment]
Hi @pdelvo 

Thanks for share the link.

We have over 100 projects in the solution, did we have no chance to share this common settings easier?

**Comment by sharwell** [comment]
You can place your **stylecop.json** file in a common location and use linked documents to include it in each project. It's the same mechanism we used in 59ec26047feb55c040cd021a2e75b4cb09630066.

**Comment by impr3ssi0n** [comment]
I am using StyleCopAnalyzers as .jar plugin for sonarqube generated via sonarqube-roslyn-sdk. Can anyone help me. How can I add this setting?
@sharwell @pdelvo
