### ISSUE TITLE
Proposal: Disable SA1305 (FieldNamesMustNotUseHungarianNotation) by default

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1530]
After reviewing the behavior of SA1305 (implemented in #1526; see pull request for example findings) on several large projects, I found that this rule had a high rate of incorrect or misleading results. In many cases, the violations were reported on fields and variables whose names could certainly be improved, yet the problems with the names did not stem from the use of Hungarian notation.

Since the violations do tend to indicate problematic names (primarily names which are too short), I propose disabling the rule by default. Users who are aware of the caveats of the messaging for this rule can enable it and configure it to behave in much the same way as StyleCop "classic".

**Comment by oatkins** [comment]
> Users... can enable it and configure it to behave in much the same way as StyleCop "classic".

In what way is this implementation different from StyleCop "classic"?

**Comment by sharwell** [comment]
@oatkins The implementation in #1526 should be a close match to the default behavior of StyleCop "classic". However, in the past I've observed this rule to have a high rate of false positives which resulted in either suppressing individual instances or modifying the configuration to exclude additional prefixes.

:memo: I am assuming this rule is enabled by default in StyleCop "classic".

**Comment by oatkins** [comment]
I think it is enabled by default, but most people probably have several exceptions in their settings files.

I would prefer to see it enabled by default too, but perhaps that's only reasonable if we also provide a means to migrate existing settings files to the new json format.

**Comment by vweijsters** [comment]
I would prefer to see this disabled by default. I find it too much trouble to configure all exceptions for an extremely low rate of positives.

**Comment by hvanbakel** [comment]
:+1: I agree on the large number of incorrect violations.

**Comment by oatkins** [comment]
I think you have your quorum. Happy to go along with the majority.

**Comment by GregReddick** [comment]
I have found that most of my exceptions are one letter prefixes that StyleCop considered to be Hungarian. Things like xMargin. I frequently added all the one letter prefixes to be allowed, then added two letter groups that it complained about. The thing that should be caught is that short prefixes are frequently abbreviations or acronyms, which should be discouraged in .NET code unless they are very well known (such as HTML). If rule SA1650 picks up that all two letter combinations must be dictionary words or added to the CodeAnalysisDictionary, then SA1305 doesn't have that much point.
