### ISSUE TITLE
StyleCopPlus rules

### ISSUE THREAD

**Issue by szilardd** [DotNetAnalyzers/StyleCopAnalyzers#1531]
Is there a plan in the future to implement StyleCopPlus rules (http://stylecopplus.codeplex.com), the most useful ones would be the advanced naming rules and the ones relating to the number of lines allowed in a property, method or file  ?

Configuration would be done in stylecop.json, not through a UI like StyleCopPlus does.

**Comment by sharwell** [comment]
Duplicate of #782 (don't feel bad, it took me a while to find it too).

See that issue for status and description of next steps if you are interested in these rules.
