### ISSUE TITLE
Integrate code coverage reporting in our CI builds

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1538]
We do a decent job with coverage right now, but it would be even better if we actively tracked this.

**Comment by Maxwe11** [comment]
Can pick up this. Also if you want stable reference with badge to the latest report you should register project on coveralls.io and provide project key.

**Comment by sharwell** [comment]
I was planning to compare the features of a few different options. Coveralls.io is one, but I wanted to look at codecov.io as well.

**Comment by Maxwe11** [comment]
okay, also note that coveralls.io have a tool for uploading reports which could be picked up through nuget (like nuget command line tool)
