### ISSUE TITLE
Consider making defaults compatible with dotnet code style

### ISSUE THREAD

**Issue by NickAb** [DotNetAnalyzers/StyleCopAnalyzers#1558]
.NET Foundation has published code style, and some StyleCop checks enabled by default contrary to those of dotnet code style. I think it should be considered making StyleCop checks in sync with dotnet standard to proliferation of minor discrepancies and need to reconfigure tools. Maybe it can be done with providing an optional standard config file that will make StyleCop checks in sync with dotnet style.

Here are some checks that are not in sync
SX1309 and SX1309 EnabledByDefault
SA1309 and SA1200 DisabledByDefault

See https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md and https://github.com/dotnet/codeformatter

**Comment by sharwell** [comment]
Unfortunately due to the policy of supporting existing StyleCop users (which has been in place for several years), this isn't going to be possible in the requested manner. However, I've been thinking of some ways to make configuration more reliable and this goal may benefit as a result.

**Comment by GregReddick** [comment]
I far prefer the StyleCop style to the .NET Foundation code style. Alternates should be allowed, but the StyleCop defaults should stay where they are.
