### ISSUE TITLE
Implement a fix all provider for SA1500 (CurlyBracketsForMultiLineStatementsMustNotShareLine)

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1565]
I received an exception trying to fix all instances of this violation in a project today. The problem stems from poor memory behavior of the batch fixer, and both the error and the performance problems could be resolved by implementing a custom fix all provider for this diagnostic.

**Comment by vweijsters** [comment]
Grabbing this
