### ISSUE TITLE
SA1513 reported when I wouldn't expect it

### ISSUE THREAD

**Issue by berkeleybross** [DotNetAnalyzers/StyleCopAnalyzers#1583]
I'm getting a violation of SA1513 (ClosingCurlyBracketMustBeFollowedByBlankLine) reported when I'm not expecting it. It's possible it's what you guys expect, but on the off chance it's a bug I thought I'd report it :)

``` CSharp
var target = isIFrame
    ? new Dictionary<string, string>
        {
            { "target", "_parent" }
        } // <-- SA1513 Violation reported here
    : new Dictionary<string, string>();
```

**Note**: The following code is not raising the issue, but personally I think it's an unnecessary new line that isn't helping readability.

``` CSharp
var target = isIFrame
    ? new Dictionary<string, string>
        {
            { "target", "_parent" }
        }

    : new Dictionary<string, string>();
```

 What do you think?

**Comment by sharwell** [comment]
I wouldn't expect SA1513 here. I think the readability of the sample code could be improved, but the problem isn't due to a missing newline after the `}`.

Marked :bug: up for grabs. :smile:

**Comment by vweijsters** [comment]
Grabbing this
