### ISSUE TITLE
SA1502 documentation does not match behavior

### ISSUE THREAD

**Issue by appel1** [DotNetAnalyzers/StyleCopAnalyzers#1594]
On https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1502.md it says that short properties, events and indexers are allowed to be on one line but it doesn't look like the code matches that. The following property causes a violation for example. 

```csharp
public IFoo Foo { get { return this.foo; } }
```

**Comment by sharwell** [comment]
The documentation says the following (emphasis mine):

> As an exception to this rule, *accessors within* properties, events, or indexers are allowed to be written all on a single line, as long as the accessor is short.

The example property would look like the following using a single-line accessor:

```csharp
public IFoo Foo
{
    get { return this.foo; }
}
```

The only two cases where a complete property may be written on one line are auto-properties and expression-bodied properties.

```csharp
// auto-property
public IFoo Foo { get; }

// expression-bodied
public IFoo Foo => this.foo;
```

**Comment by appel1** [comment]
You're right. I misread.
