### ISSUE TITLE
Analyzers as Extension to Install for all Projects

### ISSUE THREAD

**Issue by huserben** [DotNetAnalyzers/StyleCopAnalyzers#1607]
Hi
as far as I saw it is currently not possible to install the Stylecop Analyzers once per Visual Studio and have them active for all loaded projects by default?
As in our department we want to have the checks enabled by default, we would very much like to have this possibility instead of installing it for every project.
Is this somehow planned?

Keep up the good work and thank you in advance

**Comment by sharwell** [comment]
Hi @huserben,

When analyzers are installed as part of the Visual Studio instance, they only run while the IDE is open. In addition, they do not run during the build process, even inside the instance of Visual Studio where the analyzer is installed. If you use a rule set file to increase the severity of one or more rules to Error, this change will also be ignored by the build process.

While the above limitations are suitable for certain purposes during the development of StyleCop.Analyzers itself, they work directly against attempts to set policy like you are looking for. As such, while some other analyzers are available in VSIX form I've chosen not to include one as part of this project's releases. I believe it would add confusion for users, who would likely be under the impression that the VSIX worked as well as the NuGet package.

**Comment by daflotsch** [comment]
I know this is closed but my request goes in the same direction: My main problem with having StyleCop.Analyzer added to all 70 projects in our solution is, that the build takes some minutes longer than without the nuget package installed.
I tried to reduce warnings and everything, but it is still much much slower.

My thought was, if there was an extension which does not effect the build at all, we could benefit from the features without the cost of the IDE to validate the rules on each build. (In all projects the property enable code analysis on build is disabled of course)

Is there another way to avoid the checks on each build or is this just how it has to work?   

Thank you!

**Comment by sharwell** [comment]
@daflotsch We're working on the build performance issue in #1618 and dotnet/roslyn#6053.

**Comment by Livven** [comment]
@daflotsch There's a way to disable analyze on build in #1711. I know super late but may be useful to someone.
