### ISSUE TITLE
SA1201 - Support order customisation

### ISSUE THREAD

**Issue by kawazoe** [DotNetAnalyzers/StyleCopAnalyzers#1610]
I think having the ability to customize the ordering of elements, specially inside classes/structs/interfaces, would be a valuable addition to this rule. I personally find the default order not so great and prefer to see non-executable code elements like interfaces, enums and classes before executable ones like fields, properties, and methods. To me, this better highlight that there might be a need to move some of this code inside their own files.

**Comment by sharwell** [comment]
I'm going to leave this open for some discussion, but I'll be up front and say I highly doubt this will occur as part of *this* project. The element ordering rules were some of the most time consuming rules to get right and this would only increase our testing burden.

That said, we intentionally licensed this project to allow people to take the code and modify it as necessary to create new rules which differ in ways we do not currently support. By disabling rule SA1201 (and a few other related rules), you could install both StyleCop.Analyzers and KawazoesOrderingAnalyzer into the same project, and get behavior very much like you requested.

**Comment by vweijsters** [comment]
Either way would be fine with me. I usually disable SA1201 anyways, as I prefer the have all methods that belong to a certain functionality together, regardless of the access modifier and static keyword.

**Comment by Piedone** [comment]
It would be great to have more customizability for the ordering rules indeed, expanding on [what's available](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md#element-order). E.g. be able to define custom order for the elements checked by [SA1201](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1201.md).

**Comment by sharwell** [comment]
Resolving as **wontfix** per https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2541#issuecomment-533150009.

**Comment by mickyman007** [comment]
> It would be great to have more customizability for the ordering rules indeed, expanding on [what's available](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md#element-order). E.g. be able to define custom order for the elements checked by [SA1201](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1201.md).

I tried doing this, and updated the schema so customization is possible, it's working for me, but I can't provide any guarnantees, check it out: https://github.com/mickyman007/StyleCopAnalyzers/tree/CustomElementOrderSA1201

**Comment by Piedone** [comment]
Very interesting, thank you!
