### ISSUE TITLE
SA1642: ConstructorSummaryDocumentationMustBeginWithStandardText

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#162]
http://www.stylecop.com/docs/SA1642.html

**Comment by sharwell** [comment]
@pdelvo If you want to work on another documentation item, this one would be particularly high-value for me.

**Comment by sharwell** [comment]
I would approve of restricting the allowed documentation forms that reference the name of the declaring class to the following:

* For a non-generic class: `<see cref="TypeName"/>`
* For a generic class: `<see cref="TypeName{T1, T2}"/>` (where `T1` and `T2` are the names of the generic type parameters for the class)

This excludes the following forms:

* Failing to wrap the name in a `<see>` element.
* Referencing a generic type without including the generic type parameters. For example `<see cref="Tuple"/>` and `<see cref="Tuple{T1, T2}"/>` reference completely different types.
* Using the metadata name <code>Tuple`2</code> instead of the name with generic type parameters.

**Comment by pdelvo** [comment]
Im taking a look at this
