### ISSUE TITLE
Support for ExcludeFromSourceAnalysis seems to be missing

### ISSUE THREAD

**Issue by fubar-coder** [DotNetAnalyzers/StyleCopAnalyzers#1626]
This would allow the exclusion of files at project level:

```xml
<Compile Include="Service\ServiceInstaller.cs">
  <ExcludeFromSourceAnalysis>true</ExcludeFromSourceAnalysis>
</Compile>
```

**Comment by sharwell** [comment]
Is this a duplicate of #726?

**Comment by fubar-coder** [comment]
Yes, it is. I missed that there was already a ticket for this. Sorry for the inconvenience

**Comment by sharwell** [comment]
No problem. :smile: I wasn't sure since the MSBuild properties used here differed slightly from the one described in #726.

**Comment by fubar-coder** [comment]
Yes, it's slightly different, but it's for the same things as far as I can see.
