### ISSUE TITLE
SA1643: DestructorSummaryDocumentationMustBeginWithStandardText

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#163]
http://www.stylecop.com/docs/SA1643.html

This is low priority because my general rule is:

> If you find yourself writing a user-defined finalizer in C#, you are *probably* doing something wrong.

To my knowledge, there is *only one* required finalizer (outside of the .NET Framework source code) which is included in a project I've worked on.

**Comment by pdelvo** [comment]
grabbed. Even though it is a very low priority one it is very easy to implement because SA1642 is already implemented
