### ISSUE TITLE
Rule proposal: All Assembly Attributes should appear in the AssemblyInfo.cs file.

### ISSUE THREAD

**Issue by GregReddick** [DotNetAnalyzers/StyleCopAnalyzers#1639]
Having an assembly attribute in any other (non-generated) file should produce a warning.

**Comment by sharwell** [comment]
I don't have a link handy, but I think the way I used TypeForwardedTo in the dotnet-threading library makes sense but breaks this rule. 

Right now I'm leaning against this rule because I've never seen a project break the rule in a way that made me want to fix it.

**Comment by sharwell** [comment]
Here's a [specific example of `TypeForwardedTo` usage](https://github.com/tunnelvisionlabs/dotnet-threading/blob/master/Rackspace.Threading/IProgress%601.cs#L9) like I was mentioning.

**Comment by vweijsters** [comment]
:question: How would this work with a pattern where several projects are using a shared file called `CommonAssemblyInfo.cs` that most assembly attributes in it, combined with an `AssemblyInfo.cs` per project that has the (few) assembly specific attributes in it?

**Comment by NikolayIT** [comment]
It is a common practice for `[assembly: OwinStartup(typeof(Startup))]` to be placed inside the `Startup.cs` in ASP.NET MVC 5 applications.

Also

    [assembly: PreApplicationStartMethod(typeof(NinjectWebCommon), "Start")]
    [assembly: ApplicationShutdownMethod(typeof(NinjectWebCommon), "Stop")]

is commonly placed inside `NinjectWebCommon.cs` in ASP.NET applications

**Comment by GregReddick** [comment]
Given the above situations. I withdraw this rule proposal.
