### ISSUE TITLE
SA1644: DocumentationHeadersMustNotContainBlankLines

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#164]
~~http://www.stylecop.com/docs/SA1644.html~~
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1644.md

**Comment by sharwell** [comment]
I think this rule had good intentions, but it's the wrong actual rule to use. I think we should implement this by making sure paragraphs are wrapped in block-level elements. Two spans of text are considered part of different paragraphs if there is a blank documentation line between them. An example of two paragraphs separated by a blank line can be seen in [**SA1616ElementReturnValueDocumentationMustHaveText.cs**](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/SA1616ElementReturnValueDocumentationMustHaveText.cs#L14-L20)

**Comment by sharwell** [comment]
It doesn't look like this rule will have a champion for the RC 1 release. Since it's a relatively minor rule and even has some disagreement (from me :wink: ), I'm moving it to the **Backlog** milestone to deal with after the 1.0 release.

**Comment by sharwell** [comment]
@vweijsters @pdelvo Any objection to closing this rule as **won't fix**? It's not especially helpful for readability, and the other items discussed above are already implemented in [DotNetAnalyzers/DocumentationAnalyzers](https://github.com/DotNetAnalyzers/DocumentationAnalyzers).

**Comment by vweijsters** [comment]
No objection from me. I don't find this rule very useful.
