### ISSUE TITLE
Rule Proposal: An assembly should have an AssemblyCopyright attribute.

### ISSUE THREAD

**Issue by GregReddick** [DotNetAnalyzers/StyleCopAnalyzers#1640]
All projects should have an AssemblyCopyright attribute. Since the Berne convention in 1988, all code is copyrighted anyway, so should give the date of publication and the owner. If you really want to place the project in the public domain, the AssemblyCopyright attribute should have the value "In the public domain".

**Comment by sharwell** [comment]
This seems better suited to be an FXCop/API design guideline analyzer rather than a C# source code style analyzer. I like the rule concept but am :-1: on including it as a StyleCop rule.

**Comment by vweijsters** [comment]
I agree with @sharwell here

**Comment by sharwell** [comment]
@GregReddick This seems conceptually close to [CA1016: Mark assemblies with AssemblyVersionAttribute](https://msdn.microsoft.com/en-us/library/ms182155.aspx). I recommend proposing this rule either in [dotnet/roslyn-analyzers](https://github.com/dotnet/roslyn-analyzers) (the temporary home for former code analysis rules being written as analyzers), or in [DotNetAnalyzers/Proposals](https://github.com/DotNetAnalyzers/Proposals).

:bulb: Consider initially making one proposal for all assembly attributes, and mention that the implementation would include several distinct diagnostics to report the various violations. This will make it easier to discuss the proposal and figure out where it will finally live.
