### ISSUE TITLE
Rule proposal: An AssemblyInformationVersion attribute should be in the project with the correct value.

### ISSUE THREAD

**Issue by GregReddick** [DotNetAnalyzers/StyleCopAnalyzers#1643]
The Application.UserAppDataPath or Application.UserAppDataRegistry properties reference paths and registry keys by building a string from the AssemblyCompany, AssemblyProduct, and AssemblyInformationalVersion attributes. If this attribute is not present, then the value in AssemblyVersion attribute is used instead. If the wildcard is used in the AssemblyVersion attribute, the compiler will change the build and revision number on each build causing information stored on the disk and registry to be stored in a different directory or registry key.

The AssemblyInformationalVersion attribute is used to provide a consistent version number for this version of the product. It should be changed along with the AssemblyVersion attribute number when the major or minor version is changed.

So the rule should check to make sure that the attribute is present, and that it has the same value as the Major and Minor version of the AssemblyVersion attribute.

**Comment by vweijsters** [comment]
:-1: Similar to the discussion in #1640

**Comment by sharwell** [comment]
Right now I'm :-1: for the same reason as #1640.

**Comment by sharwell** [comment]
:arrow_right: See #1640 for my recommendation for proposing this rule as a code analysis warning rather than a StyleCop analyzer.
