### ISSUE TITLE
Rule proposal: A project should have a NeutralResourcesLanguageAttribute

### ISSUE THREAD

**Issue by GregReddick** [DotNetAnalyzers/StyleCopAnalyzers#1646]
If an assembly contains resources, the NeutralResourcesLanguages attribute identifies that the assembly shares the language neutral resources and the language specified in the attribute. This makes it clear to .NET that it does not need to look for a satellite assembly for that language. In most cases, the value specified will be the codes for the language and country of the programming team, and the default language of the user interface. This value is set to the RFC 1766 (https://tools.ietf.org/html/rfc1766) specifier for the language and country of the neutral resources.

Even if the assembly does not have any resources, the attribute indicates the language and country of the comments specified by the developers.

The rule should check that it is in the project (presumably in the AssemblyInfo.cs file) and give a warning if it is not present.

**Comment by vweijsters** [comment]
:-1: Similar to the discussion in #1640

**Comment by sharwell** [comment]
Right now I'm :-1: for the same reason as #1640.

**Comment by sharwell** [comment]
:arrow_right: See #1640 for my recommendation for proposing this rule as a code analysis warning rather than a StyleCop analyzer.
