### ISSUE TITLE
SA1645: IncludedDocumentationFileDoesNotExist

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#165]
http://www.stylecop.com/docs/SA1645.html

**Comment by pdelvo** [comment]
I was looking into this and I saw that this diagnostic is a dublicate. A missing documentation file for an include is already reported by the compiler itself as [CS1589](https://msdn.microsoft.com/en-us/library/3y857kz5(v=vs.90).aspx).

**Comment by sharwell** [comment]
:question: Would it make sense to include unit tests proving it solves the intended problem? It might be possible to locate some reference tests in the Roslyn repository.

**Comment by sharwell** [comment]
I agree with disabling this. It helps keep this project out of the business of probing the file system. :+1:
