### ISSUE TITLE
SA1010 and SA1013 conflict in some circumstances

### ISSUE THREAD

**Issue by yaakov-h** [DotNetAnalyzers/StyleCopAnalyzers#1657]
Here's an example where SA1010 and SA1013 conflict. The Dictionary can be replaced with inline property setting (`new Thing { Prop = value }`) as long as it's immediately followed by an indexer, but the principle is the same.

```
namespace SampleApp
{
    using System.Collections.Generic;

    public class Class1
    {
        public static void Main(string[] args)
        {
            var banana = new Dictionary<string, string> { { "foo", "banana" } }["foo"];
        }
    }
}
```

SA1013 says a closing curly bracket must be followed by a space, so the line should be:
```
            var banana = new Dictionary<string, string> { { "foo", "banana" } } ["foo"];
```

However, then SA1010 says that an opening square bracket must not be preceded by a space, so the line should be:
```
            var banana = new Dictionary<string, string> { { "foo", "banana" } }["foo"];
```

The only resolution I've found is to break out the object initialization into a variable.

**Comment by sharwell** [comment]
I find the example much more readable when written as:

```csharp
var banana = "banana";
```

I've never seen a case where the described form appeared and it didn't make sense to simplify it. Is this just a hypothetical situation or are there other cases where someone might want to use this?

Currently my vote is to not make any changes, as the indicated form is not readable regardless of the spacing. When working with an initializer and indexer, at minimum it makes sense to separate the initializer as part of a local variable, and then use the local variable with an indexer for the second statement:

```csharp
var fooBanana = new Dictionary<string, string> { { "foo", "banana } };
var banana = fooBanana["foo"];
```

**Comment by vweijsters** [comment]
I agree with the analysis of @sharwell  here

**Comment by yaakov-h** [comment]
I agree that the example I provided is illogical, but I couldn't recall what the actual code was that had triggered this.

I looked it up this morning, it was this function in a WPF application:

```
		internal static T GetResource<T>(string name)
		{
			var uri = new Uri("/AssemblyNameHere;component/Path/To/Resource.xaml", UriKind.Relative);
			return (T)new ResourceDictionary { Source = uri }[name];
		}
```

I resolved the StyleCop violation by changing it to the following:

```
		internal static T GetResource<T>(string name)
		{
			var uri = new Uri("/AssemblyNameHere;component/Path/To/Resource.xaml", UriKind.Relative);
			var resourceDictionary = new ResourceDictionary { Source = uri };
			return (T)resourceDictionary[name];
		}
```

Yes it is simplifiable, however the guidance from the Code Fixes is to insert whitespace, then to remove it, then to insert it and then to remove it, forever.

I'd suggest that in a case such as this, where neither rule accepts it, the guidance should be to break it out into a separate variable.

**Comment by sharwell** [comment]
@yaakov-h The rules for special cases can get pretty complicated, especially when we're talking about code fixes. If you think of a specific proposal for new behavior (both when it should apply, and exactly how it should be applied), please feel free to open a new issue with a complete description of the proposed behavior. For now I'm going to mark this as **resolved**.
