### ISSUE TITLE
SA1646: IncludedDocumentationXPathDoesNotExist

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#166]
http://www.stylecop.com/docs/SA1646.html

**Comment by pdelvo** [comment]
The compiler already checks this (SA1589). See #165.

**Comment by sharwell** [comment]
:question: Would it make sense to include unit tests proving it solves the intended problem? It might be possible to locate some reference tests in the Roslyn repository.

**Comment by sharwell** [comment]
I agree with disabling this. It helps keep this project out of the business of probing the file system. :+1:
