### ISSUE TITLE
SA1649 (FileHeaderFileNameDocumentationMustMatchTypeName) should allow GenericType`1.cs pattern

### ISSUE THREAD

**Issue by AArnott** [DotNetAnalyzers/StyleCopAnalyzers#1664]
The dotnet/corefx and other repos contain projects that follow the convention of naming files after their CLR-type names (which uses the tilda syntax). For example: `List<T>` would appear in a file called 
    
     List`1.cs

Ideally this rule would not fire a warning for such a file name.

Related to #1662

**Comment by sharwell** [comment]
This is already supported by the `metadata` file naming convention. You can enable it in **stylecop.json** by following the steps in [Configuration.md](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md#file-naming-conventions).

**Comment by AArnott** [comment]
Oh! Awesome.
