### ISSUE TITLE
SA1129DoNotUseDefaultValueTypeConstructor throws System.NullReferenceException

### ISSUE THREAD

**Issue by vweijsters** [DotNetAnalyzers/StyleCopAnalyzers#1668]
Got this AD0001 message while (heavily) editing source code in VS2015 using beta 14.

> The User Diagnostic Analyzer 'StyleCop.Analyzers.ReadabilityRules.SA1129DoNotUseDefaultValueTypeConstructor' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.

I haven't been able to reproduce it yet.

**Comment by GregReddick** [comment]
I just recently got this on the release community edition. There is no file associated with the error, so it is hard to isolate what is causing it.

**Comment by NikolayIT** [comment]
I've just got this exception:

	Message	AD0001	The User Diagnostic Analyzer 'StyleCop.Analyzers.ReadabilityRules.SA1129DoNotUseDefaultValueTypeConstructor' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	TexasHoldem.Logic		1	Analyzer 'StyleCop.Analyzers.ReadabilityRules.SA1129DoNotUseDefaultValueTypeConstructor' threw the following exception:
	'System.NullReferenceException: Object reference not set to an instance of an object.
	   at StyleCop.Analyzers.ReadabilityRules.SA1129DoNotUseDefaultValueTypeConstructor.HandleObjectCreationExpression(SyntaxNodeAnalysisContext context)
	   at StyleCop.Analyzers.AnalyzerExtensions.<>c__DisplayClass4_0`1.<RegisterSyntaxNodeActionHonorExclusions>b__0(SyntaxNodeAnalysisContext c)
	   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass35_0`1.<ExecuteSyntaxNodeAction>b__1()
	   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze)'.

**Comment by pontusi** [comment]
I've had this error happen twice, but it disappears when I reopen the solution making reproduction hard. Trace matches Nikolay's.

My project contains classes that use the ["implicit operator"](https://msdn.microsoft.com/en-us/library/z5z9kes2.aspx) to convert from integers and strings. That may or may not be relevant.

**Comment by vweijsters** [comment]
Grabbing this
