### ISSUE TITLE
SA1647: IncludeNodeDoesNotContainValidFileAndPath

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#167]
http://www.stylecop.com/docs/SA1647.html

**Comment by pdelvo** [comment]
The compiler has CS1590 for this.

**Comment by sharwell** [comment]
:question: Would it make sense to include unit tests proving it solves the intended problem? It might be possible to locate some reference tests in the Roslyn repository.

**Comment by sharwell** [comment]
I agree with disabling this. It helps keep this project out of the business of probing the file system. :+1:
