### ISSUE TITLE
SA1107 (multiple statements on one line) incorrectly reported when previous line is missing semicolon.

### ISSUE THREAD

**Issue by otac0n** [DotNetAnalyzers/StyleCopAnalyzers#1670]
As you can see from the screenshot, the preceding line is missing its semicolon.  This is getting incorrectly detected as two statements on the same line. The code fix also results in strange indentation.

![New Line Error](http://i.imgur.com/qOAW8Zh.png)

**Comment by pdelvo** [comment]
In what version did you experience this? I think #1543 should have fixed that.

**Comment by otac0n** [comment]
Yeah, it was a while ago, I just had the screenshot sitting around still.
