### ISSUE TITLE
New rules for test classes and names

### ISSUE THREAD

**Issue by emanoelxavier** [DotNetAnalyzers/StyleCopAnalyzers#1673]
I have been using some custom StyleCop rules (v 4.7) to enforce things like test class and test method names for different types of tests (unit, functional, etc) within my team. These rules are there to enforce that our test code is consistent with our test approach and vision. It also facilitate test discovery and readability on Visual Studio, TFS, reports etc. I find that it might be beneficial to share these rules with others and would like to publish them on GitHub. While reading a bit more about StyleCop I came across this port to Roslyn. So I have a few questions:
1. It seems that instead of publishing my SyleCop v 4.7 Analyzers it might be better to port them to Roslyn. So I would like to confirm if I correct on that assumption. In other words, is this port the way to go forward with StyleCop?
2. I believe that rather than having those custom Analyzers added as part of this repository It might be better to create a new repository since those would not be part of the core StyleCop Analyzers but an additional set of custom rules. Are there other repositories where people are creating new custom Analyzers for Roslyn or is most of the contributions in these core rules?

Thanks.
Emanoel

**Comment by sharwell** [comment]
> In other words, is this port the way to go forward with StyleCop?

We believe that it is.

> Are there other repositories where people are creating new custom Analyzers for Roslyn or is most of the contributions in these core rules?

The most actively developed single repositories containing Roslyn analyzers (to my knowledge) are [DotNetAnalyzers/StyleCopAnalyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers), [dotnet/roslyn-analyzers](https://github.com/dotnet/roslyn-analyzers), and [code-cracker/code-cracker](https://github.com/code-cracker/code-cracker).

It is my personal belief that a set of analyzers like you describe would make sense as a separate repository and NuGet package. We did something similar with [DotNetAnalyzers/AsyncUsageAnalyzers](https://github.com/DotNetAnalyzers/AsyncUsageAnalyzers) for analyzers targeting async usage patterns. If you are interested, one option is to create your new repository as part of the DotNetAnalyzers organization on GitHub, allowing it to be developed separately from StyleCopAnalyzers but still be visible among other repositories for developing analyzers.

**Comment by sharwell** [comment]
I'm going to close this issue as **external**, but if you have further questions on this subject please feel free to add additional comments and I'll answer them as best I can. :smile:

**Comment by emanoelxavier** [comment]
Thanks a lot for the prompt response and guidance Sam. I am definitely be interested on this "one option is to create your new repository as part of the DotNetAnalyzers organization on GitHub, allowing it to be developed separately from StyleCopAnalyzers". I think it would be good to increase the visibility of these new analyzers. Let me get started and have something in place first and then I will ping you to have this new repository created under the DotNetAnalyzers  org.

Cheers,
Emanoel

**Comment by emanoelxavier** [comment]
Hi Sam,

I am finally ready to start working on the unit test analyzers. Can we have the repo DotNetAnalyzers/UnitTestAnalyzers created?

Thanks!
Emanoel

**Comment by emanoelxavier** [comment]
Hi Sam,

Any news on this?

Thanks,
Emanoel
