### ISSUE TITLE
SA1500 does not handle complex element initializer expressions

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1679]
During a code review today I observed that SA1500 does not handle `SyntaxKind.ComplexElementInitializerExpression`. This should be reviewed to determine if it is a bug or not.

**Comment by vweijsters** [comment]
I think this is a bug. All other initializer expressions are handled by SA1500, to me this is clearly an oversight, as this one was introduced in C# 6.

**Comment by sharwell** [comment]
Is this the new syntax for dictionary initializers?

**Comment by vweijsters** [comment]
As far as I know, yes.

**Comment by vweijsters** [comment]
Grabbing this

**Comment by vweijsters** [comment]
Apparently I was wrong. Complex initializer expressions are like:
```C#
var dictionary = new Dictionary<string, string> { { "foo", "bar" }, { "baz", "qux" } };
```

**Comment by vweijsters** [comment]
Still a bug though :wink:
