### ISSUE TITLE
SA1648 does not handle certain member declarations

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1680]
During a code review today I observed that SA1648 does not handle `SyntaxKind.DestructorDeclaration`, `SyntaxKind.OperatorDeclaration`, or `SyntaxKind.ConversionOperatorDeclaration`. This should be reviewed to determine if it is a bug or not.

**Comment by vweijsters** [comment]
I think we can close this. None of these types are inheritable. For more details:
- Destructors cannot be inherited (CSharp Language Specification v5.0 - §10.13)
- Operators cannot be inherited because they must be static (CSharp Language Specification v5.0 - §10.10)

**Comment by vweijsters** [comment]
These kinds are not inheritable, therefore using `/// <inheritdoc/>` on them should produce a diagnostic. I think this is a bug.

**Comment by sharwell** [comment]
Agreed. Also, this matches the behavior we use for documentation comments on fields.

**Comment by vweijsters** [comment]
Grabbing this
