### ISSUE TITLE
SA1506 does not handle certain declarations

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1681]
During a code review today I observed that SA1506 does not handle `SyntaxKind.EnumMemberDeclaration`, `SyntaxKind.OperatorDeclaration` or `SyntaxKind.ConversionOperatorDeclaration`. This should be reviewed to determine if it is a bug or not.

**Comment by sharwell** [comment]
This looks like a bug to me.

**Comment by nbarbettini** [comment]
I can grab this one, if no one else has their eye on it!
