### ISSUE TITLE
Suppress missing file header with pragma adds invalid leading trivia

### ISSUE THREAD

**Issue by bexxx** [DotNetAnalyzers/StyleCopAnalyzers#1685]
The cs file start with:

```csharp
//*********************************************************
// Copyright (c) Microsoft. All rights reserved.
// This code is licensed under the MIT License (MIT).
...
//*********************************************************
```

This get me a SA1633 (OK).
When I select Suppress with pragma, the whole block gets indented (unexpected).

**Comment by sharwell** [comment]
This functionality is part of Roslyn itself. I recommend you file this issue in the [dotnet/roslyn](https://github.com/dotnet/roslyn) issue tracker.
