### ISSUE TITLE
Proposal: Merge assemblies to avoid adding Newtonsoft.Json to analyzers

### ISSUE THREAD

**Issue by fubar-coder** [DotNetAnalyzers/StyleCopAnalyzers#1698]
I'd like to see that Newtonsoft.Json isn't added to analyzers anymore. This could be achieved by merging Newtonsoft.Json into the StyleCop.Analyzers (and StyleCop.Analyzers.CodeFixes?) assembly. There are several tools out there like [ILMerge](http://research.microsoft.com/en-us/people/mbarnett/ilmerge.aspx), [LibZ](https://libz.codeplex.com/), and [IL-Repack](https://github.com/gluck/il-repack).

**Comment by appel1** [comment]
Why not change the install and uninstall scripts to exclude it instead?

**Comment by fubar-coder** [comment]
AFAIK it's added automatically by NuGet and those install/uninstall scripts aren't run on DNX projects - and they are quite unreliable.

**Comment by sharwell** [comment]
I recommend filing this as a bug with the Roslyn team to improve the user experience around the requirement that dependencies be installed as analyzers. Starting with Beta 15, we have two such dependencies exposed in the UI, and other analyzer projects 

Merging the assembly is not necessary for functionality (as established in #1624) and would slow down the build. The UI improvement would be questionable at best. I don't think there's anything to be done here at least until the Roslyn team looks at the issue again.
