### ISSUE TITLE
Add more ways to exclude files from Analysis

### ISSUE THREAD

**Issue by johnnyelwailer** [DotNetAnalyzers/StyleCopAnalyzers#1699]
In our project using legacy StyleCop, we put an `//<unstyled/>` comment on top of the file, I know there's an `<autogenerated>` comment but 'unstyled' would be more fitting.

Addidtionally we used this GeneratedFileFIlters to exclude things like EF Migrations. It looks like this:
````xml
 <CollectionProperty Name="GeneratedFileFilters">
   <Value>\.g\.cs$</Value>
   <Value>\.generated\.cs$</Value>
   <Value>\.g\.i\.cs$</Value>
   <Value>\.xaml\.cs$</Value>
   <Value>\.aspx\.cs$</Value>
   <Value>Form\.cs$</Value>
   <Value>Mixin\.cs$</Value>
   <Value>SpecFlow_\d*\.cs$</Value>
   <Value>SpecFlow_\d*\.feature\.cs$</Value>
   <Value>Generation\.cs$</Value>
   <Value>Designer\.cs$</Value>
   <Value>(\d{15})_(.*)\.cs$</Value>
 </CollectionProperty>
```
Exclusions of generated files using a custom filter is quite an essential feature for large projects.

**Comment by sharwell** [comment]
I see two different proposals here. The GeneratedFilesFilter description would probably best be placed in #1430 (it is a more general approach to the same problem). The `//<unstyled/>` comment would be a new feature.

**Comment by Sam13** [comment]
In classic StyleCop there is also the possibility to exclude certain files via
`<Compile Include="File.cs">
  <ExcludeFromStyleCop>true</ExcludeFromStyleCop>
</Compile> ` 
in the project file.
Support for something similar would be great for upgrade scenarios from classic StyleCop to that one,...

**Comment by sharwell** [comment]
@Sam13 That's filed separately as issue #726.

**Comment by sharwell** [comment]
Starting with 1.1 Beta 1, generated files (detection and exclusion) are handled entirely by Roslyn itself.
