### ISSUE TITLE
Violation of some rules only generate IntelliSense errors, but not build errors

### ISSUE THREAD

**Issue by mzervos** [DotNetAnalyzers/StyleCopAnalyzers#1718]
Some rules (like SA1642) produce InitelliSense errors but the project builds successfully without reporting those errors. I'm using beta15 version.
I don't see any warnings/errors on msbuild logs (i have set verbosity to Diagnostic)

![code](https://cloud.githubusercontent.com/assets/1730009/10866016/01ac27ec-7fdc-11e5-9b74-80a555c17ba5.png)
![build_intellisense](https://cloud.githubusercontent.com/assets/1730009/10866015/ffb08bae-7fdb-11e5-8ca1-e129c978f493.PNG)
![build](https://cloud.githubusercontent.com/assets/1730009/10866014/fcb0c036-7fdb-11e5-9d10-261ef35cf832.PNG)
![settings](https://cloud.githubusercontent.com/assets/1730009/10866039/177df298-7fdd-11e5-8e97-65f153cba2aa.PNG)

**Comment by sharwell** [comment]
Do you see any **AD0001** instances in your diagnostic build output?

**Comment by mzervos** [comment]
No. I couldn't find anything weird in the build output. Here it is: http://pastebin.com/Rz5g9rgs

**Comment by mzervos** [comment]
I notice the same behavior for the following rules:
SA1514
SA1609
SA1642
SA1643

**Comment by sharwell** [comment]
@mzervos Thanks, that's very helpful. We recently fixed similar issues in a number of spacing rules. Currently I'm not sure what's causing the discrepancy for the rules you identified but we'll figure it out! :smile:

**Comment by sharwell** [comment]
@mzervos Do you have SA1652 disabled?

**Comment by mzervos** [comment]
Yes, SA1652 is disabled. If I enabled it, the other rules cause errors on build as well.
Is this the expected behavior or is it a bug?
I'd prefer to be able to enable the other rules without having to enable XML documentation output.

**Comment by sharwell** [comment]
> I'd prefer to be able to enable the other rules without having to enable XML documentation output.

This is not possible. SA1652 should not be disabled, even if you are not using the output files. See the [documentation for SA1652](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1652.md) for more information.

**Comment by mzervos** [comment]
How are they enabled and detected on IntelliSense though without having SA1652 turned on?

**Comment by sharwell** [comment]
> How are they enabled and detected on IntelliSense though without having SA1652 turned on?

I have no idea actually. It could be that Roslyn uses special settings for the IntelliSense parser in order to properly apply syntax highlighting and other editor features inside of documentation comments, but these are disabled when compiling unless the XML output is enabled. I'm going to mark this as **external** since it's other case where the underlying cause of dotnet/roslyn#2773 is causing problems.
