### ISSUE TITLE
SX1309S is close but not quite right for CoreClr guidelines

### ISSUE THREAD

**Issue by rkeithhill** [DotNetAnalyzers/StyleCopAnalyzers#1723]
This rule needs to enforce `s_` prefix for private/internal static (non-readonly) fields. See #3 here:

https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md

**Comment by sharwell** [comment]
This particular rule wasn't created as a corefx rule. I've been thinking about how this can be better generalized, but I'm not quite ready to make a proposal.

**Comment by sharwell** [comment]
Marking as invalid, since the current behavior was by design. I am confident this will be revisited in the future (after the 1.0 release) when we shift focus to supporting a wider variety of usage scenarios.
