### ISSUE TITLE
ExcludeFromStyleCop should accept True as well as true

### ISSUE THREAD

**Issue by rkeithhill** [DotNetAnalyzers/StyleCopAnalyzers#1727]
I was wondering why StyleCop.Analyzers wasn't skipping a file and it was because I used the value `True` which is prevalent in CSPROJ file.  It seems to me that both `True` and `true` should be accepted.

**Comment by sharwell** [comment]
Currently StyleCop Analyzers doesn't support ExcludeFromStyleCop at all. This is a duplicate of #726.

**Comment by rkeithhill** [comment]
Yeah, I just noticed that.  Thought it was working but no.  :-(
