### ISSUE TITLE
Documentation rules inside of setting file not working

### ISSUE THREAD

**Issue by arashk1368** [DotNetAnalyzers/StyleCopAnalyzers#1731]
Hi, 

I tried to use the option of not requiring documentation of internal members as instructed in https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md

``` csharp
 "documentationRules": {
      "documentInterfaces": true,
      "documentInternalMembers": false
    }
```

However, it does not work. I closed visual studio and re-opened it. Added the file to additional files but, none of them worked. 
Even this element is not defined in the schema.

**Comment by arashk1368** [comment]
Sorry it was a mistake in the definition of the settings file.

**Comment by sharwell** [comment]
@arashk1368 It turns out this was a legitimate bug report. Thanks for filing it and sorry I missed it!

**Comment by arashk1368** [comment]
@sharwell Thank you for reopening. Currently we are using the schema like the following and it works for the internal members. I did not test the interface option with the new versions though.
`{
  "$schema": "https://raw.githubusercontent.com/DotNetAnalyzers/StyleCopAnalyzers/master/StyleCop.Analyzers/StyleCop.Analyzers/Settings/stylecop.schema.json",
  "settings": {
    "documentationRules": {
      "documentInternalElements": false
    }
  }
}`

**Comment by sharwell** [comment]
Yes, the setting was always called `documentInternalElements` in code. The mistake was one location in the documentation which referred to it by a different name.
