### ISSUE TITLE
DiagnosticVerifier.VerifyDiagnosticResults should cope with non-deterministic Roslyn behavior

### ISSUE THREAD

**Issue by vweijsters** [DotNetAnalyzers/StyleCopAnalyzers#1734]
Currently `DiagnosticVerifier.VerifyDiagnosticResults` does check the order in which expected diagnostics occur. This occasionally leads to failed tests, because the order in which diagnostics are produced by Roslyn is not (always) deterministic at the moment.

Also see dotnet/roslyn#372 and dotnet/roslyn#1506 for details

**Comment by sharwell** [comment]
Marking this as a :bug: since we shouldn't have been making these assumptions from the start.

**Comment by sharwell** [comment]
Grabbed
