### ISSUE TITLE
Convert UsingCodeFixProvider use of IsAnalyzerSuppressed to configuration

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1744]
Currently the behavior of `UsingCodeFixProvider` varies based on whether or not SA1200 is suppressed. The code fix should not rely on this type of configuration; the behavior should instead be exposed as an explicit option in **stylecop.json**.

**Comment by vweijsters** [comment]
I don't agree. The end user would not benefit from this. He/she would have to remember to correctly configure the **stylecop.json** file, besides enabling/disabling the desired analyzers. The goal of the current behavior is to generate correct code based on the analyzers enabled and that cannot be done more efficiently by adding a configuration setting.

**Comment by sharwell** [comment]
:memo: I responded to this in #1747.
