### ISSUE TITLE
Convert SA1210 (UsingDirectivesMustBeOrderedAlphabeticallyByNamespace) use of IsAnalyzerSuppressed to configuration

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1747]
Currently the behavior of SA1210 (UsingDirectivesMustBeOrderedAlphabeticallyByNamespace) varies based on whether or not SA1208 is suppressed. The analyzer should not rely on this type of configuration; the behavior should instead be exposed as an explicit option in **stylecop.json**.

**Comment by vweijsters** [comment]
Are you talking about the UsingCodeFixProvider or the SA1210 analyzer here?

**Comment by sharwell** [comment]
This one is the analyzer. Sorry about the copy/paste confusion. :smile:

**Comment by vweijsters** [comment]
Then I don't agree. Adding a configuration option would only make things more difficult for the end user, as the option in the **stylecop.json** file would only be another way of indicating that SA1208 is suppressed. Unless we eliminate one of the analyzers, there is in my opinion no elegant solution.

**Comment by sharwell** [comment]
@vweijsters The goal here is to make the analyzer configuration deterministic. There are two limitations which this will overcome:

1. The current behavior does not allow users to disable problematic analyzers (e.g. for performance reasons, to avoid bugs, or in cases where they are not yet ready to address violations reported by the analyzer) without changing the behavior of other analyzers which they are ready to include.
2. I've had people express the desire to have a command line tool which runs analyzers for various reporting purposes. It will be easier to ensure the tool produces results consistent with the analyzers executing during a build if the behavior of individual analyzers is independent from enabling/disabling other analyzers, especially considering that the current analyzers are sensitive to the *manner* in which analyzers are enabled/disabled.

**Comment by vweijsters** [comment]
Fair points, but I still have issues with disabling functionality in two places, but there may be a way around that. My suggestion would be to make the setting leading, effectively giving it the power to disable (parts of) certain analyzers.

For example:
If there would be a configuration option called **systemUsingsFirst** and it would have a value of **false**, would it be acceptable to make SA1208 do nothing then?

**Comment by sharwell** [comment]
> If there would be a configuration option called **systemUsingsFirst** and it would have a value of **false**, would it be acceptable to make SA1208 do nothing then?

Absolutely :+1:

**Comment by vweijsters** [comment]
@sharwell would you be so kind to amend the mentioned issues with the proposed configuration settings and their effect?

**Comment by sharwell** [comment]
@vweijsters  Good point. I removed the **up for grabs** label from each of the affected issues until I can get this information in.
