### ISSUE TITLE
SA1649 ignores delegate types

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1757]
Currently SA1649 does not treat a top-level delegate as a type, and thus ignores it for the purpose of checking the name of a class. Since delegates are compiled to types, they should be considered by this diagnostic.

@vweijsters Do you have any objections to me marking this as a :bug:?

**Comment by vweijsters** [comment]
I'm not sure, but I'm leaning towards a no. All depends on the usage scenarios of top level delegates. I personally never use them, but if a common usage scenario is to define several of them in one file, people might get annoyed by having to name the file after the first delegate. 

I also did a quick test with StyleCop classic and it does not flag top level delegates for SA1649.

**Comment by sharwell** [comment]
Marking **wontfix**, at least for now.
