### ISSUE TITLE
Implement SA1135: Using directives must be qualified

### ISSUE THREAD

**Issue by 0x084E** [DotNetAnalyzers/StyleCopAnalyzers#1761]
In Visual Studio 2015 if you add a using directive via quick actions inside of a namespace the namespace in the using statement is cut down if a part of the included namespace is also part of the outer namepsace.

E.g.: You Are In N1.N2 and you include N1.N2.N3 it is cut down to N3
`namepsace N1.N2 { using N3; }`
You are in N1.N2 and include N1.N4.N5 it is cut down to N4.N5
`namepsace N1.N2 { using N4.N5; }`

I think this is problematic since you do not know what the namespace actually is. In the second example I would think from the context that N4 is contained in N1.N2 but it is not. What's your opinion?

**Comment by sharwell** [comment]
I've been back and forth on this issue. I think it does make sense though, and I also think most existing code using StyleCop Classic would already follow this rule.

:+1:

**Comment by vweijsters** [comment]
:+1: I prefer the explicit clarity without me having to puzzle at what point the common part starts.

**Comment by 0x084E** [comment]
I've mentioned one more problem: Consider the namepsaces `System.Xml``System.Xml.Linq` and `System.Linq`. If you want to import a type from `System.Xml.Linq` or `System.Linq` into `System.Xml` the analyzer is smart enough to detect that importing one of them as `Linq` would result in a not resolvable using and imports it qualified.
If either of `System.Xml.Linq` or `System.Linq` doesn't exist at the time of importing it is imported as `Linq` (of course) but if you add it after importing your code won't compile anymore...

**Comment by vweijsters** [comment]
Grabbing this. 

My proposal for the name is: `SA1135 Using directives must be fully qualified`

**Comment by sharwell** [comment]
@vweijsters There is already a pull request open for this (#1762)

**Comment by 0x084E** [comment]
@vweijsters You can undertake it if you want. Maybe someone with more knowledge about roslyn can do it better. I just did it myself because I really wanted to have it.

**Comment by vweijsters** [comment]
I missed the pull request :blush: 

@0x084E no point in me redoing the work. I'll have a look at the pull request.

**Comment by icnocop** [comment]
For reference, @sharwell has since merged https://github.com/DotNetAnalyzers/StyleCopAnalyzers/pull/1979 to work around the issue reported in https://github.com/dotnet/roslyn/issues/7446.

**Comment by sharwell** [comment]
@tdworshak Can you file a new bug for that? 👍

**Comment by tdworshak** [comment]
Sure thing: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2690
