### ISSUE TITLE
New rule proposal: "Naming": All async methods should end with "Async".

### ISSUE THREAD

**Issue by bexxx** [DotNetAnalyzers/StyleCopAnalyzers#1786]
All methods declared in source with an async modifier should end with "Async" in their name.

Most probably this should not fire on methods that just return Task or Task<T>.

**Comment by vweijsters** [comment]
:-1: This is rule is already present in https://github.com/DotNetAnalyzers/AsyncUsageAnalyzers and for me that is the correct place.

**Comment by bexxx** [comment]
nice! Thanks for this link!
Agree, let's not duplicate work.
