### ISSUE TITLE
Update using directive code fix to support blank lines between groups

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1787]
As mentioned by @vweijsters during code review in #1785:

> We [should] also add a setting that will insert blank lines between the top-level groups, as described in [CoreFx coding guidelines](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md) point 6.

Marking as **needs discussion** since this will require a new configuration property which we haven't named yet.

**Edit:** Rule SA1516 would be updated to report violations according to this setting. The supported values would be **allow** (default), **require**, and **omit**, just like we implemented for a similar situation in #1820.

**Comment by vweijsters** [comment]
:+1:

**Comment by sharwell** [comment]
I'm marking this as a proposal.

**Comment by rkeithhill** [comment]
Yes, please make this change to better support the CoreFx coding guidelines.

**Comment by vweijsters** [comment]
:+1: (including the edit)

**Comment by vweijsters** [comment]
Grabbing this
