### ISSUE TITLE
Mishit with rule SA1513

### ISSUE THREAD

**Issue by ursenzler** [DotNetAnalyzers/StyleCopAnalyzers#1789]
The following code cannot be made violation free:

```
            using (var p = new Process
            {
                StartInfo =
                          {
                              FileName = yedPath,
                              Arguments = outputPath
                          }
            })
            {
                p.Start();
            }
```

Either there is no blank line after closing `}` or there are spaces before `)` on line 8 `})`

**Comment by vweijsters** [comment]
This has been fixed with #1752, but there is no release yet with that fix in it unfortunately.

**Comment by ursenzler** [comment]
Thanks for the info.

**Comment by sharwell** [comment]
@ursenzler The beta 16 release is now available and includes this fix!
