### ISSUE TITLE
Does not support 'Class Library (Package)' Projects (*.xproj File Extension)

### ISSUE THREAD

**Issue by RehanSaeed** [DotNetAnalyzers/StyleCopAnalyzers#1814]
Adding the StyleCop.Analyzers NuGet package to the new 'Class Library (Package)' project type with the .xproj file extension has no effect. No analyzers are visible.

**Comment by sharwell** [comment]
This *seems* like a bug in the project system, but I've never used this type of project so I'm not sure.

**Comment by RehanSaeed** [comment]
The project does not contain a list of the files within it. As long as files are in the same folder as the xproj file, they are included in the project. Most likely, this is why StyleCop.Analyzers is having trouble.

**Comment by sharwell** [comment]
Is this a duplicate of #806?

**Comment by RehanSaeed** [comment]
Yes

**Comment by sharwell** [comment]
:+1: Thanks! :smile:
