### ISSUE TITLE
SA1649 - File name must match first type name - false positive error

### ISSUE THREAD

**Issue by soerennielsen** [DotNetAnalyzers/StyleCopAnalyzers#1829]
This rule mistakenly fires for files with double postfix names, i.e. 

File "AppEventReceiver.svc.cs"

That contains class:
	public class AppEventReceiver : AppEventReceiverBase

Will fire the rule. It shouldn't and it doesn't in the original stylecop tool. .

Fix should be fairly easy by using the filename "before the first dot" instead of "filename without extension" for matching the class name. 

And thanks for a great tool :-)

**Comment by sharwell** [comment]
Thanks for the report. I think that makes sense, and it should definitely be an easy fix :+1:

**Comment by sharwell** [comment]
Well this didn't qualify as easy after all - it required modifications to the test framework to allow testing these cases. But I got it working!

**Comment by soerennielsen** [comment]
Fantastic, thanks! :-) 

Looking forward to RC1.
