### ISSUE TITLE
SA1401 Fix raises SA1101

### ISSUE THREAD

**Issue by ischas** [DotNetAnalyzers/StyleCopAnalyzers#1833]
If I have this code:

```csharp
public class Test
{
    protected readonly bool IsATest;
}
```

StyleCop.Analyzers recommends:

```csharp
public class Test
{
    private readonly bool isATest;
    protected bool IsATest
    {
        get
        {
            return isATest;
        }
    }
}
```

Now StyleCop raises a SA1201. The fixed code should look like this:

```csharp
public class Test
{
    private readonly bool isATest;
    protected bool IsATest
    {
        get
        {
            return this.isATest;
        }
    }
}
```

Notice the added `this.`.

**Comment by sharwell** [comment]
The code fix for SA1401 is provided by Visual Studio. The first thing to check is that you have the following option checked:

![image](https://cloud.githubusercontent.com/assets/1408396/11424491/4436d008-9413-11e5-9229-d99e66b26ba7.png)

If you have this checked and the problem still occurs, then this is actually a bug in Roslyn or Visual Studio, and I would recommend filing a bug in the [dotnet/roslyn](https://github.com/dotnet/roslyn) repository to get it fixed.
