### ISSUE TITLE
SA1623 - Property summary documentation in private class

### ISSUE THREAD

**Issue by roadz99** [DotNetAnalyzers/StyleCopAnalyzers#1844]
After updating to Beta 17 I am getting SA1623 reported for the following scenario (note the class is private):

    private class TestClass
    {
        /// <summary>
        /// Gets the name
        /// </summary>
        public string Name { get; private set; }
    }

It thinks that the summary should start with "Gets or sets". The analyzer gets confused because the effective accessibility of the getter/setter is determined to be private due to the fact that is in contained in a private class.
I started trying to fix this but it's rather tricky. It's a low priority for me because we very rarely use private classes.

For what it's worth, I think the following unit test should pass.

        [Theory]
        [InlineData("public", "int", "{ get; set; }", "Gets or sets")]
        [InlineData("public", "int", "{ get; protected set; }", "Gets or sets")]
        [InlineData("public", "int", "{ get; protected internal set; }", "Gets or sets")]
        [InlineData("public", "int", "{ get; internal set; }", "Gets")]
        [InlineData("public", "int", "{ get; private set; }", "Gets")]
        [InlineData("public", "int", "{ get; }", "Gets")]
        [InlineData("public", "int", "{ get; } = 0;", "Gets")]
        [InlineData("public", "int", "=> 0;", "Gets")]
        [InlineData("public", "int", "{ set { } }", "Sets")]
        [InlineData("public", "int", "{ internal get { return 0; } set { } }", "Sets")]
        [InlineData("public", "int", "{ private get { return 0; } set { } }", "Sets")]
        [InlineData("public", "bool", "{ get; set; }", "Gets or sets a value indicating whether")]
        [InlineData("public", "bool", "{ get; }", "Gets a value indicating whether")]
        [InlineData("public", "bool", "{ get; } = true;", "Gets a value indicating whether")]
        [InlineData("public", "bool", "=> true;", "Gets a value indicating whether")]
        [InlineData("public", "bool", "{ get; private set; }", "Gets a value indicating whether")]
        [InlineData("public", "bool", "{ set { } }", "Sets a value indicating whether")]
        [InlineData("public", "bool", "{ private get { return false; } set { } }", "Sets a value indicating whether")]
        [InlineData("protected", "int", "{ get; private set; }", "Gets")]
        [InlineData("protected", "int", "{ private get { return 0; } set { } }", "Sets")]
        [InlineData("protected internal", "int", "{ get; internal set; }", "Gets")]
        [InlineData("protected internal", "int", "{ get; private set; }", "Gets")]
        [InlineData("protected internal", "int", "{ internal get { return 0; } set { } }", "Sets")]
        [InlineData("protected internal", "int", "{ private get { return 0; } set { } }", "Sets")]
        [InlineData("internal", "int", "{ get; private set; }", "Gets")]
        [InlineData("internal", "int", "{ private get { return 0; } set { } }", "Sets")]
        public async Task VerifyDocumentationOfPublicMethodInPrivateClassWillProduceDiagnosticAsync(string accessibility, string type, string accessors, string expectedArgument)
        {
            var testCode = $@"
    public class TestClass
    {{
        private class PrivateTestClass
        {{
            /// <summary>
            /// The first test value.
            /// </summary>
            {accessibility} {type} TestProperty {accessors}
        }}
    }}
    ";

            var fixedTestCode = $@"
    public class TestClass
    {{
        private class PrivateTestClass
        {{
            /// <summary>
            /// {expectedArgument} the first test value.
            /// </summary>
            {accessibility} {type} TestProperty {accessors}
        }}
    }}
    ";

            var expected = this.CSharpDiagnostic(PropertySummaryDocumentationAnalyzer.SA1623Descriptor).WithLocation(9, 11 + accessibility.Length + type.Length).WithArguments(expectedArgument);

            await this.VerifyCSharpDiagnosticAsync(testCode, expected, CancellationToken.None).ConfigureAwait(false);
            await this.VerifyCSharpDiagnosticAsync(fixedTestCode, EmptyDiagnosticResults, CancellationToken.None).ConfigureAwait(false);
            await this.VerifyCSharpFixAsync(testCode, fixedTestCode).ConfigureAwait(false);
        }

**Comment by sharwell** [comment]
@vweijsters What did StyleCop Classic report in this case?

**Comment by sharwell** [comment]
According to the documentation, "restricted accessibility" is defined as one accessor method being accessible to a larger number of members than the other. In the example above, this is certainly the case. I believe the solution for this is to use the *declared* accessibility instead of the *effective* accessibility.

**Comment by roadz99** [comment]
Yes it is that simple. My unit tests pass after that change. Since you've started I'll leave you to work on it.

**Comment by sharwell** [comment]
I used your unit test, but I massively simplified the accessibility checks (down to two lines). I'll post a code review soon.

**Comment by vweijsters** [comment]
The proposed solution is not correct. There is a bug in the implementation regarding the private setter mentioned in the example, but the implementation is correct for other cases. Below the relevant quote from the documentation:

> 3 The property is private or is contained beneath a private class, and the set accessor has any access modifier other than private.

**Comment by sharwell** [comment]
@vweijsters That's the conclusion I came to as well.

**Comment by vweijsters** [comment]
Point 1 does not cover everything, for example an public property with a protected setter should have the Gets or sets text.

I would say `public`, `protected` and `protected internal` must be document, as these are part of the public API of a component.  Internal and private should not be documented. It could be a future extension to control flagging of internals with a property in the settings file.

The second point is part of the C# language specification (section 10.7.2), so no need to do anything there.

**Comment by sharwell** [comment]
@vweijsters The rules I suggested as preferable are certainly not equivalent to the documented rules. I was just saying they would be easier to explain, and much easier to implement.

**Comment by vweijsters** [comment]
@sharwell I figured that much and I think that would be a good thing. The point I was trying to make is that your suggested rules do not cover all cases that I think should be documented, the given example being the most prominent issue.

I do think that it is desirable to simplify the rules, hence the alternative suggestion in my post.

**Comment by sharwell** [comment]
I think I finally figured this out... PR coming if tests actually pass.
