### ISSUE TITLE
Diagnostic unit tests: CommasMustBeSpacedCorrectly

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#185]
Implement unit tests for #7.

**Comment by camilojd** [comment]
I can take this, as well as #264!

**Comment by sharwell** [comment]
Sweet, a new contributor :+1: :smiley: 

@camilojd I sent you an invitation to join the DotNetAnalyzers organization. Once you do, I can assign the issue to you. Of course you are free to work on it in the meantime; other users can see that you commented. :+1:

**Comment by sharwell** [comment]
Fixed in #457 and #458.
