### ISSUE TITLE
Auto-Generated Files Still Require Documentation

### ISSUE THREAD

**Issue by vermiceli** [DotNetAnalyzers/StyleCopAnalyzers#1867]
I've enabled documentation checking SA1600 by enabling XML documentation in the project properties.  This works well. However, stylecop is forcing files with `// <auto-generated` to have documentation, even though all other stylecop warnings are disabled.

I think there is a bug where the documentation rule doesn't know that the file is auto-generated.

I've attached an example.  You can see that stylecop isn't checking SA1500 on the brace, but it is still forcing documentation.

![auto-generated example](https://cloud.githubusercontent.com/assets/1617040/11478710/95cc000e-975c-11e5-8e88-3584ec301e6b.png)
![xml output setup](https://cloud.githubusercontent.com/assets/1617040/11478711/95db98ac-975c-11e5-9cba-c4bbcea38ab5.png)

**Comment by sharwell** [comment]
You are seeing CS1591, which is a warning produced by the C# compiler. See the [How to fix violations](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1652.md#how-to-fix-violations) section of the SA1652 documentation for more information on how to handle this warning.

**Comment by vermiceli** [comment]
@sharwell Thank you very much.  I didn't realize that the error was a code analysis issue and not a stylecop issue.

In case someone gets this error and finds #1697, I'm mentioning the issue here so that people may realize that the error isn't from stylecop.
