### ISSUE TITLE
SA1133CodeFixProvider crash

### ISSUE THREAD

**Issue by vbfox** [DotNetAnalyzers/StyleCopAnalyzers#1878]
Given the following code :

```csharp
namespace Stylecop_rc1_bug_repro
{
    using System;

    internal class Program
    {
        [Foo, Bar]
        private static void Main(string[] args)
        {
        }
    }

    internal class FooAttribute : Attribute
    {
    }

    internal class BarAttribute : Attribute
    {
    }
}
```

SA1133 is raised on `Bar` usage but activating the CodeFix throw an exception :

```text
Exception thrown: 'System.InvalidCastException' in StyleCop.Analyzers.CodeFixes.dll

Additional information: Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.AttributeListSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.AttributeSyntax'.

   at StyleCop.Analyzers.ReadabilityRules.SA1133CodeFixProvider.<GetTransformedDocumentAsync>d__5.MoveNext()
```

(*VS2015 update 1, StyleCop 1.0 RC1*)

**Comment by sharwell** [comment]
Thanks for the report!

I am very much hoping this reproduces the problem in our unit tests. :smile:

**Comment by NikolayIT** [comment]
This code is enough to reproduce the problem. 

I've created a new branch in my fork in order to try fixing the issue. Here is the repro test: https://github.com/NikolayIT/StyleCopAnalyzers/commit/f25bde0e7eb2efa9e6a936e72dcbaf112606a968

**Comment by NikolayIT** [comment]
Well, that was very easy to fix. I am sending pull request in a minute.

**Comment by sharwell** [comment]
@NikolayIT Make sure to send your pull request to the **stabilization** branch instead of the default **master** branch.

**Comment by NikolayIT** [comment]
@sharwell did it :smile:
