### ISSUE TITLE
Update SA1642 (ConstructorSummaryDocumentationMustBeginWithStandardText) to handle included documentation

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1917]
The issue described in #1603 applies to SA1642 as well.

**Comment by peteroupc** [comment]
This issue appears to be reappearing for me, in that this check seems not to expand included documentation even if that documentation contains the required text.

Here is a class which exhibits this issue.

    namespace MyNamespace {
      public class MyClass {
        /// <include file='docs.xml'
        /// path='docs/doc[@name="MyClassCons"]/*'/>
        public MyClass(int x){ }
      }
    }

Note that the include file references a file called `docs.xml`, which is as follows for the purposes of this report:

    <docs><doc name="MyClassCons">
    <summary>Initializes a new instance of the <see cref='MyClass' /> class.</summary></doc></docs>

**Comment by sharwell** [comment]
@peteroupc Can you create a new issue for this?
