### ISSUE TITLE
Diagnostic unit tests: SA1008 (OpeningParenthesisMustBeSpacedCorrectly)

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#193]
Implement unit tests for #14.

**Comment by sharwell** [comment]
Make sure to consider #683 during testing of this analyzer.

**Comment by sharwell** [comment]
Make sure to consider #876 during testing of this analyzer.

**Comment by vweijsters** [comment]
Grabbing this
