### ISSUE TITLE
RC2: NullReferenceException in SA1606

### ISSUE THREAD

**Issue by qmfrederik** [DotNetAnalyzers/StyleCopAnalyzers#1937]
After upgrading to RC2 from Beta15, I'm seeing the following exception occur frequently:

```
Analyzer 'StyleCop.Analyzers.DocumentationRules.SA1606ElementDocumentationMustHaveSummaryText' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null.
Parameter name: s'
```

If there's anything I can do to capture & provide additional information, let me know

**Comment by pdelvo** [comment]
Hi!

Thanks for reporting this :bug:!
The analyzer that is crashing here is (relatively) complicated. In the error dialog there is a small arrow next to the exception. If you expand this visual studio will show the stack trace. You can copy & paste that.

Also some code that reproduces this problem would be great.

**Comment by qmfrederik** [comment]
Here's the stack trace:

```
'System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at System.IO.StringReader..ctor(String s)
   at System.Xml.Linq.XElement.Parse(String text, LoadOptions options)
   at StyleCop.Analyzers.DocumentationRules.ElementDocumentationSummaryBase.HandleDeclaration(SyntaxNodeAnalysisContext context, SyntaxNode node, Location[] locations)
   at StyleCop.Analyzers.DocumentationRules.ElementDocumentationSummaryBase.HandleFieldDeclaration(SyntaxNodeAnalysisContext context)
   at StyleCop.Analyzers.AnalyzerExtensions.<>c__DisplayClass8_0`1.<RegisterSyntaxNodeActionHonorExclusions>b__0(SyntaxNodeAnalysisContext c)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass38_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze)'.
```

Visual Studio doesn't indicate the path to a source file, and the projects are relatively large, so I can't easily provide you with a piece of code that reproduces this issue (yet).

Hope the stack trace helps!

**Comment by sharwell** [comment]
Thanks for the additional information @qmfrederik. I'm believe this will be enough to reproduce and correct the issue, but I'll let you know if we run into trouble. :smile:

**Comment by qmfrederik** [comment]
Hi @sharwell 

Thanks for the feedback. Yes, this code uses `<include>` statements.

Since it's causing a crash, would you consider removing the support for `<include>` statements alltogether then?

**Comment by sharwell** [comment]
@qmfrederik We're definitely going to get this fixed, and I expect it to be included in the "1.1.0 Beta 1" release, possibly even before 1.0.0 stable is released. The question was just whether or not to include it in 1.0 stable, which would require a new RC release and reset the 30-day clock counting down to the 1.0 release.

**Comment by AArnott** [comment]
I'm seeing NREs thrown from lots of analyers in a new project I just installed it to. I'll be happy to verify the fix for this against that repro when it's ready.

**Comment by sharwell** [comment]
@AArnott The handling for `<include>` elements was only added to SA1604, SA1606, and SA1615. If you are seeing the crashes only in those analyzers then it could be related. Otherwise you should probably file a new issue.
