### ISSUE TITLE
SA1623 code fix throws exception for empty summary

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1943]
The code fix for SA1623 throws an exception when attempting to fix the following code:

```csharp
public class ClassName
{
    /// <summary></summary>
    public int Property
    {
        get;
    }
}
```

**Comment by NikolayIT** [comment]
@sharwell, What should the code fix do when given empty summary?

I am suggesting replacing the code with

```cs
public class ClassName
{
    /// <summary>Gets Property</summary>
    public int Property
    {
        get;
    }
}
```

**Comment by sharwell** [comment]
> What should the code fix do when given empty summary?

I vote for nothing at all.

**Comment by NikolayIT** [comment]
@sharwell doing nothing will leave the warning :smile:

**Comment by sharwell** [comment]
Yes, the warning would remain because this is a situation where we cannot provide a meaningful code fix.
