### ISSUE TITLE
CSharpTestForEmptyStringsUsingStringLengthAnalyzer throws null reference exception

### ISSUE THREAD

**Issue by BGrojer** [DotNetAnalyzers/StyleCopAnalyzers#1964]
CSC (0): Analyzer 'System.Runtime.Analyzers.CSharpTestForEmptyStringsUsingStringLengthAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.

We face this problem with the RC Version for multiple .NET 4.6 projects.

**Comment by sharwell** [comment]
I believe the particular analyzer you refer to is part of an unrelated set of analyzer. Hopefully someone else can confirm this?

**Comment by BGrojer** [comment]
I'm sorry its related to System.Runtime.Analyzers :-(
