### ISSUE TITLE
Improve SA1129 code fix for enum types

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#1972]
Currently the SA1129 code fix replaces `new TaskState()` with `default(TaskState)`. An improved code fix for enum types would be the following:

* If a single member `Member` in the enum declaration `T` has the value 0, replace `new T()` with `T.Member`
* Otherwise, replace `new T()` with `default(T)` (i.e. fall back to the current behavior)

**Comment by nbarbettini** [comment]
For this and #1973, does it makes sense to just keep expanding the existing code fix with additional branches? Or should this be split into separate diagnostics/fixes?

**Comment by vweijsters** [comment]
Either way you will have to create additional branches, as splitting into separate diagnostics/fixes will require exceptions to be added to the current implementation.

I would therefore prefer to go with extending the existing code fix, as adding exceptions for more specific diagnostics / fixes have not been problem free (For examples I'm thinking of SA1003 and SA1020-SA1024, but there are more).

**Comment by nbarbettini** [comment]
Grabbing this.

**Comment by nbarbettini** [comment]
@sharwell To clarify, do you mean "enum declaration `T` has only one member", or "enum declaration `T` has one member with value 0, among many members"?

**Comment by sharwell** [comment]
I meant the latter. :smile:
