### ISSUE TITLE
RC2: analyzers don't pick up stylecop.json

### ISSUE THREAD

**Issue by aensidhe** [DotNetAnalyzers/StyleCopAnalyzers#1975]
Hello.

We are using beta15 version and it's working good, but with upgrade to RC2 our build is broken. We have several solutions in our repo and we share `stylecop.json` and `fxcop.ruleset`. But one project also using msbuild feature of including project files to reduce clutter and to unify versioning, output folders and also including of stylecop.json file.

So, including file, named `common.props` is included into every project and it has this section:
````
<PropertyGroup>
    <CompanySolutionDir>$(MSBuildThisFileDirectory)</CompanySolutionDir>
    <StyleCopJsonPath>$(CompanySolutionDir)..\stylecop.json</StyleCopJsonPath>
</PropertyGroup>

  <ItemGroup>
    <None Include="$(StyleCopJsonPath)">
      <Link>stylecop.json</Link>
    </None>
  </ItemGroup>
````

On beta15 everything is good: stylecop.json was read by analyzers and all settings from file applied, but in RC2 either file is not read or settings somehow broken, because analyzers don't see company name and other setttings in file.

Attachment contains minimal solution and directory structure to reproduce this behavior.

[BugInStyleCop.zip](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/files/67777/BugInStyleCop.zip)

**Comment by vweijsters** [comment]
The mechanism for including stylecop.json has been changed between beta15 and RC2, due to the many problems that people were experiencing with the old mechanism. More information can be found in [EnableConfiguration.md](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/EnableConfiguration.md)

In your specific case, the following `common.props` should do the trick:
```msbuild
<PropertyGroup>
  <CompanySolutionDir>$(MSBuildThisFileDirectory)</CompanySolutionDir>
  <StyleCopJsonPath>$(CompanySolutionDir)..\stylecop.json</StyleCopJsonPath>
</PropertyGroup>

<ItemGroup>
  <AdditionalFiles Include="$(StyleCopJsonPath)">
    <Link>stylecop.json</Link>
  </AdditionalFiles>
</ItemGroup>
```

**Comment by aensidhe** [comment]
Oops, my bad. Need to read release notes more carefully. Thank you, it fixed the issue.
