### ISSUE TITLE
Implement SA1137: Elements should have the same indentation

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#2023]
**Category:** Readability
**Title:** Elements should have the same indentation
**Description:** When two elements _A_ and _B_ have the same syntactical parent and each start on their own line, the indentation of each element should be the same.

The following collections of syntax nodes are considered:
- Members of a `CompilationUnitSyntax`
- Members of a `NamespaceDeclarationSyntax`
- Statements of a `BlockSyntax`
- Expressions of an initializer
- Declarators
- Parameters and arguments
- Attribute lists
- Attributes within an attribute list

The following syntax nodes need to be treated specially for this:
- `CaseSwitchLabel`/`DefaultSwitchLabel` (labels in the same switch statement are compared to each other, separately from the statements in the switch statement)
- `LabeledStatement` (labels in the same block are compared to each other, and the child statement of the labeled statement is compared to other non-labeled statements in the block)

**Comment by vweijsters** [comment]
:+1: I like the idea very much.

I have some questions and remarks:

> * Attributes within an attribute list

How would this relate to SA1134?

Shouldn't query expressions be part of this as well? (They can occur outside of an initializer expression)

I also think that attribute lists on (type) parameters should be ignored, in line with SA1134.

How would fluent syntax be handled by this? (Can also occur outside of an initializer expression)

**Comment by sharwell** [comment]
> How would this relate to SA1134?

It's independent of SA1134.

> Shouldn't query expressions be part of this as well?

For now I'm shying away from them, but I could see them being added to this rule after the initial implementation.

> I also think that attribute lists on (type) parameters should be ignored, in line with SA1134.

They already are, assuming they appear on the same line as each other and/or don't start as the first token on a line. To qualify for this rule, two elements have to each start on separate lines, and the first token of each must be the first token on the line.

> How would fluent syntax be handled by this?

Not currently covered, but could be proposed for addition to this rule in the future, as could the positioning of other operators/operands in expressions. Due to the relatively complex shape of the syntax tree for these, it would require careful consideration.

**Comment by Noryoko** [comment]
:+1: Very good idea.

**Comment by oatkins** [comment]
:+1: 

Don't see this violated a lot in practice, except perhaps where a merge tool has left some funny indentation of { and } characters.

**Comment by nbarbettini** [comment]
:+1: from me.
