### ISSUE TITLE
Implement SA0002: Invalid settings file

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#2029]
It would be nice to use a compilation end event to report a single instance of this violation if we are unable to deserialize **stylecop.json**. This would catch (at least) the following situations:

1. JSON syntax errors (e.g. #2028)
2. Semantic errors, such as using an array instead of a string or an unknown value for an enumerated type

This would *not* report a diagnostic if the file is not [configured correctly](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/EnableConfiguration.md).

**Comment by nbarbettini** [comment]
:+1:

Will probably be even more helpful in the future when/if the configuration becomes more complex.

**Comment by vweijsters** [comment]
:+1:
