### ISSUE TITLE
Proposal: Consistent use of "must" and "should"

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#2036]
I propose updating the titles, messages, and descriptions of all rules to be consistent with the following:

| Default severity | Wording |
| --- | --- |
| Hidden/Info | May |
| Warning | Should |
| Error | Must |

**Comment by vweijsters** [comment]
:+1: But we will be needing clear guidelines on when a diagnostic will be marked as error.

**Comment by sharwell** [comment]
> when a diagnostic will be marked as error.

No diagnostics are currently or planned to be marked as error.

**Comment by vweijsters** [comment]
That definitely is a clear guideline :smile:

**Comment by GregReddick** [comment]
The standard for May, Should, Must comes from RFC 2119 (https://tools.ietf.org/html/rfc2119). We should consider updating the documentation of rules to use RFC 2119 consistently.
