### ISSUE TITLE
SA1205 fired wrongly

### ISSUE THREAD

**Issue by froufrou121** [DotNetAnalyzers/StyleCopAnalyzers#2040]
I have some auto-generated code whose structure looks like that:

```csharp
    internal static partial class TestPartial
    {
        private sealed partial class PartialInner
        {
            public int Do()
            {
                return 2;
            }
        }
    }
```

I get SA1205 (Partial elements must declare an access modifier) when I have specified private access. The proposed fix is to prepend internal before private sealed partial which obviously leads to a compilation error. The issue does not happen if the inner class is internal / public but only when it is private.

The other thing is that styleCop does not care if there is a GeneratedCode attribute or not on the outer or inner class.

**Comment by sharwell** [comment]
I was able to reproduce this with the provided code.

@vweijsters Want to take this one?

**Comment by vweijsters** [comment]
I'll pick this up :wink:
