### ISSUE TITLE
Add different language support

### ISSUE THREAD

**Issue by yodasad** [DotNetAnalyzers/StyleCopAnalyzers#2043]
Old StyleCop plugin for VisualStudio had different languages support. 
For example, it suggested different documentation text for properties depending on project language.

Current StyleCopAnylyzers uses English only to validate documentation text.

**Comment by sharwell** [comment]
I think this is a duplicate of #1143.

**Comment by yodasad** [comment]
Yes, it's a duplicate. I'm very sorry, I should have searched existing issues more carefully.

**Comment by sharwell** [comment]
@yodasad I don't mind duplicates. If you can't find something just ask (or create an issue) and we'll point you in the right direction. :smile:
