### ISSUE TITLE
Visual Studio forgets Analyzers

### ISSUE THREAD

**Issue by ursenzler** [DotNetAnalyzers/StyleCopAnalyzers#2047]
Not sure whether this is a StyleCopAnalyzers problem or a Visual Studio Problem in general.

From time to time, Visual Studio loses the Analyzers. To fix this, I need to uninstall StyleCopAnalyzers and reinstall the nuget package. Then the Analyzers (under References/Analyzers) are back where they belong.

Any suggestions?

Thanks for this project!

**Comment by sharwell** [comment]
I've never seen this. :worried: 

My guess is you have another extension installed which is interfering. You might try filing a report on [dotnet/roslyn](https://github.com/dotnet/roslyn) and see if they've encountered it.

**Comment by zynthar** [comment]
I had this issue when using it together with Visual Studio Tools for Unity, because the solution and project files are then re-generated very often. Solved it by hooking into the file generation event and re-adding the StyleCop lines each time.

**Comment by tcchau** [comment]
@jizc Would you be willing to publish the code that provides the event handlers to re-add the StyleCop lines each time in a gist or something like that? It would be much appreciated!

**Comment by jizc** [comment]
Sure thing @tcchau! You can see an example of it here: [ProjectFileHook.cs](https://github.com/jizc/WitchWing/blob/master/WitchWing/Assets/Scripts/Editor/ProjectFileHook.cs)
