### ISSUE TITLE
Is there a specific date set for v1 NuGet release

### ISSUE THREAD

**Issue by shaggygi** [DotNetAnalyzers/StyleCopAnalyzers#2054]
I see the 1/28 goal for v1 milestone in GitHub.  Just wondering when v1 NuGet will hit so we can plan to begin adding to projects.

Thx and good job on the first release.

**Comment by sharwell** [comment]
Right now we are on track for an on-time release. It's extremely likely that the only change to the code between RC 3 and 1.0.0 will be a change to the assembly version number (metadata). Considering how long RC 3 has been out without a single report of a major bug, I would recommend adding it to your projects early in case you need to provide feedback before the 1.0 release.

**Comment by shaggygi** [comment]
Thanks for the update.  We've been using the analyzers as your team has made progress the last several weeks.  I just wanted to narrow down the release so we could add the RTM version to all our projects.  Looks good!  Thx.
