### ISSUE TITLE
How to get the assigned rule set programmatically

### ISSUE THREAD

**Issue by shaggygi** [DotNetAnalyzers/StyleCopAnalyzers#2065]
This is not specific to StyleCop.Analyzers, but thought the team might know.  If you assign a rule set in a project's Properties Window, how can you get that value programmatically?  Meaning, I want to open .csproj file and get the value for CodeAnalysisRuleSet.  This would be for all configurations.

Any help is appreciated.

**Comment by sharwell** [comment]
I recommend asking this in one of the following places:

* [Microsoft/extendvs](https://github.com/Microsoft/extendvs) (the Gitter room for this is also quite active)
* [dotnet/roslyn](https://github.com/dotnet/roslyn)
