### ISSUE TITLE
How to reference StyleCop.Analyzers.NoCodeFixAttribute

### ISSUE THREAD

**Issue by shaggygi** [DotNetAnalyzers/StyleCopAnalyzers#2066]
I know I'm overlooking something simple, but can't figure it out.  I'm trying to create a utility using some code based on StyleCopTester.  I'm using the code with the GetAllAnalyzers method and don't see NoCodeFixAttribute as it seems internal/sealed.  It appears I have all the NuGet packages and such added to my project.

So my question is how to reference NoCodeFixAttribute and/or is there a better mechanism to get the analyzers that are added to a project?  Thx

**Comment by sharwell** [comment]
To prevent other analyzers from relying on our APIs (and thus requiring us to avoid source or binary breaking changes between releases), there are no publicly exposed types or members in this project. We have a [unit test](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers.Test/PublicApiTests.cs#L19) to verify that this is the case, although I'm considering switching to the use of [PublicApiAnalyzer](https://github.com/DotNetAnalyzers/PublicApiAnalyzer) to verify this instead. See #1502 for more information.

If you are trying to write a utility to gather statistics or other information about our project, and not actually building a different set of analyzers, can you be more specific about your goals? For example, the [status page](https://stylecop.pdelvo.com/) also does not have access to the internal API, but we were still able to make it work. :smile:

**Comment by shaggygi** [comment]
Thx for quick response.  Our goals are to review each project separately instead of how StyleCopTester checks all projects within a solution.  For example, it would be nice to see how many times we violated SA1028 in a particular project.  We reference the same class projects throughout other solutions, so it is duplicating results in areas of some of those solutions.

We would like the process to output the results in a format (XML, JSON, etc.) we could save to file for record keeping.  This would include miscellaneous data like project name, date/time stamp, collection of each violation with reference number (SA1028), title (for easier readability) and total number of violation, etc.

Results would allow our team to review/decide what to tackle next in cleaning up code.  Also, having the ability to store the results in files would allow us to create a few reports for progress.  Of course, this isn't that big of a deal for devs to go clean up the code.  However, our quality peeps get giddy seeing this kind of progress. :smile:

Hope this explains what we're trying to accomplish.

**Comment by sharwell** [comment]
I would recommend adding the functionality you need to StyleCopTester, for the following reasons:

1. You can contribute them back here to help other users :tada:
2. Even if you aren't able to contribute them back (or if we don't merge them for some reason), this particular project is part of an `[InternalsVisibleTo]` attribute for the main project. Your modified build of StyleCopTester will be able to use the internal API of our reference 1.0.0 release without problems.
