### ISSUE TITLE
Large amount of NullReferenceException when running StyleCop.Analyzers from MSBuild

### ISSUE THREAD

**Issue by kawazoe** [DotNetAnalyzers/StyleCopAnalyzers#2073]
We have recently updated our project from v1.0.0-rc1 to v1 and since then, we have been getting a large amount of NullReferenceException from our build server which is building the solution using MSBuild directly. We do not see those errors when using Quick Fixes or building our app in Visual Studio (even tough Run CA on build is enabled on the project). Here is the log I'm getting from MSBuild.

I think this is related to #1931 for which the fix was needed by our project. We also enabled SA0000 in the move over to the final release.

```
CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1203ConstantsMustAppearBeforeFields' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [d:\Jenkins\workspace\Departments\RB\ScheduAll.Reports\Dev\Build\src\RB.ScheduAll.Reports.Core\RB.ScheduAll.Reports.Core.csproj]
CSC : error AD0001: Analyzer 'StyleCop.Analyzers.MaintainabilityRules.SA1402FileMayOnlyContainASingleClass' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [d:\Jenkins\workspace\Departments\RB\ScheduAll.Reports\Dev\Build\src\RB.ScheduAll.Reports.Core\RB.ScheduAll.Reports.Core.csproj]
CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1208SystemUsingDirectivesMustBePlacedBeforeOtherUsingDirectives' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [d:\Jenkins\workspace\Departments\RB\ScheduAll.Reports\Dev\Build\src\RB.ScheduAll.Reports.Core\RB.ScheduAll.Reports.Core.csproj]
CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1214ReadonlyElementsMustAppearBeforeNonReadonlyElements' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [d:\Jenkins\workspace\Departments\RB\ScheduAll.Reports\Dev\Build\src\RB.ScheduAll.Reports.Core\RB.ScheduAll.Reports.Core.csproj]
CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1210UsingDirectivesMustBeOrderedAlphabeticallyByNamespace' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [d:\Jenkins\workspace\Departments\RB\ScheduAll.Reports\Dev\Build\src\RB.ScheduAll.Reports.Core\RB.ScheduAll.Reports.Core.csproj]
CSC : error AD0001: Analyzer 'StyleCop.Analyzers.LayoutRules.SA1518UseLineEndingsCorrectlyAtEndOfFile' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [d:\Jenkins\workspace\Departments\RB\ScheduAll.Reports\Dev\Build\src\RB.ScheduAll.Reports.Core\RB.ScheduAll.Reports.Core.csproj]
CSC : error AD0001: Analyzer 'StyleCop.Analyzers.DocumentationRules.SA1649FileNameMustMatchTypeName' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [d:\Jenkins\workspace\Departments\RB\ScheduAll.Reports\Dev\Build\src\RB.ScheduAll.Reports.Core\RB.ScheduAll.Reports.Core.csproj]
CSC : error AD0001: Analyzer 'StyleCop.Analyzers.NamingRules.SA1305FieldNamesMustNotUseHungarianNotation' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. 
```

I am willing to provide a PR as a fix, but I will need further guidance on how to debug this use case.

**Comment by sharwell** [comment]
> We also enabled SA0000 in the move over to the final release.

:question: Can you try setting the severity of this rule to **Hidden** instead of **Warning**? We already made this change for the 1.1 branch but in the 1.0 release if you simply enable SA0000 it will be configured as a warning.

:question: Can you include a copy of the **stylecop.json** file you are using?

**Comment by kawazoe** [comment]
Sorry for the slow reply, I haven't had a chance to touch this project since then. Switching over the SA0000 rule to hidden seems to have done the trick.

Here is the stylecop.json settings that I am using, just in case it might be related to the issue I was getting:

```
"settings": {
    "orderingRules": {
      "usingDirectivesPlacement": "preserve"
    },
    "namingRules": {
      "allowCommonHungarianPrefixes": true
    }
  }
```

**Comment by pvandervelde** [comment]
What was the solution to the NullReferenceExceptions? I'm running into a similar issue and in my case SA0000 is set to None. Changing to hidden doesn't make any difference.

If it helps. The errors started occurring after clearing out the package directory and restoring it. It looks like there's something missing but I have no idea what that would be.

**Comment by pdelvo** [comment]
Are you able to share a (minimal) test project that reproduces this problem?

Can you try to run msbuild with the /v:debug flag and see if it prints the stack strace of the NullReferenceException?

I tried to reproduce it with the StyleCopAnalyzers repo itself but clearing the packages directory, restoring it, and running msbuild works for me.

**Comment by pvandervelde** [comment]
I've just tried it again, but this time on my work machine and I can reproduce it. I've made a test case which you can find here: https://github.com/pvandervelde/StyleCopNullReferenceSample

The solution is in the src directory. You can either run:

    msbuild src\Nuclei.Configuration.sln /p:Configuration=Debug

Or you can build it from Visual Studio. 

The output I looks something like this (but much more of it)

    "C:\temp\examples\nuclei.configuration\src\Nuclei.Configuration.sln" (default target) (1) ->
    "C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nuclei.Configuration.Samples.csproj" (default target) (4) ->
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1200UsingDirectivesMustBePlacedCorrectly' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nucl
    ei.Configuration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.DocumentationRules.SA1600ElementsMustBeDocumented' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nuclei.Conf
    iguration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1200UsingDirectivesMustBePlacedCorrectly' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nucl
    ei.Configuration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1208SystemUsingDirectivesMustBePlacedBeforeOtherUsingDirectives' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Con
    figuration.Samples\Nuclei.Configuration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1201ElementsMustAppearInTheCorrectOrder' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nucle
    i.Configuration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.DocumentationRules.SA1600ElementsMustBeDocumented' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nuclei.Conf
    iguration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1201ElementsMustAppearInTheCorrectOrder' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nucle
    i.Configuration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1210UsingDirectivesMustBeOrderedAlphabeticallyByNamespace' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configura
    tion.Samples\Nuclei.Configuration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1202ElementsMustBeOrderedByAccess' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nuclei.Conf
    iguration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.DocumentationRules.SA1600ElementsMustBeDocumented' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nuclei.Conf
    iguration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1203ConstantsMustAppearBeforeFields' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nuclei.Co
    nfiguration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1200UsingDirectivesMustBePlacedCorrectly' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nucl
    ei.Configuration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.LayoutRules.SA1518UseLineEndingsCorrectlyAtEndOfFile' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nuclei.C
    onfiguration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1202ElementsMustBeOrderedByAccess' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nuclei.Conf
    iguration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1210UsingDirectivesMustBeOrderedAlphabeticallyByNamespace' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configura
    tion.Samples\Nuclei.Configuration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1214ReadonlyElementsMustAppearBeforeNonReadonlyElements' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configurati
    on.Samples\Nuclei.Configuration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.DocumentationRules.SA1600ElementsMustBeDocumented' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nuclei.Conf
    iguration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1200UsingDirectivesMustBePlacedCorrectly' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nucl
    ei.Configuration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.DocumentationRules.SA1649FileNameMustMatchTypeName' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nuclei.Con
    figuration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1214ReadonlyElementsMustAppearBeforeNonReadonlyElements' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configurati
    on.Samples\Nuclei.Configuration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.DocumentationRules.SA1600ElementsMustBeDocumented' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nuclei.Conf
    iguration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.DocumentationRules.SA1649FileNameMustMatchTypeName' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nuclei.Con
    figuration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1214ReadonlyElementsMustAppearBeforeNonReadonlyElements' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configurati
    on.Samples\Nuclei.Configuration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1208SystemUsingDirectivesMustBePlacedBeforeOtherUsingDirectives' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Con
    figuration.Samples\Nuclei.Configuration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1201ElementsMustAppearInTheCorrectOrder' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nucle
    i.Configuration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1202ElementsMustBeOrderedByAccess' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nuclei.Conf
    iguration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.LayoutRules.SA1518UseLineEndingsCorrectlyAtEndOfFile' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nuclei.C
    onfiguration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1208SystemUsingDirectivesMustBePlacedBeforeOtherUsingDirectives' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Con
    figuration.Samples\Nuclei.Configuration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.DocumentationRules.SA1601PartialElementsMustBeDocumented' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nucl
    ei.Configuration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1202ElementsMustBeOrderedByAccess' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nuclei.Conf
    iguration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1204StaticElementsMustAppearBeforeInstanceElements' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Sa
    mples\Nuclei.Configuration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.DocumentationRules.SA1601PartialElementsMustBeDocumented' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nucl
    ei.Configuration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1208SystemUsingDirectivesMustBePlacedBeforeOtherUsingDirectives' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Con
    figuration.Samples\Nuclei.Configuration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1201ElementsMustAppearInTheCorrectOrder' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nucle
    i.Configuration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.DocumentationRules.SA1601PartialElementsMustBeDocumented' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nucl
    ei.Configuration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1202ElementsMustBeOrderedByAccess' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nuclei.Conf
    iguration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1204StaticElementsMustAppearBeforeInstanceElements' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Sa
    mples\Nuclei.Configuration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.DocumentationRules.SA1600ElementsMustBeDocumented' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nuclei.Conf
    iguration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1210UsingDirectivesMustBeOrderedAlphabeticallyByNamespace' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configura
    tion.Samples\Nuclei.Configuration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.DocumentationRules.SA1600ElementsMustBeDocumented' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nuclei.Conf
    iguration.Samples.csproj]
      CSC : error AD0001: Analyzer 'StyleCop.Analyzers.DocumentationRules.SA1600ElementsMustBeDocumented' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'. [C:\temp\examples\nuclei.configuration\doc\Nuclei.Configuration.Samples\Nuclei.Conf
    iguration.Samples.csproj]

**Comment by pdelvo** [comment]
Thanks!

I was able to get a stacktrace and I found the problem. The stylecop.json file specified does not exist. Roslyn still gives us a SourceText with empty string as its content. We deserialize that to null and try to access a member. A workaround is to make sure that the stylecop.json file provided by msbuild exists. Im preparing a fix for that right now.

**Comment by pvandervelde** [comment]
Interesting. I think that then found a bug on my side because that stylecop.json file should most definitely exist. I'll go put it back :)

**Comment by pdelvo** [comment]
But we still should not crash in that case ;)

**Comment by sharwell** [comment]
@pvandervelde Thanks for following up so quickly! With your help, we were finally able to fix this for the next preview.
