### ISSUE TITLE
Problems when closing huge Solution

### ISSUE THREAD

**Issue by huserben** [DotNetAnalyzers/StyleCopAnalyzers#2078]
Hi there

in our team we started using your analyzer for some months now it we really like it. Sadly we noticed that in our solution, everytime we close it, Visual Studio freezes and does not respond for some time. After some investigation we found out that the time it takes to close is related to how often we build, after a full working day it sometimes takes more than 5 minutes till the solution actually is closed.

Therefore we started analyzing what the cause could be, and we managed to reproduce it in a sample project. It looks like the StyleCop.Analyzers have something to do with it.

A sample project can be found here: https://github.com/huserben/AnalyzerPerformanceTest
It's just a solution with 130 empty class libraries and all of them have the StyleCop Analyzer installed. Just rebuild 3 times and then close the solution to recreate the issue.

We also have other analyzers installed (SonarLint, FxCop), and I tested those in the test solution as well, there we did not experience any issue while closing the solution...

Regards and thanks for your help

**Comment by sharwell** [comment]
Hi @huserben,

Thank you so much for taking the time to report this and especially create that sample repository. I'll investigate a bit and see who the best people to fix it are!

**Comment by sharwell** [comment]
@huserben I wasn't able to reproduce the issue *as described*, but I continued to try various things. I finally reproduced this using the following steps:

1. Clone the reference project
2. Open the solution in Visual Studio
3. Restore NuGet packages
4. Restart Visual Studio and open the solution again
5. Fix all SA1633 violations in solution
6. Fix all SA1028 violations in solution
7. Rebuild 3 times
8. Close Visual Studio

@mavasani When profiling the close operation, I found substantial time was spent in `Microsoft.CodeAnalysis.Diagnostics.AnalyzerManager.ClearAnalyzerState(valuetype System.Collections.Immutable.ImmutableArray`1<class Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer>)`. Most of this was accessing `Keys` and calling `ToImmutableArray` in `ClearAnalysisScopeState`.

**Comment by mavasani** [comment]
Thanks @sharwell. Let me prepare a PR to clean up that code - avoid unncessary `ToImmutableArray` invocation and replace concurrent dictionary with a normal dictionary + lock.

**Comment by qmfrederik** [comment]
Hi,

Cool, I saw the exact same behavior (VS taking a long time before closing & slowing down after using it for a while).

Just wondering - I saw a fix for this has been merged into Roslyn. Is there an (easy) way to use this in an existing installation of Visual Studio, or do we need to wait for the next VS update to incorporate this fix?

Thx!

Frederik.

**Comment by mavasani** [comment]
Unfortunately, you'll just have to wait for an update.
