### ISSUE TITLE
InheritDoc documentation triggers every other missing documentation item warnings.

### ISSUE THREAD

**Issue by JabX** [DotNetAnalyzers/StyleCopAnalyzers#2083]
Hello,

I'm using `/// <inheritDoc />` all over my implementations, but I'm getting all kinds of warning about missing summary, missing parameters, missing return, etc.

I thought `inheritDoc` would prevent me from having to rewrite/copy paste the entire documentation ?

**Comment by sharwell** [comment]
I'm fairly confident the issue here lies in the difference between `inheritDoc` and `inheritdoc`. XML is case-sensitive, and we only look for the latter in our analyzers.

**Comment by JabX** [comment]
Yep, I tried with a lowercase 'D' and it works as expected. Looks like I'm going to do a lot of search and replace then.
Thanks!
