### ISSUE TITLE
Customizing Rule Set

### ISSUE THREAD

**Issue by brinko99** [DotNetAnalyzers/StyleCopAnalyzers#2089]
I am having trouble modifying my project's rule set (custom .ruleset file). No matter what I configure, the full set of rules are applied.

I do have ReSharper installed (with no extensions). I've verified that the rule set is applied on the current build configuration, etc. I am successful with the custom stylecop.json.

Clicking "Open Active Rule Set" on the Analyzers node gives me the error "The rule set file could not be opened"... 

Any ideas?
![stylecop 01](https://cloud.githubusercontent.com/assets/1231765/13193344/9d2620e6-d72b-11e5-8503-abce7227d262.jpg)
![stylecop 02](https://cloud.githubusercontent.com/assets/1231765/13193343/9d25be8a-d72b-11e5-8869-6277bc88727c.jpg)
![stylecop 03](https://cloud.githubusercontent.com/assets/1231765/13193345/9d261e98-d72b-11e5-8361-bbe82b75095e.jpg)

**Comment by MADCookie** [comment]
FYI, if you open the project properties and select "Code Analysis", you'll see what rule set is selected and it should show you the path it used to find the rules. 

At one point, I didn't have my rule set saved, and I got nearly the same error. Looking at the properties might help you troubleshoot.

![properties](https://cloud.githubusercontent.com/assets/359919/13193752/ed336326-d732-11e5-9788-4effa9dd7059.png)

**Comment by brinko99** [comment]
@MADCookie  Yes, thanks. I did verify the location of the rule set. It is indeed the one that I'm editing.

Unfortunately my problem is elsewhere.

**Comment by justkao** [comment]
The very same problem occurred in my project. My ruleset path was relative to current project in form of `<CodeAnalysisRuleSet>..\..\Shared\Common.ruleset</CodeAnalysisRuleSet>` and I was getting the very same error. Unload the project and reloading it again fixed the problem temporary. 
I would like to know the reason why this is happening as I am getting the error quite frequently.

**Comment by pdelvo** [comment]
I would report this bug to the visual studio team. I don't think we can do anything about it. The settings are provided to us by visual studio/the compiler. We don't parse them ourself.

**Comment by brinko99** [comment]
My issue was resolved only by fully reinstalling Visual Studio 2015. Even a repair was insufficient.

Thanks.
