### ISSUE TITLE
Suggestion for new rule to detect redundant string.ToString() calls

### ISSUE THREAD

**Issue by t-johnson** [DotNetAnalyzers/StyleCopAnalyzers#2092]
I have a suggestion for a rule to identify (&fix) instances where ToString() is being called on a System.String member.

This is a "Readability" rule, from my perspective as the additional ToString() calls pollute the code and imply that the target is not, in fact, a string. However there is a very tiny performance gain as the redundant method call will not be removed by the compiler.

I have implemented this in another project, but would be happy to merge it in here if it makes sense for this library.
https://github.com/t-johnson/StringToStringAnalyzer

**Comment by nbarbettini** [comment]
This is a simple case to detect and fix. :+1: from me.

**Comment by otac0n** [comment]
I don't think this belongs in the StyleCop analyzers assembly.  Seems more like semantic analysis to me.

**Comment by t-johnson** [comment]
@otac0n yes i agree it is technically not a _style_ issue per-se.

Would you have a suggestion of another analysis library this might be a better fit for?

**Comment by otac0n** [comment]
I'd defer to @sharwell, but probably [DotNetAnalyzers/DotNetAnalyzers](/DotNetAnalyzers/DotNetAnalyzers)
