### ISSUE TITLE
SA1101 misfires when member name coincides with type name

### ISSUE THREAD

**Issue by AArnott** [DotNetAnalyzers/StyleCopAnalyzers#2093]
In the below sample (which references `System.Drawing.dll`), the use of the static method `Region.FromHrgn` causes SA1101 to inappropriately report that `this.` should be used in front of the `Region` type. Evidently it is confusing the `Program.Region` member with the `Region` type.

```csharp
using System;
using System.Drawing;

internal class Program
{
    public Region Region => Region.FromHrgn(IntPtr.Zero);
}
```

**Comment by vweijsters** [comment]
This one is similar to #1501
