### ISSUE TITLE
VB.NET support?

### ISSUE THREAD

**Issue by richardversluis** [DotNetAnalyzers/StyleCopAnalyzers#2095]
What is the projects opinion about partly supporting VB.NET? At the moment there aren't much Analyzers for VB.NET. I would be great to have some support, like the category _NamingRules_. 

I haven't much experience with creating Analyzers, so I don't know the impact of supporting this.

**Comment by nbarbettini** [comment]
I'd love to see some VB.NET support, but I'm not sure if it's in the scope of this project. There are some analyzers that support VB.NET over at [awesome-analyzers](https://github.com/Cybermaxs/awesome-analyzers).

**Comment by sharwell** [comment]
I believe this is outside the scope of this project, at least for now. No style rules are defined for VB.NET, and even if they were created it would overlap with existing work on dotnet/roslyn#7071.
