### ISSUE TITLE
Property hiding method?

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/StyleCopAnalyzers#2096]
internal class Foo
    {
        internal bool Equals { get; }
    }

![image](https://cloud.githubusercontent.com/assets/1640096/13572557/37b19ddc-e47b-11e5-87c6-5a693e8b33de.png)

Bug?

**Comment by appel1** [comment]
That's not from StyleCop.Analyzers but from VS/Roslyn. Code is CS0108.

**Comment by JohanLarsson** [comment]
Oh, sorry.
