### ISSUE TITLE
File 'stylecop.json' has no Effect on Tabs / Spaces Setting

### ISSUE THREAD

**Issue by ilexp** [DotNetAnalyzers/StyleCopAnalyzers#2101]
As commented in issue #1896, I can't get the stylecop analyzers to accepts tabs as the default indentation character. This may very well be an error on my side, but so far I wasn't able to get it working. Maybe I'm missing something very simple.

Quoting from my comment on the above, closed issue:

> I'm not sure what's wrong, but I appear to be running into a similar issue with the config file. Despite setting "useTabs" to true, it still reports one warning per line stating that "Tabs must not be used". This leads me to assuming that the settings file I use is either incorrect or not parsed.
>
> I followed the steps in the above documentation and created a minimal Console application to reproduce this behavior: [ConsoleApplication1.zip](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/files/160365/ConsoleApplication1.zip)
>
> Since most people don't seem to have a problem with this, it might very well be a problem with my configuration, but if anyone can point me into the right direction, this would very much be appreciated.

On a different note, is there a way to specify a "Require tabs for indentation, but spaces for alignment" usage pattern?

**Comment by vweijsters** [comment]
Hello, I just had a look at your problem and I think I've found the problem. The `useTabs` setting was added to the project in pull request #2045. This pull request is not available in the 1.0.0 release unfortunately. It will become available whenever the 1.1.0 beta 1 is released, but there currently is no release date for that.

**Comment by ilexp** [comment]
Ah, that explains it. Thanks! :)

**Comment by Jeavon** [comment]
Any update of any release containing the useTabs setting? 
A MyGet feed of current code pushed from AppVeyor might be an idea for those that want early access to new stuff?

**Comment by vweijsters** [comment]
@Jeavon no update unfortunately, hopefully somewhere in the 2nd half of this month (April) after we integrate the Roslyn 1.2 stuff.
