### ISSUE TITLE
Creation of new repo DotNetAnalyzers/UnitTestAnalyzers

### ISSUE THREAD

**Issue by emanoelxavier** [DotNetAnalyzers/StyleCopAnalyzers#2103]
This is regarding the closed issue  #1673 in case it lost visibility since it is closed. It would be great if we could have DotNetAnalyzers/UnitTestAnalyzers for me to start adding unit test related analyzers. Please let me know if you  have any questions.

**Comment by vweijsters** [comment]
Closing this as the repository has been created.
