### ISSUE TITLE
SA1513 should ignore four forward slashes

### ISSUE THREAD

**Issue by felickz** [DotNetAnalyzers/StyleCopAnalyzers#2107]
[SA1513 ](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1513.md)should ignore four forward slashes as is done in  [SA1515](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1515.md)

```
            if (x)
            {
             y
            }
            ////else
            ////{
            ////z
            ////{
```

Wants to refactor to:

```
            if (x)
            {
             y
            }

            ////else
            ////{
            ////z
            ////{
```

**Comment by vweijsters** [comment]
Thanks for reporting this. I'll mark it as a bug.
