### ISSUE TITLE
Auto-generated files being analyzed.

### ISSUE THREAD

**Issue by klynch67** [DotNetAnalyzers/StyleCopAnalyzers#2109]
Using StyleCop.Analyzers NuGet package v1.0.0

A short list of errors being flagged and the files headers the flagged files have:
  IDE0001  Name can be simplified.  E:\repo\foo\src\obj\x86\Debug\foo.Version.cs  11  Active
  IDE0002  Name can be simplified.  E:\repo\foo\src\Resources.Designer.cs  41  Active
  IDE0005  Using directive is unnecessary.  E:\repo\foo\src\\Resources.Designer.cs  12  Active
```
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
```
  IDE0005  Using directive is unnecessary.  C:\Users\kelly\AppData\Local\Temp\.NETFramework,Version=v4.5.2.AssemblyAttributes.cs  2  Active
```
// <autogenerated />
```
I expect that this may be fixed by some configuration flag. Unfortunately, searching the Internet is only coming with solution in the classic StyleCop.

**Comment by felickz** [comment]
See #1430 

For now use:
> <auto-generated or <autogenerated

**Comment by klynch67** [comment]
Doh. I didn't put the headers in MD code blocks and the XML in the headers was hidden when rendered.

I fixed the MD and now it is plain to see that those generated files use <auto-generated and <autogenerated

**Comment by vweijsters** [comment]
The issues that you mention (IDE0001, IDE0002, and IDE0005) are not StyleCop Analyzers issues, but Visual Studio internal ones. All our analyzers use the format SAxxxx.

How the Visual Studio ones behave with generated code I do not know, but it would be a safe bet to ask that question in dotnet/roslyn.
