### ISSUE TITLE
SA1202 Wrong access level based order?

### ISSUE THREAD

**Issue by strohhut** [DotNetAnalyzers/StyleCopAnalyzers#2124]
The [documentation](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1202.md) says 

> A violation of this rule occurs when the code elements within a file do not follow a standard ordering scheme based on access level.

I would either change the wording to 

> A violation of this rule occurs when the code elements within a file do not follow a standard ordering scheme based on **their access modifiers**.

or leave the wording and change the implementation to really follow an access level order based approach. Then it would be 
    
`public -> protected internal -> internal -> protected -> private `

instead of

`public -> internal -> protected internal -> protected -> private`

because `protected internal` is the second highest access level after public.

**Comment by vweijsters** [comment]
We are following the convention set by StyleCop classic here.
As far as I can determine there is no fixed ordering in access levels within C#.

I've found several informational sources and none of them seem to fully agree:

- https://msdn.microsoft.com/en-us/library/ba0a1yw2.aspx
- https://github.com/dotnet/roslyn/blob/master/src/Compilers/Core/Portable/Symbols/Accessibility.cs
- CSharp Language specification 5.0, section 3.5.1
- http://stackoverflow.com/questions/191929/is-there-a-convention-to-the-order-of-modifiers-in-c

**Comment by sharwell** [comment]
@strohhut Technically the ordering is based on access level and not the access modifiers (specifically with respect to the omission of `private`). Arguably the order which would "make the most sense" is the following:

public &rarr; protected internal &rarr; protected &rarr; internal &rarr; private

This order would be determined by the combination of the following partial orders:

* Strict containment
  * public &rarr; protected internal &rarr; internal &rarr; private
  * public &rarr; protected internal &rarr; protected &rarr; private
* Strict containment in public API
  * :memo: `protected internal` is equivalent to `protected` in a public API
  * :memo: `internal` is equivalent to `private` in a public API
  * public &rarr; protected &rarr; internal

However, the ordering we used was already defined by StyleCop Classic and it seemed of little value to change the behavior of this rule for existing users, especially considering that reordering members of a file produces very large and difficult to review code changes (diffs).
