### ISSUE TITLE
How to disable SA1633 (and others)?

### ISSUE THREAD

**Issue by jongleur1983** [DotNetAnalyzers/StyleCopAnalyzers#2125]
Most of the documentation rules doesn't apply for us here, so I would like to disable them, but that seems not to work properly.

What I did yet:
- added a stylecop.ruleset file to the solution, where I disabled several rules (Action is set to None)
- added that stylecop.ruleset to the project as usual by "Add existing item as link" in visual studio (as I want to share the same rules across several projects).
- Disabled several stylecop rules in the stylecop.ruleset using the built-in ruleset editor of VisualStudio 2015, e.g. SA1600-SA1624, SA1633 to SA1643, SA1648, SA1652 and others.

- added a stylecop.json to the project the same way.
- manipulate the .csproj files according to https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/EnableConfiguration.md, now the config file is included as 
```xml
<AdditionalFiles Include="..\stylecop.json">
  <Link>stylecop.json</Link>
</AdditionalFiles>
```

The stylecop.json file currently contains the following code (I removed the source requirement from the auto-generated version as we don't need it):
```json
{
  "$schema": "https://raw.githubusercontent.com/DotNetAnalyzers/StyleCopAnalyzers/master/StyleCop.Analyzers/StyleCop.Analyzers/Settings/stylecop.schema.json" 
}
```

Nevertheless I get warnings e.g. for
- SA1604
- SA1611
- SA1612
- SA1614
and others. What's wrong? how to fix that?

regards
Peter

**Comment by vweijsters** [comment]
That seems weird indeed. The only step that I see missing in the description above is actually setting the rule set as the active rule set for the project. 

This is done either via the project options, in the code analysis section or by right clicking the rule set file and selecting 'Set as Active Rule Set'. Could you please verify if this step has been done?

**Comment by jongleur1983** [comment]
Thanks, might have missed some of my projects in that step before. Evaluating the result currently, but at the first glance this might have been at least part of the solution. Doing so for every project decreased the number of warnings from 6716 to 4778 at least, where some old settings I could not yet migrate successfully, perhaps more on that in another ticket, to keep this one clean for others to research.

Thanks so far.
