### ISSUE TITLE
How do you specify additionalFiles in project.json?

### ISSUE THREAD

**Issue by tillig** [DotNetAnalyzers/StyleCopAnalyzers#2130]
I'm working in RC2 and StyleCop analyzers work great by referencing them as a build-time dependency. However, there's no .csproj, only a project.json. How do I specify where stylecop.json is using project.json?

**Comment by vweijsters** [comment]
I'm assuming that you are talking about ASP.Net Core 1.0 RC2 here. More information can be found in #806 and #2133.
