### ISSUE TITLE
stylecop.json ignored in WPF application

### ISSUE THREAD

**Issue by reasra** [DotNetAnalyzers/StyleCopAnalyzers#2131]
I've read #1720, #1896, and #2121, but despite everything i've tried, the analyzers seem to ignore my stylecop.json "Additional File."

I ran the code fix "Add StyleCop settings file", changed the "companyName", and saved it.  Then made it an additional file, reloaded the project, even ran the "install.ps1" tool.  I still see the SA1636 warning telling me to use "PlaceholderCompany" instead of my own.

I could just ignore it, but I'm sure in a week, I'll find a reason to add something else to this json file...

**Comment by vweijsters** [comment]
Hi, can you share the `stylecop.json` and the `.csproj` files, so that I can have a look at them?
Can you also post which version of Visual Studio 2015 and StyleCopAnalyzers you are using?

**Comment by reasra** [comment]
**VS2015 Version:** 14.0.24720.00 Update 1

[Tiger.csproj.txt](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/files/268181/Tiger.csproj.txt)

[stylecop.json.txt](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/files/268179/stylecop.json.txt)

**Comment by pdelvo** [comment]
The stylecop.json file has syntactic erros. There are ',' missing. It should work if the syntax errors are corrected:
[stylecop.json.txt](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/files/268197/stylecop.json.txt)

**Comment by reasra** [comment]
Fixed it, thanks.  May want to consider fixing this in the **Add StyleCop settings file** code fix.  I just changed the placeholder information and deleted the comment (thought the comment might be the problem at one point).  I assumed the generated format was correct.
