### ISSUE TITLE
support for using name other than stylecop.json

### ISSUE THREAD

**Issue by myusrn** [DotNetAnalyzers/StyleCopAnalyzers#2132]
i'd like to have my $(SolutionDir) contain analysis.custom.ruleset and analysis.stylecop.json file names for each project to reference.

is there a way to get stylecop roslyn analyzers to use a file name other than stylecop.json for rule customization settings?

**Comment by vweijsters** [comment]
Hi, currently this is not supported. I'll mark this issue as an enhancement request to get some discussion going on whether or not this should be added.

**Comment by sharwell** [comment]
This will end up superseded by the work in dotnet/roslyn to generalize **.editorconfig** for analyzer authors.

**Comment by myusrn** [comment]
Thanks for update.  

Are you saying that in the vs17/dev15 environment one should move to using [create-portable-custom-editor-options](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options) for all languages coverage of this new oob style rules analysis configuration settings support and [editorconfig-code-style-settings-reference](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference) for the c# specific code style rules analysis settings?

**Comment by sharwell** [comment]
@myusrn Sorry for the confusion. The feature is not actually supported for StyleCop Analyzers settings yet. However, enabling this feature is a top priority for my team working on Roslyn, so I expect it to be complete prior to being able to implement something specific to this project.

**Comment by myusrn** [comment]
Thanks for clarification.  At the point when stylecop Roslyn analyzers use .editconfig settings file to control what style rules they enforce will this be considered an extended set of style rules for the oob ones that vs17/dev15 delivered?
