### ISSUE TITLE
Disappearing analyzer warnings

### ISSUE THREAD

**Issue by reasra** [DotNetAnalyzers/StyleCopAnalyzers#2134]
Just cleaned up an old project with thousands of formatting issues with this analyzer and saved lots of time (thanks!).  However, I have a program down to the last ~100 warnings with an output that looks like:

> Position.xaml.cs(1290,9,1290,70): warning SA1201: A event should not follow a method
> Position.xaml.cs(1417,30,1417,39): warning SA1201: A field should not follow a method
> Position.xaml.cs(1573,36,1573,49): warning SA1201: A method should not follow a struct
> Position.xaml.cs(1594,9,1594,66): warning SA1201: A event should not follow a method
> Position.xaml.cs(55,5,55,8): warning SA1514: Element documentation header must be preceded by blank line
> Position.xaml.cs(1417,30,1417,39): warning SA1203: Constant fields must appear before non-constant fields
> Position.xaml.cs(1368,33,1368,43): warning SA1202: 'public' members must come before 'private' members
> Record.xaml.cs(103,42,103,48): warning SA1201: A field should not follow a enum
> Processor.xaml.cs(884,29,884,36): warning SA1204: Static members must appear before non-static members
> Processor.xaml.cs(124,27,124,36): warning SA1201: A field should not follow a struct
> Processor.xaml.cs(21,5,21,8): warning SA1514: Element documentation header must be preceded by blank line
> Options.xaml.cs(105,21,105,30): warning SA1201: A field should not follow a property
> Options.xaml.cs(127,33,127,39): warning SA1201: A field should not follow a property
> ...etc

Immediately after build, the Error List is populated with randomly somewhere between 20-60 warnings, but when I double click the first one to go to it, they all disappear.  This may not be StyleCop specific, but it's the only analyzer I'm using.

Thanks.

**Comment by vweijsters** [comment]
Hi, this sounds like problem in the [dotnet/roslyn](https://github.com/dotnet/roslyn) component itself.

As you are using Visual Studio 2015 Update 1, you may want to try and enable the SA0000 (its disabled by default), which is designed to work around an issue that will sometimes mess up the error window.

If that doesn't work for you, try upgrading to Visual Studio Update 2 to see if that resolves the issue for you. If not, please report the issue in the [dotnet/roslyn](https://github.com/dotnet/roslyn) project, as they are the only ones that can solve it.

**Comment by reasra** [comment]
Setting the SA0000 to anything except **Default** or **None** seems to have fixed my problem.  It's funny to watch the warnings repopulate slowly just as they disappeared.  Thanks!

Will look into updating to VS Update 2.
