### ISSUE TITLE
Run autofix across the entire solution

### ISSUE THREAD

**Issue by alexandru-calinoiu** [DotNetAnalyzers/StyleCopAnalyzers#2147]
Is there a way I can run autofix across the entire solution, let's say I want the `this` prefix to be applied to all the files in the solution.

**Comment by sharwell** [comment]
Do you mean from a command line, or from within Visual Studio?

**Comment by darrensteadman** [comment]
I'm interested in this as well, Is it possible to just tell Visual Studio to auto fix an entire file?

**Comment by tiesmaster** [comment]
@darrensteadman In Visual Studio, this is possible for the current document, project, or even entire solution (already from the very first release of VS with analyzers):
![image](https://cloud.githubusercontent.com/assets/460904/16266002/d9168718-3882-11e6-86f6-1a705d48a29a.png)

@sharwell Do you know of any oss tools out there that will run code fixers on an entire solution, as a command line tool?

**Comment by alexandru-calinoiu** [comment]
@tiesmaster yes, `rubocop` a linter for linux simply run `rubocop -a` and it will autofix all the issues it can, there is also `eslint` that has a similar ability

**Comment by tiesmaster** [comment]
@alexandru-calinoiu Thnx for the tips, however, I was talking about tools that allow you to run the Roslyn analyzers/code fixers, as what this project is about.

**Comment by IanKemp** [comment]
Why was this closed? The question wasn't answered.

**Comment by tiesmaster** [comment]
I'm also interested to see something like that the day of light. [I believe](https://twitter.com/kuhlenhuth/status/986812326505361410) the Roslyn team(s) are working on something like that, and if it's ["Fix most code style violations in the current document with a single click."](https://docs.microsoft.com/en-us/visualstudio/productinfo/vs2018-roadmap) on the VS 2018 roadmap, then it should be due at the end of the month ;) Though, looking at [this issue](https://github.com/dotnet/roslyn/issues/7071), I see there is still a lot to do ;)

**Comment by sharwell** [comment]
@IanKemp There is no officially supported mechanism to do that. If you build this repository from source, the StyleCopTester tool may be able to provide some untested/unsupported functionality that looks like this. See #2017.

**Comment by rdcm** [comment]
Any updates on this?
