### ISSUE TITLE
SA0001 parsing exception for method parameter named '_'

### ISSUE THREAD

**Issue by Bananaroth** [DotNetAnalyzers/StyleCopAnalyzers#2154]
This code should reproduce the issue:
```
        public void IgnoreParameter(int _)
        { }
```
This seems related to #1343. But even if the underscore is disallowed in methods it shouldn't throw a parsing exception that's difficult to diagnose.

**Comment by sharwell** [comment]
I think you may be talking about StyleCop Classic (a different project).  In StyleCop Analyzers, [SA0001](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA0001.md) is a warning given when a specific compiler option is disabled, and is unrelated to parsing.
