### ISSUE TITLE
Code analysis not always reporting all issues

### ISSUE THREAD

**Issue by srudin** [DotNetAnalyzers/StyleCopAnalyzers#2161]
We have a rather large solution (~60 projects) and we are fully using code analysis for it. I have done that on similar solutions before and never had problems with it.

But this time (using VS2015 Update 2 with https://github.com/DotNetAnalyzers/StyleCopAnalyzers and compiling for .NET 4.6.1) I can see that we have situations where a build succeeds locally but then fails on the build server with a code analysis issue. Rebuilding locally then shows the same issue - so obviously the first build "ignored" that issue.

This is rather strange and very difficult to analyze. My stomach points me in the direction of a caching issue (what about that lastcodeanalysissucceeded file or the xml log?) but that's just guessing.

So my questions are:
1. Who can help me with this question? Is this the right forum? I posted it here as it could be related to the package and I also posted it in the MS Roslyn forum (https://social.msdn.microsoft.com/Forums/vstudio/en-US/a3af3a8d-ccdd-4d9e-949f-af3f1cce5da4/code-analysis-not-always-reporting-all-issues?forum=roslyn). Any better places?
2. Any ideas on how to analyze / solve this? Is there a cache I could check / clear? Any other ideas?

Thanks in advance

**Comment by sharwell** [comment]
If you are using StyleCop Analyzers 1.0.0, you should be able to resolve this by using a rule set file to set **SA0000** to **Hidden**.

**Comment by srudin** [comment]
I haven't been able to solve this yet. As it remained open for a long time I will first try again with the latest release and close the issue for now.
