### ISSUE TITLE
Any way to localize SA1623?

### ISSUE THREAD

**Issue by Dennis-Petrov** [DotNetAnalyzers/StyleCopAnalyzers#2162]
Hi.
Is there any way to localize SA1623 rule?
I've much code, which contains XML documentation, written in Russian. So, instead of checking for "Gets or sets..." I want Code Analysis to check for "Возвращает или задает...", e.g.:

        /// <summary>
        /// Возвращает или задает наименование элемента.
        /// </summary>
        public string Name { get; set; }

Actually, this is useful rule and I don't want to disable it.

**Comment by yodasad** [comment]
Maybe this is a duplicate of #1143. Can you check and see? 😄

**Comment by Dennis-Petrov** [comment]
@yodasad, thanks, it's a duplicate. I'll close this issue and post comment on #1143.
