### ISSUE TITLE
Provide Sonar Plugin

### ISSUE THREAD

**Issue by pascalberger** [DotNetAnalyzers/StyleCopAnalyzers#2166]
Since SonarLint currently only support Roselyn analyzers, StyleCop errors won't be shown in SonarLint (See [here](
http://stackoverflow.com/questions/36696945/sonarlint-doesnt-bring-managed-binary-analysis-rules-to-visual-studio/36697281#36697281)). 

Do you plan to provide a plugin for SonarQube for this Analyzer (See https://github.com/SonarSource-VisualStudio/sonarqube-roslyn-sdk/)? This would allow to use the analyzer in a CI scenario to manage technical dept, but also have it in Visual Studio through SonarLint.

**Comment by sharwell** [comment]
StyleCop Analyzers already operates as a Roslyn analyzer. It sounds like there is no more work to be done to support this scenario.

That said, if SonarQube/SonarLint didn't support Roslyn analyzers (or this Roslyn analyzer in particular), I believe it would be outside the scope of this project to try to handle it as a special case.

:memo: Starting with StyleCop Analyzers 1.1, the analyzer will require Roslyn 1.2. According to the documentation at the link you sent, the "connected experience" requires a maximum of 1.1. If you stay with StyleCop Analyzers 1.0, you will be inside the indicated specifications.

**Comment by pascalberger** [comment]
Thanks for the quick reply @sharwell. Supporting Roslyn analyzers is not the point (contrary SonarLint supports only Roslyn analyzers, and therefore not the existing StyleCop plugin). But it requires also a Sonar plugin (as explained [here](https://blogs.msdn.microsoft.com/visualstudioalm/2016/02/18/sonarqube-scanner-for-msbuild-v2-0-released-support-for-third-party-roslyn-analyzers/)). The Sonar SDK automatizes most of this, it is just a matter of adding some metadata additionally. 

I can create the Sonar plugin myself, but best would be if it can be maintained and provided by the official creator.

**Comment by sharwell** [comment]
I would prefer the plugin be created and maintained externally.

Hopefully SonarQube releases a new version of their Roslyn Analyzer support in the future which works without creating a plugin, similar to the way MSBuild automatically uses the analyzers when they are installed in the project.

**Comment by NeilCross** [comment]
@sharwell, I asume you know this already, but AFAIK the main reason sonar requires a "plugin" is to enable distribution to build slaves, as well as store some extra data per rule (category, default severity, tags and remediation time).  Currently these are provided by Annotations provided by the Sonar SDK.  Is there a way that CodeAnalysis libs provide a way to specify this information and allow the Sonar SDK to leverage CodeAnalysis attributes rather then having to define it's own?

Also @pascalberger, did you ever end up with a sqale template xml for StyleCopAnalyzers with a Sonarqube plugin?

**Comment by sharwell** [comment]
@NeilCross See our use of `AnalyzerCategory` and `DiagnosticSeverity` here: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers/LayoutRules/SA1500BracesForMultiLineStatementsMustNotShareLine.cs#L69

I'm not sure what the specific semantics of "tags" and "remediation time" are.

**Comment by pascalberger** [comment]
@NeilCross No, I just wrapped the analyzer in a Sonar plugin without providing any metadata.

**Comment by NeilCross** [comment]
@sharwell, Those properties have a _similar_ purpose. Specifically though, the properties I mention are for exposing details for each diagnostic based on the SQALE Quality Model (from www.sqale.org), which is used by SonarQube (and similar products, I presume) to identify the impact and technical debt associated with specific issues.

Here's a sample of the headers provided by the SonarQube Roslyn Analyzer library:

    [SqaleConstantRemediation("15min")]
    [SqaleSubCharacteristic(SqaleSubCharacteristic.InstructionReliability)]

They're currently making plans to provide an abstraction library for SQALE for Roslyn analyzer authors to provide this information; see [information about attributes](https://jira.sonarsource.com/browse/SFSRAP-7) and [a general overview of the plan](https://jira.sonarsource.com/browse/MMF-224).)  

Out of interest, are Attributes the kind of thing your team (as Analyzer developers) would consider adopting, or are these categorization methodologies too numerous to add first class support for any specific one directly into the Analyzer?  The ALM team has been tooting SonarQube's horn a bit recently and Stylecop is _the dude_ for .net analysis, to it'd be great to see them even more closely aligned.

Without this, the SQALE definition xml files would need to be created/maintained separately from the codebase, by either analyzer authors, or the community (or, sadly not created at all, with our tools providing less than optimal value, which is where @pascalberger and myself have found ourselves for now).

On top of this, the Tags (which isn't part of SQALE) I mentioned in an earlier post apparently differ in meaning between [SonarQube "Rule" Tags](http://docs.sonarqube.org/display/SONAR/Tags) and DiagnosticDescriptor Tags, as apparently the latter is currently used by diagnostics in VS, and seems inappropriate to leverage for the purpose.

@pascalberger thanks for the reply, if I ever get both to write up a configuration, I'll share or post back on this thread.

**Comment by sharwell** [comment]
> Out of interest, are Attributes the kind of thing your team (as Analyzer developers) would consider adopting

I would be against adding targeted support for one issue management platform unless it was either a standard Roslyn feature or was clear that the support was broadly relevant to others as well (e.g. Coverity tooling).

**Comment by NeilCross** [comment]
I expected that answer.  I think allowing analyzer authors to add 1st party support (by using Attributes) is wishful thinking on their part.  I'll link them to this thread, but I expect the support for configuration xml is the simplest way they could provide for third parties to specify the extra configuration details not stored within the Analyzer itself.
