### ISSUE TITLE
Control which build configuration causes Analyzers to run

### ISSUE THREAD

**Issue by gep13** [DotNetAnalyzers/StyleCopAnalyzers#2179]
Apologies if a duplicate issue, but couldn't find anything on initial search.

Is there a way to control which build configuration causes the StyleCop Analyzers to run?  i.e. don't run on a Debug Build, but run on a Release Build?

Thanks!

**Comment by sharwell** [comment]
The rule set file is specified for specific configurations. You can create two rule set files, and in the one for the debug configuration just disable all the StyleCop Analyzers rules.

**Comment by gep13** [comment]
@sharwell thanks for your quick response.  We will give that a try.

**Comment by patriksvensson** [comment]
@sharwell Is there a way of accomplishing this with a .NET Core project? Currently I've set everthing up in `project.json` but can't figure out how to separate this per configuration.

```json
  "buildOptions": {
    "xmlDoc": true,
    "additionalArguments": [
      "/ruleset:../Cake.ruleset",
      "/additionalfile:../stylecop.json"
    ]
  }
```

**Comment by sharwell** [comment]
I'm going to reopen this since .NET Core would be a different question.

@pdelvo Do you know if this is possible?

**Comment by sharwell** [comment]
@patriksvensson Keep in mind that the work to [eliminate xproj/project.json](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) may cause this problem to work itself out without further intervention, since csproj does already support the required functionality for conditional analysis.

**Comment by pdelvo** [comment]
This should be possible. I don't have time to test it, but you can specify different buildOptions for each configuration. Something like this should work:
```json
  "configurations": {
    "Debug": {
      "buildOptions": {
        "xmlDoc": false,
        "additionalArguments": [
          "/ruleset:../Cake.Debug.ruleset",
          "/additionalfile:../stylecop.json"
        ]
      }
    },
    "Release": {
      "buildOptions": {
        "xmlDoc": true,
        "additionalArguments": [
          "/ruleset:../Cake.Release.ruleset",
          "/additionalfile:../stylecop.json"
        ]
      }
    }
  },
```

**Comment by patriksvensson** [comment]
@sharwell @pdelvo That worked for me. Thanks!
