### ISSUE TITLE
SA1519 not detecting double using statement without braces

### ISSUE THREAD

**Issue by vweijsters** [DotNetAnalyzers/StyleCopAnalyzers#2180]
The following code does not produce ~~SA1503~~ SA1519 for the first `using` where it probably should:

``` C#
namespace Test
{
  using System.IO;

  public class TestClass
  {
    public void TestMethod()
    {
      using (var s = File.OpenRead("Test.data"))
      using (var b = new BinaryReader(s))
      {
        // ...
      }
    }
  }
}
```

**Comment by sharwell** [comment]
:memo: It looks like it's coded to give SA1519 in this scenario.

**Comment by sharwell** [comment]
Update: SA1519 does not currently consider using statements, hence no warning.

**Comment by oatkins** [comment]
FWIW, StyleCop classic doesn't mind double `using` statements. I reckon this is probably intentional. I for one would have preferred to keep it that way.

**Comment by sharwell** [comment]
@oatkins Sounds like a reasonable thing to make an option. Can you open a new issue proposing that?
