### ISSUE TITLE
Add setting to relax SA1519 to allow consecutive with braces omitted on all but the last one

### ISSUE THREAD

**Issue by oatkins** [DotNetAnalyzers/StyleCopAnalyzers#2184]
#2180 modified the rule to disallow this:

```
using (var a = GetDisposable())
using (var b = GetAnotherDisposable())
{
}
```

This was permitted in classic StyleCop. It would be helpful to have a setting that allows this behaviour to be retained.

**Comment by sharwell** [comment]
:+1:

**Comment by oatkins** [comment]
Good question. I just checked classic SC behaviour. The exception applies only to `using`. The following examples *do* result in `SA1503`.

```
for (int x = 0; x < 100; x++)
for (int y = 0; y < 100; y++)
{
}

while (true)
while (false)
{
}

if (true)
if (false)
{
}
```

Personally I think the classic behaviour is sensible. The concise form doesn't sacrifice readability for `using` directives, but for flow control structures requiring the braces *is* preferable.

**Comment by vweijsters** [comment]
:+1:  for `using` only

**Comment by appel1** [comment]
I'd prefer if the classic StyleCop behavior was the default with a setting to make it more strict if wanted/needed.

**Comment by ThomasZitzler** [comment]
👍 for using only

**Comment by dfyx** [comment]
:+1: for using only

**Comment by sharwell** [comment]
:memo: We made the default compatible with StyleCop Classic so no updates to **KnownChanges.md** were required.
