### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by dliuzzi** [DotNetAnalyzers/StyleCopAnalyzers#2194]
I don't know if this is a known issue, but the link to the list of rules (https://stylecop.pdelvo.com/) in the main README file is broken at them moment. First, Chrome shows a `NET::ERR_CERT_COMMON_NAME_INVALID` error because the security certificate it's using is for a different domain (dfischer.xyz). And then, after clicking *Proceed to stylecop.pdelvo.com (unsafe)* it serves an `403 Forbidden` page:

![pdelvo-1](https://cloud.githubusercontent.com/assets/143884/17971013/44a19ddc-6ad9-11e6-9447-59f64d5b7904.png)

![pdelvo-2](https://cloud.githubusercontent.com/assets/143884/17971016/4a156f14-6ad9-11e6-96bc-2cf8c7b3a7a4.png)

**Comment by dliuzzi** [comment]
The "up-to-date source code" link is broken as well. It looks like the whole of pdelvo.com is down.

**Comment by pdelvo** [comment]
I had some problems with my server at the worst possible time. Im currently working on my bachelor thesis which is now (mostly) done. Im now working on bringing these sites back up.

**Comment by pdelvo** [comment]
I fixed both websites

**Comment by dliuzzi** [comment]
Thanks a lot!
