### ISSUE TITLE
SA1118: ParameterMustNotSpanMultipleLines with nested constructor

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/StyleCopAnalyzers#2200]
In WPF it is pretty common to write:

```
public static readonly DependencyProperty BarProperty = DependencyProperty.Register(
    nameof(Bar),
    typeof(bool),
    typeof(Foo),
    new FrameworkPropertyMetadata(
        default(bool),
        FrameworkPropertyMetadataOptions.BindsTwoWayByDefault | FrameworkPropertyMetadataOptions.AffectsMeasure | FrameworkPropertyMetadataOptions.AffectsArrange,
        OnFooChanged,
        OnFooCoerce),
    OnFooValidate);
```

Rule 1118 does not like indenting the parameters of the nested constructor like this.
Putting the constructor of `FrameworkPropertyMetadata` on one long row mutes the message.

**Comment by sharwell** [comment]
I believe our intent was for this to be covered by #1597, but it appears to have been omitted. Marking as a bug based on this.

**Comment by bjornhellander** [comment]
I can have a look at this.
