### ISSUE TITLE
How to get a rule's default diagnostic severity or alternatively iterate over all rules

### ISSUE THREAD

**Issue by gh3x78E** [DotNetAnalyzers/StyleCopAnalyzers#2204]
Is there a way from within a rule implementation to get some other rule's (with a given diagnostic ID) diagnostic severity?

Alternatively can I get a list of all rules (other than with reflection) in order to iterate over them and get the diagnostic severity which was set it their respective DiagnosticDescriptor?

**Comment by vweijsters** [comment]
Yes there is a way, assuming that you have an analysis context available. Have a look at the [DiagnosticOptionsHelper.cs](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers/Helpers/DiagnosticOptionsHelper.cs) source to see how it can be done.

**Comment by gh3x78E** [comment]
Thanks for the hint. I looked into DiagnoticOptionsHelper, but unfortunately I am coming from SA1401 and therefore a SyntaxTreeAnalysisContext which does not supply a Compilation property. Is there another way?

**Comment by vweijsters** [comment]
Unfortunately its not possible for a `SyntaxTreeAnalysisContext`, as the `Compilation` property is internal.

I'm somewhat confused though, as [SA1401](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers/MaintainabilityRules/SA1401FieldsMustBePrivate.cs) is using a `SymbolAnalysisContext` and that one does have the `Compilation` property.
