### ISSUE TITLE
1407 ArithmeticExpressionsMustDeclarePrecedence

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/StyleCopAnalyzers#2210]
I like this style: `a + b*c`, ie. declare precedence by proximity. I find it easier to read than with parentheses.

What do you  think about relaxing the rule so that it treats lack of space as declared precedence.
We can still check that it is correct and flag `a+b*c` and `a + b * c`

**Comment by sharwell** [comment]
I think it doesn't look bad for this particular example, but for real-world cases involving longer identifiers (or perhaps even dotted expressions), I don't believe it would be nearly so readable.

Visual Studio doesn't have any equivalent formatting setting. Every time you type `}` to close a block containing an expression using this feature it will mess it up. By itself this certainly isn't a reason to reject a feature, but right now I see this as implementing a lot of changes to many rules (several spacing rules are affected), for little to no gain on readability and moving backward on usability.

**Comment by vweijsters** [comment]
👎 @sharwell sums it up nicely above.
