### ISSUE TITLE
SA1129 is an invalid rule

### ISSUE THREAD

**Issue by matthewDDennis** [DotNetAnalyzers/StyleCopAnalyzers#2212]
This rule say that you should use default(T) rather than new T() to create a default instance.
However default(T), when T is a reference type, returns null, not an instance of T.

https://msdn.microsoft.com/en-us/library/xwth0h0d.aspx

**Comment by bjornhellander** [comment]
@matthewDDennis Did you have an example of when you think this rule is not valid?

**Comment by sharwell** [comment]
Without further information, closing this as by-design. Let me know if there is anything we can do to improve communication surrounding this rule. :smile:
