### ISSUE TITLE
Analyzer does not show warning for SA1625

### ISSUE THREAD

**Issue by bootrider** [DotNetAnalyzers/StyleCopAnalyzers#2215]
Although the code includes copied documentation and the rule is set  as a warning and enable, after a Rebuild,  the analyzer does not show the warning

**Comment by vweijsters** [comment]
Hi, can you provide a code sample that triggers this behavior?

**Comment by bootrider** [comment]
Sorry, I was using an out-date version of the analyzer. my mistake
