### ISSUE TITLE
What is the project status?

### ISSUE THREAD

**Issue by lukas-ais** [DotNetAnalyzers/StyleCopAnalyzers#2219]
I really like this project!!
But, recently I feel, the project becomes inactive more and more. The number of commits is going down since month, the last one is nearly two month ago.
There are currently 215 issues open, 21 pull requests. The numbers are getting bigger and bigger.

I know, that it takes a lot of time to work on such project. But it is very angry to create pull requests without getting feedback.
Is there any road-map? When getting 1.0.1 or 1.1.0 or similar? (1.0.0 is 10 months ago.)
StyleCop (original) still seems not to run with C# 6 features. So StyleCop.Analysers is the best solution I found.

Please, feedback project status, give a (small) road-map, clarify work-flow (pull request, code review, ...).

**Comment by dfyx** [comment]
Yeah, I'm still waiting for #2198 to be merged...

Please show at least any signs of life or we have to assume that this project is dead.

**Comment by sharwell** [comment]
My main focus is helping finish a configurable, user-friendly code style feature tied in with Roslyn itself. Think of it like a less opinionated StyleCop which can be broadly adopted by projects where code style may differ. Eventually this will likely be the solution most users prefer.

I try to help out with StyleCop Analyzers as a small part of the work to make sure Roslyn APIs work well for external developers, and hopefully to keep the project up-to-date as the language evolves.

**Comment by sharwell** [comment]
@madelson We've made periodic update releases in that time and the product appears to be largely stable. Is there something in particular you are looking for?

**Comment by madelson** [comment]
@sharwell we have a large number of solutions on StyleCop.MsBuild which are running up against more and more of the C#7 syntax limitations. I'm trying to figure out whether we should migrate everything over to StyleCop Analyzers vs. waiting for the Roslyn-based solution you mention.

**Comment by sharwell** [comment]
@madelson If you are already using StyleCop, you'll probably want to switch to this project. The 1.1 beta releases have full support for C# 7. The Roslyn code style work targets users who *aren't* using StyleCop (and want a code style experience for either a different code style than StyleCop or want a simpler UI for it).
