### ISSUE TITLE
Use trailing commas for Enums (similar to SA1413)

### ISSUE THREAD

**Issue by RalfKoban** [DotNetAnalyzers/StyleCopAnalyzers#2239]
Similar to the new introduced maintainability rule SA1413 it would be nice to have such kind of rule for enum members as well (just to be consistent here).
It may also be less work for a reviewer as he can concentrate on the lines that changed but not the one that just got a trailing comma.

**Comment by sharwell** [comment]
👍 but I would prefer to just treat enums as lists for the purpose of the existing rule.

**Comment by vweijsters** [comment]
👍 I would also prefer to extend SA1413 to cover this case as well.

**Comment by RalfKoban** [comment]
Would be nice if SA1413 gets extended to cover this case as well.
