### ISSUE TITLE
StyleCopRules.ruleset manage panel in Visual Studio 2015 SP3.

### ISSUE THREAD

**Issue by AlekseyDev** [DotNetAnalyzers/StyleCopAnalyzers#2247]
I'm using  StyleCop.Analyzers "1.0.0" in Visual Studio 2015 SP3.
In manager window of StyleCopRules.ruleset for all rules of StyleCop.Analyzers in the column Name the value is "Uknown". May be I'm not right, please tell me how to configure Studio or extension to show the values of Rule Names. Or, May be it is the error in manager or in nuget. Project is NetCore.
Thank You.
![uknown names in rules](https://cloud.githubusercontent.com/assets/1162516/21003220/2c1f69f6-bd3b-11e6-84cd-a8eb1d7033da.png)

**Comment by agentschmitt** [comment]
I have the same issue in Visual Studio 2017 15.3 with NetCore Project.

**Comment by sharwell** [comment]
:memo: I believe this is a limitation in Visual Studio, where the rule set editor doesn't work with the new project system.
