### ISSUE TITLE
Fix all doesn't work in VS2017 RC (.NET Core)

### ISSUE THREAD

**Issue by FelschR** [DotNetAnalyzers/StyleCopAnalyzers#2254]
While testing the VS2017 RC release I noticed that "fix all occurrences" feature isn't working.

At least it's the case for .NET Core projects. Single fixes work as expected.

**Comment by LeastOne** [comment]
+1

**Comment by starkcolin** [comment]
Seems to be working fine in VS 2017 RTM

**Comment by FelschR** [comment]
Yeah, works again for me, too.
