### ISSUE TITLE
SA1501 is not applied to method blocks

### ISSUE THREAD

**Issue by tom-dudley** [DotNetAnalyzers/StyleCopAnalyzers#2257]
With SA1501 set I correctly get an error for the following code:
`if(true) { }`
indicating that the braces cannot be on the same line.

However the following code does not raise SA1501:

       public Foo()
            : this(true)
        { }

I'm guessing that the difference is that the if statement braces can be syntactically omitted, whereas the method body braces cannot. Could SA1501 be adjusted to support method body braces?

**Comment by sharwell** [comment]
:memo: SA1502 is reported for the provided sample, and the code fix moves the closing brace to its own line. Does this not work for your case?

**Comment by tom-dudley** [comment]
Ah, SA1502 does indeed work. Looks like I didn't have it enabled. Sorry about that!
