### ISSUE TITLE
SA1516 warning mispelled

### ISSUE THREAD

**Issue by GregReddick** [DotNetAnalyzers/StyleCopAnalyzers#2272]
"must" is spelled "myst" in SA1516. Somebody had an old computer game in mind or something.

**Comment by sharwell** [comment]
😆 

Might as well replace it with 'should' while we're fixing it.

**Comment by bjornhellander** [comment]
The spelling has already been fixed in commit bc574fc5, except for a comment in the code. Is it supposed to be 'must' for errors and 'should' for warnings for all diagnostics?

**Comment by sharwell** [comment]
@bjornhellander Technically yes, but we never went and updated them all.
