### ISSUE TITLE
Add new analyzer to validate that return value from function is used

### ISSUE THREAD

**Issue by tomekjanicki** [DotNetAnalyzers/StyleCopAnalyzers#2274]
try to do something similar to ReturnValueUsageAnalyzer in https://richiban.uk/2016/03/17/roslyn-analyzers/

**Comment by vweijsters** [comment]
StyleCopAnalyzers is all about coding style. The described case is about usage and not style, and therefore not suitable for StyleCopAnalyzers in my opinion. 

A better place would probably be [dotnet/roslyn-analyzers](https://github.com/dotnet/roslyn-analyzers), as they already have a rule that does something similar: [CA1806](https://msdn.microsoft.com/en-us/library/ms182273.aspx)
