### ISSUE TITLE
SA1314 (Type parameter names must begin with T) - 'K' name

### ISSUE THREAD

**Issue by kindermannhubert** [DotNetAnalyzers/StyleCopAnalyzers#2276]
SA1314 allows names like "T", "TKey", "TType" and so on.

There is of often use of single-letter name "K" in combination with single-letter "T" in existing code bases and it's problematic to start using this analyzer without manual rewriting o names.

Shouldn't be single-letter name "K" allowed too?

**Comment by sharwell** [comment]
It is common practice in Java for generic type parameters to omit the `T` prefix with the exception of the parameter named `T` itself. This includes single-letter parameter like you'd find in `Map<K, V>`. However, C# code tends to use longer and more descriptive names to which the `T` prefix is added. We would expect a violation to be reported for a generic type parameter named `K`, with the resolution being renaming the parameter to `TKey`.
