### ISSUE TITLE
Some stylecop warnings does not disappear from Error List  when fixed (VS 2015)

### ISSUE THREAD

**Issue by ChristianKuhre** [DotNetAnalyzers/StyleCopAnalyzers#2279]
I and my department has just switched from stylecop classic to stylecop analyzers for all of our projects.

As a consequence of this we have had to fix a bunch of new stylecop errors introduced by the cool new rules and improvements. While performing this freshening of our code base, we have experienced that reported style warnings sometimes seem to persist in the Error List after being fixed. We are using Visual Studio 2015 with Update 3, and the stylecop warnings are reported and listed through IntelliSense with full solution analysis enabled. The persisted errors, as far as I can see, only disappear when Visual Studio is restarted.

Do any you have an idea about what could the reason for this behavior? 

Thank you very much in advanced.

**Comment by sharwell** [comment]
Sometimes it takes a while for the IDE to refresh the defects.

:question: What version of StyleCop Analyzers are you using?

💭 If you are using 1.0.0, it may help to use a rule set file to set the severity of SA0000 to Hidden. This is the default starting with 1.1.0.

**Comment by ChristianKuhre** [comment]
We are using 1.0.0, so I will try to set the severity of SA0000 to Hidden and see if it gets better.

Thanks again for the help.
