### ISSUE TITLE
headerDecoration is not being generated

### ISSUE THREAD

**Issue by THammond9** [DotNetAnalyzers/StyleCopAnalyzers#2285]
Following the instructions at [Configuration.md](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md) I am using the following settings in the stylecop.jason file:

    "settings": {
        "documentationRules": {
          "companyName": "FooCorp",
          "copyrightText": "Copyright (c) {companyName}. All rights reserved.",
          "headerDecoration": "-----------------------------------------------------------------------"
        }
      }

but the header generated looks like:

    // <copyright file="LDMApp.cs" company="FooCorp">
    // Copyright (c) FooCorp. All rights reserved.
    // </copyright>

As you can see the decoration is missing. Why is that? What do I need to do the generate the header decoration?

**Comment by vweijsters** [comment]
Hi, what version of StyleCop.Analyzers are you using?
The functionality that you mention is only available since 1.1.0-beta1

**Comment by THammond9** [comment]
The latest version from NuGet, version 1.0 I think.

**Comment by THammond9** [comment]
Looks like you answered my question. This feature is not in the stable version. It is confusing because the documentation does not mention version information anywhere. When reading it as a first time user I expected all of the features mentioned to be in the stable version since there is no information indicating otherwise.

**Comment by vweijsters** [comment]
I understand your confusion, that's why I created issue #2294 to update the documentation.

**Comment by DasOhmoff** [comment]
Hallo, I have the newest version and the following settings

```
        "documentationRules":
        {
            "copyrightText": "Copyright (c) Test. All rights reserved.",
            "headerDecoration": "################################################################################################",

            "companyName": "Test",
            "xmlHeader": false
        },
```

But the generated text is as follows:
```
// Copyright (c) Test. All rights reserved.
```

As you can see, without any decoration. I have the newest StyleCop.Analyzers version installed. How can I fix that?
