### ISSUE TITLE
How to enable AdditionalRules

### ISSUE THREAD

**Issue by vfabregat** [DotNetAnalyzers/StyleCopAnalyzers#2291]
Hi all,

I want to enable the additionalrule SX1309 available in [Beta001](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/releases/1.1.0-beta001) but I don't know how to do it, and I cant find any information about this.

There are some documentation about how that?
Regards.

**Comment by bjornhellander** [comment]
It's mentioned in Configuration.md, linked from the project's README, which is visible on https://github.com/DotNetAnalyzers/StyleCopAnalyzers. From the top of my head:

Enabling rules, disabling rules and configuring severity for rules are all done from the Solution Explorer for all Roslyn based analyzers. Locate your project and expand References -> Analyzers -> StyleCop.Analyzers. You will see a list of all available rules, so in your case you can scroll down to SX1309 and set it's severity to Warning or Error. The configuration will be saved in a ruleset file which Visual Studio will add for you if you don't already have one in your project.

If you have more than one project in the solution, they can share ruleset files if you want to. In that case, bring up the project's Properties view and select the "Code Analysis" page. In there, you can select which ruleset file to use in your project.

**Comment by vfabregat** [comment]
Thanks a lot! I forgot to mention, i'm working in a aspnet core project (.net full framework). In that case the analysers aren't listed in the project references. Is an error in the project template (or visual studio) itself?
