### ISSUE TITLE
Wrong SA1119

### ISSUE THREAD

**Issue by taoyouh** [DotNetAnalyzers/StyleCopAnalyzers#2312]
In the following statement, the parenthesis are necessary, but the analyzer throws an SA1119.
`emailBlock.Text = (new ResourceLoader).GetString(Email);`

**Comment by sharwell** [comment]
I get CS1526 when I try that. Was that example intended to be valid C# code?

**Comment by taoyouh** [comment]
Sorry, the problem is that I missed a pair of parentheses.

**Comment by sharwell** [comment]
@vweijsters @pdelvo Should we suppress SA1119 when the expression contains a syntax error?

**Comment by vweijsters** [comment]
That would be a nice feature to have and probably several other rules can benefit from such a construction as well. It would not be high on my priority list though, as it is only a minor inconvenience.
