### ISSUE TITLE
SA 1101 Showing up even though I set '"Do not prefer 'this.'" on my options

### ISSUE THREAD

**Issue by jewpaltz** [DotNetAnalyzers/StyleCopAnalyzers#2321]
Microsoft Visual Studio Enterprise 2017
Version 15.0.26228.9 D15RTWSVC
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Enterprise

Visual C# 2017   00369-60000-00001-AA436
Microsoft Visual C# 2017

ASP.NET and Web Tools 2017   15.0.30223.0
ASP.NET and Web Tools 2017

ASP.NET Web Frameworks and Tools 2017   5.2.50127.0
For additional information, visit https://www.asp.net/

**Comment by bjornhellander** [comment]
The option that you mention is for Visual Studio itself and does not affect how StyleCop Analyzers behave. 
There is information about how to configure StyleCop Analyzers' behaviour on this site, reachable from the top page. Let us know if you don't find what you're looking for!

**Comment by jewpaltz** [comment]
Thank you so much.
