### ISSUE TITLE
custom ruleset is not picked up during build in VS2015 and 2017. The StyleCop.Analyzers are running the default rules and throwing warnings.

### ISSUE THREAD

**Issue by manistellar2016** [DotNetAnalyzers/StyleCopAnalyzers#2323]

**Comment by bjornhellander** [comment]
Could you supply a simple project file which behaves in this way?

**Comment by mikes-gh** [comment]
Have you added the ruleset and json to your migrated csproj
I found the migrate didn't do this.
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2310

**Comment by manistellar2016** [comment]
i think i've fixed this issue by adding a custom build.props and pointing the ruleset. All projects are now using the ruleset.

**Comment by mikes-gh** [comment]
I didn't know you could set it globally.  That would be great
I always added it to each project.
Could you share the config.

**Comment by tpluscode** [comment]
Similar here, I think. In `csproj` we have 

```
<PropertyGroup>
  <CodeAnalysisRuleSet>..\..\dotnetrdf.ruleset</CodeAnalysisRuleSet>
</PropertyGroup>

<ItemGroup>
    <AdditionalFiles Include="..\..\stylecop.json" />
  </ItemGroup>
```

Analysis works fine with `dotnet test` but building with VS2017 doesn't run it.

**Comment by suras48** [comment]
Is their any way to execute this in command line?

**Comment by sharwell** [comment]
@suras48 The analyzers execute when the project is compiled. The command line equivalent would simply be MSBuild.
