### ISSUE TITLE
Diagnostic unit tests: SA1025 (CodeMustNotContainMultipleWhitespaceInARow)

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#233]
Implement unit tests for #31.

**Comment by Noryoko** [comment]
Grabbing this if that's OK.

**Comment by Noryoko** [comment]
Multiple whitespace characters in an argument list do not produce a diagnostic result. Should this be reported as SA1025 or SA1001?
