### ISSUE TITLE
Ruleset vs GlobalSuppression.cs

### ISSUE THREAD

**Issue by mikes-gh** [DotNetAnalyzers/StyleCopAnalyzers#2332]
Are there any disadvantages to using Global suppression vs ruleset.
Global suppression seems to be more natural to me.

**Comment by vweijsters** [comment]
There is a small difference, but I'm not sure if it is very relevant (have a look [here](https://github.com/dotnet/roslyn/blob/47220dbdae9957abd7e1e64868ef8a2a38bd4e7b/src/Compilers/Core/Portable/DiagnosticAnalyzer/CompilationWithAnalyzers.cs#L1095)).

There is a minor performance benefit to using rule sets, but that would only become relevant for seriously large numbers of suppressed diagnostics.
