### ISSUE TITLE
Importing StyleCop.Analyzers Ruleset into another StyleCop ruleset is not loading the imported rules

### ISSUE THREAD

**Issue by manistellar2016** [DotNetAnalyzers/StyleCopAnalyzers#2334]
I am trying to import a ruleset into another ruleset. When my build runs it's not picking up the imported ruleset configurations.
Here is my configuration:
<?xml version="1.0" encoding="utf-8"?>  
<RuleSet Name="Static Analysis Rules" Description="Ruleset." ToolsVersion="14.0">
  <Include Path="..\test\analysis\test.ruleset" Action="Default" />
  <Rules AnalyzerId="StyleCop.Analyzers" RuleNamespace="StyleCop.Analyzers">
  <Rule Id="SA1120" Action="None" />
  <Rule Id="SA1121" Action="None" />
  <Rule Id="SA1122" Action="None" />
  <Rule Id="SA1028" Action="None" />
  <Rule Id="SA1515" Action="None" />
  </Rules>
</RuleSet>
The rules configured under test.ruleset are not picked up.

**Comment by vweijsters** [comment]
Hi, thanks for your feedback. The handling of rule sets is not done by StyleCop.Analyzers, but by the roslyn platform. I would advice you to create an issue in the dotnet/roslyn repository, as they will be more capable of helping you.

**Comment by sharwell** [comment]
@manistellar2016 If you are still encountering this issue, you should start by filing an issue in the [dotnet/roslyn](https://github.com/dotnet/roslyn) repository. If investigation reveals that the problem turns out to lie somewhere else we can help you get it to the right place.
