### ISSUE TITLE
SA1616 and asynchronous methods.

### ISSUE THREAD

**Issue by dlemstra** [DotNetAnalyzers/StyleCopAnalyzers#2335]
This project has unit tests to make sure that for the examples below the return type should be documented. 

```C#
public Task MethodAsync(string foo, string bar) { return null; }
public Task<int> MethodAsync(string foo, string bar) { return null; }
```

I do think this makes sense for the second case where the method returns an `Task<int>`. But I think that we should consider the first case as a `void` and not force the user to document this. I could create a pull request for this if you agree with this purposed change.

**Comment by sharwell** [comment]
I do not agree with the proposed change, since the method does have a return value. A code fix is provided which should suffice for the majority of these cases. It adds the following documentation for the `<returns>` element:

> A [Task]() representing the asynchronous operation.
