### ISSUE TITLE
Custom Code Analysis Rule Set does not display name or description of StyleCop.Analyzer rules

### ISSUE THREAD

**Issue by jayce-leathers** [DotNetAnalyzers/StyleCopAnalyzers#2340]
Having an issue this morning where the name of each of my StyleCop rules shows as unknown and the descriptions for each do not appear. Has anyone else had this issue? 

I'm running Visual Studio 2017 with the latest update. 
Where are these names/descriptions populated from, so that I can try track down why they are not appearing? 
![capture](https://cloud.githubusercontent.com/assets/6518729/24866536/651b83ae-1dd8-11e7-94f4-fe66f6d9c56e.PNG)

**Comment by jayce-leathers** [comment]
Problem has stopped after the weekend. I never did figure out what caused  it.

**Comment by t03apt** [comment]
I am having the same issue now. See: https://www.screencast.com/t/mR0wsmQ6bok
Analyzers tree also looks wired but it may not be an issue. There are many `StyleCop.Analyzers.resources` there. See: https://www.screencast.com/t/hiHiib3JJQJ

**Comment by sharwell** [comment]
> There are many StyleCop.Analyzers.resources there

dotnet/roslyn#21083

**Comment by t03apt** [comment]
Can anyone reproduce this issue? I mean all rule names being unknown.
Or is it working for you?

**Comment by inbabbini** [comment]
This is currently happening to me, also using VS2017 (Community)
![image](https://user-images.githubusercontent.com/11368222/36595096-ad4abbc0-187f-11e8-9534-07510d0a3e26.png)

**Comment by julealgon** [comment]
I'm seeing this exact same issue as well. Does anybody know how to fix it?

**Comment by Gav-Brown** [comment]
All my rules when viewed in Visual Studio 2017 or 2019 show **Unknown** for there name. Have done for some time now.

**Comment by iSeiryu** [comment]
VS 2017 Professional. Same problem with some analyzers. Roslynator displays the names properly only when its extension is installed.

![image](https://user-images.githubusercontent.com/129137/56746201-bf397c80-6749-11e9-85b8-502ac4858e93.png)

![image](https://user-images.githubusercontent.com/129137/56746278-e1cb9580-6749-11e9-8a88-97cb93171163.png)
