### ISSUE TITLE
System.TypeLoad Exception when stylecop.json file is included

### ISSUE THREAD

**Issue by munishxs** [DotNetAnalyzers/StyleCopAnalyzers#2343]
Hi ,

The steps to generate the issue :
1. Create a new Console project in VS2017.
2. Edit the project to have target framework as "net452"
3. Add nuget package StyleCop.Analyzers V 1.0.0.
4. Do some intentional changes in code to get analyzer warning.
5. Build the project using dotnet build command. Warning here will be same as at step 4.
6. Now include a stylecop.json file in the project , build action as Include Additional file.
7. Build project using the dot net build command

At this point it starts throwing System.TypeLoadException for mscorlib....Anyone ever encountered this issue ??

**Comment by frattaro** [comment]
The build action is 'AdditionalFiles', right?

**Comment by munishxs** [comment]
![image](https://cloud.githubusercontent.com/assets/27287323/25071386/64d2e7e6-22ad-11e7-9708-97080ed855bf.png)

**Comment by munishxs** [comment]
yes it is..see the above image

**Comment by frattaro** [comment]
I wonder if the package is being restored properly before building.

**Comment by munishxs** [comment]
yes it is , VS2017 editor don't give any issues , if I comment the AdditionalFiles thing , it works all fine. No Exception messages...So the reason for sure is this...but why ? I don't know...

**Comment by frattaro** [comment]
Can you post the contents of your stylecop.json?

**Comment by munishxs** [comment]
here it is 

![image](https://cloud.githubusercontent.com/assets/27287323/25071479/966fd1bc-22b0-11e7-9ff3-180fc9be729e.png)

**Comment by munishxs** [comment]
and the command prompt messages are 

![image](https://cloud.githubusercontent.com/assets/27287323/25071482/c6bd23c4-22b0-11e7-9453-36880ecf18ee.png)

**Comment by munishxs** [comment]
Any update on this ?

**Comment by mikes-gh** [comment]
Currently Stylecop analyzers doesnt support netstandard yet.

Because dotnet build uses the xplat version of msbuild which is netstandard based it wont work.

I am guessing if you build in visual studio it works because that uses full framework msbuild?

I too am waiting for this

**Comment by munishxs** [comment]
Yes building in Visual Studio is fine ...no warnings there...

**Comment by mikes-gh** [comment]
In that case you will have to wait for netstandard support.
I believe the warning are all related to JSON.NET which needs to be updated to a netstandard version with its netcore dependencies which is why when you include a json file you get all the warnings.
I really hope we get a new version soon as all my projects  use this analyser and all my new projects are netcore.  I am also using vscode now whenever I can as vs 2017 is so slow and buggy at the moment.

**Comment by mikes-gh** [comment]
This issue is the same as #2310
