### ISSUE TITLE
StyleCop Analyzers still runs analysis when <RunCodeAnalysis> is false

### ISSUE THREAD

**Issue by nathanscottdaniels** [DotNetAnalyzers/StyleCopAnalyzers#2345]
Here's our situation:

We are using Visual Studio 2017.
We use StyleCop Analyzers to ensure all of our code is well documented.  Since we are producing proprietary software, we don't want to have XML documentation output upon build.  Since this output is required in order for StyleCop to actually check any of the doc rules (itself a serious breaking change from SC classic, IMO), we decided that as a workaround we will enable code analysis only for the Debug configuration.  So we set 

`<RunCodeAnalysis>true</RunCodeAnalysis>`

for the Debug config and

`<RunCodeAnalysis>false</RunCodeAnalysis>`

for the Release config.

However, even with analysis disabled, we get StyleCop warning/errors when we build under the Release configuration.  As a test, I disabled code analysis for all configurations and globally and we _still_ get the warnings and errors when we build.

Is there any way to disable stylecop for a certain config?  Why does it not obey the <RunCodeAnalysis> option?

Thanks for any help you can provide.

**Comment by vweijsters** [comment]
Hello, as far as I know the `<RunCodeAnalysis>` tag is used to trigger the execution of FxCop at the end of a build. The effect that you are trying to achieve can probably be done by using different code analysis rulesets for debug and release builds (using the `<CodeAnalysisRuleSet>` tag).
