### ISSUE TITLE
SA1011 false positive in interpolation string with formatting parameter

### ISSUE THREAD

**Issue by NikolayIT** [DotNetAnalyzers/StyleCopAnalyzers#2347]
Consider this code:

    $"{x.Name} [ZIP: {x.ZipCode}] ({officeZipsWithDistances[x.ZipCode]:F2})"

I don't think StyleCopAnalyzers should report `SA1011 Closing square bracket must be followed by a space.`.

What do you think?

**Comment by vweijsters** [comment]
You are correct. There already is an issue about this:  #2289, so marking this duplicate.
