### ISSUE TITLE
Combine StyleCop settings

### ISSUE THREAD

**Issue by mu88** [DotNetAnalyzers/StyleCopAnalyzers#2349]
Hello,

Is there a way to combine two different StyleCop settings files?

In our company, we are sharing StyleCop settings across several projects to ensure a common code quality. Right now, our settings are stored within an old `Settings.StyleCop` file, so I have to migrate them to `stylecop.json` anyway. This common settings file is referenced from all our projects via NuGet (we have encapsulated the StyleCop settings file into a NuGet package and placed it on our own NuGet server). In addition, I'd like to have the ability to disable specific StyleCop rules on a project-level, so the general and the project-specific have to be brought together to check StyleCop rules within VS and on our CI server, but without changing the project-spanning settings file.

How could I achieve this with the new analyzers?

Regards

**Comment by vweijsters** [comment]
Hello, I think the best approach here would be to have a shared `stylecop.json` file that you can distribute through NuGet and to use custom rule sets per project to exclude specific rules.

StyleCop Analyzer rules are not disabled in the `stylecop.json` file, but through the rule set mechanism of Visual Studio. See https://msdn.microsoft.com/en-us/library/dd264949.aspx for details.

**Comment by mu88** [comment]
Great! I will try this, thank you very much.
