### ISSUE TITLE
Creating your own rule

### ISSUE THREAD

**Issue by alex3848** [DotNetAnalyzers/StyleCopAnalyzers#2350]
Tell please, it is possible to create the own rule in net core?

I tried so:

1) created a "Analyzer with Code Fix (NuGet + VSIX)" project
2) created a nuget package from this project (dotnet pack)
3) created a test project(net core), download my package , and registered in .ruleset the id of the rule

The new rule isn't applied.

**Comment by alex3848** [comment]
Tell please, it is possible to create the own rule in net core?

  I tried so:
  1) I created the "Analyzer with Code Fix (NuGet + VSIX)" project
  2) create nuget package for new rule
  3) I created a test project,  download my package , and registered in .ruleset the id of the rule

The new rule isn't applied.

**Comment by sharwell** [comment]
@alex3848 The best place to ask this question is here:

https://github.com/dotnet/roslyn/issues

That project is either directly responsible for making these templates work correctly, or they know who is. :smile:
