### ISSUE TITLE
SA 1126 reports false positive with new C#7 inplace definition out construct

### ISSUE THREAD

**Issue by CFlatWouldbeMinor** [DotNetAnalyzers/StyleCopAnalyzers#2355]
The code feature out variable from C#7 results in a false positive 

public void PrintCoordinates(Point p)
{
    p.GetCoordinates(out int x, out int y);
SA1126:CSharp.Readability: The call to x must begin with...

**Comment by CFlatWouldbeMinor** [comment]
Forgot to mention this is with the version for 1.1.0-beta001 (via nuget)

**Comment by bjornhellander** [comment]
With the risk of looking like a complete idiot... This rule is not implemented in StyleCop Analyzers.
I'm, not sure what you have done... Maybe you have StyleCop Classic installed?

**Comment by sharwell** [comment]
It does sound like both StyleCop Classic and StyleCop Analyzers is installed. Here's the code for SA1126 in StyleCop Analyzers:

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers/ReadabilityRules/SA1126PrefixCallsCorrectly.cs#L48
