### ISSUE TITLE
VS15 - different results in code analysis and intellisense.

### ISSUE THREAD

**Issue by SpindlerS** [DotNetAnalyzers/StyleCopAnalyzers#2357]
Hello,

I changed StyleCop in my project to use Analyzers (StyleCop.Analyzers 1.0.0). I made my ruleset and everything was fine ...until I noticed that VS intellisense tells me a broken rule (SA1623). But code analysis does not.
The rule is broken in my code so I expected a warning on code analysis as configured in the ruleset.

I checked:

* Changing other rules has an impact on code analysis
* Changing SA1623 to error has the expected effect on intellisense

Addition:
I also get no warning for SA1600. In stylecop.json I added:
`"documentPrivateElements": true, "documentPrivateFields": true`
but it seems to have no effect. Company name and copyright text are known, there is no problem.
Intellisense continues to show everything correct.

I'm not sure if this a StyleCop-Analyzers related problem, but that's my first point. Any help is greatly appreciated!
best regards, Sören

**Comment by tom-dudley** [comment]
@SpindlerS Where are you looking for the warning? The `Error List` pane?

Also if it's your first time setting up the `stylecop.json`, did you set the `Build Action` to `AdditionalFiles`?

**Comment by SpindlerS** [comment]
@tom-dudley thanks for your response.

Yes, I look at the Error List pane in VS.
And yes, I changed Build Action to AdditionalFiles.

**Comment by tom-dudley** [comment]
Do you find them if you switch the dropdown from `Build + IntelliSense` to the `Build Only` or `IntelliSense Only`?

**Comment by SpindlerS** [comment]
`Intellisense Only` shows the correct warnings to be expected.
`Build Only` falsely shows no warnings (ignores some rules like I mentioned, SA1600, SA1623).
`Build + Intellisense` shows the same as `Intellisense Only` does.

**Comment by sharwell** [comment]
@SpindlerS You disabled rule SA1652 in your rule set file. In more recent releases, we renamed this to [SA0001](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA0001.md) and made the message much more aggressive because people kept disabling it. The new message reads as follows:

> ⚠️ All diagnostics of XML documentation comments has been disabled due to the current project configuration.

**Comment by SpindlerS** [comment]
Okay, so I think I have not understood this rule correctly. 
Thanks for yor answer, I appreciate it very much!
