### ISSUE TITLE
Using stylecop.json offline

### ISSUE THREAD

**Issue by deanchester** [DotNetAnalyzers/StyleCopAnalyzers#2359]
I have a standalone development machine that is not internet connected, So in my stylecop.json file this line is not valid: 

    {
      "$schema": "https://raw.githubusercontent.com/DotNetAnalyzers/StyleCopAnalyzers/master/StyleCop.Analyzers/StyleCop.Analyzers/Settings/stylecop.schema.json"
    }

Is there anyway I can set the schema to a local directory?

**Comment by sharwell** [comment]
You can change it to any URI provided the machine can resolve it to a schema. However, if you have multiple developers working on the project you'll want to make sure it resolves the same way for everyone.
