### ISSUE TITLE
SA1303 suggest to rename "_1var" to "1var"

### ISSUE THREAD

**Issue by sm-g** [DotNetAnalyzers/StyleCopAnalyzers#2360]
"1var" is invalid name for compiler

**Comment by bjornhellander** [comment]
@sm-g, could you check again that you actually get SA1303 for this? I get SA1309 instead. Just so we don't have more than one problem here... If you do get SA1303, which version are you using?

**Comment by bjornhellander** [comment]
I can fix the problem with the code fix for now, until we have sorted out which diagnostic is actually triggered.

**Comment by sm-g** [comment]
Now I got SA1312 in same place.

**Comment by bjornhellander** [comment]
Me saying "I get SA1309 instead" is really stupid, since you didn't tell us what your code looks like :-)
Could you provide more information about your code and in what situations you see SA1303 and SA1312?
