### ISSUE TITLE
Add tests for LocalFunctionStatementSyntaxWrapper

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#2384]
This wrapper type was added in #2370 without tests. It's not too difficult to add them; see commit c31beae and other examples from that pull request for how to implement good coverage of these types.

**Comment by bjornhellander** [comment]
I can have a look at this

**Comment by sharwell** [comment]
@bjornhellander Maybe start with #2376 (a simpler case) and then do this one?

**Comment by bjornhellander** [comment]
😄 Yes, I just randomly picked one and I see that there are smaller ones available, so I'll have a look at some other wrappers first and come back to this soon. You can keep it assigned to me for now if you want.
