### ISSUE TITLE
Add tests for ParenthesizedVariableDesignationSyntaxWrapper.AddVariables

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#2387]
This method was added in #2370, but tests were not added for this particular method.

**Comment by zanseb** [comment]
Grabbed. Is there anything I have to consider?

**Comment by sharwell** [comment]
@zanseb Can you send a pull request with your changes? That will help us review them. :smile:

**Comment by zanseb** [comment]
Ok, done. 😃
