### ISSUE TITLE
double click on warning in output window can open the wrong file

### ISSUE THREAD

**Issue by Jero9999** [DotNetAnalyzers/StyleCopAnalyzers#2417]
This seems to happen if there are files with the same name in different projects. It could happen to files with the same name that are in different folders of the same project too. I haven't checked.
The error is that when you double click the warning in the output window it will always take you to the same file of that name. For example if you have two projects, both of them having a file called `class1.cs` and both of those files have style warnings in them. Then warnings in the output file for both projects will open the first project's class.cs file. 
They should open the specific file that the warning was generated about.

Running VS2017 Enterprise, stylecop 1.1.0-beta003

**Comment by sharwell** [comment]
@Jero9999 I was noticing that as well, and I'm 99% sure it's a Roslyn bug. Do you know what specific version of VS 2017 you are using?

**Comment by Jero9999** [comment]
More details than you were looking for probably :) :

 

Microsoft Visual Studio Enterprise 2017 

Version 15.2 (26430.13) Release

VisualStudio.15.Release/15.2.0+26430.13

Microsoft .NET Framework

Version 4.6.01038

 

Installed Version: Enterprise

 

Visual Basic 2017   00369-60000-00001-AA757

Microsoft Visual Basic 2017

 

Visual C# 2017   00369-60000-00001-AA757

Microsoft Visual C# 2017

 

Visual F# 4.1   00369-60000-00001-AA757

Microsoft Visual F# 4.1

 

Add New File   3.5

The fastest and easiest way to add new files to any project - including files that start with a dot

 

ASP.NET and Web Tools 2017   15.0.30503.0

ASP.NET and Web Tools 2017

 

ASP.NET Core Razor Language Services   1.0

Provides languages services for ASP.NET Core Razor.

 

ASP.NET Web Frameworks and Tools 2017   5.2.50303.0

For additional information, visit https://www.asp.net/

 

Azure App Service Tools v3.0.0   15.0.30209.0

Azure App Service Tools v3.0.0

 

Azure Data Lake Node   1.0

This package contains the Data Lake integration nodes for Server Explorer.

 

Azure Data Lake Tools for Visual Studio   2.2.5000.0

Microsoft Azure Data Lake Tools for Visual Studio

 

Bundler & Minifier   2.4.340

Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

 

Common Azure Tools   1.9

Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

 

CSS Tools   1.0.14

Provides additional features to the CSS editor in Visual Studio.

 

Editor Enhancements   1.0.27

Provides additional features such as HTML and URL encodings, transformations and sorting of selected text the editor.

 

EditorConfig Language Service   1.17.204

Language service for .editorconfig files.

 

EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs.

 

Fabric.DiagnosticEvents   1.0

Fabric Diagnostic Events

 

File Icons   2.7

Adds icons for files that are not recognized by Solution Explorer

 

File Nesting   2.6.67

Automatically nest files based on file name and enables developers to nest and unnest any file manually

 

HTML Tools   1.0.3

Productivity tools for the HTML editor

 

Image Optimizer   3.6.103

Uses industry standard tools to optimize any JPEG, PNG and Gifs - including animated Gifs. Can do both lossy and lossless optimization.

 

Image Sprites   1.4.47

Boost your website's performance by creating image sprites to reduce the amount of HTTP requests needed.

 

JavaScript Language Service   2.0

JavaScript Language Service

 

JavaScript Transpiler   0.9.24

The simplest way to transpile JS and JSX to EcmaScript 5 without any complicated node.js tools in your project. It uses the TypeScript compiler behind the scenes.

 

KofePackagePackage Extension   1.0

KofePackagePackage Visual Studio Extension Detailed Info

 

Markdown Editor   1.11.214

A full featured Markdown editor with live preview and syntax highlighting. Supports GitHub flavored Markdown.

 

Microsoft Azure Hive Query Language Service   2.2.5000.0

Language service for Hive query

 

Microsoft Azure Tools   2.9

Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50131.1

 

Microsoft MI-Based Debugger   1.0

Provides support for connecting Visual Studio to MI compatible debuggers

 

NuGet Package Manager   4.2.0

NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

 

Open Command Line   2.1.179

Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc. Provides syntax highlighting, Intellisense and execution of .cmd and .bat files.

 

Package Installer   2.0.101

Makes it easier, faster and more convenient than ever to install Bower, npm, Yarn, JSPM, TSD, Typings and NuGet packages to any project

 

Package Security Alerts   1.0.17

Identifies npm and Bower packages that contains known security vulnerabilities to ensure your project is always using the most secure package versions.

 

Project File Tools   1.0.1

Provides Intellisense and other tooling for XML based project files such as .csproj and .vbproj files.

 

SQL Server Data Tools   15.1.61702.140

Microsoft SQL Server Data Tools

 

Syntax Highlighting Pack   2.7.125

Adds syntax highlighting and snippet support for a wide variety of programming languages such as Clojure, Go, Jade, Lua, Swift, Ruby and many more...

 

ToolWindowHostedEditor   1.0

Hosting json editor into a tool window

 

TypeScript   2.2.2.0

TypeScript tools for Visual Studio

 

Vue.js Pack 2017   1.1.8

Contains HTML Intellisense and code snippets for the Vue.js JavaScript library

 

Web Compiler   1.11.326

Compiler for LESS, Sass and CoffeeScript files

 

Web Extension Pack 2017   15.0.2

The easiest way to set up Visual Studio for the ultimate web development experience.

 

ZenCoding   1.2.11

Provides ZenCoding for the HTML Editor - full support for static HTML, Razor and WebForms.

**Comment by sharwell** [comment]
This is an issue either with Visual Studio or with Roslyn. A workaround can be found in dotnet/roslyn#26904.
