### ISSUE TITLE
stylecop.json settings don't appear to work in .NET Standard projects

### ISSUE THREAD

**Issue by DRAirey1** [DotNetAnalyzers/StyleCopAnalyzers#2433]
1. Create a blank solution.
2. Add a .NET Standard library project to the solution.
3. Use NuGet to add StyleCop Analyzer 1.0.2 to the library project.
4. Open up Class1.cs.  Click on the suggestion at the top of the file, click on the option to 'Add Style Cop Settings to Project.'
5. Edit the stylecop.json file created in step 4 to add a company name and copyright text.
6. Go back to Class1.  Click on the suggestions had have it add the header.  It adds 'PlaceholderCompany' and continues to tell you there's an error.
It doesn't appear that StyleCop Analyzer is able to read the settings in the stylecop.json files with the .NET Standard projects.
Edit: If you manually set the build type to be 'C# Analyzer Additional File', it kicks into gear and starts working again.

**Comment by sharwell** [comment]
It's not possible to automatically add the file to the project and enable it for use, so we settled for adding the file with a big message that links to the instructions for enabling it. I updated the instructions in #2434 since the wording is slightly different in 2017.
