### ISSUE TITLE
SA1310 Add configuration option to allow UPPER_CASE_CONSTANTS

### ISSUE THREAD

**Issue by sdiachen** [DotNetAnalyzers/StyleCopAnalyzers#2448]
Can SA1310 rule be extended to allow UPPER_CASE_CONSTANTS?

While many teams prefer default naming for constants there are many devs who prefer proposed notation. Given that I think adding option in stylecop.json might be a good solution.

**Comment by sharwell** [comment]
Hi @sdiachen,

This project has made minor configuration changes related to very common C# coding styles, but this would be a substantial deviation to a style the project aims to avoid. Your best bet is waiting for the .editorconfig support in Visual Studio 2017 to be moved from the IDE layer to the compiler layer so the naming rules in dotnet/roslyn can be customized and used during your build.

Here's the specific issue for supporting this: dotnet/roslyn#18279

**Comment by sdiachen** [comment]
thanks @sharwell
