### ISSUE TITLE
"// <auto-generated />" does not work anymore ?

### ISSUE THREAD

**Issue by vd3d** [DotNetAnalyzers/StyleCopAnalyzers#2456]
Hi there,

I have several files generated by SWIG and they contains the `// <auto-generated />` comment at the second line.

The problem is that when I start an analysis, theses files are checked too !

It is intended to work, right ?

PS: I have also put it on the first line, no way !

**Comment by sharwell** [comment]
This should be working. Can you give an example of a warning you see in such a file?

**Comment by vd3d** [comment]
Sure,

`//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class luciadsdk_module {
}`

And the warning:

`MSBUILD : warning CA1050: Microsoft.Design : 'luciadsdk_module' should be declared inside a namespace.`

**Comment by bjornhellander** [comment]
CA1050 is a diagnostic from Visual Studios own code analysis. StyleCop's rules all start with SA or in some rare cases SX. Does any StyleCop dignostics trigger for you?

**Comment by sharwell** [comment]
@bjornhellander is right. Many different parts of the build are capable of reporting warnings, but we only have control over the ones reported by StyleCop Analyzers (and even then only limited control). If you see a StyleCop Analyzers warning in the generated code please feel free to reopen the issue.

**Comment by vd3d** [comment]
Ok I see, but when I remove all the MS rules, I got the following warning:

"CA0064 : No analysis was performed because the specified rule set could not be loaded or did not contain any managed code analysis rules"

So, it seems that StyleCopeAnalyzer rules are not checked ?

**Comment by sharwell** [comment]
@vd3d StyleCop Analyzers is not affected by the "Run Code Analysis" option (i.e. it will always run whether or not that setting is enabled).
