### ISSUE TITLE
SA1008 conflicting with C# 7 Tuples

### ISSUE THREAD

**Issue by zuckerthoben** [DotNetAnalyzers/StyleCopAnalyzers#2458]
The following line results in SA1008 being thrown on the returning tuple, but it makes no sense here.

`public (Appointment a, FolderId folderId) ConstructSendableExchangeAppointment(ExchangeAppointment ea)`

The fix is:

`public(Appointment a, FolderId folderId) ConstructSendableExchangeAppointment(ExchangeAppointment ea)`

This cant be right

**Comment by sharwell** [comment]
Duplicate of #2308. This was fixed in 1.1.0-beta003, which is the first version of the project to support C# 7. I highly recommend upgrading since it sounds like you are using the new features.

**Comment by zuckerthoben** [comment]
Awkward that the search did not show me this issue, when I searched for SA1008. Thank you anyway 👍

**Comment by sharwell** [comment]
No problem at all 👍
