### ISSUE TITLE
using CS 7 tuples causes warning SA1009

### ISSUE THREAD

**Issue by philipag** [DotNetAnalyzers/StyleCopAnalyzers#2484]
The following line does it:

async Task<(string, bool)> Function()

**Comment by philipag** [comment]
")>" should  be exempt from SA1009

**Comment by vweijsters** [comment]
I'm assuming that you are working with version 1.0.2, which does not support C# 7 features. 

Please try again with version 1.1.0-beta004 and let me know if the problem remains. I could not reproduce the issue using 1.1.0-beta004.

**Comment by philipag** [comment]
Nice catch. 1.1.0 resolves this.
