### ISSUE TITLE
SA1300 - allow exceptions

### ISSUE THREAD

**Issue by lukeguy99** [DotNetAnalyzers/StyleCopAnalyzers#2491]
Is it possible to specify specific prefixes or patterns which should be excluded from this rule? Looking at the documentation I could not find any way to do so.
Working with Xamarin and iOS, I get lots of violations for namespaces named "iOSsomething", which is styled that way by convention.

**Comment by sharwell** [comment]
@lukeguy99 Can you file an issue on [dotnet/roslyn](https://github.com/dotnet/roslyn). We're in the process of moving the naming rules, which are intended to be configurable, down to the compiler layer. The solution for cases like you describe would then be one of the following:

1. Rename the namespace to something like `IosSomething` or `AppleSomething`
2. Use a suppression that suppresses warnings created for that namespace declaration, but does not ignore anything inside it
    * This feature is already provided by Roslyn, but I believe you would need to include a suppression in every affected file
3. Disable rule SA1300, and optionally define a coding style using the Roslyn naming analyzers which supports your use case without reporting a violation on this namespace

**Comment by sharwell** [comment]
:memo: Given that StyleCop (and StyleCop Analyzers) are openly opinionated about matters of subjective style *and* the fact that the Roslyn project is planning to provide a less-opinionated (configurable) implementation of your feature request, it is unlikely that this configuration feature would move forward as part of SA1300.

**Comment by lukeguy99** [comment]
@sharwell Thanks for your inputs! I'm not aware of these changes you mentioned and I'm not sure where to look for more info about this process of moving rules to Roslyn. Could you point me in the right direction to get more information about this? Thanks!

**Comment by sharwell** [comment]
@lukeguy99 Sure. Keep in mind that the work in Roslyn would be considered an alternative to StyleCop developed from scratch, and targeting a slightly different audience. It's still a fairly early work in progress (making things configurable turns out to also be very time consuming). The work is generally being tracked here:

https://github.com/dotnet/roslyn/projects/4
https://github.com/dotnet/roslyn/projects/18

**Comment by lukeguy99** [comment]
@sharwell Thanks for the links, I'll take a look!
