### ISSUE TITLE
SA1009 with nullable value tuples

### ISSUE THREAD

**Issue by professor-k** [DotNetAnalyzers/StyleCopAnalyzers#2494]
`(int a, string b)? myVar;`
Is it just me? I would rather keep it without whitespace here.

**Comment by vweijsters** [comment]
I would classify that as a bug as well. The syntax as you wrote it is correct.

**Comment by vweijsters** [comment]
This has been fixed in #2478. I've added an additional testcase in #2495 to ensure that this case will remain covered. This change will show up in 1.1.0 Beta 5 when it is released.
