### ISSUE TITLE
How to fail .netcore2.0 build on stylecop warnings

### ISSUE THREAD

**Issue by alexandru-calinoiu** [DotNetAnalyzers/StyleCopAnalyzers#2511]
Is there a way to make the build fail on warning?

I can update ruleset and make all rules action="Error" but that is very tedious.

**Comment by sharwell** [comment]
You can turn on Treat Warnings as Errors, but make sure to only do so for command line builds:
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/2592d5b3572490da5196dd730af95882348f9565/StyleCop.Analyzers/Directory.Build.props#L25-L28

**Comment by Ravindra-a** [comment]
Can we do this at solution level or pass it as additional parameter ?
