### ISSUE TITLE
Enforce no file attribute in copyright header

### ISSUE THREAD

**Issue by twsouthwick** [DotNetAnalyzers/StyleCopAnalyzers#2512]
There doesn't seem to be the opposite option SA1637 "File Header Must Contain File Name" which would be "File Header Must Not Contain File Name". Is there a way for the analyzers to enforce this?

**Comment by sharwell** [comment]
SA1637 is never reported when XML headers are disabled. Can you add two examples here:

1. An example of a good header
2. An example of a header which, when configured like you want, will report a warning

**Comment by twsouthwick** [comment]
Good header:

```xml
// <copyright company="SomeCompany">
// Copyright info
// </copyright>
```

bad header (should be converted to what's above):


```xml
// <copyright file="somefile.cs" company="SomeCompany">
// Copyright info
// </copyright>
```

**Comment by sharwell** [comment]
💭 If you turn off XML headers, then you can set your desired header text to this:

```text
<copyright company="SomeCompany">
Copyright info
</copyright>
```

You won't get SA1637 but you will get a warning related to the extra text if you try to put the file attribute.

**Comment by twsouthwick** [comment]
That works as well - I can also force it to be one line instead of multiline this way :)

Is there any desire to include this as an first-class analyzer or should I close the issue?

**Comment by sharwell** [comment]
👍 Seems resolved for now.
