### ISSUE TITLE
suppress SA0001 for a project without suppressing in ruleset

### ISSUE THREAD

**Issue by SurajGupta** [DotNetAnalyzers/StyleCopAnalyzers#2514]
How do I suppress SA0001 for a project without suppressing in my ruleset?  Is there some analogy to Code Analysis' GlobalSuppressions.cs?

**Comment by sharwell** [comment]
SA0001 should never be disabled. In all cases where it is reported, the compiler is behaving incorrectly in ways that affect even the built-in IDE features.

**Comment by SurajGupta** [comment]
Maybe I'm misunderstanding that rule.   I thought it warns when XML doc is turned off?  We don't turn-on XML doc in Test projects.

**Comment by sharwell** [comment]
@SurajGupta Yes, it is frequently misunderstood. Disabling XML documentation is always a problem, even in test projects. My recommendation for test projects is the following:

* Leave SA0001 enabled
* Enable documentation generation
* Disable SA1573 and SA1591 in one of the manners described in [SA0001.md](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA0001.md#how-to-fix-violations)

This will fix the compiler analysis of documentation comments without reporting warnings for any cases where comments are not added.

**Comment by SurajGupta** [comment]
Hi Sam - at a high level you're saying that we can achieve the same effect (not require documentation in Test projects), but enabling XML Doc and then suppressing CS1573 and CS1591 (you meant CS, not SA, right?)

**Comment by sharwell** [comment]
Yes, that is correct (both in approach and identification of my typo).

**Comment by dsempi** [comment]
Hi @sharwell,
could you please be more specific in which respect the compiler is behaving incorrectly on what IDE features are affected?
> SA0001 should never be disabled. In all cases where it is reported, the compiler is behaving incorrectly in ways that affect even the built-in IDE features.

Is it by that meant only 

> Each project should be configured to include an XML documentation file with the compiled output. Otherwise, the semantics of all documentation comments are not checked and comments are likely to contain an increasing number of errors over time.

as described on [SA0001.md](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA0001.md#how-to-fix-violations) or anything more? Thanks!

**Comment by sharwell** [comment]
> could you please be more specific in which respect the compiler is behaving incorrectly on what IDE features are affected?

The compiler is treating `///` comments as if they were `//` comments. The most common side effect of this is having `cref` attributes that are incorrect and/or outdated. We also see a bunch of cases where the XML structure of the comment can't be parsed, which leaves Quick Info unable to use them.

**Comment by dsempi** [comment]
Thanks! It means, if no `///` were used in the code, it's safe to disable documentation generation, right?

**Comment by izhovkin** [comment]
We are not using xml documentation and don't care how compiler treats /// comments. And there is no way to build the project because SA0001 fires up. There should be a way to use StyleCop in projects that does not use xml documentations at all.
