### ISSUE TITLE
is it normal that StyleCop.Analizers gets added as a depency?

### ISSUE THREAD

**Issue by JuanZamudioGBM** [DotNetAnalyzers/StyleCopAnalyzers#2515]
I added StyleCop.Analizers to all my projects in my solution, but when I created my packages using
 msbuild /t:pack /p:Configuration=Release (.net core preview 2)

StyleCop.Analizers its added as a dependency

Is there a way to avoid this? obviously I don't want the analyzer to be a dependency on my package

**Comment by sharwell** [comment]
Did you set up your project according to the [.NET SDK Projects](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/DotNetCli.md#net-sdk-projects-csproj) documentation?

**Comment by JuanZamudioGBM** [comment]
I was the PrivateAssets part, thanks for your help
