### ISSUE TITLE
Spelling check should automatically ignore URLs in comments

### ISSUE THREAD

**Issue by cnshenj** [DotNetAnalyzers/StyleCopAnalyzers#2516]
URLs in comments should be exempt from spelling check.

- Adding words to dictionary doesn't work because fragments in URLs are not valid words
- Adding suppression doesn't work because it will suppress the whole comment which may contain spelling errors.

Example:
`/// <summary>See http://foo/bar for detals</summary>`
Both "foo" and "bar" are not spelling errors, but "detals" is a typo of "details".

**Comment by bjornhellander** [comment]
I'm not aware that there is spell checking in StyleCop.Analyzers. Are you possibly confusing this product with the original StyleCop? If you still think this is the correct product, please provide more information about what errors or warnings that you get and what version you are using.

**Comment by sharwell** [comment]
@bjornhellander is correct. The spelling check was omitted from StyleCop Analyzers in favor of allowing users to choose a suitable alternative that best meets their needs (e.g. an IDE extension or other standalone analyzer option).
