### ISSUE TITLE
requests to  https://raw.githubusercontent.com/DotNetAnalyzers/StyleCopAnalyzers/master/StyleCop.Analyzers/StyleCop.Analyzers/Settings/stylecop.schema.json from VS

### ISSUE THREAD

**Issue by JuanZamudioGBM** [DotNetAnalyzers/StyleCopAnalyzers#2519]
I have a lot of request to https://raw.githubusercontent.com/DotNetAnalyzers/StyleCopAnalyzers/master/StyleCop.Analyzers/StyleCop.Analyzers/Settings/stylecop.schema.json withing VS,

is there a way to configure this? I dont see the point of making that many request

**Comment by sharwell** [comment]
❓ How many is "a lot"? These files are cached by Visual Studio on each machine to reduce the number of lookups.

You can copy the schema to a location within your source repository, and update your **stylecop.json** file to use a relative URI pointing to that instead.

**Comment by JuanZamudioGBM** [comment]
about 100 requests a second

I will try that, thanks

**Comment by sharwell** [comment]
@JuanZamudioGBM Which IDE are you using? Do you know the source of these lookups? These requests should only occur when the stylecop.json file is opened for editing, and should only occur once per user per machine.

**Comment by JuanZamudioGBM** [comment]
VS2017 15.3 (released yesterday)
When I Open the file the requests don't stop until I close the file, I'm using .net core 2 and the version of the analyzer is 1.0.2
