### ISSUE TITLE
Rule SA1009 should deal with closing parenthesis as the end of a value tuple

### ISSUE THREAD

**Issue by hen1990fr** [DotNetAnalyzers/StyleCopAnalyzers#2522]
The Rule SA1009 is defined as:
"A closing parenthesis should never be preceded by whitespace. In most cases, a closing parenthesis should be followed by a single space, unless the closing parenthesis comes at the end of a cast, or the closing parenthesis is followed by certain types of operator symbols, such as positive signs, negative signs, and colons.

If the closing parenthesis is followed by whitespace, the next non-whitespace character should not be an opening or closing parenthesis or square bracket, or a semicolon or comma."

In some cases the closing parenthesis can be used to define a value tuple.
If, for example, a list of value tuples is defined, the syntax can be like

`IEnumerable<(string a, int b)> tupleList;`.

I suggest to add the "greater-than-sign" as an additional exception for the rule SA1009 to allow these code structures.

Maybe code changes concerning this issue can be combined with a solution for the issue [Rule SA1008 should add => for expression based properties/functions as exception](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2521) by handling value tuples generally.

**Comment by sharwell** [comment]
:memo: This is supposed to be covered by the following test:

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/94ff9be5073f74e8bffa3bed7ff3e5b85be5183f/StyleCop.Analyzers/StyleCop.Analyzers.Test.CSharp7/SpacingRules/SA1009CSharp7UnitTests.cs#L808-L841

**Comment by bjornhellander** [comment]
@hen1990fr Which version are you using?

**Comment by hen1990fr** [comment]
@bjornhellander I'm currently using the last stable Version 1.0.2 via NuGet.  So there is the point. A short research showed, that the commits, in which the support of value tuples was added, were made later with the tag 1.1.0 (beta4). Correct me, if I'm wrong.

**Comment by sharwell** [comment]
@hen1990fr The 1.1.0 beta releases are the first ones to support C# 7 syntax.

**Comment by msmolka** [comment]
I'm using .NET 4.6.2 and 1.1.0-beta4 and still seeing this error.

**Comment by vweijsters** [comment]
@msmolka Can you provide sample code? I cannot reproduce it here.

**Comment by msmolka** [comment]
All looks working it occurred that even if NuGet was installed, the analyzer section in csproj was missing, and I missed that because of resharper. It would be good to have easier info when StyleCop is not properly installed. I had the same issue today, when tried to create empty project to reproduce. Added new nuget but there were no StyleCopAnalyzers under Analyzers section in references.

**Comment by sharwell** [comment]
> It would be good to have easier info when StyleCop is not properly installed.

The new project system will deal with this by no longer requiring that the section exist in the project at all.

**Comment by DrGriff** [comment]
I get this using the v1.0.2 with
`public Dictionary<Guid, IEnumerable<(Guid p1, string p2, Guid p3)>> MyProperty { get; set; }`

**Comment by sharwell** [comment]
@DrGriff that is expected; see https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2522#issuecomment-325152888 above
