### ISSUE TITLE
Question - When will 1.10 be released?

### ISSUE THREAD

**Issue by SurajGupta** [DotNetAnalyzers/StyleCopAnalyzers#2523]
Hello - Wondering if you have a rough estimate of when 1.10 will be out of beta and fully released?  Are there specific issues that are holding-up the release or some fixed-window that's been set to allow it to bake?

**Comment by sharwell** [comment]
It's possible we could have the release finalized by the end of January. There isn't a lot of pressure typically because (as far as I know) the NuGet limitations that apply to pre-release packages don't apply to development-only dependencies.

**Comment by SurajGupta** [comment]
Thanks!

**Comment by SurajGupta** [comment]
This has been pre-release without a version rev in years; that feels like an abuse of the pre-release concept and it's creating problems with our process.

Our internal analyzer package depends on this this package.  As such, our internal analyzer package remains in pre-release.  As such, our internal analyzer package doesn't show up in Visual Studio unless we check the "include pre-release" box.  So often enough, we'll mistakenly install an older version of our analyzer package (non-pre-release) because it's atypical to need or want to install or update any pre-release packages.

What's the major barrier to releasing this thing?

**Comment by wlscaudill** [comment]
I agree with @SurajGupta, two years seems a little egregious for a pre-release package. 

Please rev the stable package.

Thank you!

**Comment by sharwell** [comment]
@SurajGupta @wlscaudill You can reference [StyleCop.Analyzers.Unstable](https://www.nuget.org/packages/StyleCop.Analyzers.Unstable/) if you want to avoid the prerelease versioning.
