### ISSUE TITLE
Stylecop.json not being picked up in old visual studio csproj (non-dotnet core)

### ISSUE THREAD

**Issue by UmairB** [DotNetAnalyzers/StyleCopAnalyzers#2528]
I am trying to use the analyzers with a previous csproj project, pre dotnet core version. So far my updated csproj looks like this

Ruleset
```
<CodeAnalysisRuleSet>$(SolutionDir)\..\References\StyleCop\StyleCop.ruleset</CodeAnalysisRuleSet>
```

stylecop json
```
<AdditionalFiles Include="$(SolutionDir)\..\References\StyleCop\stylecop.json">
    <Link>stylecop.json</Link> 
</AdditionalFiles>
```
As well as the analyzer dlls
```
  <ItemGroup>
    <Analyzer Include="..\..\packages\StyleCop.Analyzers.1.0.2\analyzers\dotnet\cs\StyleCop.Analyzers.CodeFixes.dll" />
    <Analyzer Include="..\..\packages\StyleCop.Analyzers.1.0.2\analyzers\dotnet\cs\StyleCop.Analyzers.dll" />
  </ItemGroup>
```

Here are the contents of my json file
```
    "settings": {
        "documentationRules": {
            "documentInterfaces": true,
            "documentExposedElements": true,
            "documentInternalElements": true,
            "fileNamingConvention": "metadata",
            "companyName": "ABC",
            "xmlHeader": false
        },
        "orderingRules": {
            "usingDirectivesPlacement": "preserve",
            "blankLinesBetweenUsingGroups": "omit"
        },
        "namingRules": {
            "allowCommonHungarianPrefixes": true,
            "allowedHungarianPrefixes": [
                "i",
                "oa",
                "sp",
                "z"
            ]
        }
    }
```

Non of the rules in the json file are being applied.

**Comment by sharwell** [comment]
> So far my updated csproj looks like this

❓ When you double click on **stylecop.json** in Solution Explorer, does the file open in the editor?

❓ When you open the **stylecop.json** file in the editor and hover over `"documentInterfaces"`, does a tool tip show?

❓ When you open the **stylecop.json** file in the editor, are any warnings shown in the Error List window?

> Here are the contents of my json file

❓ It appears that the content of your settings file is not valid JSON. Have you posted the complete file contents?

> Non of the rules in the json file are being applied.

❓ Can you indicate a specific warning you see appearing which suggests this is the case?

**Comment by UmairB** [comment]
(1) yes it opens
(2) no tooltip!
(3) no warnings
(4) Entire file
```
{
    "$schema": "https://raw.githubusercontent.com/DotNetAnalyzers/StyleCopAnalyzers/master/StyleCop.Analyzers/StyleCop.Analyzers/Settings/stylecop.schema.json",
    "settings": {
        "documentationRules": {
            "documentInterfaces": true,
            "documentExposedElements": true,
            "documentInternalElements": true,
            "fileNamingConvention": "metadata",
            "companyName": "Orbus Software",
            "xmlHeader": false
        },
        "orderingRules": {
            "usingDirectivesPlacement": "preserve",
            "blankLinesBetweenUsingGroups": "omit"
        },
        "namingRules": {
            "allowCommonHungarianPrefixes": true,
            "allowedHungarianPrefixes": [
                "i",
                "oa",
                "sp",
                "z"
            ]
        }
    }
}
```
(5) For example, the prefixes in the namingRules are not being applied, nor am I getting an error for missing documentation on, e.g. interfaces (I have the ruleset setup to throw errors).

I have tried the same thing on new VS project csproj format. Json file does get picked up on those.

**Comment by sharwell** [comment]
Can you add a copy of your rule set file?

**Comment by UmairB** [comment]
Yes ofcourse:
[StyleCop.ruleset.txt](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/files/1281433/StyleCop.ruleset.txt)

**Comment by sharwell** [comment]
@UmairB First of all, you need to re-enable SA0001. That rule should never be disabled. I'll look through the rest of the rules now.

**Comment by sharwell** [comment]
> For example, the prefixes in the namingRules are not being applied

SA1305 is disabled, which is the only rule that uses the configuration values you specified under `"namingRules"`.

> nor am I getting an error for missing documentation on, e.g. interfaces

SA0001 is designed to prevent this from occurring, but you have it disabled.

**Comment by UmairB** [comment]
Ah naming rules is now working! Thanks (and sorry about that). I set SA0001 to Warning, but it is still not giving me any warnings on missing interface documentation?

**Comment by sharwell** [comment]
Are you seeing SA0001 reported during the build?

**Comment by UmairB** [comment]
No I am not seeing it.

**Comment by sharwell** [comment]
@UmairB Since you are using version 1.0.2, rule SA0001 is actually SA1652. We renumbered it for 1.1.x. You'll need to enable SA1652 to get diagnostics when using the old version.

**Comment by UmairB** [comment]
Ok yes. That did it. I need to go through the ruleset in more detail. Thank you again!
