### ISSUE TITLE
Unable to suppress issues of generated files

### ISSUE THREAD

**Issue by HardySoftware** [DotNetAnalyzers/StyleCopAnalyzers#2531]
To be honest I don't know if this is a VS2017 bug or StyleCop.Analyzers bug.

- I created a brand new UWP project
- Installed StyleCop.Analyzers via Nuget
- Project properties -> Build -> Treat warning as errors -> All
- Project properties -> Code Analysis -> Suppress result from generated codes

I fixed all style cop errors on build, but there is one I can never get around 

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS1591	Missing XML comment for publicly visible type or member 'MainPage.GetBindingConnector(int, object)'	App1	D:\Temp\App1\App1\obj\x86\Debug\MainPage.g.cs	30	Active

As you can see this cs file is generated from XAML. I attach entire project here for your reference, and use VS2017 Update 3 to open it on Windows 10.

Please let me know what is wrong with it.

Thanks

[App1.zip](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/files/1294448/App1.zip)

**Comment by sharwell** [comment]
There are two big things to point out here:

1. The "Suppress result from generated codes" option only applies to the old code analysis infrastructure. It is not used at all by Roslyn or Roslyn-based analyzers, including but not limited StyleCop Analyzers or the rewrite of FxCop rules being done in the [dotnet/roslyn-analyzers](https://github.com/dotnet/roslyn-analyzers) repository. Over time its use will wane with the goal of removing everything that once referenced it.
1. StyleCop Analyzers only reports warnings starting with SA and SX (though in theory we could cause one starting with AD). We have absolutely no control over any other warning. Warnings starting with CS are reported by the C# compiler itself.

One solution is to disable CS1591 for your project, as documented in the help page for [SA0001](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA0001.md). However, in response to https://github.com/dotnet/roslyn/issues/12702#issuecomment-308773795 I filed a bug internally (internally it's [Microsoft 13310683](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/13310683)) to fix this and it's been reported as not reproducible. According to [Daniel Zilcsak](https://www.linkedin.com/in/danielzilcsak/):

> I tried this repro on SDK 16240 (a recent RS3 one) and I could not reproduce any errors in Mainpage.g.cs. The error I saw was in Mainpage.xaml.cs around the MainPage constructor, and as soon as I added a documentation comment, the solution built fine.
>
> Which SDK were you using? I remember we fixed a bunch of these in RS3.

**Comment by HardySoftware** [comment]
The solution fi disable 1591 is to globally disable XML comment checking everywhere, including my own code?

**Comment by sharwell** [comment]
@HardySoftware If you are using StyleCop Analyzers, you should be able to turn on StyleCop Analyzers rules ([SA1600](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1600.md) and the like) which serve the same purpose as CS1591. The StyleCop Analyzers rules will not fire in generated code.

**Comment by HardySoftware** [comment]
Ok, it works for me. It turned off the annoying error from generated classes, and meanwhile my own code is still enforced by the stylecop.

Even though I don't quite understand how the change of rule set can only impact generated classes. Is it because the "RuleNamespace" in the rule set file? My current rule set file looks like

```
<?xml version="1.0" encoding="utf-8"?>
<RuleSet Name="New Rule Set" Description=" " ToolsVersion="15.0">
  <Rules AnalyzerId="Microsoft.CodeAnalysis.CSharp" RuleNamespace="Microsoft.CodeAnalysis.CSharp">
    <Rule Id="CS1591" Action="None" />
  </Rules>
  <Rules AnalyzerId="StyleCop.Analyzers" RuleNamespace="StyleCop.Analyzers">
    <Rule Id="SA1633" Action="None" />
  </Rules>
</RuleSet>
```

**Comment by sharwell** [comment]
@HardySoftware The C# compiler does not consider generated code when deciding where to report warnings, but the analyzer infrastructure does.
