### ISSUE TITLE
SA1008 false positive on out tuple

### ISSUE THREAD

**Issue by WiZaRo** [DotNetAnalyzers/StyleCopAnalyzers#2532]
The following code:

    var x = new Dictionary<string, (int, bool)>;
    x.TryGetValue("Test", out (int, bool) value);

Triggers "SA1008: Opening parenthesis should not be preceded by a space." on the second parentheses in the second line.
Fixing it causes "SA1000: The keyword 'out' should be followed by a space."
I beleive that after the 'out' keyword there should always be a space and thus SA1008 is giving a false positive.

I am using the NuGet package v1.1.0-beta004 in Visual Studio Community 2017 15.3.3

**Comment by sharwell** [comment]
It's possible this was already fixed as part of #2472, but I don't see a specific test case for it yet.

**Comment by dlemstra** [comment]
@sharwell Can we close this issue?
