### ISSUE TITLE
SA1101 false report for named tuple elements

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#2534]
The following code produced an SA1101 report, and the code fix threw an exception:

```csharp
protected async Task Method(Func<(Project project, bool fixAll), Task> verifyFixedProjectAsync)
{
  // SA1101 reported twice on the following line:
  Func<Project, Task> verifyAsync = project => verifyFixedProjectAsync((project: project, fixAll: false));
}
```

**Comment by NikolayIT** [comment]
Can confirm the problem on my side.

Example:
![image](https://user-images.githubusercontent.com/3106986/31663145-aff046d8-b349-11e7-897c-47e18db98f6b.png)

Code:

    audit.ClaimCreditorsOptions = localCaseInfo.Claims
        .Select(x => (CreditorName: $"{x.CreditorName} ({x.ClaimDescription})", x.NdcClaimId))
        .Distinct();

**Comment by dlemstra** [comment]
@sharwell Do you need help with this issue? I would not mind giving it a try.

**Comment by sharwell** [comment]
@dlemstra Go for it 👍

**Comment by petrce** [comment]
are you planning to release it? thanks :)
