### ISSUE TITLE
[Question] Why the rule Identifier isn't showing in some cases?

### ISSUE THREAD

**Issue by WAir** [DotNetAnalyzers/StyleCopAnalyzers#2545]
I know I can desactivate ordering rules (or other kind of rules) to avoid warnings (SA1201     ElementsMustAppearInTheCorrectOrder in this case):

![pasted image at 2017_10_16 10_44 am](https://user-images.githubusercontent.com/30416977/31618579-b3f7dc78-b268-11e7-809a-3a34884d18be.png)

But why it's not showing the rule identifier? I'm guessing that StyleCopAnalyzer doesn't want to mess with my code that much or something like that.

(I'm sorry if this is not the place for this kind of question)

**Comment by vweijsters** [comment]
The message displayed is the formatted message that we pass to Roslyn. It would be possible to add the identifier to the formatted message. Marking the issue with the enhancement / discussion tag to see if there is consensus about doing this.

**Comment by sharwell** [comment]
@vweijsters We should do the same thing the IDE does for all other messages, which means two things:

1. We shouldn't manually add the ID ourselves, as the compiler doesn't do that
2. If the situation changes, it would change within Roslyn itself and not within this project specifically

Here is the issue tracker for the project which is responsible for this situation:
https://github.com/dotnet/roslyn/issues
