### ISSUE TITLE
SA1650 - SpellCheckCorrectly problem with language

### ISSUE THREAD

**Issue by marspion** [DotNetAnalyzers/StyleCopAnalyzers#2552]
Hello,

Im not sure it is issue with StyleCop or with my PC configuration.
I have a problem with SA1650 rule. I reinstalled system on my PC (before reinstallation everything worked properly) and after that my StyleCop don't check documentation headers by correctly check (Polish language). I tried to reinstall StyleCop, copy settings from other programmers but it didn't help.

Do you know anything about this problem?

**Comment by vweijsters** [comment]
StyleCopAnalyzers does not have an implementation for SA1650, so the issue you have is with StyleCop classic.  You may want to file an issue with https://github.com/StyleCop/StyleCop for this.
