### ISSUE TITLE
SA1615 is raised for async methods returning a Task

### ISSUE THREAD

**Issue by Nihlus** [DotNetAnalyzers/StyleCopAnalyzers#2563]
I'm not sure if this is by design, but SA1615 is raised for async methods returning a Task. These methods are the async equivalent of returning void, for which return value documentation is not required.

**Comment by sharwell** [comment]
SA1615 is the expected result from this case. However, a code fix is provided to assist you in adding a standard documentation line covering the scenario.

**Comment by momt99** [comment]
@sharwell 
Excuse me, but I didn't get why this is an expected result. The function returning a `Task` is an async returning nothing, so no documentation is needed.

**Comment by sharwell** [comment]
@momt99 This rule interprets `Task` as a return value which is not `void`. If your project uses a different approach for interpreting/documenting return values, it would make sense to either disable SA1615 for your project, or implement a [`DiagnosticSuppressor`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.diagnostics.diagnosticsuppressor) for your project which automatically suppresses SA1615 for specific scenarios.

@mavasani do we have documentation for creating diagnostic suppressors? I wasn't able to find any in a search.

**Comment by manfred-brands** [comment]
@sharwell You can look at https://github.com/nunit/nunit.analyzers/tree/master/src/nunit.analyzers/DiagnosticSuppressors for examples. I can't recall what resources I used, but eventually got there.

**Comment by momt99** [comment]
Thanks for your information. I thought it would be better if there was built-in support for this special case.
