### ISSUE TITLE
A button to fix everything!

### ISSUE THREAD

**Issue by TheTota** [DotNetAnalyzers/StyleCopAnalyzers#2580]
When I use Stylecop Analyser on my projects, I just find myself going through each and every Stylecop-related warning and just chosing the fix option for that warning.
A button or something to fix every Stylecop-related warnings would be an interesting feature in my opinion, and a gain of time.

**Comment by vweijsters** [comment]
I would agree on that, but unfortunately that behaviour is the responsibility of Visual Studio and it is not something that we can influence.

**Comment by sharwell** [comment]
This is effectively a duplicate of dotnet/roslyn#8928.
