### ISSUE TITLE
SA1008 broken with tuples

### ISSUE THREAD

**Issue by crazycrank** [DotNetAnalyzers/StyleCopAnalyzers#2581]
SA1008 enforces spaces before opening parenthesises. 
This breaks together with tuples, since tuples should have a space before (and sometimes need to).
eg: 
`public static (int number, string name) MethodName()`
can not be written withouth a space infront of it.
eg2:
`var t = (1, "test");`
can actually be written without a space, but SA1003 enforces a space after the assign operator.

We're using version 1.0.2 of StyleCop.Analyzers

**Comment by vweijsters** [comment]
These issue have been fixed in 1.1.0-beta004. For projects using C# 7, I would advice to use this version, as its quality is quite good. It will not cover everything concerning new features in C# 7.0, 7.1 and 7.2 yet, but it is a serious improvement.

**Comment by elladan06** [comment]
How I can use the version 1.1.0-beta004 in my project? I used the Nuget StyleCop.Analyzers 1.0.2 and Nuget doesn't show any update.

**Comment by vweijsters** [comment]
Make sure to enable the 'Include prerelease' checkbox in the NuGet manager screen (or use the -IncludePrerelease command line option).
