### ISSUE TITLE
SA1513 falsely triggered in a tuple

### ISSUE THREAD

**Issue by llehn** [DotNetAnalyzers/StyleCopAnalyzers#2583]
return (actorRef, () =>
            {
                if (task.Wait(1))
                {
                    if (task.IsFaulted)
                        throw task.Exception;
                }
                else
                {
                    throw new TimeoutException("Simulator still not finished!");
                }
            });

Last line triggers SA1513 with a message:
 Error SA1513: Closing brace should be followed by blank line (41, 14)

I can't fix it, since inserting a newline causes SA1009
  Error SA1009: Closing parenthesis should not be preceded by a space. (43, 1)

**Comment by vweijsters** [comment]
This has been fixed in #2364. This fix will be released with 1.1.0-beta005, when it is done.
