### ISSUE TITLE
SA1210 is inconsistent with IDE's Remove and Sort Usings

### ISSUE THREAD

**Issue by ali-hk** [DotNetAnalyzers/StyleCopAnalyzers#2587]
SA1210 is inconsistent with IDE's Remove and Sort Usings when "Place 'System' directives first when sorting usings" settings is enabled for a UWP project. In that scenario, the IDE treats Windows.* namespaces as 'System' usings as well, where as SA1210 doesn't.
Sadly this setting exists and even more sadly the Windows.* idiosyncrasy exists, but SA1210 should respect that setting as well.

**Comment by ali-hk** [comment]
@vweijsters the IDEs behavior has apparently changed and is now limited to System.*. As such this change should probably be reverted.
Sorry for the trouble.

**Comment by vweijsters** [comment]
Ok, I'll create an issue for that. Thanks for letting me know.
