### ISSUE TITLE
Support for Visual Studio for Mac

### ISSUE THREAD

**Issue by johannes-schmitt** [DotNetAnalyzers/StyleCopAnalyzers#2588]
(This issue should be labeled with "question")

In _Visual Studio for Mac_, I can add the NuGet package. But no warnings are generated (neither during build nor during code changes in the IDE).

Is this is a problem of StyleCopAnalyzers?
Or does Visual Studio for Mac not (yet) support Roslyn analyzers via NuGet (and if so, does someone know where to find more information about that)?

**Comment by joelhess** [comment]
@johannes-schmitt Using VS4Mac 7.3 and the beta version of the analyzers worked for me to get the warnings/errors that I needed. I'm not sure if the beta is required, but that's what I had. You make need to edit the project to specify the Code Analysis rule set.
`<CodeAnalysisRuleSet>../../StyleCop.Analyzers.ruleset</CodeAnalysisRuleSet>`

**Comment by sharwell** [comment]
@KirillOsenkov this would be considered 'external' for this project, but do you know where this user can make such a request (or where a duplicate bug is already filed)?

**Comment by KirillOsenkov** [comment]
This repo is the best place to file this issue: https://github.com/mono/monodevelop

**Comment by TomSoderling** [comment]
> @johannes-schmitt Using VS4Mac 7.3 and the beta version of the analyzers worked for me to get the warnings/errors that I needed. I'm not sure if the beta is required, but that's what I had. You make need to edit the project to specify the Code Analysis rule set.
> `<CodeAnalysisRuleSet>../../StyleCop.Analyzers.ruleset</CodeAnalysisRuleSet>`

This worked for me as well - at least to get build warnings/errors to show up on rebuild of a particular project. I'm using VS for Mac 8.4.8 from the stable channel.
Using [this ruleset file](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers.ruleset) as a template I can set behavior for specific SA rules

Unfortunately, I don't see any of the nice roslyn squiggles I'm expecting to see at coding-time. Still trying to figure that out.
