### ISSUE TITLE
Settings.StyleCop not functioning properly

### ISSUE THREAD

**Issue by suras48** [DotNetAnalyzers/StyleCopAnalyzers#2591]
As per our requirement 
we have to analyse our code with styelcop rules and perform code analysis and export the result in to any file,For this we have performed belwo mentioned steps

1.Installed StylCop 4.7
2.From the installed path we have got the Settings.StyleCop file which can be used to select or unselect rules based on our requirement.
3.We have copied and pasted it inot our root directory of our code.
4.By Using StyleCopCmd we are trying to execute or perform teh code analysis using settings.StyleCop file.refer below command we are using
("StyleCopCmd.exe -sc E:\stylecop\FAPrint\Settings.StyleCop -d E:\stylecop\FAPrint\Configuration -of StyleCopReport.xml")

After executing the report is generated showing all the unselected rules as well.
FOr eg: if we unchecked the rule SA1600 but after executing it shows the SA1600 violation warning.

Kindly assist

**Comment by DarkCloud14** [comment]
I think you're at the wrong project reporting this problem. If you want to use the old StyleCop checkout the following project which also provides a newer version of the old StyleCop.
https://github.com/rfennell/StyleCopCmdLine
