### ISSUE TITLE
StyleCop Checks Do Not Respect Ruleset File During Build with dotnet from CommandLine- .NET Core

### ISSUE THREAD

**Issue by angelovstanton** [DotNetAnalyzers/StyleCopAnalyzers#2600]
I wanted to ask the same thing. I have modified in my ruleset file some specific checks. During the build in Visual Studio, no warnings are displayed. In CI the project is built with dotnet build (the projects are .NET Core and .NET Standard). All warnings are displayed - [https://www.screencast.com/t/wwAB1kgMB](https://www.screencast.com/t/wwAB1kgMB)
Here is how we use StyleCop in the MSBuild: https://gist.github.com/angelovstanton/d677299f3bb65cc790a4cf76e141be77

1. Is there a way the ruleset file to be respected during the build from the command line?

I tried different ways to stop the code analysis for specific build configuration but without success. 
2. Is there a proper way of doing it?

Thank you in advance for any help on the matter!

P.S. Maybe my issue is related to this one- #2596

**Comment by sharwell** [comment]
As indicated by line 13 of the log file, the variable `$(SolutionDir)` is not defined during the command line build with `dotnet`. You should replace the use of that variable with a relative path.

**Comment by angelovstanton** [comment]
You are absolutely right. I did what you suggested and everything is working as expected!
