### ISSUE TITLE
SA1500 reported for new arrays

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#2607]
Starting in 1.1.0-beta005 (currently unlisted from NuGet due to this bug), SA1500 is getting reported for lines like the following:

```csharp
yield return new object[] { $"class Foo\r\n{{\r\n}}" };
```

It appears to apply to any case of the following:

```csharp
new Type[] { object, ... }
```

**Comment by JimBobSquarePants** [comment]
I'm still seeing this for multiline arrays in 1.1.0-beta006

e.g.

``` c#
        private static readonly float[,] AtkinsonMatrix =
            new float[,]
            {
               { 0, 0, 1, 1 },
               { 1, 1, 1, 0 },
               { 0, 1, 0, 0 }
            };
```

**Comment by vweijsters** [comment]
Confirmed. As this is a closed issue, I'll file a new one for it.
