### ISSUE TITLE
Run StyleCop only on modified code

### ISSUE THREAD

**Issue by martinmine** [DotNetAnalyzers/StyleCopAnalyzers#2622]
I am working on applying StyleCop to an existing project. This project is however quite large and contains lots of different styles. I don't want to enforce StyleCop over night as the project will drown in warnings/errors from StyleCop. Is there a way to configure StyleCop in such a way that it will only report new code violations (e.g. only touched code based on a git diff)?

**Comment by sharwell** [comment]
This is not directly supported by StyleCop Analyzers, but Visual Studio 2017 includes a tool to help you:

> **Bulk-suppression / Baselining** – To suppress all active issues, you can select all issues in the Error List, right-click, and navigate to "Suppress" or you can right-click on your project in the Solution Explorer and navigate to *Analyze &rarr; Run Code Analysis and Suppress Active Issues*.

/cc @kuhlenh
