### ISSUE TITLE
StyleCopAnalyzers cannot be used in VS2017 only because StyleCopAnalyzers references Microsoft.CodeAnalysis, Version=1.2.0.0

### ISSUE THREAD

**Issue by RalfKoban** [DotNetAnalyzers/StyleCopAnalyzers#2633]
The StyleCop analyzers seem to have a reference to "_Microsoft.CodeAnalysis, Version=1.2.0.0_".
So unfortunately, when I try to build a project that uses the analyzers on a machine that only has VS2017 installed, I get compilation errors:

_(translated to English)_
```
CSC : error CS8032: An instance of StyleCop.Analyzers.SpacingRules.SA1004DocumentationLinesMustBeginWithSingleSpace-Analyzers cannot be built from <PathToMyNuGetPackages>\StyleCop.Analyzers.1.1.0-beta006\analyzers\dotnet\cs\StyleCop.Analyzers.dll: File or assembly "Microsoft.CodeAnalysis, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" or one of its dependencies cannot be found."
```
To get it working, it seems that I need to install VS2015.

It would be great if there would be no such reference so that I can use the analyzers also on a new machine that solely has VS2017 installed.

**Comment by sharwell** [comment]
It sounds like the assembly binding redirection for the compiler instance you are using are not correctly applied. On a system with only Visual Studio 2017, the compiler is required (per the backwards compatibility policy) to automatically substitute the 2.x versions of these assemblies when an analyzer requests to load a 1.x version.

**Comment by dchaib** [comment]
I have the same issue (although I have not tried to install VS2015), but I'm not sure I understand your answer. Is there something I can do to fix the issue?

**Comment by sharwell** [comment]
@RalfKoban @dchaib I'm going to need the inner exceptions information to do anything here.

**Comment by dchaib** [comment]
@sharwell I'll be happy to help but I don't know how to get the inner exceptions... Can you help me?

**Comment by sharwell** [comment]
@dchaib If you use the Report a Problem tool in Visual Studio, you can record the steps triggering the problem. The instructions for Performance problems shown on https://aka.ms/reportPerf are sufficient for capturing the errors you described. After uploading your performance report, reply to this thread with a link to the feedback item and I can look at the details.

**Comment by dchaib** [comment]
@sharwell Sorry for the late reply. I have been trying to record the problem, but every time I start recording, it stops immediately, saying :

> Please wait while we finish collecting additional information. This may take a few minutes and the Visual Studio instance you are recording for cannot be accessed at this time.

I don't have time to reproduce the issue before...

**Comment by dchaib** [comment]
I finally found a way to fix my issue!

I first upgraded the .Net framework version from 4.5.1 to 4.7.1. It didn't fix the issue, but was maybe necessary for the next step.

I then upgraded the NuGet package `Microsoft.Net.Compilers` from 1.0.0 to 2.8.2 and all the warnings disappeared.

**Comment by sharwell** [comment]
> I then upgraded the NuGet package Microsoft.Net.Compilers from 1.0.0 to 2.8.2 and all the warnings disappeared.

Ah, yes. This forced the compiler to Roslyn 1.0.0, which is lower than the minimum version (1.2.0) supported by StyleCop Analyzers.
