### ISSUE TITLE
RESOLVED [question] MSBuild StyleCopTask like in the classic Stylecop

### ISSUE THREAD

**Issue by snowinmars** [DotNetAnalyzers/StyleCopAnalyzers#2638]
Hi.

I'm using [the classic StyleCop library](https://github.com/StyleCop/StyleCop) for force checking the project using the StyleCopTask from the StyleCop.dll inside the .target file

On the one hand, I want to migrate to the StyleCopAnalyzers.

On the other hand, I should save the MSBuild force checking process during building. Is there any way to inject the new approach inside MSBuild pipeline?

I found [the similar question](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2317#issuecomment-305753550) here, but it's still unanswered.

I tried to replace the old classic dlls with new StyleCopAnalyzers libraries, but I've been getting a message that the StyleCopTask class could not be loaded from the StyleCopAnalyzers dlls. Fairly...

**Comment by sharwell** [comment]
> Is there any way to inject the new approach inside MSBuild pipeline?

There is no way to *prevent* StyleCop Analyzers from running inside MSBuild. You can uninstall the old MSBuild tasks related to StyleCop Classic in the upgrade.

**Comment by snowinmars** [comment]
Well, thanks. I'll try to update my libraries.

**Comment by sharwell** [comment]
👍 Let us know if something isn't working for you
