### ISSUE TITLE
Why does SA1600 force the documentation of explicit interface implementations?

### ISSUE THREAD

**Issue by TiltonJH** [DotNetAnalyzers/StyleCopAnalyzers#2642]
I am forced to document explicit interface implementations.

For example:
```
/// <summary>
/// Returns an enumerator that iterates through this instance.
/// </summary>
/// <returns>An enumerator that can be used to iterate through this instance.</returns>
public IEnumerator<T> GetEnumerator()
{
	return this.list.GetEnumerator();
}

IEnumerator IEnumerable.GetEnumerator()
{
	return this.list.GetEnumerator();
}
```
I rather don't do that, because I am missing the point in doing so.

The code fix is to add `/// <inheritdoc/>` and I don't see how or in what case that fixes it, since it does not show up in intellisense.

**Comment by JimBobSquarePants** [comment]
`/// <inheritdoc/>` is not supported by intellisense yet (See https://github.com/dotnet/csharplang/issues/313) but this is coming. It does however, already work with most doc generators (SandCastle, docFX, Wyam)
