### ISSUE TITLE
Wrong error SA1008 : "Opening parenthesis must be spaced correctly" for c# 7 Value type tuple

### ISSUE THREAD

**Issue by shahjay748** [DotNetAnalyzers/StyleCopAnalyzers#2654]
![image](https://user-images.githubusercontent.com/17333887/38731261-a2998ce0-3ee7-11e8-95d6-ac4b296e58d0.png)

public static (double? From, double? To) xyz(...)
{
.....
}

This gives error at method return type declaration that SA1008 : Opening parenthesis must be spaced correctly

**Comment by vweijsters** [comment]
What version of StyleCop.Analyzers are you using? I can't reproduce this error in 1.1.0-beta006.

**Comment by shahjay748** [comment]
The latest one : 1.0.2, and I'm using .Net Core

**Comment by vweijsters** [comment]
For C# 7.0 features you need to use 1.1.0-beta006 or higher, as these features are not supported in 1.0.2.

**Comment by vweijsters** [comment]
The quality of the beta version is quite close to a release version, it just hasn't passed the stabilization phase yet. A discussion on the next release can be found in #2585.
