### ISSUE TITLE
How to use empty line as header decoration without triggering SA1028, SA1120

### ISSUE THREAD

**Issue by lennylxx** [DotNetAnalyzers/StyleCopAnalyzers#2657]
I'm using version `1.1.0-beta006`, and I have below settings:

```json
  "settings": {
    "documentationRules": {
      "companyName": "Foo",
      "copyrightText": "\r\nCopyright (c) {companyName} Corporation. All rights reserved.\r\n",
      "xmlHeader": false
    }
```

What I want to achieve is that:
```csharp
//<- no spaces here
// Copyright (c) Foo Corporation. All rights reserved.
//<- no spaces here
```
But the generated header contains an extra space in the 1st and 3rd line, like this:

```csharp
// <- 1 space here
// Copyright (c) Foo Corporation. All rights reserved.
// <- 1 space here
```

And it's violating [SA1028](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1028.md), if I removed the extra space manually, it's violating [SA1120](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1120.md).
How can I achieve the result I expected, without turning off SA1028 and SA1120?

**Comment by sharwell** [comment]
It's not currently possible, but it's fixable so I'm marking this as a bug. 😄

**Comment by lennylxx** [comment]
Nice to see this fixed, thank you for your work.
