### ISSUE TITLE
Adding StyleCop.Analyzers NuGet package to VS2017 Locks Up VS

### ISSUE THREAD

**Issue by CreepyGnome** [DotNetAnalyzers/StyleCopAnalyzers#2658]
Anytime I try to add StyleCop.Analyzer to my solution using NuGet and I select all 13 projects it locks up Visual Studio pretty quickly and requires it to be killed and restarted. It did it 3 times in a row. I could only add it in smaller batches of 5, 4, and 4. When adding "normal" Nuget packages that are just a DLL never have this issue. Something is special about this package causing it to crash/lockup VS2017 when doing a large number of projects at the same time.

**My VS - About - Installed Products**

Microsoft Visual Studio Enterprise 2017 
Version 15.6.6
VisualStudio.15.Release/15.6.6+27428.2037
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Enterprise

Architecture Diagrams and Analysis Tools   00369-90252-86752-AA170
Microsoft Architecture Diagrams and Analysis Tools

Visual C++ 2017   00369-90252-86752-AA170
Microsoft Visual C++ 2017

Visual F# Tools 10.1 for F# 4.1   00369-90252-86752-AA170
Microsoft Visual F# Tools 10.1 for F# 4.1

Application Insights Tools for Visual Studio Package   8.11.10402.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.40314.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.51214.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.40215.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.3000.4
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   15.0.40405.0
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.3.3000.4
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GitHub.VisualStudio   2.4.3.1737
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 2017.3.5    Build 111.0.20180323.160610
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2018 JetBrains, Inc.

JustDecompilePackage2017 Extension   1.0
JustDecompilePackage2017 Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.3.3000.4
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.3000.4
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   2.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.3.3000.4
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.51212.2

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Node.js Tools   1.4.11027.3
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61801.210
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   15.6.20202.3
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.7.0-beta3-62715-05. Commit Hash: db02128e6e3c4bdfc93e6ec425ac9162b4d4fe80
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

**Comment by sharwell** [comment]
Can you follow the steps listed here to report the issue? This will provide additional information that we can use to fix the problem, even if it lies somewhere inside Visual Studio or NuGet.
https://aka.ms/reportPerf

**Comment by CreepyGnome** [comment]
I'm a little confused as that doc, itself is also confusing, because it basically just says I should use the "Report a Problem Tool" in VS17 in a very long-winded way. Which doesn't send any data to you. Or are you asking me to give you a dmp file from the last crash or are you asking me to report the problem and attach a dmp file to it. As it also suggest adding a dmp file to an issue that is reported with the tool.

I can only reproduce the issue with this NuGet package, are you saying this isn't caused directly by your nuget package and that this is really a Visual Studio issue?

**Comment by sharwell** [comment]
@CreepyGnome I work for Microsoft and one of my roles here is reviewing performance reports submitted through that tool. 😄
