### ISSUE TITLE
One stylecop.json file per solution

### ISSUE THREAD

**Issue by RubenMateus** [DotNetAnalyzers/StyleCopAnalyzers#2660]
i am wondering if it's possible to have a single stylecop.json file for an entire solution with several projects inside.

**Comment by sharwell** [comment]
@frattaro is correct. The **stylecop.json** file can be included as a link so it can be placed in a shared location. This is the approach we use for the StyleCop Analyzers repository itself. 😄

**Comment by RubenMateus** [comment]
Thanks guys!
