### ISSUE TITLE
SA1139 fires for casts without an appropriate suffix alternative

### ISSUE THREAD

**Issue by Nihlus** [DotNetAnalyzers/StyleCopAnalyzers#2661]
The following code produces a SA1139 violation:

```csharp
var val = (byte)-1;
```

The same holds true for all casts (int, sbyte, byte, etc) that do not have corresponding suffixes. The rule also fires inside unchecked blocks.

**Comment by sharwell** [comment]
Related to #2275

**Comment by sharwell** [comment]
I was not able to reproduce this, but I added a few new tests for the cases.
