### ISSUE TITLE
SA1119 Works incorrectly with C# 7.0 pattern matching

### ISSUE THREAD

**Issue by neris** [DotNetAnalyzers/StyleCopAnalyzers#2662]
This code will trigger SA1119 (Statement must not use unnecessary parenthesis) while those parenthesis are necessary to make the expression negative.
```csharp
if (!(someVariable is TypeA typeAVariable))
```

On the other hand, if we use only type check without pattern matching, the error will not pop up:
```csharp
if (!(someVariable is TypeA))
```

**Comment by sharwell** [comment]
Duplicate of #2372
