### ISSUE TITLE
How can I import all my rules to Resharper so I can automatically fix all StyleCopAnalyzers suggestions? 

### ISSUE THREAD

**Issue by dmitribodiu** [DotNetAnalyzers/StyleCopAnalyzers#2685]
How can I import all my rules to Resharper so I can automatically fix all suggestions stylecop is giving? Or is there any autofix tool for StyleCopAnalyzers?

**Comment by JohanLarsson** [comment]
There are built in fixes for many rules, no need for Reshaper for fixing them. Moving forward you probably want to configure Resharper to be aligned with StyleCop so it does not generate code that needs fixing and to avoid conflicting nags. Resharer is very configurable so it is doable.

**Comment by dmitribodiu** [comment]
"There are built in fixes for many rules, no need for Resharper for fixing them." - Ok, I have a lot of lines of code, and I want to fix them all at once, is there any way to do it automatically?
"Moving forward you probably want to configure Resharper to be aligned with StyleCop so it does not generate code that needs fixing and to avoid conflicting nags. Resharper is very configurable so it is doable." - Exactly. The question is whether Stylecop rules can be easily imported into resharper, or I have to align my resharper rules manually...

**Comment by JohanLarsson** [comment]
Try `alt+enter` on the squigglies to see the fixes offered, for many there are fix all in project and sln. `Alt + enter` assumes Resharper without you use `ctrl+.` o the lightbulb thing.

There is no tool for importing from StyleCop to Resharper that I know of. There is a StyleCop extension for Resharper but I have not used it much so you have to try it. Configuring manually is not the end of the world IME, save to sln.dotsettings and check it in with the code.
