### ISSUE TITLE
Automatically consume stylecop.json if it exists

### ISSUE THREAD

**Issue by jeffkl** [DotNetAnalyzers/StyleCopAnalyzers#2698]
I'd like to contribute a feature to the NuGet package where StyleCop can automatically consume my `stylecop.json`.

I'd like to add a file to the package `build\StyleCop.Analyzers.props` which will search the directory structure of a code base for `stylecop.json` and include it.  Alternatively, users can just set a property like `StyleCopJsonPath` and it will get added appropriately.

```xml
<Project>
  <PropertyGroup>
    <!-- Walk up the directory tree looking for a stylecop.json -->
    <StyleCopJsonPath Condition=" '$(StyleCopJsonPath)' == '' ">$([MSBuild]::GetPathOfFileAbove('stylecop.json'))<StyleCopJsonPath>
  </PropertyGroup>

  <!-- Add $(StyleCopJsonPath) to <AdditionalFiles /> if the property is set and exists -->
  <ItemGroup Condition=" '$(StyleCopJsonPath)' != '' And Exists($(StyleCopJsonPath)) ">
    <AdditionalFiles Include="$(StyleCopJsonPath)">
      <Link>stylecop.json</Link>
    </AdditionalFiles>
  </ItemGroup>
</Project>
```

This would make it so I can just add a `<PackageReference />` and create a `stylecop.json` in the root of my repository.  Thoughts?

**Comment by sharwell** [comment]
I'm for this if we can avoid the pitfalls that led to #1788.

**Comment by jeffkl** [comment]
Thanks for the background.  I think creating the MSBuild items outside of a target should do the trick.  I'll also add some escape hatches so people can turn it off if necessary.
