### ISSUE TITLE
Should I use the pre-release package?

### ISSUE THREAD

**Issue by TimSirmovics** [DotNetAnalyzers/StyleCopAnalyzers#2701]
As a general rule we do not use pre-release NuGet packages and just stick to full releases.

I have been waiting a while for the 1.1.0 version of StyleCop to leave beta, and we are now coming up to almost a year since the first beta I can see on the releases page, the 1.1.0 Beta 2 release.

Is this version ever going to leave beta or should we just use the pre-release version?

**Comment by sharwell** [comment]
The pre-release will eventually go through stabilization late summer or early fall. I would recommend using the beta releases as they are maintained to a high quality bar.
