### ISSUE TITLE
Cannot change version StyleCop from 4.7 to 5.0

### ISSUE THREAD

**Issue by mefmund** [DotNetAnalyzers/StyleCopAnalyzers#2704]
Hello,
I have problem that i cannot change version of StyleCop from 4.7 to 5.0. In my company project starts on Visual Studio 2015 and now we want to change to Visual Studio 2017. 
When i enable built integration StyleCop in file csproj have line:

> Import Project="$(ProgramFiles)\MSBuild\StyleCop\v4.7\StyleCop.targets" 

Steps to reproduce:
1. right click on project 
2. Choose StyleCop Settings
3. It's opens window "StyleCop 5.0(5.0.6419.0) Project Setting
4. Change tab to "Build Integration"
5. Mark "Enable build integration"

Another thing is that StyleCop do not find any brakes of rules whet is started manually. I have marked all rules. Style errors in code exist I add them.
Steps to reproduce
1. Right click on file to check
2. From pop-up menu choose "Run StyleCop"
3. Check for errors

Please help me. :)

**Comment by sharwell** [comment]
This project is StyleCop Analyzers, which is an implementation of the original StyleCop rules using new C# compiler features. While we worked hard to implement this library so users of StyleCop Classic (the name we refer to the old StyleCop) can adopt StyleCop Analyzers instead, please keep in mind that the projects share at most a name. All of the code was rewritten from scratch and none of the authors are the same. I am not aware of the location (or if) StyleCop Classic is being maintained today.
