### ISSUE TITLE
How can I share a single CodeAnalysisRuleSet file between multiple git repositories?

### ISSUE THREAD

**Issue by comdw** [DotNetAnalyzers/StyleCopAnalyzers#2738]
I realise this may not be the perfect home for this question, it occurred to me that the contributors and followers of this project are more likely to know the answer.

Essentially we share a single stylecop ruleset file between multiple code repositories and that's done using an SVN external reference in each repository.  The ruleset is included in each project using the `<CodeAnalysisRuleSet>` element in the .csproj file (and the project also has the StyleCopAnalyzers package installed).

We're in the process of migrating to Git and can no longer use the external method.  A subtree or submodule just for a ruleset file seems overkill (its probably fewer commands to just copy the updated file everywhere vs updating a submodule/subtree everywhere anyway).  `<CodeAnalysisRuleSet>` doesn't support a URL location for the file, and although UNC paths appear to work, this isn't a viable solution for us.

Are there any other solutions to this that I'm missing?

**Comment by sharwell** [comment]
This is essentially a duplicate of #2637

**Comment by comdw** [comment]
I'll take a look at this, thanks.
