### ISSUE TITLE
Get indentation configuration from editorconfig/visualstudio

### ISSUE THREAD

**Issue by dnperfors** [DotNetAnalyzers/StyleCopAnalyzers#2745]
Hi,

I was thinking about a way to remove some duplicate settings in my solution and thought it would be nice to not have to specify the indentation settings twice: once in the editorconfig and once in the stylecop.json.

Would it be possible to use Roslyn’s Microsoft.CodeAnalysis.Formatting.FormattingOptions as a fallback?

If it is possible, could it be used for other rules as well, like naming rules?

**Comment by robertmclaws** [comment]
Any update on this?

**Comment by flcdrg** [comment]
I assume https://github.com/dotnet/roslyn/issues/18217 is what needs to be implemented to allow this to happen

**Comment by sharwell** [comment]
@flcdrg Yes, that's currently in progress. 😄

**Comment by HolisticDeveloper** [comment]
dotnet/roslyn#18217 is now done, but it looks like it is part of a larger effort for .editorconfig validation that is still unreleased. Am I reading that correctly?

**Comment by sharwell** [comment]
@HolisticDeveloper The APIs are now available, and would should be able to implement them as part of the existing light-up layer.

**Comment by manfred-brands** [comment]
@sharwell See my question in #3045 [comment](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3045#issuecomment-679461813):
> are there plans to make the code from Analyzer.Utilities.Options from the roslyn analyzers available to 3rd party analyzers like StyleCop and NUnitAnalyzers?

**Comment by sharwell** [comment]
@manfred-brands I'm not aware of any such plans. For this project, **.editorconfig** would only work in cases where the compiler is new enough to provide the feature directly.
