### ISSUE TITLE
False positive on SA1629 if text contains <code>

### ISSUE THREAD

**Issue by Allinuon** [DotNetAnalyzers/StyleCopAnalyzers#2761]
SA1629 reports a missing period if the text contains `<code>` .

For example SA1629 is saying a period is missing at the end of "Returns":

`<returns>Returns <code>true</code> if <paramref name="value1"/> equals <paramref name="value2"/>.</returns>`

**Comment by Allinuon** [comment]
Thanks. (learned something today!).

Given that <code> causes issue, perhaps another there should a new warning that makes the recommendation you just suggested?

**Comment by sharwell** [comment]
> Given that `<code>` causes issue, perhaps another there should a new warning that makes the recommendation you just suggested?

There are a few analyzers for documentation form that I've been meaning to place in a separate project. The recent work to create a portable test framework that many projects can use will hopefully simplify that effort.

**Comment by peteroupc** [comment]
Here is an example that shows why I believe SA1629 should not trigger if a `<code>` block appears at the end of a `<summary>`, `<param>`, `<example>`, `<remarks>`, etc.  Here, `code` really is a valid block of code:

    <example>
        The following is a code example.
        <code>
        public static void ExampleMethod(){
            Console.WriteLine("Example");
        }
        </code>
    </example>
