### ISSUE TITLE
Add support for tuple types for SA1008

### ISSUE THREAD

**Issue by PhilipAlexanderWallin** [DotNetAnalyzers/StyleCopAnalyzers#2762]
Currently for tuple variable declaration:
`var (a, b) = GetTupleResult();`
is suggested to be written as:
`var(a, b) = GetTupleResult();`

Also, same problem for method declarations:
`private (int, int) GetTupleResult()`
is suggested to be written as
`private(int, int) GetTupleResult()`

**Comment by vweijsters** [comment]
This problem only occurs when using C# 7.x in combination with StyleCop.Analyzers v1.02. Unfortunately this combination is not supported. C# 7.x support has been added in the 1.1.0-beta releases.
