### ISSUE TITLE
SA1650 Documentation mentions StyleCop.Settings

### ISSUE THREAD

**Issue by mario123456789o** [DotNetAnalyzers/StyleCopAnalyzers#2764]
Hi,
The documentation to [SA1650](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1650.md) mentions to put the customDictionary.xml next to the StyleCop.Settings. But in the new StyleCop, there is no StyleCop.Settings in my understanding?
Where do I have to put my CustomDictionary.xml?

Regards
Mario

**Comment by sharwell** [comment]
Duplicate of #1057

**Comment by mario123456789o** [comment]
OK thank you
I probably misunderstood the .md file.
