### ISSUE TITLE
CS1591 / SA1600 - disable for properties?

### ISSUE THREAD

**Issue by Compufreak345** [DotNetAnalyzers/StyleCopAnalyzers#2765]
Is it possible to disable CS1591 and SA1600 for properties, but not for methods, constructors, etc.? 

Especially on plain data-transferring objects I don't need a comment with "Gets or sets [Propertyname]" on each property.

Thanks & best regards,
Christoph

**Comment by sharwell** [comment]
> CS1591

This is controlled by the compiler, so the only thing users can do here is disable it altogether.

> Is it possible to disable ... SA1600 for properties ...

Perhaps not currently. There are a few possible solutions:

* Use `documentInterfaces` only
* Set `documentInternalElements` to false and mark DTO types as `internal`

It seems reasonable to create a configuration option for this, but the implementation has some interested versioning considerations so it may take some time to get a good design.
