### ISSUE TITLE
SA1008 false positive with tuples

### ISSUE THREAD

**Issue by af4jm** [DotNetAnalyzers/StyleCopAnalyzers#2766]
The parens at the start of the tuple should not be flagged for "SA1008 Opening parentheses must not be preceded by a space."

`protected RepositoryBase(IDbContext dbContext, IMapper mapper, ILogger<T> logger) =>
    (this.DbContext, this.Mapper, this.Logger) = (dbContext, mapper, logger);`

The analyzer incorrectly claims there should be no space after the `=` and before the `(`.  Removing that space results in a correct warning for SA1003.

**Comment by vweijsters** [comment]
This problem only occurs when using C# 7.x in combination with StyleCop.Analyzers v1.0.2. Unfortunately this combination is not supported. C# 7.x support has been added in the 1.1.0-beta releases.
