### ISSUE TITLE
variable names beginning with 'my' triggers SA1305 - should not use hungarian notation

### ISSUE THREAD

**Issue by jamesjohnmcguire** [DotNetAnalyzers/StyleCopAnalyzers#2770]
Pretty all stated in the title.

Example:

```csharp
private Xamarin.Forms.Maps.Position myPosition =
	new Xamarin.Forms.Maps.Position(-37.8141, 144.9633);
```

As a side note, not sure if 'my' actually means anything in Hungarian.

**Comment by sharwell** [comment]
This is the expected behavior. Allowed prefixes can be configured as described in [Hungarian Notation (Configuration.md)](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md#hungarian-notation).
