### ISSUE TITLE
SA1135 was not in StyleCop Classic?

### ISSUE THREAD

**Issue by Livven** [DotNetAnalyzers/StyleCopAnalyzers#2782]
I believe the SA1135 rule (SA1135UsingDirectivesMustBeQualified) was not in StyleCop Classic, but the [documentation](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1135.md) for it does not contain the corresponding notice.

**Comment by sharwell** [comment]
👍
