### ISSUE TITLE
Is possible to configure `this` keyword?

### ISSUE THREAD

**Issue by kkorus** [DotNetAnalyzers/StyleCopAnalyzers#2789]
Is it possible to configure `this` keyword. 
I want to enable rule `SA1101 Prefix local calls with this` but only for fields of a class, not a method.

Ideal: 
```csharp
var a = privateField; // warning, missing this
var b = PrivateOrPublicMethod(); // no warning
```

**Comment by sharwell** [comment]
No, it is not currently possible.

**Comment by kkorus** [comment]
@sharwell Would be nice to have it 😉

**Comment by sharwell** [comment]
Duplicate of #2612
