### ISSUE TITLE
Unnecessary parenthesis check is incompatible with `is` operator

### ISSUE THREAD

**Issue by abatishchev** [DotNetAnalyzers/StyleCopAnalyzers#2790]
Having the following expression:

```c#
var obj = new GetSome();
if (!(obj is null))
{
}
```

I'm getting a suggestion:

>Statement must not use unnecessary parenthesis.

Removing the parenthesis:

```c#
var obj = new GetSome();
if (!obj is null)
{
}
```

leads to a compiler error:

>Error    CS0023    Operator '!' cannot be applied to operand of type 'Foo'

The version I'm using:

```xml
<PackageReference Include="StyleCop.Analyzers" Version="1.0.2" PrivateAssets="All" />
```

**Comment by vweijsters** [comment]
The `obj is null` is  a C# 7 language construct. StyleCop.Analyzers 1.0.2 does not support c# 7, 1.1.0-beta releases are meant for that.
