### ISSUE TITLE
Format document

### ISSUE THREAD

**Issue by philipktlin** [DotNetAnalyzers/StyleCopAnalyzers#2792]
I used StyleCop (https://marketplace.visualstudio.com/items?itemName=ChrisDahlberg.StyleCop) with Visual Studio and Resharper;  and Resharper integrated with Visual Studio to format document based on StyleCop settings.  I would like to ask if StyleCop Analyzers can integrate with Visual Studio or Resharper to support "format document" based on StyleCop settings.

**Comment by sharwell** [comment]
The Format Document command uses configuration from [.editorconfig](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/5b9dc9ebfc22f8c8c4fec2be20d53d8606a69e32/.editorconfig#L29-L67), which can be manually specified for consistency with your StyleCop Analyzers configuration. Visual Studio 2019 is expected to add features allowing Code Cleanup operations to leverage third-party analyzers and code fixes, which should cover the remaining cases.

**Comment by beeuhtricks** [comment]
Any updates on this since the Code Cleanup features came out?

**Comment by sharwell** [comment]
Code cleanup does not currently support third-party analyzers and code fixes. I would recommend filing a feature request on https://github.com/dotnet/roslyn to add APIs supporting this functionality.
