### ISSUE TITLE
production usage for StyleCopAnalyzers

### ISSUE THREAD

**Issue by fish0185** [DotNetAnalyzers/StyleCopAnalyzers#2797]
Hi Guys, I really like this nuget package. It seems to it will leverage .NET Compiler to do the code analysis. However my team question me, is this package going to casing other issue for production, say performance or  security or any other considration?  here is usage on my project.
```xml
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>bin\Debug\netcoreapp2.0\Identity.xml</DocumentationFile>
    <NoWarn>1701;1702;1705;1591</NoWarn>
    <CodeAnalysisRuleSet>custom.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>bin\Release\netcoreapp2.0\Identity.xml</DocumentationFile>
    <NoWarn>1701;1702;1705;1591</NoWarn>
    <CodeAnalysisRuleSet>custom.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
 <ItemGroup>
    <PackageReference Include="StyleCop.Analyzers" Version="1.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  .........
  </ItemGroup>
```

Any help will much appropriate!

**Comment by sharwell** [comment]
This project is not intended to have any runtime component. However, it's not possible for us to provide any guarantee that the code behaves correctly (e.g. bugs in this project or differences in configuration where it is used resulting in unexpected behavior). If you have any specific concern, we can answer questions about the *intended* behavior, but your legal team will need to make a decision based on the [license agreement](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/LICENSE).
