### ISSUE TITLE
SemVer 2 update places releases in an unexpected order

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#2815]
Release **1.1.0-beta.47** is listed as "older" than **1.1.0-beta009**, but was intended to be newer. Without giving up the benefits of SemVer 2 and the new StyleCop.Analyzers.Unstable package, I see three ways this could be fixed:

1. Switch to **1.1.1-beta.x**
1. Switch to **1.1.x-beta**
1. Switch to **1.2.0-beta.x**

Do people have a preference?

**Comment by sharwell** [comment]
💭 I'm initially leaning towards option 3, **1.2.0-beta.x**

**Comment by vweijsters** [comment]
To stay (somewhat) in line with semver numbering: As there has been no new functionality added, it would make sense to bump it to 1.1.1-beta.x

**Comment by sharwell** [comment]
@vweijsters A fourth option would be to unlist (hide) the earlier 1.1.0 beta releases in the NuGet UI, so the new packages are the first 1.1.0 packages showing in the list.

**Comment by vweijsters** [comment]
That's fine with me as well, but I still prefer the 1.1.1-beta.x, as unlisting the packages may result in additional questions.
