### ISSUE TITLE
Proposal: add configuration to require space after cast

### ISSUE THREAD

**Issue by MariusVolkhart** [DotNetAnalyzers/StyleCopAnalyzers#2816]
Assume the code:
```C#
var str = "a string";
var obj = (object) str;
```

Currently, the cast on line 2 produces a warning due to SA1003 and SA1009 ([which can be disabled](#2151)).

I propose a configuration that _requires_ the space after the closing parenthesis of the cast.

**Comment by sharwell** [comment]
I lean towards not implementing this configuration for the same reasons given in :

> * Options in StyleCop Analyzers are typically implemented to handle one of two situations, neither of which applies to this case:
>     1. Compatibility with StyleCop Classic while offering an optional improvement
>     2. Cases where users are bucketed into large groups according to the option
> * The new Formatting Analyzer in Roslyn (in active development and already in a preview package on MyGet) will support this case

**Comment by sharwell** [comment]
📝 My recommendation in cases such as this is to use the Fix All provider in StyleCop Analyzers to update the code base to follow the recommended style, which does not include the space after a cast.

**Comment by YoshiRulz** [comment]
This is now covered by the built-in rule IDE0055; set [`csharp_space_after_cast = true`](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/csharp-formatting-options#csharp_space_after_cast) in your EditorConfig file.
