### ISSUE TITLE
1.1.0-beta009 crashed Visual Studio - too much memory consumed.

### ISSUE THREAD

**Issue by DrGriff** [DotNetAnalyzers/StyleCopAnalyzers#2826]
We have a very old Assembly that has many files and has never had the loving attention of someone used to StyleCop.  I analyzed it using the 1.1.0-beta009 version of StyleCopAnalyzers and Visual Studio stopped responding.  Visual Studio eventually came back to life (after about 5 mins) and briefly reported > 12,000 errors, then gave up the ghost.

With the StyleCop.MSBuild version, it identified the first 1,000 errors or so and then stopped.  My suggestion would be to have a similar cap for this Roslyn version (at least until VS becomes a 64bit application).

**Comment by sharwell** [comment]
I've verified in the past that StyleCop Analyzers can run single-pass Fix All in Solution operations effectively with 200,000+ errors shown. If you are still encountering memory-related crashes, I would recommend following the steps in https://aka.ms/reportPerf so we can investigate them directly. 😄

**Comment by DrGriff** [comment]
I'll investigate - thanks for the link.
