### ISSUE TITLE
StatementMustNotUseUnnecessaryParenthesis forces removing needed paranthesis

### ISSUE THREAD

**Issue by idigra** [DotNetAnalyzers/StyleCopAnalyzers#2828]
The mentioned rules claims that the following line is illegal:
            if (maybe.HasNoValue || !(maybe.Value is TTo value))
(maybe is a struct of type Maybe<T> from CSharpFunctionalExtensions nuget).

However it is not syntactically equivalent to remove this parenthesis. Without them, the compiler complains that operator "!" cannot be applied on maybe.Value.

**Comment by sharwell** [comment]
Duplicate of #2372
