### ISSUE TITLE
SA1633:FileMustHaveHeader warning comes for company name except PlaceholderCompany

### ISSUE THREAD

**Issue by subhendu-de** [DotNetAnalyzers/StyleCopAnalyzers#2834]
While I set up Stylecop Analyzer 1.0.2, I started getting SA1633 which is expected.
Once I put following text at the top of code file, it works
```
// <copyright file="Sample.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
```
But when I change the placeholderCompany to "Fabrikam Corp", it starts showing warning.
```
// <copyright file="Sample.cs" company="Fabrikam Corp">
// Copyright (c) Fabrikam Corp. All rights reserved.
// </copyright>
```
My understanding is we can put any company name. How could changing company name bring back the warning?

**Comment by sharwell** [comment]
The company name needs to be configured in **stylecop.json**. See [Copyright headers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md#copyright-headers).
