### ISSUE TITLE
Conflict between SA1407 and IDE0047

### ISSUE THREAD

**Issue by MrMikeJJ** [DotNetAnalyzers/StyleCopAnalyzers#2838]
Hi,
I know that SA1407 and IDE0047 are from separate places, but i didn't know the best place to report this to. (The IDE one is from Visual Studio 2017 - 15.9.4)

If you take the sample code: 
`int minutes = Math.Floor((input % (60 * 60)) / 60);`

IDE0047 fires and says should remove the extra parentheses around `(input % (60 * 60)`
If i remove these, SA1407 fires and says that they should be added.

Personally i agree with StyleCop on this one, i added them for clarity. Just thought i should make you aware of this conflict.
thanks
Mike

**Comment by MrMikeJJ** [comment]
Could anyone point me in the direction of where to report this to, to try and get IDE0047 changed ?
As mentioned, i agree with stylecop on this one, and believe the parentheses after the modulus aid clarity.
thanks
Mike

**Comment by sharwell** [comment]
Issues with IDE0047 can be reported to [dotnet/roslyn](https://github.com/dotnet/roslyn).

**Comment by AdamWillden** [comment]
@MrMikeJJ did you raise it with roslyn? If so can you link me?
