### ISSUE TITLE
Still get warnings despite ruleset file

### ISSUE THREAD

**Issue by postb99** [DotNetAnalyzers/StyleCopAnalyzers#2847]
Hello,
We just installed StyleCop with a .ruleset and a .json configuration files in our project (https://github.com/SOFTINUX/Base), in repository root.

In .csproj, there is a relative path to .ruleset and .json files. Both VS 2017 and dotnet cli (2.2) still output warnings, despite some rules being flagged "None" in .ruleset file.
The .json file works fine.

What did we miss?

Thanks

**Comment by sharwell** [comment]
I left some notes here: https://github.com/SOFTINUX/Base/commit/be71f1ce0fd46836869657d9d5c1e58425e04034

It looks like the cause was a `Condition` attribute that resulted in the rules only getting configured for Release builds.

**Comment by sharwell** [comment]
I also left a note in https://github.com/SOFTINUX/Base/commit/07ff879a18df2efae0a9550df976bb21aa725e78 regarding versioning.
