### ISSUE TITLE
Relative path and platform

### ISSUE THREAD

**Issue by postb99** [DotNetAnalyzers/StyleCopAnalyzers#2848]
Hello,
I have a question about relative path of .ruleset and .json configuration files: it seems it's OS-dependent (backslashes or forward slashes), I tested forward slashes but VS grumps and accepts only back slashes since I'm using Windows. Can you do anything about it? Or is this not managed at your level?

The workaround would be to declare several PropertyGroup/ItemGroup with a condition onto platform.

Just to be sure, because I believe some paths declared in .csproj don't have this platform issue, but I'm unsure.

Thanks

**Comment by sharwell** [comment]
I believe you can use backslashes, even on non-Windows systems. However, if that's not working, it would be a bug in a different repository (most likely Microsoft/msbuild, dotnet/project-system, or dotnet/roslyn).
