### ISSUE TITLE
Proposed exception to SA1312

### ISSUE THREAD

**Issue by lcsondes** [DotNetAnalyzers/StyleCopAnalyzers#2851]
Names such as `_`, `__`, etc. are commonly used to indicate that they're otherwise ignored, which is now "official" syntax in some instances such as `out _`.

There are cases where you want to evaluate an expression for its side effects, but are otherwise uninterested in the results, this would be written as `var _ = expression;`. It's also a relatively common convention to use `(_, __) => blah` for a lambda that's used as an event handler (sender, args) if you don't want to use the `delegate{blah}` syntax for ignoring arguments.

I'd like to propose names that are made up of only underscores to not trigger SA1312.

**Comment by sharwell** [comment]
> There are cases where you want to evaluate an expression for its side effects, but are otherwise uninterested in the results, this would be written as `var _ = expression;`.

The new discard form for these is:

```csharp
_ = expression;
```

The discard syntax does not trigger SA1312, and can be used any number of times within the same method.

> It's also a relatively common convention to use `(_, __) => blah` for a lambda that's used as an event handler (sender, args) if you don't want to use the `delegate{blah}` syntax for ignoring arguments.

This is SA1313, and covered by previous issue #1606.

**Comment by lcsondes** [comment]
I did not know that, suggestion withdrawn.

**Comment by colgreen** [comment]
The exception doesn't seem to be working in this case:

    await foreach (var _ in sut.GetListAsync()) { }

(seen in a unit test that was exhausting an IAsyncEnumerable without using the enumerated items.)

In this case I just changed it to use a normal variable name \<shrugs\> :)
