### ISSUE TITLE
Difference between 1.1.1-beta.61 and 1.1.1.61

### ISSUE THREAD

**Issue by zplan** [DotNetAnalyzers/StyleCopAnalyzers#2857]
What is the difference between 'beta' and 'Unstable' in general, for example these two binaries?

NuGet: StyleCop.Analyzers 1.1.1-beta.61
NuGet (Unstable): StyleCop.Analyzers.Unstable 1.1.1.61

I was not successful to find anything by searching the Issues.
Thanks in advance for clarification.

**Comment by sharwell** [comment]
In general, they are the same content.

1. StyleCop.Analyzers prereleases use SemVer 2 versioning syntax, so older clients need to reference StyleCop.Analyzers.Unstable.
2. StyleCop.Analyzers.Unstable releases show up even when the user doesn't select "Show prereleases". For some users, this avoids restrictions related to the use of prerelease packages.

**Comment by zplan** [comment]
Thanks
