### ISSUE TITLE
[Question] Is it possible to use kind of variable in the stylecop.json file?

### ISSUE THREAD

**Issue by xaviersolau** [DotNetAnalyzers/StyleCopAnalyzers#2878]
In the case where we are using a shared stylecop.json file (with link).

I would like to use some project property to personalized the stylecop settings.
For example I would like to have in my csproj some property like:
```
<PropertyGroup>
   <MyVariable>some text</MyVariable>
</PropertyGroup>
```
and in stylecop.json:
```
"settings": {
    "documentationRules": {
      "companyName": "{MyVariable}"
    }
}
```
resulting in defining the "companyName" to "some text".

**Comment by sharwell** [comment]
No, it is not possible. Build tasks are not allowed to reference properties without declaring them in advance by name, otherwise it would bypass the build system's support for incremental builds. Since analyzers run as a child of the `Csc` task, there is no way to pass a value through.

**Comment by xaviersolau** [comment]
ok, thanks.
