### ISSUE TITLE
Alternative to SA1500 which requires braces on the same line

### ISSUE THREAD

**Issue by lfairy** [DotNetAnalyzers/StyleCopAnalyzers#2883]
SA1500 requires that the opening brace of a compound statement is on a separate line. This is standard C# style and so is a good default.

However, the code style at by company requires the opening brace on the same line, like Java. Is there a StyleCop rule that enforces this, and if not, do we want to add it? I think it would work well as an alternative "SX1500" rule.

**Comment by sharwell** [comment]
I would prefer to not add this rule. The Formatting Analyzer being prepared by the Roslyn team is capable of enforcing this convention, allowing SA1500 to simply be turned off by users.

**Comment by lfairy** [comment]
By Formatting Analyzer do you mean supporting [`.editorconfig` options](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017) outside of Visual Studio?

That sounds pretty cool – where would StyleCop fit in when that's ready, given that many StyleCop rules duplicate what it does?

**Comment by lfairy** [comment]
I'm happy to close this if we're moving toward the `.editorconfig` method.
