### ISSUE TITLE
SA1519 should apply to lock and fixed statements

### ISSUE THREAD

**Issue by jnm2** [DotNetAnalyzers/StyleCopAnalyzers#2885]
Currently, it only applies to `if`, `while`, `do`, `for`, `foreach`, and `using`:

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/836d74a15e4479f69e482de918fc71873a5647ea/StyleCop.Analyzers/StyleCop.Analyzers/LayoutRules/SA1519BracesMustNotBeOmittedFromMultiLineChildStatement.cs#L68-L73

**Comment by sharwell** [comment]
💡 This may require updates to SA1503 to match (not certain).
