### ISSUE TITLE
Allow suppression of all rules for a file

### ISSUE THREAD

**Issue by ses4j** [DotNetAnalyzers/StyleCopAnalyzers#2886]
StyleCop Classic allowed you to do this:

    <Compile Include="Collection\OrderedDictionary.cs">
      <ExcludeFromStyleCop>true</ExcludeFromStyleCop>
    </Compile>

Which we found very useful when we wanted to just drop externally-written code in without having to make it conform to our typical StyleCop rules.  I cannot find a good replacement in StyleCopAnalyzers.  It seems I need to [SuppressMessage] or #pragma each element and each rule in turn, which can be quite a lot of work and requires changing the original file which is not ideal.

Is there/can there be a simpler way to mark a file as "don't bother, StyleCop!"?

**Comment by ses4j** [comment]
It seems like

    // <auto-generated />

sort of would do this, though I don't quite understand how it works and anyway, it's obviously a hack.  

Being able to externally mark the file as do-not-process or being able to flag it with something would be of value.

**Comment by sharwell** [comment]
> sort of would do this, though I don't quite understand how it works and anyway, it's obviously a hack.

This is the standard way to indicate that a file should not have style analysis run on it. It's implemented in an optimized manner within the compiler itself. 😄

**Comment by ses4j** [comment]
@sharwell Should that be documented then as the official prescribed way to mark a file as "do not bother to analyze", or should there be some kind of stylecop-specific mark?

**Comment by sharwell** [comment]
@mavasani is this pattern documented anywhere for Roslyn?

**Comment by mavasani** [comment]
No, it is part of heuristic that determines generated code in the analyzer driver, which is not documented behavior but it will likely not break in future. Note that autogenerated tag will skip execution and/or diagnostic reporting on file only if analyzer has explicitly configured generated code analysis by invoking AnalysisContext.CongigureGeneratedCode API.

**Comment by sharwell** [comment]
> Note that autogenerated tag will skip execution and/or diagnostic reporting on file only if analyzer has explicitly configured generated code analysis by invoking AnalysisContext.CongigureGeneratedCode API.

All analyzers in this repository are configured that way 🛩

**Comment by ses4j** [comment]
It seems to me that a method to control StyleCop specifically rather than incidentally disabling all analyzers might be nice, but we can definitely move forward with this.

Thanks a lot @sharwell @mavasani!

**Comment by sharwell** [comment]
@watsonsong This project does not control code exclusions. You'll want to file a feature request on [dotnet/roslyn](https://github.com/dotnet/roslyn) for that.

**Comment by watsonsong** [comment]
Thanks, I asked in roslyn-analyzers because I think this is a common request not just for stylecop. And I get a link to this issue.
https://github.com/dotnet/roslyn-analyzers/issues/2140
May be I will wait the .editorconfig support for c# compilers.
