### ISSUE TITLE
SA1008 when unpacking a tuple

### ISSUE THREAD

**Issue by Tvde1** [DotNetAnalyzers/StyleCopAnalyzers#2898]
I have this snippet:
```cs
var (variableA, variableB) = MyMethodThatReturnsATuple();
```
SA1008 is telling me I should not have a space before the opening parenthesis. Like this:
```cs
var(variableA, variableB) = MyMethodThatReturnsATuple();
```
I don't think this is correct.

**Comment by Tvde1** [comment]
This also applies to:
```cs
public (MyType, MyOtherType) MyMethodThatReturnsATuple()
```
It wants
```cs
public(MyType, MyOtherType) MyMethodThatReturnsATuple()
```

**Comment by vweijsters** [comment]
This problem only occurs when using C# 7.x in combination with StyleCop.Analyzers v1.0.2. Unfortunately this combination is not supported. C# 7.x support has been added in the 1.1.0-beta releases.

**Comment by ChrisTorng** [comment]
The newest 1.1.118 release doesn't resolve this...

**Comment by sharwell** [comment]
@ChrisTorng can you file a new bug for that?
