### ISSUE TITLE
The false alert about SA1011

### ISSUE THREAD

**Issue by watsonsong** [DotNetAnalyzers/StyleCopAnalyzers#2900]
For the nullable check in c# 8.0, I change by byte[] return type into byte[]?, and the stylecop report error:
`public byte[]? Foo() {}`

`SA1011 Closing square bracket should be followed by a space`

**Comment by iron9light** [comment]
#2927 Same thing?

**Comment by sharwell** [comment]
It seems like there is a good chance this is already fixed, but I'll leave this open for someone to add a new regression test here: https://github.com/vweijsters/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers.Test.CSharp8/SpacingRules/SA1011CSharp8UnitTests.cs
