### ISSUE TITLE
Nuget install fails weirdly with C++ projects

### ISSUE THREAD

**Issue by mikeparker** [DotNetAnalyzers/StyleCopAnalyzers#2907]
I have a solution with both C# and C++ projects in. I want to only use stylecop on C# projects.

When I have a `Directory.build.props` file with:
```
  <ItemGroup>
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.1-rc.108" PrivateAssets="all" />
  </ItemGroup>
```
When running MSBuild from the command line, it appears to cause failures in building C++ projects:
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets(186,5): error : Your project does not ref
erence ".NETFramework,Version=v4.0" framework. Add a reference to ".NETFramework,Version=v4.0" in the "TargetFrameworks" property of your project file and then re-run NuGet restore. [C:\Git\src\github.com\xx\xx\xx.vcxproj]
```
I'm guessing this is because the Directory.Build.props file is attemping to add this package to every project in the solution, not just the C# projects? 

It's odd because this doesnt happen when building from Visual Studio.

I can reproduce a similar error message by manually trying to add the nuget package for a C++ project, which succeeds, but then will not build. Any attempt to uninstall the package then fails here:
```
Attempting to gather dependency information for package 'StyleCop.Analyzers.1.0.2' with respect to project 'xx', targeting 'native,Version=v0.0'
Resolving actions to uninstall package 'StyleCop.Analyzers.1.0.2'
Resolved actions to uninstall package 'StyleCop.Analyzers.1.0.2'
Executing script file 'C:\Git\src\github.com\xxx\packages\StyleCop.Analyzers.1.0.2\tools\uninstall.ps1'...
& : File C:\Git\src\github.com\xxx\packages\StyleCop.Analyzers.1.0.2\tools\uninstall.ps1 cannot be 
loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at 
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:45
+ ... rgs+=$_}; & 'C:\Git\src\github.com\xxx\packages\Sty ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
Removed package 'StyleCop.Analyzers.1.0.2' from 'packages.config'
Successfully uninstalled 'StyleCop.Analyzers.1.0.2' from XXXX
Removing package 'StyleCop.Analyzers.1.0.2' from folder 'C:\Git\src\github.com\xxx\packages'
Removed package 'StyleCop.Analyzers.1.0.2' from folder 'C:\Git\src\github.com\xxx\packages'
Executing nuget actions took 569.67 ms
Time Elapsed: 00:00:00.6310001
========== Finished ==========
```
1. Is there a bug in the uninstall.ps1 here?
2. Should the nuget package detect it's not compatible and refuse to install?
3. Is there some way I should be preventing this package from installing itself to C# projects in the `Directory.build.props` file?

**Comment by sharwell** [comment]
It seems like this would be a NuGet bug. I'm not aware of a way to limit the installation based on package metadata.

> Is there a bug in the uninstall.ps1 here?

Install scripts do not run when using Directory.Build.props. They are only provided for use with the NuGet Package Manager UI in combination with the old style projects.

**Comment by mikeparker** [comment]
So whats the 'normal' (if there is such a thing) method of using stylecop across C++ and C# projects? Just reference the stylecop package manually from every C# project? Or I guess make a props file that all the C# projects reference?

Seems a shame not to be able to automatically include it with every new C# project, if I'm understanding correctly.

**Comment by sharwell** [comment]
We should probably document the answer to that question when we have it, but I'm thinking the way to get the answer is to ask on https://github.com/NuGet/Home/issues.

**Comment by mikeparker** [comment]
I was in the process of raising an issue there but the issue template asks `NuGet product used (NuGet.exe | VS UI | Package Manager Console | dotnet.exe):` and I'm thinking hmm, we're using the MSBuild command line, and thats not in the list. Should I still raise it there or is it part of MSBuild?

**Comment by sharwell** [comment]
You can just say MSBuild there.

**Comment by mikeparker** [comment]
Raised here https://github.com/NuGet/Home/issues/7831

Thanks for your help and quick response!
Feel free to close if you wish.
