### ISSUE TITLE
SA1627: MessageFormat contains \'

### ISSUE THREAD

**Issue by RalfKoban** [DotNetAnalyzers/StyleCopAnalyzers#2918]
The rule 'SA1627' reports a violation if an XML element is empty.

The documentation resource `SA1627MessageFormat` for the rule wraps the XML element inside `\'`.
So a violation would be reported as `The documentation text within the \'remarks\' tag should not be empty.`

It would be better if the documentation resource text would use `'` instead of `\'`, so that the violation would be reported as  `The documentation text within the 'remarks' tag should not be empty.`

**Comment by sharwell** [comment]
Fixed by #2919
