### ISSUE TITLE
.NET Analyzer fails with IDE1003 due to missing netstandard 2.0

### ISSUE THREAD

**Issue by michsco** [DotNetAnalyzers/StyleCopAnalyzers#2921]
I created a Roslyn analyzer which targeted the .NET Standard 2.0 framework. When I reference it from one of my .NET Core assemblies as an analyzer, it fails with an Analyzer assembly warning `IDE1003`. The message is '{DLL Path}.dll' depends on 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' but it was not found. Analyzers may not run correctly unless the missing assembly is added as an analyzer reference as well.

When I downgraded to a lower version of .NET Standard for the same analyzer without any other configuration changes, this error goes away. Based on this [StackOverflow post](https://stackoverflow.com/questions/50047063/roslyn-analyzer-missing-assembly-warning), it seems like there is a whitelisted assembly missing somewhere.

Since we run with warnings as error, this is causing multiple false positives.

**Comment by sharwell** [comment]
@michsco Can you file this bug on [dotnet/roslyn](https://github.com/dotnet/roslyn) instead?
