### ISSUE TITLE
warning SA1206: The 'public' modifier must appear before 'virtual'.  Could you please make StyleCop agree with Rosylin?

### ISSUE THREAD

**Issue by GammaFour** [DotNetAnalyzers/StyleCopAnalyzers#2922]
I'm getting a warning SA1206: The 'public' modifier must appear before 'virtual' on Roslyn generated code:

```
        /// <summary>
        /// Gets or sets the <see cref="AccountCanonMap"/> set.
        /// </summary>
        virtual public DbSet<AccountCanonMap> AccountCanonMaps { get; set; }

```
I have no idea how I change the order on generated code as it's just a bit field.
I'll leave the same notice on the Rosylin site as well.

**Comment by sharwell** [comment]
This is the expected behavior for StyleCop Analyzers, so I'm going to mark this **external** and watch for the Roslyn issue.
