### ISSUE TITLE
Support for nontraditional casing in namespaces (SA1300)

### ISSUE THREAD

**Issue by jedidja** [DotNetAnalyzers/StyleCopAnalyzers#2923]
Applying StyleCop analyzers to an existing codebase is always difficult, but what happens when the company name begins with a small letter, e.g. eBay? How can you apply SA1300 to everything _except_ the `namespace`s? Imagine tens of thousands of files with several hundred namespaces like:

```
eBay.Services.Shipping
eBay.Services.Shipping.Entities
eBay.Services.Auction
eBay.Services.Auction.Bidding
```

Although normally namespace names are `PascalCase`, Microsoft admits in their [naming guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces) that 

> If your brand employs nontraditional casing, you should follow the casing defined by your brand, even if it deviates from normal namespace casing.

If someone were to do the work and create a PR, would it be acceptable to either:

a) include a "known terms dictionary" that SA1300 could use to ignore certain words?
b) make a *very* specific exception for namespaces since company names do not always follow `PascalCase`?

Or, if neither of those would be accepted, is there any way to accomodate this situation?

**Comment by vweijsters** [comment]
The preferable option for me would be a combination of both listed options: Add a configuration option to ignore certain words for namespaces only. The ignored words will then have to be matched in the exact case that they are specified in, to guard the consistency as much as possible.

**Comment by jedidja** [comment]
@vweijsters Thanks for the response; your idea makes sense to me as I think it still keeps the underlying spirit of the StyleCop guideline alive while allowing for real-world issues. 

I took a look at the [contributing guidelines](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/CONTRIBUTING.md) but I'm still unsure if it's worth spending any time on creating a PR for this yet, or if I should wait for feedback from @sharwell or someone else first? It seems like perhaps I would at least wait for a specific label to be applied and then go from there? (Maybe I'm not even the right person to create the PR heh)

**Comment by sharwell** [comment]
@jedida can you add a proposal for the exact change to stylecop.json for this?

**Comment by jedidja** [comment]
Sure; here's a first stab at it :)

**Property**: `allowedNamespaceComponentTerms`

**Default Value**: `[]`

**Summary**: Specifies non-PascalCase terms that would not normally qualify for a `namespace` component (e.g. company or brand names) but should be allowed. The term only matches a specific component, not a subset. For example, `eBay` would match `eBay.Services.Auction` but *not* `eBayServices.Auction`.

```
{
  "settings": {
    "namingRules": {
      "allowedNamespaceComponentTerms": [
        "eBay",
        "iPod",
      ]
    }
  }
}
```

**Comment by mzhukovs** [comment]
Totally agree - get this issue with Xamarin projects out the box thanks to iOS and a way to specify exceptions would be ideal.

**Comment by mzhukovs** [comment]
Thoughts on not limiting to just namespaces for the exceptions?

**Comment by jedidja** [comment]
Oh, oops .. forgot to ping @sharwell :) I can't seem to add a "code review" tag to the PR, nor add the appropriate label to this issue.

**Comment by cytron201** [comment]
@jedidja @sharwell  This is exactly what i've been looking for. Our company has a branding choice which results in a lowercase first letter for an element in the namespaces. A way to allow exclusions in the Stylecop.json is spot on.

Any way of raising this to get it reviewed?

**Comment by mlessmann** [comment]
This feature is the only thing blocking our company from adopting StyleCop.Analysers. We followed Microsofts guideline and used our branding in our namespaces. The proposed whitelist mechanism would work well for us.

**Comment by jedidja** [comment]
@sharwell Even if Roslyn 3+ does support post-processing, perhaps this addition is still worthwhile for people working in older environments?

I'm happy to update the PR if anything else is required, but I'm not sure if it'll get approved still :)

**Comment by sharwell** [comment]
@jedidja I'm planning to merge/release #2996 once a few details are cleared up:

1. Do we want to configure _namespaces_ or _namespace components_?
2. The descriptors 'component' and 'term' are redundant. We should stick to one, and I'm leaning towards 'component'.

**Comment by jedidja** [comment]
@sharwell Thank you for looking at the PR and the comments; will push an update in the next ten minutes or so.

1. I was hoping to configure _namespace components_
2. Totally agree with `component`

**Comment by sharwell** [comment]
@jedidja this is now released to NuGet

**Comment by jedidja** [comment]
@mzhukovs @mlessmann @cytron201 Hope this works out for you :) Thanks @sharwell for merging this!
