### ISSUE TITLE
Disabling stylecop referenced via dependency

### ISSUE THREAD

**Issue by sakopov** [DotNetAnalyzers/StyleCopAnalyzers#2925]
I have project A and project B, which references it. Project A uses StyleCop code analyzer. Project B does not. When project A is built StyleCop rules are executed and I get build warnings. How do I stop StyleCop from executing in the host project?

**Comment by sharwell** [comment]
You need to set `PrivateAssets="all"` on the `PackageReference`, like this:
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/921316e0b24b3777ba3d538ab26e0b8d2a4c0bbe/StyleCop.Analyzers/Directory.Build.props#L47

**Comment by sakopov** [comment]
Slightly different syntax, but I'm already doing this.

```
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.0-beta009">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
```

Still no dice as StyleCop analyzers flow to whatever project is consuming it.

**Comment by sakopov** [comment]
Closing, since it's unrelated to StyleCop, but is a known issue in Nuget [1].

[1] https://github.com/dotnet/sdk/issues/968#issuecomment-410319090
