### ISSUE TITLE
InvalidCastException in PropertyChangedEventArgsUnnecessaryAllocationAnalyzer

### ISSUE THREAD

**Issue by kindermannhubert** [DotNetAnalyzers/StyleCopAnalyzers#2929]
While using 921316e0b24b3777ba3d538ab26e0b8d2a4c0bbe build of StyleCop I'm seeing following exception when I build our solution in VS 2019 (16.0.0):

warning AD0001: Analyzer 'CodeCracker.CSharp.Refactoring.PropertyChangedEventArgsUnnecessaryAllocationAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.GenericNameSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.IdentifierNameSyntax'.'.

**Comment by kindermannhubert** [comment]
Really sorry - bad repo :)

**Comment by sharwell** [comment]
No problem!
