### ISSUE TITLE
SA1412 - SA1412StoreFilesAsUtf8 -- Time to disable this rule?

### ISSUE THREAD

**Issue by henrygab** [DotNetAnalyzers/StyleCopAnalyzers#2937]
(note: this issue differs from #2100, which wants to create a new rule to **_remove_** the BOM from UTF-8...)

The current ruleset shows that Rule SA1412 is set to warning:
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/0aa107e56acf7054bb53b77d44240eeba1fe43b0/StyleCop.Analyzers/StyleCop.Analyzers.ruleset#L81

However, the world has changed over the last few years, suggesting this rule may not be the best choice anymore.  For example:
1. Windows 10 notepad.exe defaults to saving UTF-8 files without BOM
2. Few Linux editors default to saving UTF-8 text files with a BOM
3. Visual Studio 2017 (and later?) default to UTF-8 without BOM, even with Unicode characters added to the file

Moreover, if a project creates files that are consumed by (for example) JAVA projects, inserting a BOM can cause regressions in those JAVA projects (JAVA passes the BOM as a character in some cases).  Causing really difficult cross-project regressions is the **_antithesis_** of StyleCop rules.

Therefore, it seems this rule should, at a minimum, no longer be enabled by default.

I'd be happy to generate a PR for this issue, if it's agreed worth fixing.

**Comment by sharwell** [comment]
I believe the original items that led to this rule remain relevant today, even if to a lesser extent. I need to look into this detail next week:

> Visual Studio 2017 (and later?) default to UTF-8 without BOM, even with Unicode characters added to the file

**Comment by henrygab** [comment]
I may have been mistaken in thinking that it was enabled by default.  The line I pointed to was used only for building StyleCop itself.  When I check on a new project, it appears to have been disabled, suggesting that the rule is, in fact, disabled by default.

Thank you for the response, and being willing to review.  If you confirm the above, this issue should be closed.

**Comment by sharwell** [comment]
@henrygab The analyzer is disabled due to a bug in Roslyn which makes the code fix difficult/unpleasant to use. It's not good to have rules enabled that cause developers trouble to fix. 😄

**Comment by sharwell** [comment]
> Visual Studio 2017 (and later?) default to UTF-8 without BOM, even with Unicode characters added to the file

I just verified that this is not the case for C# source files. The default templates for source files and projects use UTF-8 with BOM.
