### ISSUE TITLE
StyleCop.Analyzers.CodeFixes too cumbersome to build.  Make it a production ready package avialable on Nuget?

### ISSUE THREAD

**Issue by TannerBragg** [DotNetAnalyzers/StyleCopAnalyzers#2942]
The StyleCop.Analyzers.CodeFixes project should not be something that is build by individual development teams to enforce code styling.  I spent several hours wrestling with the package references since I do not have access to MyGet feeds.  I only have access to official Nuget.org feeds.  If you want to reproduce this issue, simply remove the Nuget.config file at the root.

I feel this package should be released as a default implementation which will use the ruleset and stylecop.json files in the same manner the StyleCop.Analyzers package does.  In fact, if we just make the CodeFixes project dependent on the official release on nuget, then including only the CodeFixes should be sufficient enough to have compiler warning and code fixes in the IDE.

This code fixes package is desperately needed as there are not any effective code cleanup tools out there that actually satisfy all the new rules.  Resharper just doesn't cut it anymore, and this could be a huge plus for the StyleCopAnalyzers package.

**Comment by Smenus** [comment]
The CodeFixes *are* included in the existing NuGet, have you checked the latest RC release on NuGet.org?

**Comment by TannerBragg** [comment]
I'll double check on this.  Perhaps my Resharper is fighting me.  I'm trying to get away from it more an more since Roslyn can do most of the code analysis stuff now.

Some documentation on how to use the code fixes and possible configurations would be a great addition on the main ReadMe, though.

**Comment by TannerBragg** [comment]
@Smenus You are correct.  My mistake.  CodeFixes are included in the package.  _#feelingdumb_

**Comment by Smenus** [comment]
@TannerBragg phew, I was just hoping that nothing else would delay the release - I'm tired of my Tuples having squigglies under them!
