### ISSUE TITLE
SA1600 in 1.1.118 works in Intellisense but not "msbuild"

### ISSUE THREAD

**Issue by ntcthorne** [DotNetAnalyzers/StyleCopAnalyzers#2948]
I believe I've read all the issues related to SA1600. I was able to recreate most (and worse) behavior reported using SCAnalyzers v1.0.x. After upgrading to 1.1.118, I am now getting proper SA1600 reporting, but only via Intellisense. In the Error List, when I select "Build" messages only, after a Rebuild all and/or Run Code Analysis on Solution, I get 0 warnings, but when I select "Intellisense" only, I get the 8 Warnings I expect based on my configuration and code.

<img width="2243" alt="SA1600-Problem" src="https://user-images.githubusercontent.com/21090613/57015407-56835180-6bda-11e9-93c0-de02de2bb431.png">

I also get 0 Warnings using MSBuild  on the same solution (or project) from the command line.

**Comment by ntcthorne** [comment]
I did enable SA1401 as a control test. My public fields did generate 7 SA1401 warnings as desired in both Intellisense and in "Build Only" Error List.

A side note that is probably unrelated to StyleCopAnalyzer: Running MSBuild on the command line produced 14 warnings, there was a ..._knq1xjin_wpftmp.csproj file that got analyzed for some reason, I'm still trying to figure that one out....

**Comment by ntcthorne** [comment]
Enabling/Disabling SA1652 seems to have no effect on this behavior. I read the discussion about whether or not SA1652 should indeed turn off all documentation comment diagnostics if disabled....it appears it does *not* do that in v1.1.118, does the Description need to be changed?

**Comment by sharwell** [comment]
@ntcthorne SA1652 was renamed to [SA0001](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA0001.md). You should make sure this rule is enabled and that this rule is not getting reported, otherwise most documentation rules will not work.

**Comment by ntcthorne** [comment]
Thanks for the quick response. I must have gotten confused when working with v1.0.x. I have enabled SA0001 in my v1.1.118 test. I am now seeing SA0001 warning in both Intellisense and Build messaging (as well as my SA1401 control message), but the 7 desired SA1600 messages are only showing up via Intellisense. MSBuild (v15.9.21.664) command line is also showing me both SA0001 and SA1401, but none of SA1600, consistent with the Build Only messaging in Visual Studio (Enterprise 2017).

**Comment by sharwell** [comment]
@ntcthorne If you receive SA0001, all analyzers related to documentation are broken. All of the following are allowed in this case:

1. Reporting no warnings
2. Reporting correct warnings
3. Reporting incorrect warnings on documentation comments
4. Reporting incorrect warnings anywhere else

**Comment by ntcthorne** [comment]
I have added
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>

to my csproj file, verfied that the output file was produced. The SA0001 is still enabled but no longer reporting the warning.

I am now seeing all expected SA1600 (as well as the SA1401) messages in both Intellisense and "msbuild". Thank you for your help.

Now, I just need to figure out why MSBuild command line thinks that temporary csproj file is actually a real proj file as far as error/warning count/reporting goes, but that's not for this forum!

Thanks again!

**Comment by Birgos** [comment]
The "solution" described here is not optimal from our view.

We have some projects that do not want to create a documentation XML file and therefore **disable rule SA0001**.

Nevertheless, e.g. these projects provides interface classes or public methods with documentation headers. As a result, violations of SA16 rules are displayed as errors or warnings in the errorlist window in Visual Studio, but **compilation** of the project does **not fail**.
**Normally, a project can not be compiled if StyleCop rules are violated.**
So, if many files violate SA16 rules and only a few other SA rules, then compilation fails and the "blocking" rule must be picked out of the non-"crucial" SA16 rules. Once this rule is found and fixed, the project can **recompile**, **even though** Visual Studio **continues to display errors** for SA16 rules in the errorlist.

In addition, the SA16 rule violations can only be seen in the errorlist window if:
* The corresponding file is open in Visual Studio
* in the Visual Studio settings the hook was set at:
_Tools - Options - TextEditor - C# - Advanced - Enable full solution analysis_

In addition to the alternative of setting the DocumentationFile property, we could also go ahead and set **all SA16 rules to None**.
However, if **new** SA16 rules are added, which **default values** throws a **warning or an error**, the **problem starts again**. And the developer concerned, would have to find this issue, to get an explanation for the strange behavior, that i described above...

Please see the attached images, that hopefully better explains the described situation.
![expectedbehavior](https://user-images.githubusercontent.com/8317890/59499352-88edc300-8e97-11e9-9b93-ae59245b7d23.png)
![weirdbehavior](https://user-images.githubusercontent.com/8317890/59499379-96a34880-8e97-11e9-8692-4f5ffc3c31ba.png)

**Comment by sharwell** [comment]
@Birgos this project has essentially no control over those scenarios (bugs can be filed at [dotnet/roslyn](https://github.com/dotnet/roslyn)). We could avoid adding new rules, but that would impair discoverability. We rely on users only updating the version of the StyleCop Analyzers NuGet package when they are ready to verify that the new package does not produce any new warnings, and if it does, they are dealt with at the time of the package upgrade.
