### ISSUE TITLE
SA1600 on a field in a partial class is not being reported.

### ISSUE THREAD

**Issue by ntcthorne** [DotNetAnalyzers/StyleCopAnalyzers#2949]
I worked through my issues with properly enabling SA0001 in order to get messages related to documentation. On a 'normal' cs file, all is working as expected. However, in my MainWindow.xaml.cs which is a partial class definition, I removed the summary documentation header from the class, a field and a method. I got SA1600 for the method, SA1601 (Partial elements should be documented) for the class, but no warning for the field.

![image](https://user-images.githubusercontent.com/21090613/57026674-f6070b00-6bff-11e9-9e34-bd4d2eccf8aa.png)

**Comment by ntcthorne** [comment]
If I change the field to public, and still lower-case first letter, I will then get SA1307, SA1401 *AND* SA1600.
If I change the field name to begin with a capital letter to avoid the SA1307, I get SA1401 *AND* SA1600.
If I change it to private and capital letter I get *ONLY* SA1306 (the SA1600 goes away!)

**Comment by sharwell** [comment]
This behavior is [configurable](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md#documentation-requirements) by the `documentPrivateFields` property, which has a default value of `false`.

**Comment by ntcthorne** [comment]
Thank you again. I have manually added a stylecop.json file to the project and changed it's Build Action from None to AdditionalFiles and started to configure it as per the link you gave me above. Back in business again.
