### ISSUE TITLE
SA1629 false positive when using '<para>' tag

### ISSUE THREAD

**Issue by JojoShow** [DotNetAnalyzers/StyleCopAnalyzers#2951]
When using several lines with the 'para' tag in an exception to separate the cases.
The rules fires a warning even if each line ends with a '.'

![SA1629 false positive](https://user-images.githubusercontent.com/5689833/57092232-330bf400-6d0b-11e9-8e9b-9a10fe482d9f.png)

**Comment by sharwell** [comment]
Duplicate of #2712

**Comment by JojoShow** [comment]
@sharwell : Sorry for having posted a duplicate, but.... the #2712 is supposed to be fixed since june 2018 (1.0.0 Beta8) and I still have the problem using the 1.1.118.
Do you have any explanation ?

**Comment by sharwell** [comment]
@JojoShow No problem. Can you create a small source file that reproduces this issue and include the text as a comment here so we can reproduce it?

**Comment by JojoShow** [comment]
@sharwell : Could not reproduce this with a small project, could not reproduce with other of my .Net standard 2 project, only with this one. But this one has also strange behaviors with other analyzers....
I suspect something wrong in the project. I've done a new project from scratch, and it seems that the issue does not occur when I include the original source files.
I must have missed something, and it's probably an error while configuring the project.
Issue is closed. 
Sorry
