### ISSUE TITLE
Proposal: Have stylecop.json fully control StyleCop settings

### ISSUE THREAD

**Issue by SetTrend** [DotNetAnalyzers/StyleCopAnalyzers#2953]
Currently, only a fraction of StyleCop warnings/errors can be configured using `stylecop.json`. This is very frustrating when trying to create settings for the team.

Can we get `stylecop.json` to _fully_ cover each and every StyleCop rule?
<br/>

Let me suggest an implementation detail that'd make fully covering StyleCop through `stylecop.json` easy: I don't believe we need dedicated texts in `stylecop.json` that differ from StyleCop warning/error numbers. They are syntactic sugar, but essentially it'd be sufficient to provide a JSON schema like this:

```
"StyleCopErrorNumber": "ignore|warning|error"
```

Providing named aliases for StyleCop error numbers would be alright, though:
```json
{ "SA1101" : "ignore" }

// equivalent to:

{ "PrefixLocalCallsWithThis" : "ignore" }
```

This way you avoid any manual implementation for parsing the `stylecop.json` file. Instead, parsing the `stylecop.json` file would be a snap. Plus, using the `stylecop.json` as single source of truth would become comprehensive.

**Comment by sharwell** [comment]
Users will soon have the ability to control this via **.editorconfig** files (a compiler feature which will ship in an upcoming release).

**Comment by HolisticDeveloper** [comment]
I'm just looking in to **.editorconfig** vs **stylecop.json** vs **.ruleset** files... Is this compiler feature now available? If so, any links that describe it?

**Comment by sharwell** [comment]
@mavasani Do you have a link to the new documentation for using **.editorconfig** to control analyzer warnings?

**Comment by mavasani** [comment]
> Do you have a link to the new documentation for using .editorconfig to control analyzer warnings?

Tagging @gewarren. I think Genevieve has the documentation in review but not yet published.

**Comment by gewarren** [comment]
> > Do you have a link to the new documentation for using .editorconfig to control analyzer warnings?
> 
> Tagging @gewarren. I think Genevieve has the documentation in review but not yet published.

Yes, that's correct. The documentation will be published on Monday on this page: https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019
