### ISSUE TITLE
SA1135 misfires on `using VSCOOKIE = System.UInt32`

### ISSUE THREAD

**Issue by AArnott** [DotNetAnalyzers/StyleCopAnalyzers#2956]
Given this:

```cs
    using VSCOOKIE = System.UInt32;
```

SA1135 reports:

```
Severity	Code	Description	Project	File	Line	Source	Suppression State	Tool
Error	SA1135	Using directive for type 'uint' should be qualified		D:\VS\src\env\shell\Connected\Impl\OnlineLicensing\OnlineLicensingManager.cs	41	IntelliSense	Active	StyleCop.Analyzers
```

However, the code fix that it offers throws an unhandled exception, causing Roslyn to terminate it. And C# won't accept this:

```cs
    using VSCOOKIE = uint;
```

So this is a false positive to begin with.

**Comment by bjornhellander** [comment]
Can't seem to reproduce this with the latest release. Can you confirm that this has been fixed, @AArnott? Seems like #3157 took care of it.

**Comment by bjornhellander** [comment]
I did however note that using such a type alias in code triggers SA1121. Filed separate issue #3424, to see if that really is wanted behavior.

**Comment by AArnott** [comment]
Agreed. It doesn't repro with 1.2.0-beta.354.
