### ISSUE TITLE
SA1629 code fix sometimes inserts periods just before last character

### ISSUE THREAD

**Issue by AArnott** [DotNetAnalyzers/StyleCopAnalyzers#2957]
SA1629 will flag docs such as these as needing to end with a period:

```cs
        /// <typeparam name="S">The service interface to retrieve</typeparam>
        /// <param name="provider">The IServiceProvider implementation</param>
        /// <returns>A reference to the service</returns>
```

The (bulk) code fix provider produced this:

```cs
        /// <typeparam name="S">The service interface to retriev.e</typeparam>
        /// <param name="provider">The IServiceProvider implementation.</param>
        /// <returns>A reference to the servic.e</returns>
```

Note this doesn't always repro. When I undo just a few lines to their period-less state and reapply the code fix, the period goes to the right place. It only happens when there are a massive number (possibly hundreds) of fixes applied in bulk.

**Comment by AArnott** [comment]
It can happen when the closing tag isn't on the same line as well:

```cs
        /// <summary>
        /// Returns the current VS font from the provide.r
        /// </summary>
```

**Comment by AArnott** [comment]
Hmm... in this one it showed up *two* characters too soon:

```cs
        /// <summary>
        /// Gets a value indicating whether the "Save and Generate CMake Cache" feature is user availab.le
        /// </summary>
```

**Comment by AArnott** [comment]
Wow. In one particularly *short* file (only 84 lines long), it put the period *way* too far to the left:

```cs
        /// <summary>
        /// Listens for global ev.ents from Visual Studio including font change events
        /// </summary>
```

It had screwed up at [one point above](https://dev.azure.com/devdiv/DevDiv/_git/VS?path=%2Fsrc%2Fvc%2Fprojbld%2FCMake%2FPackage%2FVsFontChangeWatcher.cs&version=GC797e1f8ab78fbfb2174d041db1a838d5fd9f92ce&line=18&lineStyle=plain&lineEnd=20&lineStartColumn=1&lineEndColumn=1) as well, which had particularly unusual comments. I wonder if that can give an idea of what kind of xml parsing might be incrementally throwing off the code fixer.

**Comment by vweijsters** [comment]
Thanks for the report. This looks like an interesting one to find and fix 😉

**Comment by AArnott** [comment]
It's not always before the last letter either. It can be before the last xml tag too:

![image](https://user-images.githubusercontent.com/3548/87251073-4a259600-c426-11ea-9148-259fabf5aa91.png)

**Comment by AArnott** [comment]
In fact it can be in the middle of a paragraph!

![image](https://user-images.githubusercontent.com/3548/87251155-c9b36500-c426-11ea-9d05-075ab8a46d1a.png)

**Comment by sharwell** [comment]
@AArnott In the last image (https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2957#issuecomment-657241850), the code fix is correct. The `<code>` element designates a new paragraph. The equivalent inline element is `<c>`.

**Comment by bjornhellander** [comment]
I tried reproducing this in a large test case, using Visual Studios "Run until failure", both in a Debug and Release build. No luck so far.

@AArnott You say that this only happen when batch fixing. Have you seen it happen when fixing all in one document, or only when fixing all in a project or the entire solution?

And since it is a couple of years old: It is still happening?

**Comment by AArnott** [comment]
I haven't noticed the behavior lately, but I only rarely have occasion to run the bulk fixer for this rule.

**Comment by bjornhellander** [comment]
@AArnott Ok. Do you remember anything about which scope you have selected when you have had this behavior before?

**Comment by AArnott** [comment]
Most likely Solution. And probably in a repo with hundreds of violations.

**Comment by bjornhellander** [comment]
Alright. Thanks for the input!

**Comment by sharwell** [comment]
@bjornhellander I'm guessing this one is due in some way to the use of `CustomFixAllProviders.BatchFixer`. Adding a custom fix all provider would likely resolve the issue.

**Comment by bjornhellander** [comment]
Yes, I suspect the batch fixer too, although I can't see why it would behave like this. I have noticed that Roslyn's built-in batch fixer has undergone some pretty big changes since you copied and improved it. How would you feel about trying out that one again for later Roslyn versions, to avoid a custom fixer?

**Comment by sharwell** [comment]
> How would you feel about trying out that one again for later Roslyn versions, to avoid a custom fixer?

The custom fixer is always tremendously better for performance. We only include a batch fixer for cases where we haven't implemented a proper fixer yet.
