### ISSUE TITLE
Codefix SA1642: single summary line split into 2 lines

### ISSUE THREAD

**Issue by gps7** [DotNetAnalyzers/StyleCopAnalyzers#2963]
Hi,
I face with code fix a minor problem when single line summary is corrected. For example class declaration:

`		/// <summary>Initializes a new instance of the DatePickerTheme class.</summary>`
`		public DatePickerTheme()`

Using CodeFix the first Summart opening tag becomes on own line and rest stays on second line instead keeping as original in same line:
`		/// <summary>`
`		/// Initializes a new instance of the <see cref="DatePickerTheme"/> class.</summary>`
`		public DatePickerTheme()`

Additional question: why new StyleCop does not accept the first sample as valid since this was accepted in StyleCop Classic?

**Comment by sharwell** [comment]
> why new StyleCop does not accept the first sample as valid since this was accepted in StyleCop Classic?

The linked reference is the preferable form, and the code fix provided by StyleCop Analyzers makes it easy to update old code to the preferred form. This change in behavior is listed under the [Known Changes for SA1642](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/KnownChanges.md#sa1642).

**Comment by sharwell** [comment]
Marking up-for-grabs for fixing the new line insertion. The new line should not be added when the only part changing is the reference.

**Comment by tokarzkj** [comment]
I would be interested in looking at this if no one has already.
