### ISSUE TITLE
SA1009 when expression-bodied member ends in exclamation

### ISSUE THREAD

**Issue by heaths** [DotNetAnalyzers/StyleCopAnalyzers#2968]
Using package version 1.1.118, we get SA1009 when we end an expression-bodied member with an exclamation to signify that we will not return null. Example:

```csharp
// Yields warning SA1009
public IService Service => container.GetService<IService>(throwIfNotDefined: true)!
```

In this case, `GetService<T>(bool throwIfNotDefined = false)` can return null, but if `throwIfNotDefined` is `true`, we will throw an exception. So the property above will never return null.

If we add a space before the `!`, no warning is emitted:

```csharp
public IService Service => container.GetService<IService>(throwIfNotDefined: true) !
```

**Comment by martincostello** [comment]
A similar example is where you're trying to return the result of a method call directly in a method where the type is nullable but you know otherwise it won't be:

```csharp
// Fires SA1009
public object Foo()
{
    return MyMethodThatMayReturnNull()!;
}

// Does not fire SA1009
public object Bar()
{
    var result = MyMethodThatMayReturnNull();
    return result!;
}
```
