### ISSUE TITLE
SA1602 triggers when an undocumented internal enumeration item is encountered even if `documentInternalElements` = false

### ISSUE THREAD

**Issue by peteroupc** [DotNetAnalyzers/StyleCopAnalyzers#2973]
Similar issues were already filed for other checks (#2443, #2444, #2445 closed, #2934 still open), but the problem in those issues also applies to SA1602 (enumeration items).  Here, "internal" means either directly or indirectly internal.

**Comment by RobSiklos** [comment]
@peteroupc I can't reproduce this with 1.2.0-beta.113. Are you still encountering this issue?

**Comment by peteroupc** [comment]
Not in that version.  Closing.
