### ISSUE TITLE
Stylecop for Jenkins

### ISSUE THREAD

**Issue by davesliu** [DotNetAnalyzers/StyleCopAnalyzers#2982]
Hi, 

Thanks for providing such a powerful tool.
Is it possible to integrate StyleCopAnalyzers to Jenkins?

**Comment by sharwell** [comment]
StyleCop Analyzers is installed in individual projects and runs with the compiler. It should not be impacted by the CI used to build the code. After installing it, it should work automatically on Jenkins as well.

**Comment by davesliu** [comment]
@sharwell 
Thanks for your comments. 
Is there a  xml format test report available for StyleCop Analyzer?

**Comment by sharwell** [comment]
No, the warnings produced by StyleCop Analyzers show up the same way as other warnings produced by the C# compiler.
