### ISSUE TITLE
What's the default action for every rules?

### ISSUE THREAD

**Issue by iron9light** [DotNetAnalyzers/StyleCopAnalyzers#2983]
It seems not all rules have action (action=none) by default.
Where can I get this kinda info?

**Comment by sharwell** [comment]
We should probably add this to the status page: https://dotnetanalyzers.github.io/StyleCopAnalyzers/

**Comment by iron9light** [comment]
Thx for replying.
So what does `EnabledByDefault` mean? Warning?

**Comment by sharwell** [comment]
Yes, all StyleCop Analyzers rules have default severity Warning. The only variation is whether or not they are enabled by default.

**Comment by vweijsters** [comment]
The [StyleCopAnalyzersDefault.ruleset](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/rulesets/StyleCopAnalyzersDefault.ruleset) included with the NuGet package also shows what the default actions are.
