### ISSUE TITLE
SA1009 can trigger when a closing parenthesis ends XML comment's cref attribute

### ISSUE THREAD

**Issue by peteroupc** [DotNetAnalyzers/StyleCopAnalyzers#2985]
SA1009 can trigger (and output the message "Closing parenthesis should be followed by a space") when a closing parenthesis ends a cref attribute in XML documentation, as in the following example:

    /// <summary>This is a test.  
    /// <see cref='MyClass.MyMethod(System.String)'/></summary>

In general, SA1009 should not apply to closing parentheses in comments at all.

**Comment by sharwell** [comment]
This started occurring with #1840. The bug occurs for the specific case of _single_ quoted XML attributes.

**Comment by sharwell** [comment]
📝 The analysis of parentheses in `cref` attributes is intentional, as mentioned in https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/1834#issuecomment-159946743.
