### ISSUE TITLE
SA1316 and others missing in 1.1.118?

### ISSUE THREAD

**Issue by bddckr** [DotNetAnalyzers/StyleCopAnalyzers#2993]
There are some rules added in #2846 which I'd like to use, but it doesn't seem like they are part of the latest NuGet package 1.1.118.

Since there's even documentation for some of them found in the master branch and the latest NuGet package is dated after the linked PR was merged I'm a bit confused 😄

Are these rules missing or are they not to be used (yet)?

**Comment by sharwell** [comment]
They will be included in the first 1.2 preview release, which should be coming soon. This is also the branch where we'll start to implement the necessary changes to account for C# 8.

**Comment by bddckr** [comment]
Awesome! Thanks for the explanation.

I'll close this issue as I don't feel it's a valid "ongoing" concern and it's easy enough to find closed issues in case someone wonders the same.
