### ISSUE TITLE
ViewBag analyzer 

### ISSUE THREAD

**Issue by kidchenko** [DotNetAnalyzers/StyleCopAnalyzers#2994]
I would like to suggest a new analyzer. `An analyzer to point out the usage of ViewBag and replace it with an model`

Before:

MyController.cs
````csharp

ViewBag.Message = "Hello World";

````

After:

MyModel.cs
````csharp

public string Message { get; set; }
````

MyController.cs
````csharp


model.Message = "Hello World;"
````

Why I think this is useful? 
ViewBag is a dynamic property and you will only catch errors at runtime making your code error prone.

**Comment by kidchenko** [comment]
I have been looking in another repositories, never saw a similar one :c If you know please let me know

**Comment by JohanLarsson** [comment]
If this is for AspNetCore there is [the official analyzer](https://github.com/aspnet/AspNetCore/tree/master/src/Analyzers)

There is also [AspNetCoreAnalyzers](https://github.com/DotNetAnalyzers/AspNetCoreAnalyzers).

**Comment by sharwell** [comment]
@kidchenko Did that answer your question?

**Comment by kidchenko** [comment]
I still using ASP .NET MVC (not core yet)! I do not think that a `ViewBag` analyzer is a good match for the oficial analyzers repo. But I completely agree with the `AspNetCoreAnalyzers`, for me sounds a better fit.

**Comment by JohanLarsson** [comment]
Note that you can roll your own analyzer easily. It is fun.

**Comment by kidchenko** [comment]
I have build already some analyzers, if I build this one do you guys consider in accept a PR?

**Comment by sharwell** [comment]
@kidchenko It probably wouldn't make sense for StyleCop Analyzers, but would make sense for one of the other projects linked above. If you are interested in contributing, I would suggest opening an issue on those to check if the project would use it. 👍
