### ISSUE TITLE
stylecop.json being ignored

### ISSUE THREAD

**Issue by lloydjatkinson** [DotNetAnalyzers/StyleCopAnalyzers#2999]
![image](https://user-images.githubusercontent.com/5633938/64080947-f02a4f00-ccf1-11e9-8d9f-746ef375b7c0.png)

I have a brand new solution and set of projects. Targetting .NET Core 2.2.

I installed the analyzer however stylecop.json is being ignored.

**Comment by sharwell** [comment]
Did you already follow the steps listed under "ACTION REQUIRED" in the comment? If so, can you also show the content of your project file?

**Comment by sharwell** [comment]
@lloydjatkinson If this is still a problem please let me know and I will reopen it.
