### ISSUE TITLE
SA1601: PartialElementsMustBeDocumented reported on non public type

### ISSUE THREAD

**Issue by thomaslevesque** [DotNetAnalyzers/StyleCopAnalyzers#3009]
I had an internal class, undocumented. It didn't produce any warning, since it was internal. But when I made it partial, I started getting SA1601: PartialElementsMustBeDocumented.

That doesn't make sense. If it was OK for the class not to be documented when it was not partial, why should making it partial imply that I have to document it?

**Comment by thomaslevesque** [comment]
> It didn't produce any warning, since it was internal

OK, that was because SA1600 was disabled in my project. This makes a bit more sense. Still, it's a little strange... SA1601 doesn't really make sense if SA1600 is disabled, since it's just a special case.

**Comment by sharwell** [comment]
SA1601 already adheres to the documentation configuration: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md#documentation-requirements

We have a few rules that are linked together (severity of one rule affects a different rule), and these rules are quite difficult to reason about. We should avoid increasing complexity like this.
