### ISSUE TITLE
SA1625: Exempt `param` elements with "discard symbol" names

### ISSUE THREAD

**Issue by peteroupc** [DotNetAnalyzers/StyleCopAnalyzers#3013]
Under the Roslyn convention, parameters named `_` or with a name starting with `_` followed by a digit are treated as unused parameters.

For the purposes of SA1625, ignore `param` elements with such names when checking for duplicate documentation elements, just as it now ignores `param` elements documented "The parameter is not used."

See also: https://github.com/dotnet/roslyn-analyzers/issues/2805

**Comment by sharwell** [comment]
Can you give an example of a method and comment that produces SA1625?

**Comment by peteroupc** [comment]
StyleCop Analyzers's SA1625 currently ignores the two parameters given in the following example.

   /// <summary>This is a test.</summary>
   /// <param name='param1'>The parameter is not used.</param>
   /// <param name='param2'>The parameter is not used.</param>
   public static void Test(int param, int param2) {
   }

But currently not in the following examples:

   /// <summary>This is a test.</summary>
   /// <param name='_'>A text string.</param>
   /// <param name='_1'>A text string.</param>
   public static void Test(string _, string _1) {
   }

   /// <summary>This is a test.</summary>
   /// <param name='_'>This parameter is no longer used.</param>
   /// <param name='_1'>This parameter is no longer used.</param>
   public static void Test2(string _, string _1) {
   }

**Comment by sharwell** [comment]
I'm assuming this case works though?

```csharp
/// <summary>This is a test.</summary>
/// <param name='_'>The parameter is not used.</param>
/// <param name='_1'>The parameter is not used.</param>
public static void Test(int param, int param2) {
}
```

:bulb: StyleCop Analyzers doesn't use the `_N` designation for discard parameters. Exposed parameters are expected to always have readable names, whether or not they are used. Unused parameters are an implementation detail which can be marked as seen in #3000.

**Comment by peteroupc** [comment]
Fine; issue withdrawn.

**Comment by peteroupc** [comment]
By the way, do you know the reason why SA1625 exempts "param" elements documented with the exact text "This parameter is not used.", whether its name is "readable" or not?

**Comment by sharwell** [comment]
My guess is it's a carry-over behavior from StyleCop Classic (this is a common source of current edge cases).
