### ISSUE TITLE
SA1011 and Nullable Arrays

### ISSUE THREAD

**Issue by duncan-G** [DotNetAnalyzers/StyleCopAnalyzers#3015]
SA1011:Closing square brackets should be spaced correctly

This does not allow for nullable arrays like `byte[]?`

Ex:
```c#
public void MyMethod(byte[]? nullableByteArray)
{
}
```

Version: 1.1.118

**Comment by duncan-G** [comment]
Closing this issue due to existing issue.
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3006

**Comment by sharwell** [comment]
@duncan-G The fix for this was released earlier today in 1.2.0-beta.66 👍

**Comment by sharwell** [comment]
Duplicate of #2927
