### ISSUE TITLE
SA1101 mis-fires on generic local method in .NET Core 3 Preview

### ISSUE THREAD

**Issue by mgurlitz** [DotNetAnalyzers/StyleCopAnalyzers#3018]
When I compile this example with .NET framework, I don't get any warnings, but with .NET Core 3 Preview, I get "warning SA1101: Prefix local calls with this" on the line `return Quux<int>()`.

I checked this occurs with any of:
- StyleCopAnalyzers version 1.02, 1.1.118, or 1.2.0-beta.66
- .NET Core 3.0.100-preview7-012821, 3.0.100-rc1-014004, or 3.0.100-rc1-014181.

```
    public class TestClass
    {
        private int foobar = 1;

        public int Foo()
        {
            int Quux<T>() => this.foobar;
            return Quux<int>();
        }
    }

**Comment by sharwell** [comment]
This seems closely related to #3012. So far we have not been able to reproduce the issue.

**Comment by sharwell** [comment]
This is fallout from https://github.com/dotnet/roslyn/pull/35822.
