### ISSUE TITLE
StyleCopAnalyzers cannot load Microsoft.Analysis!?

### ISSUE THREAD

**Issue by R-Murison** [DotNetAnalyzers/StyleCopAnalyzers#3022]
Environment VisualStudio 2019 (and 2017 have looked at it in both with the same reults)

I have been upgrading our StyleCop to StyleCop.Analyzers.1.1.118
Usually this works fine on 4 other projects I have done it for so far. 
However on our WebUI project
I am getting the error on some but not all StyleCop warnings.

"cannot be created from D:\Dev\Git\prism-web-ui\packages\StyleCop.Analyzers.1.1.118\analyzers\dotnet\cs\StyleCop.Analyzers.dll : Could not load file or assembly 'Microsoft.CodeAnalysis"

When StyleCop.Analyzer has no dependencies.
I tried adding the Latest Microsoft.CodeAnalysis but that has no effect.

I also read that FxCop has exactly the same issue With FxCop
https://github.com/dotnet/roslyn-analyzers/issues/1785
I tried the suggested fix and applied that to StyleCop.Analyzers.1.1.118 but that did solve the issue.
I changed:
  ```
`<ItemGroup>`
    <Analyzer Include="..\packages\StyleCop.Analyzers.1.1.118\analyzers\dotnet\cs\StyleCop.Analyzers.CodeFixes.dll"/>
    <Analyzer Include="..\packages\StyleCop.Analyzers.1.1.118\analyzers\dotnet\cs\StyleCop.Analyzers.dll"/>
  </ItemGroup>
```
to:
 ```
 <ItemGroup>
    <Analyzer Include="..\packages\StyleCop.Analyzers.1.1.118\analyzers\dotnet\cs\StyleCop.Analyzers.CodeFixes.dll">
      <PrivateAssets>all</PrivateAssets>     
    </Analyzer>
    <Analyzer Include="..\packages\StyleCop.Analyzers.1.1.118\analyzers\dotnet\cs\StyleCop.Analyzers.dll">
      <PrivateAssets>all</PrivateAssets>
    </Analyzer>
  </ItemGroup>
```
As it did not work I reverted the change but I still cannot use StyleCop.Analyzers.1.1.118 on this project.

**Comment by sharwell** [comment]
Can you create a simple GitHub project that reproduces this error? I'm not familiar with some parts of the scenario. It's fine if this is a temporary project under your user account.

**Comment by R-Murison** [comment]
Sam,

this is not my highest priority and i will get back to you, when I succeed in reproducing this in a non-production project.

Robin

**Comment by sharwell** [comment]
@R-Murison No problem. Whenever that occurs I am hoping we get it resolved quickly 👍

**Comment by R-Murison** [comment]
Hi @sharwell,

I have stripped down the production project,as far as I can until it only contains Microsoft and System NUGet packages. This stripped down project only shows the symptoms only on a Clean and Rebuild.

The production product show the symptoms on every build, but the more generic failure depends on inter project dependencies with too much code to anonymize. I hope this enough for you to isolate the issue.

Let me know if you have not recieved an Invitation from me to share 
https://github.com/R-Murison/StyleCopMicrosoftAnalysisIssue
Or if you are having access issues.

Robin

**Comment by sharwell** [comment]
The example project has Microsoft.Net.Compilers version 1.0.0 installed. StyleCop Analyzers requires version 1.2 or newer.

**Comment by R-Murison** [comment]
Thanks, Problem sorted! 👍
