### ISSUE TITLE
Preferences for .resx files

### ISSUE THREAD

**Issue by NextTurn** [DotNetAnalyzers/StyleCopAnalyzers#3024]
Why are some literals (titles, descriptions, etc.) defined in the source files and others defined in the resource files?

**Comment by vweijsters** [comment]
That is a remnant of the past. The project started out without translatable resources and quite a few rules where implemented before translatable resources were added. As it is quite a bit of work to convert everything, we just never got around to do it all.

Feel free to submit a PR that converts (part of) the remaining literals to resources 😉
