### ISSUE TITLE
Code fix: UseBuiltInTypeAlias

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#304]
Implement code fix for #54.

**Comment by pdelvo** [comment]
Visual Studio provides a built in solution to do this so I don't think we need a code fix for it.

**Comment by sharwell** [comment]
The **Simplify Type Name** code fix does handle this, but I noticed that the batch fixer it uses only operates on a single *specific* type of violation. For example, if you tell it to simplify `UInt32`, it will replace all instance of `UInt32` with `uint`. However, it will *not* replace any instances of `Int32` with `int`. It will also *not* replace any instance of `System.UInt32` (the fully-qualified reference) with `uint`.

I believe a general code fix could be implemented for SA1121 which covers all instances of this specific violation while ignoring all the other kinds of simplification which might be performed by the built-in **Simplify Type Name** code fix.

**Comment by sharwell** [comment]
I'm reopening this issue, because we could do a better job of implementing this rule than Visual Studio currently does. It's a relatively low priority issue though because we do have an alternative available.

**Comment by sharwell** [comment]
Fixed in #350.
