### ISSUE TITLE
Shared configuration via NuGet ignoring stylecop.json config

### ISSUE THREAD

**Issue by nheath99** [DotNetAnalyzers/StyleCopAnalyzers#3043]
Further to #2637, I have created a NuGet package with the appropriate .props file and .nuspec file, however the rules in the stylecop.json file I have added are being ignored when I reference the package in the target projects.

For example the stylecop.json file sets indentation:useTabs = true, however I am receiving warning messages instructing me to use spaces.

CSharp.Styleguide.props:
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<PropertyGroup>
		<PackageName>XYZ.CSharp.Styleguide</PackageName>
		<PackageVersion>1.0.0</PackageVersion>
	</PropertyGroup>
	<PropertyGroup>
		<CodeAnalysisRuleSetLocation Condition=" '$(NuGetPackageRoot)' != '' ">$(NuGetPackageRoot)$(PackageName)\$(PackageVersion)</CodeAnalysisRuleSetLocation>
		<CodeAnalysisRuleSetLocation Condition=" '$(CodeAnalysisRuleSetLocation)' == '' and '$(SolutionDir)' != '' ">$(SolutionDir)packages\$(PackageName).$(PackageVersion)</CodeAnalysisRuleSetLocation>
		<CodeAnalysisRuleSetLocation Condition=" '$(CodeAnalysisRuleSetLocation)' == '' ">$([System.IO.Path]::GetDirectoryName($(MSBuildProjectDirectory)))\packages\$(PackageName).$(PackageVersion)</CodeAnalysisRuleSetLocation>
	</PropertyGroup>
	<PropertyGroup>
		<CodeAnalysisRuleSet>$(CodeAnalysisRuleSetLocation)\StyleCop.ruleset</CodeAnalysisRuleSet>
	</PropertyGroup>
	<ItemGroup>
		<AdditionalFiles Include="$(CodeAnalysisRuleSetLocation)\stylecop.json" Link="stylecop.json" />
	</ItemGroup>
</Project>
```

CSharp.StyleGuide.nuspec file:
```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
	<metadata>
		<id>XYZ.CSharp.Styleguide</id>
		<version>1.0.0</version>
		<description>C# Styleguide</description>
		<authors>Nick Heath</authors>
		<dependencies>
			<dependency id="StyleCop.Analyzers" version="1.1.118" />
		</dependencies>
	</metadata>
	<files>
		<file src="stylecop.json" target="" />
		<file src="StyleCop.ruleset" target="" />
		<file src="CSharp.Styleguide.props" target="build" />
	</files>
</package>
```

stylecop.json file:
```
{
  "$schema": "https://raw.githubusercontent.com/DotNetAnalyzers/StyleCopAnalyzers/master/StyleCop.Analyzers/StyleCop.Analyzers/Settings/stylecop.schema.json",
  "settings": {
    "documentationRules": {
      "companyName": "Tapiit",
      "documentInterfaces": false,
      "documentExposedElements": false,
      "documentInternalElements": false
    },
    "indentation": {
      "useTabs": true
    },
    "orderingRules": {
      "usingDirectivesPlacement": "outsideNamespace"
    }
  }
}
```

**Comment by sharwell** [comment]
Are you using a `<PackageReference>` line to reference the **CSharp.Styleguide** package?

Does the following resolve it?

```
<AdditionalFiles Include="$(MSBuildThisFileDirectory)..\stylecop.json" Link="stylecop.json" />
```

**Comment by nheath99** [comment]
Thanks for coming back to me.
- Yes there is a PackageReference to the NuGet package
- No that doesn't fix it

I've also removed [SA1027](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1027.md) from the StyleCop.ruleset file (don't use tabs), however I'm still getting the warning.

I think the NuGet project is setup correctly, is there any other configuration I need to do in my target project so that the files are recognised?

**Comment by sharwell** [comment]
Can you build using MSBuild on the command line with the `/bl /t:Rebuild` switch, and then use Visual Studio's "report a problem" tool to report that it's not passing your settings to the compiler? Attach the **build.binlog** file produced by the build, and then post a link here to the resulting developercommunity.visualstudio.com issue.

**Comment by nheath99** [comment]
https://developercommunity.visualstudio.com/content/problem/789998/stylecop-nuget-package-not-passing-settings-to-com.html

**Comment by nheath99** [comment]
Ok, I realised my error - in the NuGet project, the .nuspec and .props filenames should follow the same naming convention as the 'id' and 'metadata' items respectively. I will create a public repo with the full nuget project and a detailed explanation and post a link here.

**Comment by sharwell** [comment]
@nheath99 Thanks for the update! I originally saw the nuspec file name as CSharp.Styleguide.nuspec, and failed to realize that the `<id>` line within it was different. Renaming the embedded properties file to match the package name should resolve the issue.
