### ISSUE TITLE
Custom ruleset not working with Visual Studio for Mac

### ISSUE THREAD

**Issue by maurei** [DotNetAnalyzers/StyleCopAnalyzers#3058]
### Description
I followed [this guide](https://carlos.mendible.com/2017/08/24/net-core-code-analysis-and-stylecop/) on how to apply a custom ruleset using a .net core project and adjusted the ruleset file to my test case
```xml
<?xml version="1.0" encoding="utf-8"?>
<RuleSet Name="Custom Rulset" Description="Custom Rulset" ToolsVersion="14.0">
    <Rules AnalyzerId="StyleCop.Analyzers" RuleNamespace="StyleCop.Analyzers">
        <Rule Id="SA1200" Action="None" />
    </Rules>
</RuleSet>
```
However this is not recognised by Visual Studio for Mac:
<img width="450" alt="Screenshot 2019-11-06 at 13 32 15" src="https://user-images.githubusercontent.com/9339132/68298520-de6e7a80-0099-11ea-9ee4-fbe2a81af7dc.png">
This works fine however on Visual Studio for windows.
when doing `dotnet build | grep SA1200` however, there are no warnings.

### Reproduction
Just create a new API boilerplate project and 
- add StyleCop.Analyzers  1.1.118 
- add `api.ruleset` with  the xml content above
- add `<PropertyGroup><CodeAnalysisRuleSet>api.ruleset</CodeAnalysisRuleSet> </PropertyGroup>`  in api.csproj

Environment:
macOS Mojave 10.14.5
Visual Studio for Mac 8.3.7 (build 1)
StyleCop.Analyzers 1.1.118

**Note** I'm not sure if this is a stylecop issue or a Visual Studio for Mac issue. If the latter: maybe there is a workaround?

**Comment by sharwell** [comment]
This is being investigated by the VS for Mac team as part of [this issue](https://developercommunity.visualstudio.com/content/problem/607865/directorybuildprops-ignored-in-ios-and-android-pro.html).
