### ISSUE TITLE
Improve SA1129 code fix for IntPtr and UIntPtr

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#3065]
This is similar to #1973 (and #2740 would apply). Currently the code fix for SA1129 replaces `new IntPtr()` with `default(IntPtr)`. It would be better to use `IntPtr.Zero` in these cases (and similar for `UIntPtr.Zero`).

**Comment by tannergooding** [comment]
I'm not sure this is better, especially considering the work towards `nint`/`nuint` which will also use `default`.

`default` is just usable in more places and is more easily understood. I don't think its worth special-casing any of the types to use things like `0` or `IntPtr.Zero` instead.

**Comment by sharwell** [comment]
Note that this is only for a code fix, and doesn't affect the analyzer. If you already use `default(IntPtr)` (or `default`) it will not try and change it to `IntPtr.Zero`.

**Comment by tannergooding** [comment]
Right, I got that. I was just indicating that it doesn't seem worth differentiating these two struct types from all the other struct types that can/do exist.

For example, there are also others like `Guid.Empty`, `null`, `0`, and others that might be viewed as "better", but I don't think we special case those either.

**Comment by sharwell** [comment]
I think it was more a case where the syntax necessary for those cases to appear wasn't very common. While `new Guid()` is certainly known to occur, the latter two would require something like `new int?()` or `new int()`, which I haven't seen used in practice.
