### ISSUE TITLE
SA1106 - incorrect warning with using declarations

### ISSUE THREAD

**Issue by trydis** [DotNetAnalyzers/StyleCopAnalyzers#3075]
As mentioned in https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3004

![](https://user-images.githubusercontent.com/446036/68934785-a3560080-0797-11ea-82d5-5ed0a111c25a.png)

**Comment by sharwell** [comment]
I was not able to reproduce this. A test is added in #3076.

**Comment by llehn** [comment]
I'm definately having this issue. I'll try to provide a repro.

**Comment by trydis** [comment]
This reproduces the warning: https://github.com/trydis/analyzers-repro

Rider JetBrains Rider 2019.2.2
macOS 10.15.1

**Comment by sharwell** [comment]
@trydis I'm not sure what tool is reporting those warnings, but it's not StyleCop Analyzers. I verified both the IDE and command line build scenarios.
