### ISSUE TITLE
StyleCop generates violation when using discard in method parameter.

### ISSUE THREAD

**Issue by Sebastriani** [DotNetAnalyzers/StyleCopAnalyzers#3087]
If naming rules for method parameters are active, it's not possible to use a discard for a parameter without having to suppress the violation.

I think that the naming rules should not be taken into account when using a discard.

**Comment by sharwell** [comment]
StyleCop Analyzers allows discards for lambdas, but does not allow discards for methods. The parameter name should be changed to better describe the intended value.

**Comment by Sebastriani** [comment]
The problem I have is on a template pattern where one of the subclasses doesn't use the parameter in its implementation of the abstract method, to me using a discard there is the clearer option to let everyone understand quickly that in that particular case the parameter is not used...

**Comment by sharwell** [comment]
StyleCop Analyzers is an opinionated code formatter, which means it does not aim to support all interpretations of "good style". In this case, the use of a discard name for a parameter is considered "bad". Among other things, changing the name in an override makes inherited documentation scenarios more difficult.

**Comment by Sebastriani** [comment]
For me there's no better documentation that good clear code itself but ok, I understand it.
