### ISSUE TITLE
How to distribute stylecop.json ?

### ISSUE THREAD

**Issue by sungam3r** [DotNetAnalyzers/StyleCopAnalyzers#3088]
Relates to NuGet/Home#8867

I want to create package like `MyAnalyzers` which contains settings file for stylecop. I managed to do this, but I came across a transitive copy of the settings file to other packages (libraries, apps, etc). I do not want the settings file to fall into the target packages. How to do it?

Honestly, I would prefer to set stylecop settings through properties, for example
```c#
<Project>
  <PropertyGroup>
    <StyleCopDocumentationCulture>bla-bla</StyleCopDocumentationCulture>
    <StyleCopExcludeFromPunctuationCheck>example</StyleCopExcludeFromPunctuationCheck>
  </PropertyGroup>
</Project>
```

Is this method supported?

In general, how do you think it is better to configure projects if my scenario is about a hundred different microservices? My goal is to centralize the analyzers configuration. I thought of doing this through a nuget package, so that it would be enough for services to write 1 line in their csproj without copying the parameter file. Also, all changes to the settings can be versioned and distributed through this package.

**Comment by sungam3r** [comment]
I have been struggling with this issue for quite some time. Either I don’t understand how msbuild works, or I’m not doing what I really need.

**Comment by sungam3r** [comment]
@sharwell could you please give some advice?

**Comment by sharwell** [comment]
@sungam3r Add `PrivateAssets="all"` to your `<PackageReference>` where you import the custom settings.

**Comment by sungam3r** [comment]
@sharwell I did that and that's what happened - https://github.com/NuGet/Home/issues/8867#issue-531559318 . I could not achieve the desired behavior with `PrivateAssets="all"`. Am I doing something wrong?

**Comment by sharwell** [comment]
You need to include the stylecop.json file in the build section of the NuGet package, and not as content. This distribution strategy is not one I generally recommend, so I don't have an up-to-date guide for using it. I think #3043 covers this the best of what I've seen so far.

**Comment by sungam3r** [comment]
This issue is tracked in NuGet/Home#8867
