### ISSUE TITLE
Proposal: recognize <c> tags with keywords and suggest <see langword=""/> tags

### ISSUE THREAD

**Issue by NextTurn** [DotNetAnalyzers/StyleCopAnalyzers#3091]
For example, suggesting `<see langword="null"/>` as a replacement for `<c>null</c>`.

The set of keywords need discussion later if the basic idea is approved.

**Comment by sharwell** [comment]
This is already implemented in [DotNetAnalyzers/DocumentationAnalyzers](https://github.com/DotNetAnalyzers/DocumentationAnalyzers) as [DOC104](https://github.com/DotNetAnalyzers/DocumentationAnalyzers/blob/master/docs/DOC104.md). I'm not sure we need to duplicate all those rules into StyleCop Analyzers.

**Comment by NextTurn** [comment]
Thanks for pointing this out. Closing as a duplicate.
