### ISSUE TITLE
Suggestion: SA1502 should allow empty blocks

### ISSUE THREAD

**Issue by bruno-brant** [DotNetAnalyzers/StyleCopAnalyzers#3093]
SA1502 complains against empty blocks that are on a single line:

```
public void Foo() {}
```

I find this a common style to make it clear that the block is intentionally left empty.

**Comment by sharwell** [comment]
This is the by-design behavior of this rule. I would recommend disabling this rule if the style does not match the expectations for your project.

**Comment by pyce-lb** [comment]
Would have been nice to have exception (like for propert) or a way to differentiate between empty blocks being on a single line or blocks with a statement being on a single line. 🙁
The rule description says:
> A violation of this rule occurs when an element that is wrapped in opening and closing braces is written on a single line.

Are whitespaces considered (or the lack of any characters in fact) an element?

**Comment by sharwell** [comment]
@pyce-lb Roslyn provides an extension point for `DiagnosticSuppressor` implementations to automatically suppress diagnostics. You could implement one of these to disable SA1502 specifically for cases where it is more strict than you'd like. Here's an example where we suppress certain naming styles for test methods:
https://github.com/dotnet/roslyn-analyzers/blob/377e81d1d5a5f41131a5191cdae8c31c42e9c20b/src/Roslyn.Diagnostics.Analyzers/Core/RelaxTestNamingSuppressor.cs
