### ISSUE TITLE
SA1009 false positive when using the null-forgiving operator with parenthesis

### ISSUE THREAD

**Issue by julealgon** [DotNetAnalyzers/StyleCopAnalyzers#3098]
I stumbled upon an interesting warning today while coding an exception unit test for one of my extensions.

The following code triggers a SA1009 warning before the `!` operator:

```csharp
await default(IAsyncEnumerable<object>)!.ToImmutableListAsync()
```

<img width="351" alt="stylecop-spacingissue" src="https://user-images.githubusercontent.com/461579/71521373-46be2900-289f-11ea-98ea-c7e75cf52ecb.png">

I believe this is incorrect, and no spaces should be added in this case.

- **Package version**: 1.1.118
- **TargetFramework**: netstandard2.1
- Nullable reference types enabled

This looks similar to #3064

**Comment by crazycrank** [comment]
I just tried to replicate this, and was successful in 1.1.118, but it seems to be already fixed in 1.2.0-beta.113.
