### ISSUE TITLE
Allow file/copyright header template to have wildcard characters

### ISSUE THREAD

**Issue by RobSiklos** [DotNetAnalyzers/StyleCopAnalyzers#3101]
In some organizations, the file/copyright header contains the year in which the file was created.

For example:
```
// Blah blah blah
// Copyright (c) 2020, My Company Inc.
// All rights reserved.
```

Unfortunately, `stylecop.json` does not currently support the handling of the "year" portion of this text, since it obviously varies from file to file.

I propose that we should be able to add some wildcard text (e.g. regex) to the copyright text config value, in order to accommodate this.

For example, something like...
```json
"copyrightText": "Blah blah blah\nCopyright (c) {regex:'\\d{4}'}\nAll rights reserved."
```

**Comment by sharwell** [comment]
This behavior is by design, as it is not possible to both support the wildcard for validation _and_ provide a deterministic and correct code fix for invalid code. This issue is discussed in detail in #1357 and #1661.
