### ISSUE TITLE
Create an analyzer to require the 'Async' prefix in names of async methods

### ISSUE THREAD

**Issue by dorfire** [DotNetAnalyzers/StyleCopAnalyzers#3114]
Or.. Does this already exist?

**Comment by sharwell** [comment]
https://github.com/microsoft/vs-threading/blob/master/doc/analyzers/VSTHRD200.md

😄

**Comment by dorfire** [comment]
Awesome! Thanks

**Comment by Dreamescaper** [comment]
Personally I don't really like to install an analyzer package with all sorts VS-related analyzers to e.g. Asp.Net Core solution.

**Comment by sharwell** [comment]
@Dreamescaper That analyzer package is designed for use in code that is unrelated to Visual Studio. Most rules that don't apply to web projects will disable themselves, but if you have any warnings from rules that you aren't interested in you can disable them.
