### ISSUE TITLE
.editorconfig does not work wirh StyleCop categories

### ISSUE THREAD

**Issue by s-krawczyk** [DotNetAnalyzers/StyleCopAnalyzers#3126]
Documentation from Microsoft says that we can change severity for whole category. It work only for categories without dots (.) StyleCop rules contain dots in category names therefore it fails to be set. Real pain.

`dotnet_diagnostic.category-StyleCop.CSharp.DocumentationRules.severity = error` this will not work

**Comment by sharwell** [comment]
@mavasani this seems like a bug in the compiler

**Comment by mavasani** [comment]
@s-krawczyk @sharwell Can you file a bug on Roslyn repo?

**Comment by mavasani** [comment]
Actually this works fine for me:

![StyleCop](https://user-images.githubusercontent.com/10605811/76861285-974b7f80-6819-11ea-8595-18e29ec2886a.png)

**Comment by mavasani** [comment]
@s-krawczyk Which version of Visual Studio/compiler toolset are you using? NOTE: This needs VS2019 16.5 or later and compiler toolset 3.5.0 or later.
