### ISSUE TITLE
headerDecoration is ignored when xmlHeader is false

### ISSUE THREAD

**Issue by DasOhmoff** [DotNetAnalyzers/StyleCopAnalyzers#3142]
First of all, thank you for your work and thank you for this amazing analyser! :)
Thank being said, I have a problem regarding the header decoration, here is my stylecop.json file:
```
"documentationRules":
{
    "copyrightText": "Copyright (c) Test. All rights reserved.",
    "headerDecoration": "################################################################################################",

    "companyName": "Test",
    "xmlHeader": false
}
```
But the generated text is as follows:
```
// Copyright (c) Test. All rights reserved.
```
As you can see, there is no decoration. I have the newest StyleCop.Analyzers version installed. How can I fix this?

I looked into #2285, but this did not help me, I have still the same problem.

Thank you for your help :)

**Comment by DasOhmoff** [comment]
Hello, did anyone see this issue?

**Comment by sharwell** [comment]
Can you clarify which specific version of the analyzer you have installed?

**Comment by sharwell** [comment]
@DasOhmoff I believe the key to your situation lies in https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2470#issuecomment-311042021.

**Comment by DasOhmoff** [comment]
Yes, you are right. This explains the problem. Thank you.
