### ISSUE TITLE
Rule proposal: braces for multiline statements must share line

### ISSUE THREAD

**Issue by jez9999** [DotNetAnalyzers/StyleCopAnalyzers#3152]
There is currently a rule `SA1500BracesForMultiLineStatementsMustNotShareLine` requiring braces for multiline statements to be on a new line.  I don't like this convention, and think code looks much nicer with the opening brace being on the same line, and would therefore like the opposite rule to be added: that braces for multiline statements must share the line.

**Comment by jez9999** [comment]
Name suggestion: SX1500BracesForMultiLineStatementsMustShareLine

to go with: [SA1500BracesForMultiLineStatementsMustNotShareLine](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1500.md)

**Comment by sharwell** [comment]
StyleCop Analyzers only supports Allman style braces. The CodeStyle package produced by dotnet/roslyn (currently published [here](https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.CodeAnalysis.CSharp.CodeStyle) but subject to change as the feature is stabilized for a production release) supports alternative styles. My recommendation would be to disable this functionality of StyleCop Analyzers and use an alternative analyzer to enforce brace placement.

**Comment by jez9999** [comment]
> StyleCop Analyzers only supports Allman style braces. The CodeStyle package produced by dotnet/roslyn (currently published [here](https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.CodeAnalysis.CSharp.CodeStyle) but subject to change as the feature is stabilized for a production release) supports alternative styles. My recommendation would be to disable this functionality of StyleCop Analyzers and use an alternative analyzer to enforce brace placement.

Surely this is a totally arbitrary decision?  You have some alternative rules:
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/AlternativeRules.md

How do you decide which ones get into there and which ones get rejected?  Opening braces on the same line is an "alternative style which is adopted by some projects".

**Comment by sharwell** [comment]
> Surely this is a totally arbitrary decision?

It largely is. However, the overall experience provided by the project I referenced is better than the experience we could provide here (it's tied directly to the formatter and other built-in IDE features) _plus_ it's already in active development.

**Comment by jez9999** [comment]
> 
> 
> > Surely this is a totally arbitrary decision?
> 
> It largely is. However, the overall experience provided by the project I referenced is better than the experience we could provide here (it's tied directly to the formatter and other built-in IDE features) _plus_ it's already in active development.

That package appears to be extremely recent (committed within the last week).  Are you aware of any documentation for it?

**Comment by sharwell** [comment]
Yes, we're working to get these packages ready for stable release as quickly as possible. 😄 

@mavasani do we have any documentation for the new CodeStyle package(s)?

**Comment by jez9999** [comment]
@sharwell Sorry to nag, but you do have any idea when `Microsoft.CodeAnalysis.CSharp.CodeStyle` is likely to get pushed onto nuget.org?  I'd really like to avoid having a dependency on MyGet.

**Comment by jez9999** [comment]
> StyleCop Analyzers only supports Allman style braces. The CodeStyle package produced by dotnet/roslyn (currently published [here](https://dotnet.myget.org/feed/roslyn/package/nuget/Microsoft.CodeAnalysis.CSharp.CodeStyle) but subject to change as the feature is stabilized for a production release) supports alternative styles. My recommendation would be to disable this functionality of StyleCop Analyzers and use an alternative analyzer to enforce brace placement.

@sharwell Sorry to resurrect a bit of a dead issue, but the Microsoft.CodeAnalysis.CSharp.CodeStyle MyGet feed we were using has just stopped working; we were pulling it from: https://dotnet.myget.org/F/roslyn/api/v3/index.json

It's now quite urgent that we get this some other way as it's broken our build pipeline.  Do you know where they're published now?  Are they on NuGet yet?

**Comment by sharwell** [comment]
It's published to this feed:

https://dev.azure.com/dnceng/public/_packaging?_a=feed&feed=dotnet-tools

Here's the line for a NuGet.config file:

```
<add key="dotnet-tools" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json" />
```

**Comment by jez9999** [comment]
@sharwell I've just discovered this: https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.CodeStyle/

Any reason we shouldn't just use this NuGet?

**Comment by sharwell** [comment]
It's the same package. All versions are published to the feed I mentioned, and a stable subset are published to NuGet.org.
