### ISSUE TITLE
Issues of some certain rules will not be reported in msbuild

### ISSUE THREAD

**Issue by daozha** [DotNetAnalyzers/StyleCopAnalyzers#3155]
Hello team,

I find some StyleCop issues are shown in Visual Studio, but won't be reported in msbuild. For example:
VS:
![image](https://user-images.githubusercontent.com/38281880/83108516-81e4b280-a0f2-11ea-9119-6f4bc90d7eef.png)

MSBuild:
![image](https://user-images.githubusercontent.com/38281880/83108582-9923a000-a0f2-11ea-98e5-673ae4322f13.png)

We can see that SA1600 are reported in VS but not in MSBuild, while SA1513 can be found on both sides. I double checked my ruleset and SA1600 is enabled:
![image](https://user-images.githubusercontent.com/38281880/83108870-01728180-a0f3-11ea-9b43-56c4a5580207.png)

Not sure why there's difference?

Thanks,
Daotian

**Comment by sharwell** [comment]
This normally occurs when SA0001 has been disabled. Can you confirm that SA0001 is enabled _and_ is not getting reported?

**Comment by daozha** [comment]
> This normally occurs when SA0001 has been disabled. Can you confirm that SA0001 is enabled _and_ is not getting reported?

Thank you Sam for the reply. Yes, SA0001 is disabled. Could you give me some hint why SA0001 is related to SA1600, and why there's difference between VS and MSBuild?

**Comment by sharwell** [comment]
The compiler disables documentation comments for command line builds in cases where SA0001 is reported. There is no guarantee that any of these rules will behave correctly or predictably until this diagnostic is resolved. See https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA0001.md#rule-description for additional information and suggestions on how to correct this.

SA0001 should only ever be disabled if all of the SA16xx rules have been disabled.

**Comment by daozha** [comment]
Many thanks for the instructions. I'll revisit our ruleset.
