### ISSUE TITLE
Confusion over settings

### ISSUE THREAD

**Issue by andyste1** [DotNetAnalyzers/StyleCopAnalyzers#3163]
Not sure if this is StyleCop specific or a more general Roslyn question/issue. I have a solution that uses StyleCop.Analyzers, and the projects are configured to use a ruleset file based on our company's coding standards. One example is SA1101, which is unchecked as we don't want warnings telling us to use the "this." prefix. The ruleset works as expected on my PC. 

Another dev has just started working on the same solution, but he is seeing hundreds of warnings for SA1101 (and others). The path to the ruleset file is correct, displayed near the bottom of the project "Code Analysis" tab, and we've confirmed that the rules are correct, via the "Configure" button (e.g. SA1101 is unchecked). So why is VS ignoring the ruleset file on his PC?

In my Solution Explorer window, if I expand References -> Analyzers -> StyleCop.Analyzers (which I assume is just a different view of the same ruleset file?), I can see that SA1101 has a severity of "None", but the other dev sees "Default". Why is this?
Also, the ruleset file on both PCs is read-only - if I try to change a rule I get "access denied", but the other dev _can_ make changes (and setting SA1101 to "None" suppresses those hundreds of warnings). His VS is obviously not updating the ruleset file, but we've noticed that a .editorconfig file appears instead.

What's going on here? Why is the ruleset file working on my PC but ignored on the other dev's? And why, when he modifies any rules, are they being saved to a .editorconfig file rather than the ruleset file?

**Comment by sharwell** [comment]
This is a bug with Roslyn. Can you collect a binlog by passing the `/bl` argument to `msbuild`, and submit the resulting issue to https://developercommunity.visualstudio.com/? Feel free to mention me in the report to make sure it gets to me.
