### ISSUE TITLE
Since C# primary constructor parameters will have to be pascal-cased, what should additional constructors do?

### ISSUE THREAD

**Issue by jnm2** [DotNetAnalyzers/StyleCopAnalyzers#3168]
https://github.com/dotnet/csharplang/blob/master/proposals/records.md
https://github.com/dotnet/csharplang/blob/master/meetings/2020/LDM-2020-05-27.md

Public properties are created with the same names as the parameters, including casing. I'm assuming camel-cased public properties are out. That leaves a requirement of pascal-casing the parameters if you use the C# 9 positional records feature.

Should consistency between constructors in the same type be enforced?

```cs
record Person(string FirstName, string? MiddleName, string LastName)
{
    public Person(string FirstName, string LastName) // Casing?
        : this(FirstName, MiddleName: null, LastName)
    {
    }
}
```

What about non-positional records? Should all constructors still use pascal-cased parameter names in case the record is refactored into a positional record, since changing the casing at that point would be a source-breaking change?

```cs
record Person
{
    public Person(string FirstName, string? MiddleName, string LastName) // Casing?
    {
        this.FirstName = FirstName;
        this.MiddleName = MiddleName;
        this.LastName = LastName;
    }

    public Person(string FirstName, string LastName) // Casing?
        : this(FirstName, MiddleName: null, LastName)
    {
    }

    public string FirstName { get; init; }
    public string MiddleName { get; init; }
    public string LastName { get; init; }
}
```

**Comment by jnm2** [comment]
Should this issue track the suppression of SA1313 on positional record parameters, since camel case is out of the question?

**Comment by sharwell** [comment]
Explicit constructors are expected to use camelCase. Positional properties are expected to use PascalCase (#3181).
