### ISSUE TITLE
SA1013 should not apply to the null-forgiving operator

### ISSUE THREAD

**Issue by Lizzy-Gallagher** [DotNetAnalyzers/StyleCopAnalyzers#3172]
When using C#8 nullable reference types, SA1013 ("Closing brace should be followed by a space") has undesirable behavior when using the null-forgiving operator (`!`):

```
// It is idiomatic for the null-forgiving operator have no white-space between itself and what it is "operating" on.
// StyleCop.Analyzers is ok with these usages.
var a = 5!;
var b = this.DoSomething()!;

// SA1013: "Closing brace should be followed by a space"
var c = new { Value = "a" }!;

// how to appease SA1013, this is weird and not inline with other usages of !
var d = new { Value = "a" } !;
```

My proposal is that SA1013 should make an exception for the null-forgiving operator to be inline with idiomatic usage.

**Comment by sharwell** [comment]
```csharp
// SA1013: "Closing brace should be followed by a space"
var c = new { Value = "a" }!;
```

I'm not sure we need to do anything about this case. The `!` is unnecessary and can be removed without changing the meaning of the code.

**Comment by Lizzy-Gallagher** [comment]
@sharwell. I chose a simple (though nonsense) example to lay out the problem.

I can put together an example where that demonstates an actually useful null-forgiving operator (this came up for my team in a real-world way, so I'll see if I can adapt that concisely).

**Comment by Lizzy-Gallagher** [comment]
@sharwell. Here's an example of necessary null-forgiving operators with anonymous objects:
 
If you have the following implicitly-typed array of anonymous objects, you'll get a compiler error:
```
var a = new[]
{
	new { Value = default(string) },
        // CS8619 "Nullability of reference types in value of type '<anonymous type: strin Value>' doesn't match target type '<anonymous type: string? Value'"
	new { Value = "a" }
};
```

One fix (without changing the meaning of the source) is to add the null-forgiving operator:
```
var a = new[]
{
	new { Value = default(string) },
        // NOTE: We need a space between '}' and '!' to avoid SA1013 "Closing brace should be followed by a space"
	new { Value = "a" } !
};
```
