### ISSUE TITLE
Diagnostic unit tests: VariableNamesMustNotBePrefixed

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#318]
Implement unit tests for #84.

**Comment by johnkoerner** [comment]
grabbed

**Comment by sharwell** [comment]
New person! :smiley: 

Consider it yours, but I also sent you an invitation to join the @DotNetAnalyzers organization, which will allow me to "officially" assign the issue to you.

**Comment by sharwell** [comment]
Fixed in #564
