### ISSUE TITLE
List of all rules?

### ISSUE THREAD

**Issue by SayusiAndo** [DotNetAnalyzers/StyleCopAnalyzers#3184]
Hi,

Is there a way [I can query the list of available rules in the package](https://stackoverflow.com/questions/63424712/how-to-get-list-of-available-analyzers)? I can see that VS can do it, de but I use Rider and I don't have VS.

Thanks

**Comment by sharwell** [comment]
[StyleCopAnalyzersDefault.ruleset](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/rulesets/StyleCopAnalyzersDefault.ruleset) is intended to serve as this list. I'm not sure whether or not we have built-time validation that the list is correct. We also have the [status page](https://dotnetanalyzers.github.io/StyleCopAnalyzers/).

**Comment by SayusiAndo** [comment]
Thank you! I haven't see that file. I should have searched more.

**Comment by p-bojkowski** [comment]
Hi @sharwell 
but StyleCopAnalyzersDefault.ruleset is not updated since 2019.

**Comment by sharwell** [comment]
@p-bojkowski the status page should still be working for a list
