### ISSUE TITLE
Code fix: VariableNamesMustNotBePrefixed

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#319]
Implement code fix for #84.

**Comment by johnkoerner** [comment]
grabbed

**Comment by johnkoerner** [comment]
Consider the following code:

    private int m_ = 6;

In this case, should we just not offer a code fix but keep the warning?

**Comment by sharwell** [comment]
Do you have any idea what StyleCop does for this (I don't have it installed so I'm not sure)?

**Comment by sharwell** [comment]
Do you know what StyleCop does here? I'm thinking we could report [SA1310](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/86) instead of this warning, and then the code fix is not a problem.

**Comment by johnkoerner** [comment]
I installed it and it seems it reports the most specific issue.  So if a variable is named `m_` it will report a 1308, if it is named `_`, it will report a 1309, and if it is `x_` it will report a 1310.

**Comment by sharwell** [comment]
Sounds good. Your suggestion to simply disable the code fix when the "prefix" is the complete name sounds correct.
