### ISSUE TITLE
Indentation isn't picked up from `stylecop.json` (SA1520)

### ISSUE THREAD

**Issue by JoshuaLight** [DotNetAnalyzers/StyleCopAnalyzers#3202]
## Description
Seems like the indentation from the `stylecop.json` isn't working.

_Note: reproduced with SA1520, but not sure whether this is a specific case._

## Specs
- *Version*: `1.1.118`.
- *Runtime*: .NET Framework 4.8 (old `csproj` format). 

## Repro
Before:
```cs
public static void Test()
{
  if (1 > 0)
  {
    Console.WriteLine("");
  }
  else
    Console.WriteLine(""); // Apply SA1520 `Wrap with braces` fix here.
}
```

After:
```cs
public static void Test()
{
  if (1 > 0)
  {
    Console.WriteLine("");
  }
  else
          {
              Console.WriteLine("");
          }
    }
```

## Additional Files
`stylecop.json`:
```json
{
  "$schema": "https://raw.githubusercontent.com/DotNetAnalyzers/StyleCopAnalyzers/master/StyleCop.Analyzers/StyleCop.Analyzers/Settings/stylecop.schema.json",
  "settings": {
    "indentation": {
      "indentationSize": 2,
      "tabSize": 2,
      "useTabs": false
    }
  }
}
```

`stylecop.json` is included in `csproj` like that:
```xml
<ItemGroup>
  <AdditionalFiles Include="stylecop.json" />
</ItemGroup>
```

**Comment by MarcFletcher** [comment]
Same problem here.

**Comment by sharwell** [comment]
This code fix provider relies on the IDE's understanding of indentation. For a consistent experience, you will need to set the indentation size in **.editorconfig** to match the values in **stylecop.json**:

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/8d2a0a0f4b35d4f29217e44f0eaeda88ff0ff7e2/.editorconfig#L7-L11

**Comment by sharwell** [comment]
Considering that we eventually want to make StyleCop Analyzers automatically recognize **.editorconfig** values, I'm going to mark this one as **wontfix**. In other words, for now, you need to set it in both locations, but eventually you will only need to set it in **.editorconfig**.

**Comment by MarcFletcher** [comment]
My editorconfig is already configured correctly. AFAIK 'wont fix' might not be suitable as setting something style related via .editorconfig only won't allow anyone to FAIL a build if a cs file is incorrectly indented. 

IMHO indentation is one of the most important style requirements to enforce.

**Comment by sharwell** [comment]
> AFAIK 'wont fix' might not be suitable as setting something style related via .editorconfig only won't allow anyone to FAIL a build if a cs file is incorrectly indented.

Once **.editorconfig** support is added (#2745), the analyzer behavior will be identical to setting it via **stylecop.json**.

> My editorconfig is already configured as you've highlighted:

I have not been able to reproduce this issue when indentation is set in **.editorconfig**. Can you post a sample project to GitHub that demonstrates this bug?

> My understanding of common stylecop implementations is that it's used within CI pipelines, there's no IDE there.

This bug concerns the code fix, not the analyzer. Code fixes only run in IDE scenarios.

**Comment by MarcFletcher** [comment]
Thanks for the quick reply @sharwell.

Please clone https://github.com/MarcFletcher/OpenPokerAI. You'll note the indentationSize is configured [here](https://github.com/MarcFletcher/OpenPokerAI/blob/main/stylecop.json) and [here](https://github.com/MarcFletcher/OpenPokerAI/blob/main/.editorconfig). No warnings or errors appear to be getting raised for the invalid (4 space indentation) in most of the existing cs files in the [this](https://github.com/MarcFletcher/OpenPokerAI/blob/main/PokerBotDefinitions/PokerDefinitions.csproj) project.

**Comment by sharwell** [comment]
> No warnings or errors appear to be getting raised on build for the invalid (4 space indentation)

StyleCop Analyzers doesn't currently have any rules that enforce indentation amounts. We currently use this package to enforce indentation formatting:

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/8d2a0a0f4b35d4f29217e44f0eaeda88ff0ff7e2/StyleCop.Analyzers/Directory.Build.props#L50

**Comment by MarcFletcher** [comment]
Thanks for clarifying that. I've added that package and can now set build errors on incorrect indentation.
