### ISSUE TITLE
SA1649 does not recognize RecordDeclaration for record types introduced in C# 9

### ISSUE THREAD

**Issue by coder2000** [DotNetAnalyzers/StyleCopAnalyzers#3213]
C#  9 introduced a new record type and the file naming SA1649 does not recognize it yet.

**Comment by sharwell** [comment]
📝 The analysis here should treat the record as a class

**Comment by coder2000** [comment]
I looked into adding it myself but wasn't familiar with how I should do it given that it is not backwards compatible with .NET 4.5.2 or .NET Standard 1.1

**Comment by IngvarKofoed** [comment]
Yes, its seem that the target new needs to be at least `netstandard2.0`. Should the whole solution jump to `netstandard2.0`?

**Comment by sharwell** [comment]
Pull request #3209 shows some examples for how to handle record declarations. It shouldn't be necessary to update the project references.

**Comment by Trolldemorted** [comment]
I am experiencing this bug with the latest stable StyleCop.Analyzers from nuget. Can you estimate when you will release a fix?

My tfm is `<TargetFramework>net5.0</TargetFramework>` if that matters.

**Comment by sharwell** [comment]
@Trolldemorted the fix is available in [1.2.0-beta.161](https://www.nuget.org/packages/StyleCop.Analyzers/1.2.0-beta.261) and newer.

**Comment by Trolldemorted** [comment]
Thanks for the quick reponse! Will you release a stable version with that fix in the near future?

**Comment by sharwell** [comment]
There are no current plans to do so in the near future.

**Comment by jpactor** [comment]
> There are no current plans to do so in the near future.

How about now, since we're already on C# 10?

**Comment by sharwell** [comment]
Given current resources and the rate of language version updates, it's questionable whether we will be able to complete a feature audit and stabilization pass for another non-beta release. Since NuGet does not have any requirement for development dependencies to have stable versions, this is not a high priority item.

**Comment by GaTechThomas** [comment]
Any chance we can get this change made as a patch to the released version? Having using packages tagged as beta in production systems raises audit flags.

**Comment by sharwell** [comment]
> Having using packages tagged as beta in production systems raises audit flags.

@GaTechThomas We publish a second package without the beta tag to support audit pipelines that fail to account for NuGet's explicit allowance of beta packages that do not contain any shipping content.
https://www.nuget.org/packages/StyleCop.Analyzers.Unstable
