### ISSUE TITLE
New rule proposal: Suggest string interpolation over string concatenation

### ISSUE THREAD

**Issue by iulianb** [DotNetAnalyzers/StyleCopAnalyzers#3220]
I have found an assortment of string concatenation cases throughout the codebases I'm working with and I'm thinking that a rule would help weeding them out. This is more about style preferences across various development teams than it is about interpolation vs. concatenation from a performance point of view.

**Examples**
```
var apiPath = "api/";
var someResourcePath = apiPath + "resource";  // should be $"{apiPath}resource"

var word = "consectetur";
var loremIpsum = "Lorem ipsum dolor sit amet, " + word + " adipiscing elit"; // should be $"Lorem ipsum dolor sit amet, {word} adipiscing elit"
```

**Comment by sharwell** [comment]
I would expect this to be more appropriate for the code style analyzers in dotnet/roslyn, since it's specifically aiding the use of a new language feature over a (roughly) equivalent previous one.

**Comment by iulianb** [comment]
@sharwell Thank you for the quick reply! I'll do some more digging in roslyn then.
