### ISSUE TITLE
C# 9 record definition using constructor raises SA1313

### ISSUE THREAD

**Issue by manfred-brands** [DotNetAnalyzers/StyleCopAnalyzers#3232]
A `record` type can be defined with a constructor where the parameter names become the Properties, such as in:

```
internal record Person(string FirstName, string LastName);
```

StyleCop raises SA1313: _Parameter 'FirstName' should begin with a lower-case letter_. Doing so raises IDE1006.
These are not just parameter name but also Property names.

Can StyleCop detect the difference?

**Comment by sharwell** [comment]
Duplicate of #3181
