### ISSUE TITLE
C#9 record declaration crashes SA1649

### ISSUE THREAD

**Issue by manfred-brands** [DotNetAnalyzers/StyleCopAnalyzers#3233]
For a file with a single record definition:

```
public record Person(string FirstName, string LastName);
```

I get the following exception when compiling:

> CSC : error AD0001: Analyzer 'StyleCop.Analyzers.DocumentationRules.SA1649FileNameMustMatchTypeName' threw an exception of type 'System.ArgumentException' with message 'Unhandled declaration kind: RecordDeclaration'.

Note that this seems to be only the case if targeting anything other than .net5.0.
However, disabling the rule results in code that runs fine under .net48 and .netcore3.1
It is a language feature and doesn't depend on .net5.0 runtime.

**Comment by sharwell** [comment]
Duplicate of #3213
