### ISSUE TITLE
SA1516 says it can be configured with useBlankLinesBetweenUsingGroups, but there is no such entry in the schema.json

### ISSUE THREAD

**Issue by Trolldemorted** [DotNetAnalyzers/StyleCopAnalyzers#3235]
I'd love to configure allowed missing blanks between properties, but the schema does not tell me which values are allowed.

The SA1516 documentation however says it should be configurable: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1516.md#cause

**Comment by sharwell** [comment]
This is a documentation bug. The correct name of the option is `blankLinesBetweenUsingGroups`.

**Comment by Trolldemorted** [comment]
I have tried out all possible values for `blankLinesBetweenUsingGroups` (allow, require, omit), but classes like this are consistently causing a SA1516:
```
class Foo
{
        public double Bar{ get; set; }
        public double Baz{ get; set; }
}
```

Are you sure `blankLinesBetweenUsingGroups` is the correct setting? From its description I would have guessed it controls how I should style subsequent `using` statements/blocks.

**Comment by sharwell** [comment]
I was responding based on the title of the issue.

I don't believe there is any configuration option to allow a blank line to be omitted between single-line property declarations.
