### ISSUE TITLE
SA1011 incompatible with nullable array reference types

### ISSUE THREAD

**Issue by PaulGarnerUk** [DotNetAnalyzers/StyleCopAnalyzers#3237]
I'm trying to quickly modernise an old library onto net5/c#9 and include `<Nullable>enable</Nullable>` in the project

One of the classes has a byte array which is not explicitly set in the constructor, so needs flagging as nullable, but my attempt to do so...

`public byte[]? Data { get; set; }`

now raises SA1011 - "Closing square bracket should be followed by a space".

**Comment by sharwell** [comment]
Duplicate of #2927
