### ISSUE TITLE
SA0001 is unreliable (same code, different results)

### ISSUE THREAD

**Issue by Trolldemorted** [DotNetAnalyzers/StyleCopAnalyzers#3238]
I am running my CI on windows, ubuntu and macos, and I got the SA0001 warning only on macos despite having no platform-specific code:

https://github.com/enowars/EnoEngine/pull/113/checks?check_run_id=1391122590

I can also sometimes see the issue in visual studio and sometimes not.

Related: #2055

**Comment by sharwell** [comment]
SA0001 detects a build configuration error. Visual Studio uses a different parse configuration when working inside the IDE, so the diagnostic would not be reported there. The project configuration for enowars/EnoEngine needs to be corrected to ensure the configuration is correct for both IDE and command line builds. See the documentation for [SA0001](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/7c80b00dd380f74db76e8a82fcb1b5458d269c9c/documentation/SA0001.md) for more information about correcting this.

**Comment by Trolldemorted** [comment]
Why does dotnet build yield different warnings with the same code on different platforms? 🤔

**Comment by sharwell** [comment]
See https://github.com/enowars/EnoEngine/commit/e01db75c70870c0092d6d60b8ef233c650709e62#r44125427. For a reason not known to me, the warning is reported on all platforms, but only one of the platforms produces a reported build failure from it.

**Comment by Trolldemorted** [comment]
>See enowars/EnoEngine@e01db75#r44125427. For a reason not known to me, the warning is reported on all platforms, but only one of the platforms produces a reported build failure from it.

you are right - something really strange must be going on, maybe the new dotnet binaries aren't setting their exit codes properly on those platforms? If I find out what is going on I'll let you know!
