### ISSUE TITLE
When is the next stable release scheduled?

### ISSUE THREAD

**Issue by prlcutting** [DotNetAnalyzers/StyleCopAnalyzers#3241]
I am wondering when the next official/stable release is scheduled please, even if only an approximate timeframe can be shared?  Or is there a roadmap of sorts you can point me to please?

It doesn't look as if there has been a stable release in over 18 months.  The C# language has evolved a good bit in that time - C#8 and now C#9 is released.  StyleCop 1.1.118 is flagging several issues because it predates the evolution of the language, which leads to lots of warning suppression, which I'm afraid will mask legitimate issues.

I see a good bit of activity in the repo suggesting that many of these issues have been fixed, but are only available in an "unstable" version.  Any chance of more smaller, incremental, frequent releases please?

Thanks to all that contribute to this awesome tool.

**Comment by sharwell** [comment]
I would recommend using the beta releases if you are working with newer versions of the language. I would expect it to be sometime around next summer before the non-beta release is completed with C# 9 support stabilized.

**Comment by prlcutting** [comment]
Thanks for the info @sharwell.  I appreciate the quick feedback.

**Comment by julealgon** [comment]
@sharwell do you have any updates on this? I went to add StyleCop to one of our solutions today and noticed that the last stable release was from 2019,  v1.1.118.

I'm going to add the beta package for now but it would definitely be nicer to have an official stable release.
