### ISSUE TITLE
SA1200 in top-level programs

### ISSUE THREAD

**Issue by Trolldemorted** [DotNetAnalyzers/StyleCopAnalyzers#3243]
For imports in top-level programs, a SA1200 is reported for every import.

**Comment by AraHaan** [comment]
@sharwell this is back again with the latest 1.2.0-beta.354 build.

However it happens when using global usings from C# 10: https://github.com/Elskom/Sdk/pull/248

**Comment by sharwell** [comment]
@AraHaan global usings are a different feature, so a new issue would be warranted for this.
