### ISSUE TITLE
SA1649 should accept OfT in addition to {T}

### ISSUE THREAD

**Issue by heaths** [DotNetAnalyzers/StyleCopAnalyzers#3250]
When file naming is set to StyleCop settings, generic type params can be in a file name like `{T}`; however, curly braces can cause issues like coverlet-coverage/coverlet#998 when an input string is formatted. I've seen this happen in other projects as well. https://github.com/dotnet/runtime seemed to have solved this by disabling SA1649 and, at least for many files (about half), use `OfT`. We'd rather not disable SA1649. It would be great if `OfT` was acceptable as well. It seems this is another common pattern from web searches.

**Comment by sharwell** [comment]
The name is currently configurable between `{T}` and `` `1``. See [Configuration.md](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md#file-naming-conventions) for details.

**Comment by heaths** [comment]
Backticks will likely (and has, judging from older reports) cause issues downstream, which is why, I imagine, dotnet/runtime chose `OfT`.

**Comment by sharwell** [comment]
I'm going to resolve this one as **external**. The current file names are common and valid on all operating systems, so it is not unreasonable to expect downstream tools to handle them correctly.
