### ISSUE TITLE
SA1201 throws KeyNotFoundException

### ISSUE THREAD

**Issue by alexanderyaremchuk** [DotNetAnalyzers/StyleCopAnalyzers#3270]
Any ideas wat could be the cause and remedy for this?:
`Error	AD0001	Analyzer 'StyleCop.Analyzers.OrderingRules.SA1201ElementsMustAppearInTheCorrectOrder' threw an exception of type 'System.Collections.Generic.KeyNotFoundException' with message 'The given key was not present in the dictionary.'`

**Comment by sharwell** [comment]
What version of StyleCop Analyzers are you using?

If you build with `/v:diag`, it should provide a stack trace and context information for the code it was analyzing at the time of the exception. Can you include that information here?

**Comment by alexanderyaremchuk** [comment]
v. 1.1.118. 
The trace output after building with` /v:diag` doesn't seem to reveal anything other than  ```
(CoreCompile target) ->
                     CSC : error AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1201ElementsMustAppearInTheCorrectOrder' threw an exception of type 'System.Collections.Generic.KeyNotFoundException' with message 'The given key 'RecordDeclaration' was not present in the dictionary.'
```. <path/to/my/project>

**Comment by sharwell** [comment]
This issue was fixed by #3264 👍
