### ISSUE TITLE
SA1202 with internal constructors

### ISSUE THREAD

**Issue by SteveAndrews** [DotNetAnalyzers/StyleCopAnalyzers#3280]
The rule says internal and public members should come before private members, but my private member is a constructor which should come before methods. It's a common pattern to have static builders with private constructors and public methods.

(Also, add global suppression for every single rule, please. And an iota of accessibility (UX) would be nice.)

**Comment by sharwell** [comment]
> (Also, add global suppression for every single rule, please. And an iota of accessibility (UX) would be nice.)

I don't understand these in their current form. Can you file a separate issue for each one so they aren't lost when the main issue here is fixed and closed?

**Comment by sharwell** [comment]
The ordering applied by the rules is configurable as described in https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md#ordering-rules. The default was chosen to match StyleCop Classic.

**Comment by SteveAndrews** [comment]
Ok, then I can't use your product if you're not considering private constructors coming before non-private members. You don't get to prescribe how people write and format code - the team that is writing code does that as a team. And that goes into my second comment - that I should be able to choose which rules apply to my project/team. But in Analyzers, I can't. Nor is there a UI to make configuring it simple. I've been a huge StyleCop advocate for many years, but the design decisions made for Analyzers, and the decision to drop Classic (instead of just improving it), means I can't use StyleCop anymore. And I'm kinda pissed off.

**Comment by sharwell** [comment]
> Ok, then I can't use your product if you're not considering private constructors coming before non-private members.

It's still not clear what the problem here is. If the previously-linked documentation did not meet your needs, I would suggest filing a new bug with:

1. Example code
2. The **stylecop.json** configuration file you are using, if any
3. The expected diagnostics for (1)
4. The actual diagnostics that StyleCop Analyzer reports for (1)
5. (If this is a compatibility issue related to converting from StyleCop Classic to StyleCop Analyzers) The diagnostics produced by StyleCop Classic for (1)

**Comment by SteveAndrews** [comment]
> The authors of StyleCop Analyzers have no overlap with StyleCop Classic, and there is no shared code. We started over from scratch...

> You could create a custom analyzer derived from StyleCop Analyzers source code

As you could have. Y'all could have gone to the original project(s) - also open source - and said, "This can be improved and I would like to invest my time here to make it better."

> StyleCop Analyzers is a highly-opinionated tool.

You say that like it's a good thing. :-/

The bottom line though is that you're wrong. Constructors always come before methods, regardless of access modifier. People generally don't put the introduction to a book after Chapter 5. And I shouldn't have to disable the rule for all of my code because your opinion is that things should be ordered differently.

**Comment by sharwell** [comment]
> > StyleCop Analyzers is a highly-opinionated tool.
>
> You say that like it's a good thing.

It is a good thing in the sense that it allows us to produce a highly reliable product within the constraints set by the limited options. Additional options exponentially increase the testing complexity, which inevitably leads to large areas of configuration that are not tested at all.

> Constructors always come before methods, regardless of access modifier.

Please see the main comment in https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3280#issuecomment-751526795. In my local testing, I was not able to find a bug in the current rules based on the limited descriptions provided so far. We cannot make progress on this until the 5 steps there are followed, and we really need a new bug for it.
