### ISSUE TITLE
SA1009 triggers with null forgiving operator

### ISSUE THREAD

**Issue by MattA48** [DotNetAnalyzers/StyleCopAnalyzers#3281]
The following code is triggering SA1009:

    provider => provider.GetService<PreferencesDbContextFactory>()!.CreateDbContext()

The only fix for this is to add a space between the closing parenthesis and the null forgiving operator to give

    provider => provider.GetService<PreferencesDbContextFactory>() !.CreateDbContext()

which IMHO looks kind of weird. Seeing that it doesn't trigger with the null coalescing operator `?.` I suspect this should be treated in the same way. With nullable reference types this is going to become more of an issue.

**Comment by sharwell** [comment]
Does this still reproduce with the 1.2 beta releases? The 1.1 release doesn't support C# 8 syntax.

**Comment by MattA48** [comment]
Appears that it does work as expected with 1.2 - thanks

**Comment by sharwell** [comment]
Duplicate of #3143
