### ISSUE TITLE
SA1106 thrown on switch statement

### ISSUE THREAD

**Issue by InfinityGhost** [DotNetAnalyzers/StyleCopAnalyzers#3294]
This is thrown on a switch statement setting a property value, where removing the semicolon would throw `CS1002`

- https://www.codefactor.io/repository/github/infinityghost/opentabletdriver/source/master/OpenTabletDriver.UX/MainForm.cs#L306
- [Permalink](https://github.com/InfinityGhost/OpenTabletDriver/blob/13b4d077301b703ba34201350cd22ca31891a7b4/OpenTabletDriver.UX/MainForm.cs#L306)

**Comment by sharwell** [comment]
This appears to be caused by one of the following:

* The compiler used for analysis is old and does not support switch expressions
* The project is using StyleCop Classic (which does not support C# language features newer than C# 5)
