### ISSUE TITLE
SA1000 Target-typed New expressions in C#9

### ISSUE THREAD

**Issue by robertlarkins** [DotNetAnalyzers/StyleCopAnalyzers#3295]
Rule SA1000 provides an error for [target-typed new expressions](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#fit-and-finish-features).

For example if I have a field:
```C#
private readonly List<Student> students = new();
```
Rule SA1000 errors on the new. Doing the following fixes it, but I don't think that is the best solution.

```C#
private readonly List<Student> students = new ();
```

Is it possible to get SA1000 to accomodate target-typed new expressions? Similar to how it allows an expression like this:
```C#
var myStrings = new[] { "a", "b", "c" };
```

**Comment by robertlarkins** [comment]
I see it has been fixed now.

**Comment by sharwell** [comment]
Duplicate of #3214
