### ISSUE TITLE
share config across multiple projects

### ISSUE THREAD

**Issue by MahaZaid** [DotNetAnalyzers/StyleCopAnalyzers#3310]
hey, 
So I am trying to publish a Nuget package that only contains the set of `rulesets`
here is my `.csproj` 
```<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <LangVersion>8</LangVersion>
    <PackageVersion>2.0.0</PackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.0-beta004" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Rules\" />
  </ItemGroup>
</Project>
```

when. I publish this package and try to use it in another library .. here is the `Directory.Build.props` file
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
      <CodeAnalysisRuleSet>$(MSBuildThisFileDirectory)../Rules/documentation.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <AdditionalFiles Include="$(MSBuildThisFileDirectory)..\stylecop.json" Link="stylecop.json" />
  </ItemGroup>
</Project>
```

I receive the warning that it can't find the file of rules 

Any idea why ?

**Comment by sharwell** [comment]
It's really hard to tell from looking at just this small subset of the code. We'd likely need to see a complete example for reproducing this.

**Comment by manfred-brands** [comment]
First, have you confirmed that your nuget package actually contains the rules?
Nuget package have specific locations where certain parts need to be.
Normally items that are needed during the build should be in the _build_ subdirectory.

> <CodeAnalysisRuleSet>$(MSBuildThisFileDirectory)../Rules/documentation.ruleset</CodeAnalysisRuleSet>

Why would your nuget package be one directory up from your source code?
The NuGet package is not copied to your project, but left in the NuGet cache.
You would need to reference that directory here and the location is unfortunately not that easy to locate.
Although there is a NuGetPackageRoot MSBuild variable, it is only set after Directory.Build.props is read, but it is available in Directory.Build.targets. 

You could try to add the following to your Directory.Build.targets file (changing the package name/version to yours):

```
  <PropertyGroup>
    <!-- Version of Project.Configuration to use -->
    <ProjectConfigurationVersion>1.0.0</ProjectConfigurationVersion>
    <ProjectConfigurationPackage>project.configuration</ProjectConfigurationPackage> 
    <ProjectConfigurationDirectory>$(NuGetPackageRoot)/$(ProjectConfigurationPackage)/$(ProjectConfigurationVersion)</ProjectConfigurationDirectory>
  </PropertyGroup>                                                                                                       

  <PropertyGroup>
      <CodeAnalysisRuleSet>$(ProjectConfigurationDirectory)/Rules/documentation.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
```

**Comment by MahaZaid** [comment]
Thank you for your help I solved it ... it appears that I had to use nuget  to pack not dotnet
