### ISSUE TITLE
StyleCop KeyNotFoundException error

### ISSUE THREAD

**Issue by piersmyers** [DotNetAnalyzers/StyleCopAnalyzers#3324]
Basic .NET5 console app (VS2019 16.9.2) with StyleCop.Analyzers v1.1.118 NuGet package gives this error:

Warning	AD0001	Analyzer 'StyleCop.Analyzers.OrderingRules.SA1201ElementsMustAppearInTheCorrectOrder' threw an exception of type 'System.Collections.Generic.KeyNotFoundException' with message 'The given key was not present in the dictionary.'.

**Comment by sharwell** [comment]
Duplicate of #3270
