### ISSUE TITLE
SA1000 must have an exception for implicit target-typed new expressions

### ISSUE THREAD

**Issue by bruno-brant** [DotNetAnalyzers/StyleCopAnalyzers#3325]
C# 9 allows for `new` to be called without a type:

```
List<string> strings = new();
```

As per rule SA1000, StyleCop will complain if there's no space between the `new` keyword and the parenthesis. However, VS2019 will remove any spaces upon formatting; this actually seems to be the desired style, so that new() seems like a function call.

**Comment by sharwell** [comment]
Duplicate of #3214

**Comment by bruno-brant** [comment]
Oooops, sorry. Of course someone already posted!
