### ISSUE TITLE
SA1201 : Does it make sense to have nested enums and interfaces in the middle of a class ?

### ISSUE THREAD

**Issue by cboittin** [DotNetAnalyzers/StyleCopAnalyzers#3327]
Hi,

I'm wondering about the order set in rule SA1201, where nested enum and interface definitions are to be put (in the general case) between the constructor and the properties.

I get that pretty much everyone has something to say about how this ordering conflicts with their personal preferences, but at least in the context of C#, this one doesn't make any sense to me. Is there a particular reason why nested interfaces and enums are not bundled together with nested classes and structs, and lie in the middle of a class' definition ?

**Comment by sharwell** [comment]
The ordering is configurable via stylecop.json.

**Comment by cboittin** [comment]
Where can i find the documentation for this ? Configuration.md only mentions changing the importance of SA1201 relative to the other ordering rules, but i haven't seen a mention of SA1201 itself being configurable.

There seems to have been some discussion on the subject already #2541, and an attempted PR #2962

**Comment by sharwell** [comment]
Resolving as **wontfix** per https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2541#issuecomment-533150009.
