### ISSUE TITLE
SA1101 - Disable across project

### ISSUE THREAD

**Issue by jpbulman** [DotNetAnalyzers/StyleCopAnalyzers#3328]
It would be nice to have a way to disable the 'prefix local calls with this' warning across a project in the `stylecop.json`

**Comment by sharwell** [comment]
Disabling via stylecop.json means you are still paying a cost for the analyzer to run and check the option. You can disable the analyzer in its entirety via **.globalconfig**:

```
dotnet_diagnostic.SA1101.severity = none
```
