### ISSUE TITLE
Update SA1649 to support compatibility with built-in Visual Studio file nesting feature

### ISSUE THREAD

**Issue by icnocop** [DotNetAnalyzers/StyleCopAnalyzers#3332]
Hi.

I'm trying to follow Steve "ardalis" Smith's Clean Architecture Web API endpoint code sample but the file names that define the API DTO model request and response classes conflict with SA1649.

When the solution is viewed in Visual Studio, the DTO model request and response classes are nested under the class that defines the API endpoint.

For example, see the [CreateEndpoint.cs](https://github.com/ardalis/CleanArchitecture/blob/ardalis/endpointdemo/src/CleanArchitecture.Web/Endpoints/ToDoItems/CreateEndpoint.cs), [CreateEndpoint.CreateCommand.cs](https://github.com/ardalis/CleanArchitecture/blob/ardalis/endpointdemo/src/CleanArchitecture.Web/Endpoints/ToDoItems/CreateEndpoint.CreateCommand.cs), and [CreateEndpoint.CreatedResult.cs](https://github.com/ardalis/CleanArchitecture/blob/ardalis/endpointdemo/src/CleanArchitecture.Web/Endpoints/ToDoItems/CreateEndpoint.CreatedResult.cs)

I expected StyleCopAnalyzers to detect this type of file naming convention.

However, StyleCopAnalyzers v1.1.118 reports the violation in both `CreateEndpoint.CreateCommand.cs` and `CreateEndpoint.CreatedResult.cs`:

`Warning	SA1649	File name should match first type name.`

Thank you.

**Comment by AraHaan** [comment]
Even the BCL Violates this rule 😄.

**Comment by sharwell** [comment]
I recommend disabling or reimplementing this rule in cases where a project intends to use filenames that do not match the type name.
