### ISSUE TITLE
SA1401 is incorrectly thrown for public fields of inner private classes

### ISSUE THREAD

**Issue by ssg** [DotNetAnalyzers/StyleCopAnalyzers#3336]
The code below causes SA1401 to be fired incorrectly. It's impossible for the field to be accessible if it's marked private. It's an incorrect suggestion, and causes code to break.

```csharp
using System;

namespace SA1401Test
{
    class Program
    {
        private class Test
        {
            public int X;
        }

        public static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            var test = new Test();
            test.X = 5;
        }
    }
}
```

**Comment by sharwell** [comment]
This is the expected behavior for SA1401. Fields are expected to only be accessible within the context of the class in which they are declared (e.g. `Program.Test` for the example above). We should probably add tests for this to make it clear for future readers.

**Comment by ssg** [comment]
@sharwell Gotcha. I thought it fired for properties too for some reason but didn't test for it.
