### ISSUE TITLE
ALL_CAPS private const field bypasses the rules

### ISSUE THREAD

**Issue by TheToughGuy** [DotNetAnalyzers/StyleCopAnalyzers#3337]
Version Used:
VS 2019 16.9.2
Steps to Reproduce:

Add style Rule to enforce PascalCase for private const fields (see PascalCaseRule.txt)

In a c# console app add the field 
    
    private const string SESSIONDB_CONTEXT_JSON_DATA_PATH = "someData";

Expected Behavior:
should be warned the field is wrongly named
Actual Behavior:
VS accepts the field
[PascalCaseRule.txt](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/files/6366422/PascalCaseRule.txt)

**Comment by sharwell** [comment]
https://github.com/dotnet/roslyn/issues/52865 is the correct location for this issue.
