### ISSUE TITLE
Code fix: DoNotPrefixCallsWithBaseUnlessLocalImplementationExists

### ISSUE THREAD

**Issue by macpak** [DotNetAnalyzers/StyleCopAnalyzers#334]
Implement a code fix for #34.

**Comment by sharwell** [comment]
This should be pretty straightforward - just replace `base` with `this`.

**Comment by macpak** [comment]
Yes, I will implement IT today.

**Comment by macpak** [comment]
Ok, I thought that the diagnostic was merged. I am gonna wait with this until the diatnostic is in master.

**Comment by sharwell** [comment]
@macpak I merged it. Thanks for all the help on it. :+1:
