### ISSUE TITLE
Defaults for SA1516 and SA1518 seem to have changed in 1.2.0-beta.354

### ISSUE THREAD

**Issue by appel1** [DotNetAnalyzers/StyleCopAnalyzers#3354]
When testing 1.2.0-beta.354 on our projects I got errors for SA1516 and SA1518 that we did not get with previous versions. Explicitly setting the default values for them in stylecop.json removes the errors. 

`"blankLinesBetweenUsingGroups": "allow"`
`"newlineAtEndOfFile": "allow"`

**Comment by sharwell** [comment]
These values now pull from **.editorconfig** when they are omitted from **stylecop.json**:

| **stylecop.json** | **.editorconfig** |
| --- | --- |
| `blankLinesBetweenUsingGroups` | `dotnet_separate_import_directive_groups` |
| `newlineAtEndOfFile` | `insert_final_newline` |

In the latest release, StyleCop Analyzers assumes that it should match properties defined in **.editorconfig**. The workaround you found is the suggestion for cases where the two should intentionally differ. Does this work for you?

**Comment by appel1** [comment]
Yes, was initially a little bit confused because those rules in editorconfig translates to the require value for stylecop analyzers. But with the values set to true in .editorconfig and then allow in stylecop.json it behaves as I want. Thanks!
