### ISSUE TITLE
AD0001	Analyzer 'StyleCop.Analyzers.DocumentationRules.SA1649FileNameMustMatchTypeName' threw an exception of type 'System.ArgumentException' with message 'Unhandled declaration kind: RecordDeclaration'.

### ISSUE THREAD

**Issue by linkdotnet** [DotNetAnalyzers/StyleCopAnalyzers#3359]
With the latest StyleCop.Analyzers version (1.1.118) SA1649 fires an `ArgumentException` when analyzing records in NET5 (C# 9).

## Error
> AD0001 Analyzer 'StyleCop.Analyzers.DocumentationRules.SA1649FileNameMustMatchTypeName' threw an exception of type 'System.ArgumentException' with message 'Unhandled declaration kind: RecordDeclaration'.

## Steps to reproduce
1. Create a new project (for example Blazor Server App) with .NET5 as target framework
2. Install dependency to StyleCop.Analyzers
3. Change the WeatherData class to a record like below (or just create a new record class)
```csharp
public record WeatherForecast
{
    public DateTime Date { get; init; }

    public int TemperatureC { get; init; }

    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);

    public string Summary { get; init; }
}
```
4. Configure StyleCop in that fashion that it throws a message (for example warning) for SA1649
5. Hit compile

For a complete example checkout: https://github.com/linkdotnet/StyleCopError

Clone / download the repo and press compile.

**Comment by linkdotnet** [comment]
1.1.118 only supports until 7.3

**Comment by sharwell** [comment]
Duplicate of #3213
