### ISSUE TITLE
Applying autofixes uses wrong line endings / should honour .editorconfig

### ISSUE THREAD

**Issue by dgeelen-uipath** [DotNetAnalyzers/StyleCopAnalyzers#3360]
`.editorconfig`:
```
[*.cs]
end_of_line = lf
```

`Example.cs`:
```c#
namespace Bug
{
    public static class Example
    {
        public static int MissingNewLine(bool condition)
        {
            if (condition)
            {
                return 42;
            } // SA1513: Closing brace should be followed by a blank line
            return 0;
        }
    }
}
```

Applying the automatic fix for SA1513 (and probably a bunch of others, but this is the one where I tracked down the problem) inserts a CRLF (carriage return + line feed) combination, but the file uses LF only. In Visual Studio, you can observe the state of line endings for the current file in the bottom right corner of the file-editor pane. It should initially say `LF`, when the automatic fix is applied it will switch to `MIXED` instead:
![image](https://user-images.githubusercontent.com/59690011/124109919-f2819f80-da67-11eb-9055-4682c653023d.png)

The next time the file is opened (but not immediately when the problem is introduced!), Visual Studio will complain about mixed line endings, and suggest to 'normalize' the line endings (using the wrong default option, of-course):
![image](https://user-images.githubusercontent.com/59690011/124109653-ad5d6d80-da67-11eb-9078-2644a27e62c8.png)

The root-cause is probably because [the fixer appears to use a hard-coded CRLF](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/82c2d90907131d939fe396e4191b3a867650615f/StyleCop.Analyzers/StyleCop.Analyzers.CodeFixes/LayoutRules/SA1513CodeFixProvider.cs#L66) ([SyntaxFactory.CarriageReturnLineFeed](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.csharp.syntaxfactory.carriagereturnlinefeed?view=roslyn-dotnet-3.9.0)) rather than the currently configured line-end character.

**Comment by bjornhellander** [comment]
There are about 40 places in the code fixers that uses `SyntaxFactory.CarriageReturnLineFeed` directly. Do you see any problem with replacing them with code that creates trivia from `GetOption(FormattingOptions.NewLine, LanguageNames.CSharp)`, @sharwell?

**Comment by sharwell** [comment]
For SA1513, I'd rather update it to match the newline already at the end of the line where the fix is being applied.
