### ISSUE TITLE
SA1313 Should not apply to record syntax constructors

### ISSUE THREAD

**Issue by JulianBirch** [DotNetAnalyzers/StyleCopAnalyzers#3363]
Consider the code

```cs
record Person(int Id) { // Id should be capitalized here
    string? _name;
    Person(int id, string name) { // id should not be capitalized here
        Id = id;
        _name = name;
    }
}
```

Since record syntax constructors determine not only the parameter name but the property name, and the property name has a larger impact on the code base, I'd argue that `Id` should be capitalized there, but in regular camelCase in other constructors.

Suggest that SA1313 should treat record syntax constructors as out of scope and conversely, StyleCop rules that apply to property naming conventions probably _should_ be applied here to record syntax constructors.

**Comment by JulianBirch** [comment]
*sigh* It's fixed on prerelease.

**Comment by sharwell** [comment]
Duplicate of #3232
