### ISSUE TITLE
New rule proposal: require named parameters

### ISSUE THREAD

**Issue by chriskuech** [DotNetAnalyzers/StyleCopAnalyzers#3365]
I have seen two style rules regarding named parameters when invoking a method/function:
1. Require named parameters for multiline argument lists
2. Require named parameters for all method/function invocations

The later has safety implications, as changing the ordering of arguments in a method definition when the arguments have the same type can lead to bugs.

**Comment by sharwell** [comment]
Duplicate of #2220
