### ISSUE TITLE
SA1000 should allow target typed new() without space

### ISSUE THREAD

**Issue by chrfin** [DotNetAnalyzers/StyleCopAnalyzers#3367]
[SA1000](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1000.md) should allow the target typed `new()` without a space in between the new and () as this is valid IMO. 

See: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/target-typed-new

**Comment by sharwell** [comment]
Duplicate of #3214
