### ISSUE TITLE
SA1116/1117 parameter rules don't apply to C# 9 new() expression

### ISSUE THREAD

**Issue by mgurlitz** [DotNetAnalyzers/StyleCopAnalyzers#3369]
I think these rules should apply to the short new() constructor since they already apply to regular constructors.

Tested in VS 2019/2022 Preview 1.1, .NET Core SDK 5.0.302, and the latest StyleCop beta 1.2.0-beta.354
```
public record TestClass(int A, int B, int C);

// triggers SA1116 and SA1117
var test = new TestClass(0,
     4, 5);

// no rules triggered
TestClass test = new(0,
     4, 5);

**Comment by bjornhellander** [comment]
Fixing this
