### ISSUE TITLE
Implemenent Lightup IOperationWrapper

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [DotNetAnalyzers/StyleCopAnalyzers#3381]
Hello,

We'd need `IOperationWrapper` to be a real wrapper for `IOperation` interface. 
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers/Lightup/IOperationWrapper.cs 

Would you accept PR with this change? 

It would:
- Remove current `IOperationWrapper` interface
- Generate `IOperationWrapper` struct with code generator
- Update existing code generation to avoid duplicated implementations of `Type` and `WrappedOperation` members.
- Update existing code generation to respect `Base` attribute from `OperationInterfaces.xml`

**Comment by andrei-epure-sonarsource** [comment]
@pavel-mikula-sonarsource is this still valid after https://github.com/DotNetAnalyzers/StyleCopAnalyzers/commit/9b5db190f53bc6e8689b4df433684d92868fb6b0 ?

**Comment by pavel-mikula-sonarsource** [comment]
Doesn't seem so
