### ISSUE TITLE
SA1000 ("'new' keyword should be followed by space") shouldn't be thrown for target-typed `new()`.

### ISSUE THREAD

**Issue by ssg** [DotNetAnalyzers/StyleCopAnalyzers#3391]
StyleCop.Analyzers 1.1.118.

csproj targets `netstandard2.1` but with `<Language>latest</Language>`. Not sure if it's related to this problem.

SA1000 wants to add a space after target-typed `new` statements making them look like `new ()`. All official examples show the new target-typed new syntax as `new()` without a space. SA1000 shouldn't suggest the space for target-typed `new` statements.

**Comment by sharwell** [comment]
Duplicate of #3214

**Comment by lachezar-gizdov** [comment]
I'm on the latest beta version, and this still appears as a warning?

**Comment by sharwell** [comment]
@lachezar-gizdov it seems likely that one way or another, an older version is still running.
