### ISSUE TITLE
Record structs in C# 10 is throwing an argument exception in SA1649

### ISSUE THREAD

**Issue by twsouthwick** [DotNetAnalyzers/StyleCopAnalyzers#3395]
With the latest version (1.2.0-beta.354) I'm hitting an error when using a record struct:

```csharp
namespace Something
{
  public readonly record struct Sometype(
  {
    public bool IsSet { get; init; }
  }
```

I'm getting the following error:
```
Analyzer 'StyleCop.Analyzers.DocumentationRules.SA1649FileNameMustMatchTypeName' threw an exception of type 'System.ArgumentException' with message 'Unhandled declaration kind: RecordStructDeclaration'.
```

**Comment by twsouthwick** [comment]
I took a look at the project structure and saw that there are different projects for the different language versions. I'm happy to provide a fix for this if you can point me to any docs on how to structure the language version projects

**Comment by AArnott** [comment]
I'm going to have to turn SA1649 completely off for my project because a simple `#pragma warning disable SA1649` in the file is evidently insufficient to suppress the AD0001 warning being emitted by the compiler.
