### ISSUE TITLE
Documentation culture does not respect DOTNET_SYSTEM_GLOBALIZATION_INVARIANT

### ISSUE THREAD

**Issue by rickardp** [DotNetAnalyzers/StyleCopAnalyzers#3402]
Normally, you want to enforce culture-invariant builds to not risk affecting the build output by the culture of the build agent or (worse) workstation.
To resolve this, we run all builds with `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT`. This crashes some documentation rules because these are newing up a CultureInfo with the hard coded default of "en-US".
As a workaround we can add a config setting the "documentationCulture" to "" (which means the invariant culture).

This is needed because it seems the behaviour of this mode was changed in .NET 6.0, previously setting it meant that all cultures were treated as the invariant culture, as documented here
https://github.com/dotnet/runtime/blob/main/docs/design/features/globalization-invariant-mode.md#cultures-and-culture-data

With .net 6 it appears it instead throws an exception, so this is possibly to be treated as a .net 6 compatibility issue in this library.

(Note that there are many ways to enable the global invariant mode, so checking for the environment variable is not sufficient)

**Comment by sharwell** [comment]
It's not clear what the issue here is.

**Comment by rickardp** [comment]
For a repro case, try to run StyleCop in a Docker dotnet 6 SDK environment 

Repro.csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.354" />
  </ItemGroup>
</Project>
```

TestClass.cs
```
namespace Test
{
    /// <summary>
    /// Hello
    /// </summary>
    public class TestClass
    {
    }
}
```

Dockerfile:
```
FROM mcr.microsoft.com/dotnet/sdk:6.0
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1

COPY *.csproj /src/
COPY *.cs /src/
WORKDIR /src
RUN dotnet build
```

To repro:
Run `docker build .`

Expected output:
```
/src/TestClass.cs(1,1): warning SA1633: The file header is missing or not located at the top of the file. [/src/Repro.csproj]
/src/TestClass.cs(4,14): warning SA1629: Documentation text should end with a period [/src/Repro.csproj]
```

Actual output:
```
/src/TestClass.cs(1,1): warning SA1633: The file header is missing or not located at the top of the file. [/src/Repro.csproj]
/src/TestClass.cs(4,14): warning SA1629: Documentation text should end with a period [/src/Repro.csproj]
CSC : warning AD0001: Analyzer 'StyleCop.Analyzers.DocumentationRules.SA1625ElementDocumentationMustNotBeCopiedAndPasted' threw an exception of type 'System.Globalization.CultureNotFoundException' with message 'Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name') [/src/Repro.csproj]
```

**Comment by sharwell** [comment]
I have no objection to merging a fix for this issue, provided it is sufficiently simple. If the fix is complicated, I would be comfortable resolving the issue as won't fix (the product is not expected to account for cases where a user manually overrides the behavior of the runtime such that standard APIs no longer behavior according to their documentation or historical expectations).

**Comment by ArturDorochowicz** [comment]
Globalization invariant mode is not necessarily something exotic that can only happen when the user manually overrides the behavior of runtime. It is for example enabled in official .Net Docker Alpine images:
https://github.com/dotnet/dotnet-docker/blob/65ebd21a6e8f574aaaa80bd53a073ed8e9923e4a/src/runtime-deps/3.1/alpine3.14/amd64/Dockerfile#L20

**Comment by rickardp** [comment]
Two thoughts from me
* This was a breaking change with .NET 6. Currently this is a compatibility issue.
* This is a feature in the .NET runtime that is very sensible to use. The default stems from the days of Windows forms and rich clients where anyone actually cares about the locale of the machine. For backend services, no one does and the default is downright harmful in that unit tests may pass or fail depending on settings of the developers workstation (yes, even in Docker. Locale is one of fee environment variables sometimes propagated to dev containers).

**Comment by ArturDorochowicz** [comment]
A possible solution to this is to replace resx resources under `StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules` (https://github.com/DotNetAnalyzers/StyleCopAnalyzers/tree/master/StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules) with some kind of in memory collection, so that ResourceManager is not used.

This should allow to still configure any supported documentation culture even in globalization invariant mode.

**Comment by JuanZamudioGBM** [comment]
> Globalization invariant mode is not necessarily something exotic that can only happen when the user manually overrides the behavior of the runtime. It is for example enabled in official .Net Docker Alpine images: https://github.com/dotnet/dotnet-docker/blob/65ebd21a6e8f574aaaa80bd53a073ed8e9923e4a/src/runtime-deps/3.1/alpine3.14/amd64/Dockerfile#L20

Excatly, I ended here because we are upgrading to .Net 6 and changing our CI/CD to arm64 and during the build we saw a lot of this errors
