### ISSUE TITLE
SA1000 colliding with C# 9.0 omit type for new operator

### ISSUE THREAD

**Issue by ZakChar** [DotNetAnalyzers/StyleCopAnalyzers#3405]
The rule SA1000 enforces that the `new` keyword must be followed by a space. However, since C# 9.0, the new keyword can be used in a method call format `new()`, meaning that the parentheses must not be spaced from the keyword.

The new keyword should have a rule that says that it needs to be followed by a space, unless what is following is an open parenthesis.

**Comment by ZakChar** [comment]
wrong repo

**Comment by lawrence-laz** [comment]
> wrong repo

Could you provide a link to where you created this issue, so others who end up here could follow it?
