### ISSUE TITLE
Is it alive or abandoned

### ISSUE THREAD

**Issue by ds1709** [DotNetAnalyzers/StyleCopAnalyzers#3420]
Well, my question is presented in subject. Is this project alive or abandoned? I got simple PR with important fix, which is hanging more than half of year. Also there's no any release since april 2019 (more than two years!).
So, is there any plans to support this project or is it abandoned?

**Comment by sharwell** [comment]
> Well, my question is presented in subject. Is this project alive or abandoned? I got simple PR with important fix, which is hanging more than half of year.

I sometimes miss things (I get so many notifications it's impossible to keep up with them all). I'll try to find the PR in question.

> Also there's no any release since april 2019 (more than two years!).

There are several preview releases in that time. I would encourage using them. 👍

**Comment by sharwell** [comment]
I'm assuming the PR in question is:
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/pull/3335

I need to find a Russian-speaking contributor to docs.microsoft.com to verify this change and then we can get it merged.

**Comment by ds1709** [comment]
The issue for PR #3335 is here #3334.

**Comment by PSanetra** [comment]
@sharwell Do you have an ETA when a new stable release can be expected?

**Comment by sharwell** [comment]
There are no plans to remove the beta suffix for releases in the short term. Since this is a development-only dependency, the beta suffix has no impact on release management.

**Comment by sharwell** [comment]
I found a team to help resolve the original request, so closing this.

**Comment by Mailaender** [comment]
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3647 is related. Why is the last release from 2022?
