### ISSUE TITLE
SA1642 Analyzer exception causes build errors due to globalization invariant mode on Linux

### ISSUE THREAD

**Issue by timmydo** [DotNetAnalyzers/StyleCopAnalyzers#3427]
Running under on .net 6 I noticed this:

CSC : error AD0001: Analyzer 'StyleCop.Analyzers.DocumentationRules.SA1642ConstructorSummaryDocumentationMustBeginWithStandardText' threw an exception of type 'System.Globalization.CultureNotFoundException' with message 'Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name') [/mnt/vss/_work/1/s/x.csproj]

**Comment by matthawley** [comment]
We're experiencing this too on a new Ubuntu 20.04 base image in ADO.

**Comment by sharwell** [comment]
Duplicate of #3402
