### ISSUE TITLE
SA1129 : C# 10 Re-evaluation

### ISSUE THREAD

**Issue by Foxtrek64** [DotNetAnalyzers/StyleCopAnalyzers#3430]
Hello,

SA1129 as many of you know is a rule that has the developer prefer `default(T)` over `new T()` for value types. Historically, these were functionally equivalent and the former was preferred to avoid confusion and to make code consistent.

With C# 10, developers are allowed to create [parameterless constructors](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/struct#parameterless-constructors-and-field-initializers) for their structs, which means that these two forms are no longer (necessarily) equivalent.

As such, it is likely time to re-evaluate this rule and discuss whether to rescope or to retire this rule entirely.

I personally see three possibilities:

1. Rescope entirely to builtin value types (prefer `default(int)` over `new int()`).
2. Rescope entirely to builtin value types and invert preference (`new int()` or `new()` over `default(int)`).
3. Retire entirely (possibly implementing 1 or 2 separately as a new rule).

**Comment by sharwell** [comment]
I believe the current rule is still correct for almost all cases. The cases to consider, if any, would be:

1. The behavior for `new T()` where `T` is a generic type parameter constrained to struct
2. The behavior for `new T()` where `T` is a value type known to have a user-defined parameterless constructor in metadata

I believe the risk associated with unintentional creation of an invalid instance is sufficient that case (1) should retain the current behavior. Case (2) is a straightforward false positive that can be addressed at any time.

**Comment by sharwell** [comment]
I fixed this with the conservative approach.

**Comment by alexrp** [comment]
@sharwell What would be the recommendation for types like `SpinWait`? It doesn't have an explicit parameterless constructor and is designed to work default-initialized. I suspect most people would find `var wait = new SpinWait(); ...; wait.SpinOnce();` more clear than `var wait = default(SpinWait); ...; wait.SpinOnce();`. But SA1129 wants the latter.

**Comment by sharwell** [comment]
I believe the simplest recommendation is to just stick to the main rule. This is what the runtime repository itself does with `SpinWait`:
https://github.com/dotnet/runtime/blob/e48558390c988a830040e355c55f729615c91246/src/libraries/System.Private.CoreLib/src/System/Threading/SpinWait.cs#L319
