### ISSUE TITLE
Problems with WindowsAppSdk

### ISSUE THREAD

**Issue by Balkoth** [DotNetAnalyzers/StyleCopAnalyzers#3441]
Once i enable StyleCop through nuget, the following warnings appear:

![image](https://user-images.githubusercontent.com/80055480/150944031-b783907b-45c0-47b5-8218-a02cf46b1495.png)

```
<ItemGroup>
  <PackageReference Include="CommunityToolkit.Mvvm" Version="7.1.2" />
  <PackageReference Include="CommunityToolkit.WinUI.UI" Version="7.1.2" />
  <PackageReference Include="CommunityToolkit.WinUI.UI.Controls" Version="7.1.2" />
  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.0" />
  <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.0" />
  <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22000.196" />
  <PackageReference Include="StyleCop.Analyzers.Unstable" Version="1.2.0.376">
    <PrivateAssets>all</PrivateAssets>
    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
  </PackageReference>
  <PackageReference Include="System.DirectoryServices.AccountManagement" Version="6.0.0" />
  <Manifest Include="$(ApplicationManifest)" />
</ItemGroup>
```

**Comment by sharwell** [comment]
It's not clear what the problem here is. Can you point out specific items which should have different behavior?

**Comment by Balkoth** [comment]
The warnings shown are in files that the developer has no control over. These are external files from the WindowsAppSdk stored in `%HOMEDRIVE%%HOMEPATH%\.nuget\packages\microsoft.windowsappsdk\1.0.0\include`.

**Comment by sharwell** [comment]
It sounds like the files in that package are missing the following required header:

```
// <auto-generated/>
```

Since the files are not considered generated code, the analyzers will consider them and report violations. I'll check the package to see if I can report a bug to the package authors.

**Comment by sharwell** [comment]
This issue should be reported here:
https://github.com/microsoft/WindowsAppSDK

I found a related comment in https://github.com/microsoft/WindowsAppSDK/issues/1226, but an improved fix would just be adding the auto-generated header comment.

**Comment by Balkoth** [comment]
Closing this here.
