### ISSUE TITLE
Question: suppressing all documentation rules a-la-cart in .globalconfig

### ISSUE THREAD

**Issue by jdvor** [DotNetAnalyzers/StyleCopAnalyzers#3448]
Is it  possible to somehow suppress all documentation rules a-la-cart in .globalconfig / .editorconfig without explicitly naming each one of them?

So instead if this:

```
dotnet_diagnostic.SA0001.severity = none    # XmlCommentAnalysisDisabled
dotnet_diagnostic.SA1600.severity = none    # ElementsMustBeDocumented
dotnet_diagnostic.SA1601.severity = none    # PartialElementsMustBeDocumented
dotnet_diagnostic.SA1602.severity = none    # EnumerationItemsMustBeDocumented
... (~ 40 entries)
```

have rather something along the lines:
_(this documents the intent of the question and is not working solution)_
```
dotnet_diagnostic.SA0001.severity = none    # XmlCommentAnalysisDisabled
dotnet_diagnostic.SA16*.severity = none      # https://documentation.help/StyleCop/Documentation%20Rules.html
```

**Comment by sharwell** [comment]
StyleCop Analyzers doesn't implement any of its own suppression logic. The limits of these files would be covered by [Configuration files for code analysis rules](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-files).

**Comment by jdvor** [comment]
Thank you.

**Comment by jdvor** [comment]
Unfortunately, although documentation says this should work: `dotnet_analyzer_diagnostic.category-Documentation.severity = none`; it simply does not, neither when using dotnet commandline or Rider IDE. It will produce all documentation warnings ignoring the category suppression. Individual rule settings do work as expected.

**Comment by sharwell** [comment]
@jdvor The category in the example won't match any StyleCop diagnostics. To get the category, first locate and select an analyzer in Solution Explorer:

![image](https://user-images.githubusercontent.com/1408396/151844951-a49826ee-9bd9-4aad-ae10-5d013b2ebd19.png)

Then press <kbd>F4</kbd> to open the **Properties** window to see the category:

![image](https://user-images.githubusercontent.com/1408396/151845082-500e635d-7415-47d4-97b7-199f57beddf3.png)

**Comment by jdvor** [comment]
Thank you very much.

For reference - this turns off all documentation related warnings:
```
dotnet_analyzer_diagnostic.category-Documentation.severity = none
dotnet_analyzer_diagnostic.category-StyleCop.CSharp.DocumentationRules.severity = none
dotnet_diagnostic.CS1591.severity = none    # Missing XML comment for publicly visible type or member
```

**Comment by sharwell** [comment]
Keep in mind that this might not be supported in the future:

```ini
dotnet_diagnostic.CS1591.severity = none    # Missing XML comment for publicly visible type or member
```

Trailing comments are not truly supported by the .editorconfig specification, so you'll want to rewrite it like this:

```ini
# Missing XML comment for publicly visible type or member
dotnet_diagnostic.CS1591.severity = none
```
