### ISSUE TITLE
AD0001 / StyleCop.Analyzers.SpecialRules.SA0002InvalidSettingsFile error introduced with version 1.2.0-beta.354

### ISSUE THREAD

**Issue by ImAMightyPirate** [DotNetAnalyzers/StyleCopAnalyzers#3453]
Once we upgrade from version 1.2.0-beta.333 to 1.2.0-beta.354 of StyleCop.Analyzers, our build now fails with the following error message:-

> CSC : error AD0001: Analyzer 'StyleCop.Analyzers.SpecialRules.SA0002InvalidSettingsFile' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null.

No changes were made to our stylecop.json file ([which I have attached](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/files/8022367/stylecop.json.txt)).

**Comment by sharwell** [comment]
Can you run a build with the `/bl` argument? The resulting **msbuild.binlog** file can be opened in the [MSBuild Structured Log Viewer](https://msbuildlog.com/), and the AD0001 message will include a stack trace in addition to the message.

**Comment by ImAMightyPirate** [comment]
Hi @sharwell, here is the stack trace as requested:

![image](https://user-images.githubusercontent.com/5412869/153235440-f7931110-83bf-4780-9274-3b5edf4b5b8a.png)

**Comment by sharwell** [comment]
@ImAMightyPirate it looks like this can only occur if the project is completely empty (i.e. no source files at all, including the default ones provided by the compiler). Is this the case for your project?

**Comment by ImAMightyPirate** [comment]
@sharwell You are absolutely correct, this project doesn't contain any files (we only use it to pull a number of internal NuGet packages at the start of our build process). We could easily exclude it from analysis if we had to, but as it currently stands we use Directory.Build.props to add StyleCop.Analyzers to all projects in our solution.

I don't see the Sources parameter in the binlog for the related csc task (I assume that's because it is has nothing set).

Thank you for such a quick turnaround on this!

**Comment by sharwell** [comment]
No problem, I'll get a fix in either way!
