### ISSUE TITLE
Duplicate warnings when multiple target frameworks

### ISSUE THREAD

**Issue by albert-asin** [DotNetAnalyzers/StyleCopAnalyzers#3454]
If you have multiple target frameworks, you will have duplicate warnings
Is there a way to prevent this?

Thanks for your work

![Capture](https://user-images.githubusercontent.com/2277145/152976668-f8033f74-5a00-4bc4-b8b1-f7185a34b714.PNG)

**Comment by manfred-brands** [comment]
This is caused by VS. I once read it was supposed to be fixed in VS2022 but I still see it.

**Comment by albert-asin** [comment]
Ops, yes, I'm using vs2019
Thanks for the replay
