### ISSUE TITLE
VS2022 Syntax errors

### ISSUE THREAD

**Issue by nstod** [DotNetAnalyzers/StyleCopAnalyzers#3457]
StyleCop doesn't seem to like using declarations in VS2022. It works fine in VS2019.

Repro:
1. Create a new C# project in VS2022.
2. Install the latest pre-release StyleCop (1.2.0-beta.406)
3. Inside a method, add the following line: `using var cts = new CancellationTokenSource();`
4. Notice that you now have an error: "A syntax error has been discovered in file Program.cs on line 5. [StyleCop Rule: SA0102]"

**Comment by sharwell** [comment]
There must be a Directory.Build.props/Directory.Build.targets file in a parent directory which is injecting additional packages outside what the project file shows. If you build on the command line and pass the `/bl` flag to the compiler, it will produce a msbuild.binlog file which you can open in the [MSBuild Structured Log Viewer](https://msbuildlog.com/) to locate the point where StyleCop Classic is running.

**Comment by sharwell** [comment]
See also #3066

This is a situation where I definitely want to help, but the error in question could not have been caused by any version of this project (it never existed). If I had a project with this error, by first choice for investigating it would be the binlog.

**Comment by nstod** [comment]
I apologize for all this. I wasn't able to track it down with the binlog, but I had forgotten that ReSharper had a StyleCop extension enabled. Once I disabled that, the problem went away. I will close this issue. I really appreciate the help.
