### ISSUE TITLE
SA1313: Warning conflicting with MSFT naming convention for record positional parameters

### ISSUE THREAD

**Issue by cjakobsen** [DotNetAnalyzers/StyleCopAnalyzers#3471]
When writing code that uses positional parameters to define record members a SA1313 warning is generated if the parameters are Pascal cased.

Pascal casing is the Microsoft recommended naming for positional parameters in records, see [Naming Conventions](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#naming-conventions).

Example that cases the warning (from the above documentation):

```
public record PhysicalAddress(
    string Street,
    string City,
    string StateOrProvince,
    string ZipCode);
```

Suggestion:
Warning should not be issued for this case.

**Comment by sharwell** [comment]
Duplicate of #3181
