### ISSUE TITLE
SA1101 in property pattern

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/StyleCopAnalyzers#3472]
![image](https://user-images.githubusercontent.com/1640096/159216920-b1e4b52e-6afc-4ffc-a0a1-adb40219c239.png)

```cs
internal object? P=> this.Value switch
{
    InvocationExpressionSyntax { Expression: LiteralExpressionSyntax { Token.ValueText: { } valueText } } =>null,
    _ => null,
};
```

**Comment by springy76** [comment]
Happens right after IDE0170 "simplify property pattern" - a C#10 feature?

BTW a simple `if` is enough:
`if(something is { Page.PageNumber: > 1 })`
