### ISSUE TITLE
How can I add new rules to StyleCop Analyzer in Visual Studio 2022?

### ISSUE THREAD

**Issue by saims21577** [DotNetAnalyzers/StyleCopAnalyzers#3474]
Hello,
How can I add a new set of rules to Stylecop Analyzer in Visual Studio 2022, for example, I want to start all the namespaces with companyname+actualnamepace?

and I want these new rules(ruleset) to be used by 100s of projects in the solution?

Thanks,
Sharath

**Comment by sharwell** [comment]
Rule extensibility is implemented by the C# compiler, and not by StyleCop Analyzers. StyleCop Analyzers is just one extension to the compiler analysis. Here's an overview of the code analysis features, which includes links to several known analyzer products as well as documentation for creating a custom analyzer:

https://docs.microsoft.com/en-us/visualstudio/code-quality/roslyn-analyzers-overview?view=vs-2022
