### ISSUE TITLE
SA1000 doesn't handle checked operator definitions

### ISSUE THREAD

**Issue by tannergooding** [DotNetAnalyzers/StyleCopAnalyzers#3478]
C# 11 is introducing user-defined checked operators (`public static T operator checked +(T value);`) and currently triggers `SA1000` saying no space is expected after `checked`.

The analyzer should be updated to allow a space when checked is used in this context, seeing as it differs from the normal `checked(expr)` syntax.

**Comment by tannergooding** [comment]
This is triggering various warnings for dotnet/runtime when trying to implement the generic math feature and so I've worked around it by switching the analyzer to `suggestion`.

**Comment by bjornhellander** [comment]
@tannergooding, is this available in a preview yet? I can't get an example class to compile using the new syntax.

**Comment by tannergooding** [comment]
I believe it went out in .NET 7 Preview 3, but it might need a nightly or to wait until .NET 7 Preview 4 if I've got my dates mixed up.

**Comment by bjornhellander** [comment]
This looks simple to fix, but I did not manage to get a unit test to compile my test code using Microsoft.CodeAnalysis.CSharp.Workspaces 4.2.0-4.final. Waiting until the next release of that package.
