### ISSUE TITLE
Project Overview

### ISSUE THREAD

**Issue by pdelvo** [DotNetAnalyzers/StyleCopAnalyzers#348]
Because it is a little bit hard to get an overview about what is implemented and what is not without either looking at all the source code files or searching through the issue list I made a little page that gives you the current status of the master branch. I think this is usefull: http://stylecop.pdelvo.com/. It updates every 15 minutes.

It is using roslyn to look through the source. It is very basic and just looks if there is a comment in the class containing "TODO: Implement analysis" to check if it is implemented and it checks if the 5th argument of the Descriptor accesses a member called DisabledNoTests.

**Comment by sharwell** [comment]
Very nice! Is this open source?

**Comment by pdelvo** [comment]
It is now. Its not very fancy but it works ;)
https://github.com/pdelvo/StyleCop.AnalyzersAnalyzer

**Comment by sharwell** [comment]
Can you submit a pull request to add a link to the readme?

**Comment by pdelvo** [comment]
I opened a pull request, but the readme could use a bit more text I think.
