### ISSUE TITLE
SA1629 should also accept other punctuation characters like '!' or '?' as valid line endings.

### ISSUE THREAD

**Issue by genxs-trading** [DotNetAnalyzers/StyleCopAnalyzers#3480]
SA1629 should also accept other punctuation characters like '!' or '?' as valid line endings.

_Originally posted by @IngbertPalm in https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2680#issuecomment-388158978_

**Comment by sharwell** [comment]
Duplicate of #2724
