### ISSUE TITLE
Anomalous SA1515 with prior inline comment

### ISSUE THREAD

**Issue by brinko99** [DotNetAnalyzers/StyleCopAnalyzers#3481]
With versions > 1.0.2 including 1.2.0-beta.406 I'm seeing anomalous behavior with SA1515 Single Line Comment Must Be Preceded By Blank Line.

In the example below I'm seeing SA1515 reported on the line `// Inline Comment 2`. Generally, there is an exception for this rule when comment follows documentation comments.

What's interesting, if either `// Inline Comment 1` or the constructor are removed from the class, the warning goes away. See the attached repo project's `Class2` and `Class3`.

The project does generate a documentation file:
`<GenerateDocumentationFile>true</GenerateDocumentationFile>`

Thanks

```
/// <summary>
/// Class1.
/// </summary>
public class Class1 // Inline Comment 1
{
    /// <summary>
    /// Initializes a new instance of the <see cref="Class1"/> class.
    /// </summary>
    public Class1()
    {
    }

    /// <summary>
    /// Gets value.
    /// </summary>
    // Inline Comment 2
    public double Value { get; }
}
```
[SA1515Repo.zip](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/files/8507291/SA1515Repo.zip)

**Comment by bjornhellander** [comment]
I can confirm the behaviour that you're reporting. Looks like this has been broken since 2016. Having a look to see if I can fix it.

**Comment by bjornhellander** [comment]
I am pretty sure that I have seen this myself many times, but not understood that it was a bug. Just got pissed on myself for never learning where it was ok to put these line comments. So good catch @brinko99! I have made a pull request that looks good to me.
