### ISSUE TITLE
SA1101: PrefixLocalCallsWithThis

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#35]
http://www.stylecop.com/docs/SA1101.html

**Comment by pdelvo** [comment]
Are you still working on this?

**Comment by macpak** [comment]
Yes. Actually I am waiting for the review of #333 because both of those issues include checking if a method being analyzed has override or is hidden by another method. 
I implemented it in #333 and if it's ok, I can reuse the same method.

**Comment by sharwell** [comment]
@macpak How is this coming along? I have an implementation that's almost ready (following work on #446) but I haven't written tests for it.

**Comment by macpak** [comment]
Allright, I haven't done much for this task, so feel free to take it.

**Comment by macpak** [comment]
I think we can add tests based on test from #400
