### ISSUE TITLE
[Question] Why this package releases only beta version for the past three years?

### ISSUE THREAD

**Issue by maxkoshevoi** [DotNetAnalyzers/StyleCopAnalyzers#3500]
Always was wondering, why StyleCop 1.2.0 wasn't released yet. If one won't look at the dates and just install latest stable version, they will miss out on a lot of rules and fixes.

**Comment by sharwell** [comment]
We haven't had the time to do an audit of all C# 8 features against each of the available rules, followed by the stabilization period. And then in that time, C# 9 and 10 were released, with C# 11 coming.

**Comment by maxkoshevoi** [comment]
So it will stay in beta for a foreseeable future? Especially since C# releases are now on annual basis?

**Comment by sharwell** [comment]
Yes, that's correct

**Comment by Corniel** [comment]
Please reconsider. The fact that some new language features are missing, does not imply that this package is unstable.

If I check [NuGet](https://www.nuget.org/packages/StyleCop.Analyzers) I can clearly see that a lot of people are using the 'unstable' versions instead (for good reasons).

**Comment by kipusoep** [comment]
I just noticed this non-pre-release 'unstable' variant on nuget: https://www.nuget.org/packages/StyleCop.Analyzers.Unstable/ :-D
