### ISSUE TITLE
SA1131 is implemented BACKWARDS

### ISSUE THREAD

**Issue by julie-mindcapers** [DotNetAnalyzers/StyleCopAnalyzers#3504]
Writing an if statement against null/NULL in C/C++/C#, if you write

if (null == x)

the compiler will catch it if you write

if (null = x)

because assigning to a constant won't compile. When you write it like this:

if (x == null)

you could end up spending hours trying to figure out where you accidently typed this:

if (x = null)

**Comment by bjornhellander** [comment]
I don't think that `if (x = null)` can ever compile in c#

**Comment by bjornhellander** [comment]
@appel1 Right. :-) Missed that one. Though not a very common case, as you pointed out.

**Comment by bjornhellander** [comment]
A similar case would be `if (x = true)` when x is a bool. In this case, this analyzer does not help, but the code is still clumsy and not something that people tend to write.

**Comment by julie-mindcapers** [comment]
It's something that those who learned C# don't tend to do, but those that
learned C and/or C++ first do indeed tend to do.

**Comment by sharwell** [comment]
SA1131 is implemented _because_ C/C++ developers tend to do this backwards. 😄
