### ISSUE TITLE
SA1009 doesn't support null forgiving operator

### ISSUE THREAD

**Issue by jeremyregnerus** [DotNetAnalyzers/StyleCopAnalyzers#3515]
The null forgiving operator `!` in C# 8.0 can be applied to methods, after the parenthesis. When doing so SA1009 asks to add a space after the parenthesis, before the !.
`obj.GetType()!`
This further conflicts with [IDE0055](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/formatting-rules) which prefers the absence of a space preceding the null forgiving operator.

**Comment by bjornhellander** [comment]
Looks like this has been fixed in1.2.0-beta.66 from 2019. Which version are you using?

**Comment by jeremyregnerus** [comment]
I am using 1.1.118 from NuGet, is there another place I should be getting this from?

**Comment by jeremyregnerus** [comment]
I updated to the Unstable version of StyleCop and this is resolved.

**Comment by sharwell** [comment]
Duplicate of #3143
