### ISSUE TITLE
SA1642 does not include records

### ISSUE THREAD

**Issue by xLEGiON** [DotNetAnalyzers/StyleCopAnalyzers#3518]
It should be possible to create a record with the following XML documentation header for the constructor:

```csharp
/// <summary>
/// Initializes a new instance of the <see cref="Customer"/> record.
/// </summary>
public Customer()
{
}
```

It should also be possible to end the summary with "record class".

Similarly, record structs should allow the summary to end with "struct" or "record struct".

**Comment by xLEGiON** [comment]
Personally, I like the XML documentation to match the declaring syntax but I guess it's a matter of preference.

My thoughts were that they are sufficiently distinct since the C# language reference lists "record" and "class" separately under "reference types", even if records are just a special type of class underneath.

I understand if there are concerns about adding complexity. I don't know if some sort of configuration setting would be a sufficient compromise? If not, then no problem.

**Comment by AArnott** [comment]
I agree that `record` is *mostly* an implementation detail of the class or struct.

At the moment, SA1642 requires the docs to end with `class` even for `record struct` types, so there is a significant defect at least there, that should be fixed as it's cramping my accurate docs.

**Comment by bjornhellander** [comment]
I can fix @AArnott's case, if you agree that it should be fixed, @sharwell. I also see that the code fix does not work properly for generic records and records structs. Given the current implementation, fixing the code fix would require adding lightup support for RecordDeclarationSyntax, to get hold of the type parameter list. I could add that manually, but it would be nice to get it through the currently missing CSharp9.md etc files instead.

**Comment by sharwell** [comment]
@bjornhellander Lightup support already exists:
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/b209e4ef9cf281963192ed77ae846ecaa3e1fe2c/StyleCop.Analyzers/StyleCop.Analyzers/Lightup/.generated/StyleCop.Analyzers.CodeGeneration/StyleCop.Analyzers.CodeGeneration.SyntaxLightupGenerator/RecordDeclarationSyntaxWrapper.g.cs

**Comment by bjornhellander** [comment]
So it does. Missed it completely. Thanks!
