### ISSUE TITLE
Code fix unit tests: FileMayOnlyContainASingleClass

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#352]
Implement unit tests for #351.

**Comment by NikolayIT** [comment]
@sharwell What do we need to do here?
Add more tests to https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers.Test/MaintainabilityRules/SA1402UnitTests.cs?

**Comment by sharwell** [comment]
Right now we only test that the second class was removed from the original file. We need to also test that the contents were correctly added to a new file with the expected name. I'm not sure what the best way to do this is, but I would at least start by looking at the unit tests for SA1649.

**Comment by bjornhellander** [comment]
PR #2140 added check of the newly created file's content. I can have a go at also checking the file name.
