### ISSUE TITLE
`/// <inheritdoc/>` when there is nothing to inherit it from

### ISSUE THREAD

**Issue by MartyIX** [DotNetAnalyzers/StyleCopAnalyzers#3522]
Hi fellows,

I wonder whether StyleCopAnalyzes can warn me when I have a method with `/// <inheritdoc/>` XML documentation and there is no method to inherit it from.

Or should I ask in https://github.com/dotnet/roslyn/ repository?

Regards!

**Comment by manfred-brands** [comment]
The rule exists [SA1648](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1648.md)

**Comment by ZacharyPatten** [comment]
related: https://github.com/dotnet/roslyn-analyzers/issues/5185
