### ISSUE TITLE
SA1201 analyzer throws exception

### ISSUE THREAD

**Issue by Siphonophora** [DotNetAnalyzers/StyleCopAnalyzers#3526]
Hello, I have been running into an exception from style cop. The message is below and a minimized example of the bug is here: https://github.com/Siphonophora/StyleCop-AD0001-exception/blob/main/StyleCopIssue/UnitTest1.cs#L11-L14

Its the nested record above that seems to be the source of the issue. though the other method in the class needs to be there too.

```
CSC : warning AD0001: Analyzer 'StyleCop.Analyzers.OrderingRules.SA1201ElementsMustAppearInTheCorrect
Order' threw an exception of type 'System.Collections.Generic.KeyNotFoundException' with message 'The
 given key 'RecordDeclaration' was not present in the dictionary.'. [\StyleCop-AD0001-exception\StyleCopIssue\StyleCopIssue.csproj]
```

**Comment by bjornhellander** [comment]
I see that you are using version 1.1.118, which is rather old. This seems to be fixed in PR #3264, which is included in 1.2.0-beta304 and later versions.

**Comment by Siphonophora** [comment]
@bjornhellander Thanks, This does work on the beta. Is 1.2.0 coming out of beta at some point? Its been a while

**Comment by sharwell** [comment]
@Siphonophora there are no plans to drop the prerelease suffix in the immediate future. NuGet doesn't require development dependencies to have stable version numbers, and the C# language is progressing faster than the stabilization process for this repository. We don't have the incentive or resources necessary to alter the current approach.
