### ISSUE TITLE
List patterns trigger SA1010 and SA1012

### ISSUE THREAD

**Issue by alexrp** [DotNetAnalyzers/StyleCopAnalyzers#3536]
![image](https://user-images.githubusercontent.com/44076/179395260-60933754-1971-4033-bbc9-238f0313bcd9.png)

**Comment by bjornhellander** [comment]
Seems like a duplicate of #3503 and #3509

**Comment by alexrp** [comment]
Sheesh, I searched for "list patterns" instead of "list pattern", so those issues didn't turn up. 🤦

Indeed, I'll go ahead and close this.
