### ISSUE TITLE
Incorrect SA1008 with pattern matching tuple

### ISSUE THREAD

**Issue by jizc** [DotNetAnalyzers/StyleCopAnalyzers#3556]
This is a similar issue to #3476. The following code results in SA1008:
```csharp
if (obj is FrameworkElement { Tag: (bool item1, bool item2) })
//                                 ^ SA1008 Opening parenthesis should not be preceded by space
```
Using StyleCop.Analyzers 1.2.0-beta.435.

**Comment by ssg** [comment]
This happens with other pattern matching structures too:
<img width="794" alt="image" src="https://user-images.githubusercontent.com/241217/201196045-16a03082-466a-48de-934d-f0718f82921c.png">

**Comment by bjornhellander** [comment]
@ssg's case seems to be a duplicate of #3230. It does not reproduce for me with 1.2.0-beta.435.

**Comment by ssg** [comment]
@bjornhellander You're probably right.
