### ISSUE TITLE
Rule conflict between SA1101 and SA1018 for nullabe Array

### ISSUE THREAD

**Issue by tznind** [DotNetAnalyzers/StyleCopAnalyzers#3572]
SA1101 and SA1018 conflict when considering a nullable array (a property which may be null or an array - not an array with nullable elements).

```csharp
internal class Example
{
    public string[]? MaybeStrings { get; set; }
}
```

SA1101: Closing square bracket should be followed by a space.
SA1018: Nullable Type symbol should not be preceded by a space.

The fix for the first is to to add a space between `[]` and `?`.  But that breaks second which wants there not to be a space before:

* <details><summary>Screenshot</summary><img src="https://user-images.githubusercontent.com/31306100/199981255-5cc1dd47-1938-49c2-b0dd-4598010027c2.gif"></details>

I am using `<PackageReference Include="StyleCop.Analyzers " Version="1.1.118" />`

**Comment by bjornhellander** [comment]
Hi! Version 1.1.118 is from 2019, which predates this syntax. You need to use the beta releases to get updates for newer language features. Or switch to the StyleCop.Analyzers.Unstable package, if beta releases are not ok for you.

**Comment by tznind** [comment]
Thanks! I've updated to:
```
<PackageReference Include="StyleCop.Analyzers.Unstable" Version="1.2.0.435">
```

Seems to have fixed the problem, thanks for the tip! Great library!
