### ISSUE TITLE
SA1200 disregards csharp_using_directive_placement in .editorconfig

### ISSUE THREAD

**Issue by ssg** [DotNetAnalyzers/StyleCopAnalyzers#3577]
SA1200 reports "Using directive should appear within a namespace declaration" despite that editorconfig setting stating otherwise:

```
csharp_using_directive_placement = outside_namespace:suggestion
```

StyleCop version is 1.1.118

**Comment by bjornhellander** [comment]
1.1.118 is quite old. Does it work with the latest beta?

**Comment by ssg** [comment]
> 1.1.118 is quite old. Does it work with the latest beta?

It's the latest stable version, how can it be too old?

**Comment by bjornhellander** [comment]
#3571 links to two other issues where @sharwell has explained his view of the situation.

**Comment by ssg** [comment]
By the way, no, this doesn't repro with 1.2.0-beta.435.
