### ISSUE TITLE
Are SA1206 and IDE0036 the same analyzers?

### ISSUE THREAD

**Issue by MartyIX** [DotNetAnalyzers/StyleCopAnalyzers#3587]
I have read:

* https://learn.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/style-rules/ide0036
* https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1206.md

and they look the same to me. Or is there a difference?

**Comment by bjornhellander** [comment]
IDE0036 has an absolute order it wants modifiers in, whereas SA1206 only cares about three modifier categories being in the correct order.

For example, this code triggers IDE0036, but not SA1206:
`public unsafe virtual void M() { }`

So they do uphold very similar coding styles, but not exactly the same.

**Comment by SergioPredatore** [comment]
Also they conflict with each other.
For example this code trigger SA1206:
`public required`
And this code trigger IDE0036:
`required public`

**Comment by sharwell** [comment]
@SergioPredatore That is a duplicate of #3527
