### ISSUE TITLE
Suggestion: Known Changes Document

### ISSUE THREAD

**Issue by pdelvo** [DotNetAnalyzers/StyleCopAnalyzers#359]
I think it would be a good idea to have a list of changes from StyleCop to this project with the reason why it is different. Im talking about known changes (not bugs) where we report a diagnostic where stylecop does not or the other way around. So that people that migrate from stylecop know if they encountered a bug or not.

**Comment by sharwell** [comment]
A very good idea.

**Comment by sharwell** [comment]
For reference, SA1001 includes an intentional deviation, where `Func<,>` is preferred over the form `Func<, >`, even though the StyleCop documentation suggests the latter would be correct. See #475 for additional information.

**Comment by sharwell** [comment]
SA1642 includes an intentional deviation as described in #413.

**Comment by sharwell** [comment]
SA1000 includes modifications to the original description, as described in #188, #189.

It also includes an intentional deviation as described in #340.

**Comment by sharwell** [comment]
SA1119 currently includes a deviation which was reported in #1450.

**Comment by sharwell** [comment]
SA1025 currently includes a deviation which was reported in #1424. The rule proposed in #993 would move this violation to its own rule, which could be disabled for improved compatibility with StyleCop "classic".

**Comment by jackwhelpton** [comment]
SA1515 currently includes a deviation which was reported in https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/1490. I think our code included another example that was less justifiable; I'll find that now.

**Comment by stylpe** [comment]
SA1649 now also checks the actual file name rather than just the file attribute in the file header, ref http://www.stylecop.com/docs/SA1649.html

I saw you asked for this explicitly in #169, otherwise I might have filed this as an issue :)
