### ISSUE TITLE
SA1206 conflicts with IDE0036 for required properties

### ISSUE THREAD

**Issue by symbiogenesis** [DotNetAnalyzers/StyleCopAnalyzers#3592]
SA1206 wants _required_ to come before the accessibility keyword. But IDE0036 wants the reverse.

https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0036

Affects version: 1.2.0-beta.435

**Comment by bjornhellander** [comment]
Duplicate of #3527
