### ISSUE TITLE
SA1135 conflicts with IDE0001

### ISSUE THREAD

**Issue by symbiogenesis** [DotNetAnalyzers/StyleCopAnalyzers#3593]
IDE0001 wants names to be simplified if possible. But for using aliases, SA1135 wants them to be fully qualified. Which is a contradiction.

Affects version: 1.2.0-beta.435

**Comment by bjornhellander** [comment]
Could you provide a small example, just so avoid misunderstandings?

**Comment by sharwell** [comment]
Yes, this is by design. Note that IDE0001 is not enforced in CI/build scenarios, so there is no build-time conflict for these.
