### ISSUE TITLE
.NET 6 not marking generated code

### ISSUE THREAD

**Issue by dude3133** [DotNetAnalyzers/StyleCopAnalyzers#3597]
From .NET 6 till .NET 8 there is issue that autogenerated code not marked properly by roslyn and it could cause errors
For more details [see](https://github.com/xamarin/xamarin-android/issues/7698)
I know that [starting from 1.1 version, StyleCop relies on Roslyn](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/1430#issuecomment-422871785), but is there any other option to ignore folders?

**Comment by manfred-brands** [comment]
You can tell Roslyn what files you consider autogenerated in your .editorconfig. See [Configure Generated code](https://learn.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?source=recommendations&view=vs-2022#configure-generated-code)

```ini
[*.g.cs]
generated_code = true
```

**Comment by dude3133** [comment]
Worked with
```
[obj/**]
generated_code = true
```

Thanks a lot
