### ISSUE TITLE
SA1102: QueryClauseMustFollowPreviousClause

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#36]
http://www.stylecop.com/docs/SA1102.html

**Comment by macpak** [comment]
This one is a little bit tricky. I checked original StyleCop and for code like:
    
     int [] a =new int[0];
            var query = from m 
                            
                            in
                
                a
               
                        
                        where m > 5


                & m > 2


                group m by m into c
                
                        
                        select c.Key;

it only reports ` where m > 5` as an incorrect part of query. In my opinion it should report more. I'd understand this SA as: each query clause (from, in, where, group, select, let) should be on the same line as the previous line or at the next line. However, doing it this way we completly change the behaviour of this SA. @sharwell , @pdelvo , what do you think about it ?

**Comment by sharwell** [comment]
The way I interpreted the rule is:

> Locate every `where`, `let`, `group`, `join`, `order`, and `select` clause. If the query as a whole spans more than one line, then each of these keywords should appear as the first token on a new line, and there should not be a blank line before it.

I did not include `from` in this list because it is always the first token of a query, and it may appear at the end of a line containing other tokens which are not part of a query (for example, the `var query =` part of your sample code). I did not include `in` because it is part of the `from` clause, like `by` is part of the `order` clause.

For example, the following code, which is your original code without the blank lines, would not produce any SA1102 warnings:

     int [] a =new int[0];
            var query = from m 
                            in
                a
                        where m > 5
                & m > 2
                group m by m into c
                        select c.Key;

**Comment by macpak** [comment]
Ok, so (just curious) you are the author of the original SA ?

**Comment by sharwell** [comment]
No, I'm actually not even a user of it. :grin:

I'm interested in this project primarily for the learning opportunity, although I do want to see it succeed for StyleCop users.

**Comment by macpak** [comment]
Allright. I'll implement it the way you proposed, because it's a very reasonable solution.
