### ISSUE TITLE
SA1121 is reported for Xml Comments

### ISSUE THREAD

**Issue by pdelvo** [DotNetAnalyzers/StyleCopAnalyzers#361]
We should allow this:
```csharp
            /// <summary>
            /// Gets or sets the <see cref="System.Object" /> at the specified index.
            /// </summary>
            /// <value>
            /// The <see cref="System.Object" />.
            /// </value>
            /// <param name="index">The index.</param>
            /// <returns></returns>
            /// <exception cref="System.NotImplementedException"></exception>
            object IList.this[int index]
            {
                get { return this[index]; }
                set { this[index] = (T)value; }
            }
```
System.Object is used in the Xml comment and it is currently reported as SA1121. Because xml comments are for many different languages it would even make sense to disallow the use of built-in type aliases.

**Comment by sharwell** [comment]
I believe if you look at the **.xml** file produced by the compiler, you'll find that references like `<see cref="object"/>` actually appear in the output as `<see cref="T:System.Object"/>`. Can you verify this?

**Comment by pdelvo** [comment]
Oh you're right.
