### ISSUE TITLE
License mismatch between nuget gallery and license file in repository

### ISSUE THREAD

**Issue by arphox** [DotNetAnalyzers/StyleCopAnalyzers#3618]
Hi,

The [nuget gallery](https://www.nuget.org/packages/StyleCop.Analyzers/1.1.118) page states **[Apache-2.0](https://licenses.nuget.org/Apache-2.0)**,  
the [License file](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/LICENSE) file states **MIT**.

Which one is authoritative? Can you consolidate them, if possible, please?

**Comment by sharwell** [comment]
The license was changed in release [1.2.0-beta.205](https://www.nuget.org/packages/StyleCop.Analyzers/1.2.0-beta.205). This is reflected in NuGet.
