### ISSUE TITLE
XmlCommentHelper.GetText Performance issues

### ISSUE THREAD

**Issue by ninedan** [DotNetAnalyzers/StyleCopAnalyzers#3619]
There are a few performance issues in GetText implementation:
1) It's recreating regular expression every time, rather costly, especially on .Net framework.
2) Even using regular expression itself is not idea. The reason is that even single white space is a match when no replacement is actually needed, but it will still be performed.
3) Usage of reused StringBuilder is not optimal, because new string is always allocated.

Suggestion: do not use regular expression, aim for not a single allocation when no change is needed.

**Comment by ninedan** [comment]
Current implementation:

![image](https://user-images.githubusercontent.com/19536938/233429935-481d14e1-9cde-4358-9b26-78e8aaeda524.png)

**Comment by ninedan** [comment]
Pull request: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/pull/3651

**Comment by bjornhellander** [comment]
Can this be closed now?
