### ISSUE TITLE
Rules not working after update to Visual Studio 17.5.3

### ISSUE THREAD

**Issue by hudecekd** [DotNetAnalyzers/StyleCopAnalyzers#3620]
Hello,

after update of VS 17.4 to VS 17.5.3 it seems that stylecop analyzers are not working correctly.
For example I have rules 1600 1609 set to error.
If i try to
- build solution from VS then only errors 1600 is shown. If I solve it then build works (and it shouldn't since there is still error 1609.
- build solution from command line `dotnet build` then 1600 and 1609 errors are shown.

Before update to VS 17.5.3 it all worked as expected.
So it seems that for some errors it works as expectd but for some it stopped working (1609) in VS.

See example project in attachments.
[StyleCopTestConsoleApp.zip](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/files/11042062/StyleCopTestConsoleApp.zip)

**Comment by bjornhellander** [comment]
I can kind of confirm this: I don't see SA1609 even on the command line when running 17.5.3. Did not try with earlier 17.5 versions though. Upgrading to Roslyn 4.5.0 in our c# 11 test projects makes 70 tests fail, including tests for SA1609, but I assume that version is used in VS 17.5.0 as well, so I don't know what to think here.

I wonder if this could be the same as https://github.com/dotnet/roslyn/issues/67211

**Comment by bjornhellander** [comment]
I tried with 4.6.0-1.final in our test project and then the problems were gone.

**Comment by bjornhellander** [comment]
Works for me now in 17.5.5. Looks like it has been fixed in 17.5.4 (https://github.com/dotnet/roslyn/pull/67300), but have not tried.
@hudecekd If you are able to update VS, can you try again and close this if it works for you as well?

**Comment by bjornhellander** [comment]
@hudecekd Have you been able to try this with a recent Visual Studio version?

**Comment by hudecekd** [comment]
Hi @bjornhellander ,

sorry for late response. I tried it on my PC and on my colleague's PC. We both updated VS to version  >= 17.5.5 and it works now.  Problem is gone. Thanks for your help and pointing out the origin of the problem.
