### ISSUE TITLE
SA1206 has a problem with c# 11 required keyword

### ISSUE THREAD

**Issue by mehdihadeli** [DotNetAnalyzers/StyleCopAnalyzers#3627]
Hi,
I get warring from `SA1206` rule when I use c# 11 `required` keyword. According to [Microsoft docs](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/required), it should be ok

``` csharp
public record Product
{
   public required decimal Price { get; init; }
}
```

**Comment by bjornhellander** [comment]
Duplicate of #3527
