### ISSUE TITLE
Weird SA1515 behaviour (Single line comment must be preceded by blank line)

### ISSUE THREAD

**Issue by bjornhellander** [DotNetAnalyzers/StyleCopAnalyzers#3631]
I ran the StyleCopTester program on this solution and got **lots** of SA1515 warnings. It looked like in every single file, on the second line of the file header. So I added a unit test for SA1515 with a two-line file header and it also gives a warning regardless of c#/roslyn version (see https://github.com/bjornhellander/StyleCopAnalyzers/tree/feature/sa1515-file-header). I also set the Vsix project as startup project and debugged a simple example project and the same thing happens. But it does not fire when having the nuget installed in a project and running Visual Studio or MSBuild.

The trivia that I see when debugging the unit test is this (which is also what I see in sharplab.io):
* `SingleLineCommentTrivia` and `EndOfLineTrivia` for the first line
* `SingleLineCommentTrivia` and `EndOfLineTrivia` for the second line

The reason for the warning is this line: https://github.com/bjornhellander/StyleCopAnalyzers/blob/feature/sa1515-file-header/StyleCop.Analyzers/StyleCop.Analyzers/LayoutRules/SA1515SingleLineCommentMustBePrecededByBlankLine.cs#L201
We have already iterated back to the very first trivia and `IsOnOwnLine` returns false, which in turn causes `IsPrecededBySingleLineCommentOnOwnLineOrDocumentation` to return false and then there are no more relevant checks to stop the warning from happening.

Based on this, I don't understand why it doesn't normally trigger. What am I missing? Can the analyzer get different trivia based on how it's executing???

**Comment by bjornhellander** [comment]
I didn't check the existing issues properly. Might be a duplicate of #3630.

**Comment by sharwell** [comment]
Duplicate of #3630
