### ISSUE TITLE
Prepare preview release

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#364]
Now that many rules are implemented, tested, and enabled by default, we should start considering the release process for preview releases. We should also consider installing the analyzer in this project so it gets some active use during the preview process.

**Comment by pdelvo** [comment]
I think so too. I think it would be really usefull to have a (nightly) nuget package so we can use it as much as possible. Sometimes when you try to find the most hidden edge case where it could break you oversee the obvios.
It might be a good idea to set up a CI system for that.

What do you want to get done before starting a preview?

**Comment by sharwell** [comment]
I went ahead and released a first preview in order to verify that the build and publish process is working correctly.

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/releases/1.0.0-alpha001
