### ISSUE TITLE
Analyzer not work when click "Start Debugging" or hit "F5"

### ISSUE THREAD

**Issue by Guyiming** [DotNetAnalyzers/StyleCopAnalyzers#3645]
I set SX1309 severity as Error.  It works when click "Build" or "Rebuild".
![image](https://user-images.githubusercontent.com/1835638/233532523-2b2918af-2906-4689-a915-76e6d5f615c8.png)
![image](https://user-images.githubusercontent.com/1835638/233532615-d86957d1-618e-4730-958a-fa23880afd34.png)

But not work when click "Start Debugging" or "F5"：
![image](https://user-images.githubusercontent.com/1835638/233532963-9ecb1d86-8b1b-46cc-8606-37926c9b90a3.png)

**Comment by manfred-brands** [comment]
Check the `Output` windows in Visual Studio, it probably contains a line indicating that it skipped running analyzers.

**Comment by Guyiming** [comment]
@manfred-brands Thanks.

**Comment by hudecekd** [comment]
Maybe it will help soneone. We want to fail build if we run in Debugging or using F5.
We have found that we can disable this in VS in Options -> Text Editor -> C# -> Advanced "Skip anaylzers for implicitly triggered builds" or in csproj so developers do not have to configure it.

```xml
<PropertyGroup>
    <OptimizeImplicitlyTriggeredBuild>False</OptimizeImplicitlyTriggeredBuild>
  </PropertyGroup>
```
