### ISSUE TITLE
SA1000 flagging target-typed new

### ISSUE THREAD

**Issue by bruno-brant** [DotNetAnalyzers/StyleCopAnalyzers#3646]
SA1000 is flagging a target-typed new in my code. As per the [documentation](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1000.md) (and usual style guides) this isn't expected:

> The new and stackalloc keywords should always be followed by a space, except in the following cases:
> (...)
> * The new keyword is part of implicit object creation (target-typed new). In this case there should be no space between the keyword and the opening parenthesis.

I've created a sample code that produces the warning [here](https://github.com/bruno-brant/StyleCopSA1000IssueSample). The warning can be seem at the top of the file: 

![image](https://user-images.githubusercontent.com/1890900/233693025-6b2a1364-6796-41a7-8d28-eff563184dbe.png)

Produced with StyleCop.Analyzers 1.1.118, compiled with .NET 6.0.

**Comment by bjornhellander** [comment]
Duplicate of #3214. You need to use the beta versions, since 1.1.118 was released before c# 9.

**Comment by bruno-brant** [comment]
> Duplicate of #3214. You need to use the beta versions, since 1.1.118 was released before c# 9.

Thanks. I'll try that out and close the issue.

By the way, shouldn't the docs be clear about a rule that's still on beta? Or: when I click the warning in VS, shouldn't it take me to the docs of that specific rule? That would have saved me the time I spend creating the repo, etc., because I though this was expected behavior that had a bug.

**Comment by bjornhellander** [comment]
Sorry for the wasted time! Having version specific documentation seems complicated to me, but I created #3647 to at least try to inform about the situation.

**Comment by bruno-brant** [comment]
> Sorry for the wasted time! Having version specific documentation seems complicated to me, but I created #3647 to at least try to inform about the situation.

Hey, no worries, just was thinking of a way to avoid this situation! Thank you!
