### ISSUE TITLE
Long file names cause build problems

### ISSUE THREAD

**Issue by bjornhellander** [DotNetAnalyzers/StyleCopAnalyzers#3649]
I could not build master anymore on my machine after the recent ResxSourceGenerator changes:

1>CSC : error CS0016: Could not write to output file 'C:\Users\bjorn\source\repos\StyleCopAnalyzers\StyleCop.Analyzers\StyleCop.Analyzers\Lightup\.generated\Microsoft.CodeAnalysis.ResxSourceGenerator.CSharp\Microsoft.CodeAnalysis.ResxSourceGenerator.CSharp.CSharpResxGenerator\StyleCop.Analyzers.DocumentationRules.DocumentationResources.Designer.cs' -- 'Could not find a part of the path 'C:\Users\bjorn\source\repos\StyleCopAnalyzers\StyleCop.Analyzers\StyleCop.Analyzers\Lightup\.generated\Microsoft.CodeAnalysis.ResxSourceGenerator.CSharp\Microsoft.CodeAnalysis.ResxSourceGenerator.CSharp.CSharpResxGenerator\StyleCop.Analyzers.DocumentationRules.DocumentationResources.Designer.cs'.'

It works again after enabling long file paths in the registry. Is this the way it is, or can something be done in the repo to not generate so long names? This part seems to have potential for improvement if it is configurable: `Microsoft.CodeAnalysis.ResxSourceGenerator.CSharp\Microsoft.CodeAnalysis.ResxSourceGenerator.CSharp.CSharpResxGenerator`

**Comment by sharwell** [comment]
For now, it's just how it is. I submitted https://github.com/dotnet/roslyn-analyzers/pull/6615 to shorten the names.

**Comment by bjornhellander** [comment]
Excellent!
