### ISSUE TITLE
SA1206 `requires` should appear before access modifiers

### ISSUE THREAD

**Issue by bruno-brant** [DotNetAnalyzers/StyleCopAnalyzers#3654]
Using version 1.2.0-beta.435.

StyleCop wants the `required` modifier to appear before access modifiers. 

![image](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/assets/1890900/26207bf2-33e8-4827-9313-2c063d30c015)

From [docs](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1206.md) that's not the preferred order; the access modifier should come first.

![image](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/assets/1890900/7274298d-0ba8-48e6-b502-1e402519a2e7)

**Comment by bjornhellander** [comment]
Duplicate of https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3527. Already fixed and will be included in the next release.

**Comment by bruno-brant** [comment]
Sorry @bjornhellander , I don't know why I couldn't find it. Thank you!

**Comment by sharwell** [comment]
Duplicate of #3527
