### ISSUE TITLE
Incorrect SA1623 on property with init accessor

### ISSUE THREAD

**Issue by bjornhellander** [DotNetAnalyzers/StyleCopAnalyzers#3657]
Consider the code below:
```
class MyClass
{
    /// <summary>
    /// Gets or sets xyz.
    /// </summary>
    public int X { get; set; }

    /// <summary>
    /// Gets or sets xyz.
    /// </summary>
    public int Y { get; init; } // Triggers SA1623, expecting only "Gets..."
}
```

I expect SA1623 to treat an init accessor exactly like a set accessor and therefore not trigger on this example.

Tested using beta 1.2.0-beta.435

**Comment by bjornhellander** [comment]
On the other hand, the property is read-only after construction, so ignoring the init accessor might make sense. Somewhat similar to a property with a private setter:
```
/// <summary>
/// Gets xyz.
/// </summary>
public int Z { get; private set; }
```

Any other opinions on this?

**Comment by sharwell** [comment]
I lean towards documenting as either "Gets xyz" or "Gets or initializes xyz". SA1623 in its current implementation will accept both of these, except for `bool`-returning properties that validate the words following `Gets`.

**Comment by bjornhellander** [comment]
Leaving it as it is seems perfectly reasonable to me. Feel free to close this if you are sure.
