### ISSUE TITLE
Plan for next beta?

### ISSUE THREAD

**Issue by bjornhellander** [DotNetAnalyzers/StyleCopAnalyzers#3664]
Created a new issue based on https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3655#issuecomment-1573751070 by @jizc.
Do you have a clear picture of what changes you would like done before making a new beta release, @sharwell? Anything which currently do not have a pull request that you would like to see fixed first?

**Comment by sharwell** [comment]
Was able to get 1.2.0-beta.507 out this week 👍

**Comment by bjornhellander** [comment]
I saw. Excellent!
