### ISSUE TITLE
(accidental issue, delete this, thanks)

### ISSUE THREAD

**Issue by Emik03** [DotNetAnalyzers/StyleCopAnalyzers#3665]
The following code block causes the warning to show up, in Rider and from `dotnet build`.

```cs
public static void MinimalExample(string str)
{
    var layer = 0;
    layer += str[0] is 'a' ? 1 : 0;

    if (layer is 0)
        Console.WriteLine();
}
```

![image](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/assets/14614115/99611f35-cb89-4be0-8fc0-ab18473d4c0b)

**Comment by Emik03** [comment]
I don't know how but I submitted this on the wrong repository while having multiple tabs on projects. I'm sorry.

**Comment by sharwell** [comment]
Duplicate of dotnet/roslyn-analyzers#4712
