### ISSUE TITLE
Improve performance of SA1121

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#367]
The diagnostic for SA1121 included in #350 is *accurate*, but the performance could be improved. In particular, the semantic analysis to detect misleading or unexpected names due to using alias directives only needs to be enabled when a file actually has such a using alias directive. In real code, this is nearly non-existent so performance gains from bypassing the semantic analysis would certainly be a win.

**Comment by pdelvo** [comment]
Do you have any tests showing that there is actually a preformance problem? We have other diagnostics that require a semantic analysis so Roslyn is going to do it anyway even if we don't require it here. If Roslyn is doing the analysis once and we use it at more locations that should not be a big performance drain.

**Comment by sharwell** [comment]
I do not. I plan on running the profiler on larger projects after the work is complete to evaluate the overhead of the analyzers. I expect SA1100 will be (one of) the most important ones to work on, but I'm leaving this open to make sure and take a closer look at it.

**Comment by sharwell** [comment]
The call to `GetSymbolInfo` in `SA1121UseBuiltInTypeAlias.HandleIdentifierNameSyntax` was 9.1% of the analysis time for all analyzers during the investigation of #732. It is the 3<sup>rd</sup> "lowest hanging fruit".

**Comment by sharwell** [comment]
Fixed by #967.
