### ISSUE TITLE
SA1011 incorrectly triggers on list pattern with variable declaration

### ISSUE THREAD

**Issue by appel1** [DotNetAnalyzers/StyleCopAnalyzers#3673]
1.2.0-beta.507

```
case "Something" when t is [SomeType s]:
```

With the code above I get a SA1011 on for the end ] in the list pattern.

**Comment by bjornhellander** [comment]
Does it want a space **after** the closing square bracket?

Did this start happening when upgrading to the new release? Just curious if it broke in that release, or if it was broken before.

**Comment by appel1** [comment]
Yes, it wants a space after the closing square bracket. 

I tested with beta.435 and it behaves the same so not a new issue. 

Simpler case:
```csharp
    public static void Foo(object[] stuff)
    {
        switch (stuff)
        {
            case [string s]:
                break;
        }
    }
```

**Comment by bjornhellander** [comment]
Thanks for the update!
