### ISSUE TITLE
SA1009 says for (; ;) dotnet format says for (; ; )

### ISSUE THREAD

**Issue by virzak** [DotNetAnalyzers/StyleCopAnalyzers#3683]
That space before the closing bracket is the difference.

**Comment by sharwell** [comment]
The recommendation for this case is to use `while (true)`.

**Comment by sharwell** [comment]
Related issues:
#633
https://github.com/dotnet/roslyn/issues/35444

Closing as Won't Fix based on https://github.com/dotnet/roslyn/issues/35444#issuecomment-491861053.
