### ISSUE TITLE
Proposing new rule 'Remove unnecessary suppression' same as IDE0079

### ISSUE THREAD

**Issue by maettu-this** [DotNetAnalyzers/StyleCopAnalyzers#3685]
[IDE0079: Remove unnecessary suppression](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0079) works fine for `IDE....` rules, but not for other analyzers. Proposing to add a new `SA....` rule 'Remove unnecessary suppression'.

Motivation: Clean code, minimum of suppressions.

Such new rule could be considered too intrusive. Still, it could be added as "opt-in" rule, i.e. keep disabled by default at first and only later default to enbled once the new rule has been adopted by the majority of users.

**Comment by maettu-this** [comment]
@sharwell, as initially stated, `IDE0079` doesn't work for other analyzers including StyleCop. Try this piece of code with `IDE0079` enabled:
```
		#pragma warning disable SA1121 // Use built-in type alias.
		#pragma warning disable IDE0049 // Name can be simplified.
			float result = (Single)0.5f + (float)0.5f;
		#pragma warning restore IDE0049
		#pragma warning restore SA1121
```
![grafik](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/assets/24897735/a5672b98-d865-4efe-bffb-9bc055801b31)

As you can see, `IDE0049` is accepted as necesary, but `SA1121` isn't. @sharwell, please reconsider.

Using Visual Studio 17.6.4 with latest StyleCop 1.1.118 on a .NET 4.8 based project.

**Comment by sharwell** [comment]
> IDE0079 doesn't work for other analyzers including StyleCop

This is a bug in IDE0079 (it is expected to work for all analyzers and not just IDE ones).

> @sharwell, please reconsider.

As mentioned previously, the requested feature is not possible. You would need to file a feature request at [dotnet/roslyn](https://github.com/dotnet/roslyn) for this.

**Comment by maettu-this** [comment]
OK, got it. Then I look forward to see `IDE0079` fixed. Thanks.

**Comment by sharwell** [comment]
> Try this piece of code with IDE0079 enabled:

I tried this, and IDE0079 was not reported for either line. If I change `Single` to `float`, IDE0079 is reported for both lines.

Note that 1.1.118 is a very old version of StyleCop Analyzers. I would recommend upgrading to the latest beta.

**Comment by maettu-this** [comment]
> Note that 1.1.118 is a very old version of StyleCop Analyzers. I would recommend upgrading to the latest beta.

Well, https://github.com/DotNetAnalyzers/StyleCopAnalyzers lists 1.1.118 being [Latest] and my project doesn't include NuGet `prerelease` packages. But seeing the many 1.2.0-beta releases, I think this policy needs reconsideration. In any case, looking forward to a final 1.2.x release.

Thanks again for clarifying and all your work on StyleCop!
