### ISSUE TITLE
False positive SA1015 when using generic attribute 

### ISSUE THREAD

**Issue by genxs-trading** [DotNetAnalyzers/StyleCopAnalyzers#3686]
`[DescriptionFromXmlDoc<MyType>]`

Triggers **SA1015: Closing generic bracket should be followed by a space**.

**Comment by bjornhellander** [comment]
I can't reproduce this. Looks like a duplicate of #3487.

If you want to use newer language constructs, you need to use the beta versions, since 1.1.118 is old. See for example #3500 for an explanation of why.

**Comment by sharwell** [comment]
Duplicate of #3487
