### ISSUE TITLE
Fix remaining issues with SA1303

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#369]
Pull request #358 is working and contains a new extension method which is blocking several other pull requests. Therefore, I'm merging the pull request prior to the completion of certain "less important" details.

1. SA1303 needs to be enabled by default
2. The implementation currently uses `char.IsLower` to check the first letter. Should this be using `char.IsUpper` instead? Considerations include non-ASCII identifier characters as well as potential conflicts of `_` with [SA1309](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/85).

**Comment by macpak** [comment]
Correct me if I am wrong ([doc] (http://msdn.microsoft.com/en-us/library/aa664670%28VS.71%29.aspx) section identifier-start-character:), but c# identifiers can start with letters, @ and _. That's why I think isLower is ok. If we used isUpper, we'd report SA1303 for a field `public const string _Bar = "qwe";` but I think we don't want to do that :)

**Comment by sharwell** [comment]
The `@` for something like `@int` (or even `@SomeNonKeyword`) is not actually part of the name.

The first character of an identifier in C# but be a Unicode letter in the character class **Lu**, **Ll**, **Lt**, **Lm**, **Lo**, or **Nl**. The `char.IsLower` method returns true for characters in the **Ll** class. The `char.IsUpper` method returns true for characters in the **Lu** class. This means no warning is reported for identifiers where the first letter is the class **Lt**, **Lm**, **Lo** or **Nl**, even though the identifier does not start with an uppercase letter. One such character is SMALL ROMAN NUMERAL EIGHT (ⅷ).

**Comment by sharwell** [comment]
:question: Do you think we should just ignore those character classes? For example, some languages do not have upper case letters at all. Should this tool prevent them from starting an identifier with a character from their language?

**Comment by macpak** [comment]
Hmm, I am not sure how the analyzer should behave when a field starts with a Greek letter from Lt, can we even say if it's valid or not ?

**Comment by pdelvo** [comment]
I think using names with those chars should create a diagnostic. If you are going to work with people globally they will not only not understand your names but they will not even be able to write them. So I think we should not report anything here and add a diagnostic that prevents names which don't match ^[a-zA-Z0-9_]*$ as it is a common set of characters used in many languages. I would even prevent non-English names at all but this would be impossible to do as there are many domain specific names you wont find in a dictionary which would give you a lot of false positives

**Comment by macpak** [comment]
I agree with @pdelvo  that English should only be used, but I also know that there are projects which use local languages for names. 
My suggestion for SA1303 would be to report it if a name uses lower case letter. Using "_" at the beginning of the field should be reported by [SA1309](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/85)

**Comment by pdelvo** [comment]
Just because there are projects not doing is not a valid reason I think, StyleCop is about whats good, not whats common

**Comment by macpak** [comment]
Agree :)
Ok, so we need to decide how e want to handle this situation. I proposed my solution, what's yours?

**Comment by sharwell** [comment]
@macpak for SA1303 I think your points are quite reasonable. I would be OK with leaving diagnostics about non-English names for a different diagnostic. 

@pdelvo I'm not sure it makes since for adding a non-StyleCop rule here *right now*. After the base rules are implemented I think it would be useful to add configuration options to many of the rules so it can be configured in other ways for projects that use different styles but still want consistency.
