### ISSUE TITLE
SA1308 does not allow "t_" Prefix.

### ISSUE THREAD

**Issue by mgraf1** [DotNetAnalyzers/StyleCopAnalyzers#3695]
**Using Version**: StyleCop.Analyzers 1.2.0-beta.507

![image](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/assets/7501795/13f4ba2c-3242-42c0-938a-e9c273c26653)

I receive a warning for a thread static field with the prefix "t_". 

The [rule description](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1308.md) states the cause as "A field name in C# is prefixed with m_ or s_."

It seems there was a past issue for this: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/688. Perhaps this is a regression bug?

**Comment by bjornhellander** [comment]
The issue you refer to updated SA1308 to trigger on "t_", so this seems to be intentional. I assume you interpreted it the other way around.

**Comment by bjornhellander** [comment]
I created a pull request to update the documentation
