### ISSUE TITLE
SA1103: QueryClausesMustBeOnSeparateLinesOrAllOnOneLine

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#37]
http://www.stylecop.com/docs/SA1103.html

**Comment by macpak** [comment]
Comparing it to #36, what's the different between them ?

**Comment by pdelvo** [comment]
I think SA1105 allows
from x in y
select z;

But I think SA1103 eliminates the need for SA1105.

**Comment by sharwell** [comment]
@macpak Issue #36 is concerned with blank lines. This issue is concern with lines that are not blank.

@pdelvo There are some subtle issues that SA1105 (#39) highlights. For example, in the sample expression in the documentation for SA1105 you'll see that all the query keywords (`from`, `in`, `select`) appear on the same line. Since SA1105 is a narrower analysis situation, for any code that could trigger both SA1103 and SA1105, we should only report SA1105.

**Comment by macpak** [comment]
@sharwell so from the perspective of SA1102 this code is valid ?

       object x = from num in numbers
                       select num;

**Comment by sharwell** [comment]
@macpak That is correct. The following code on the other hand would produce both SA1102 and SA1103:

```
object x = from num in numbers

           select num;
```

**Comment by macpak** [comment]
Hmm, on the other hand, in my example, **from** and **select** are placed on different lnes, and select is located on the next line. So the only thing I can see is that **object x** is on the same line as **select**. However, it's a variable declaration so it's not a part of the query. So I actually don't see any problems with that example.

**Comment by vweijsters** [comment]
Grabbing this
