### ISSUE TITLE
SA1119 is too sensitive for Preprocessor directives in Dotnet Templates

### ISSUE THREAD

**Issue by EdLichtman** [DotNetAnalyzers/StyleCopAnalyzers#3716]
I'm trying to create dotnet templates, and finding that the SA1119 warning is popping up when I write:
#if (MyProperty)

However, encapsulating the properties within a paranthesis is required for dotnet preprocessor directives.

https://github.com/dotnet/templating/wiki/Conditional-processing-and-comment-syntax#json-files

**Comment by EdLichtman** [comment]
I've opened up another bug with IDE0047 for the same reason. 

Here's some code to reproduce.

https://github.com/EdLichtman/UniformPackagesDemo/tree/DemoIDE0047Error

Open up

Final_Demo/Templates/templates/Demo.PackageLibrary/Demo.PackageLibrary.sln

**Comment by bjornhellander** [comment]
@sharwell, the thing here (as I understand it) is that the template files are normal csproj and c# files, The template engine uses the extra parenthesis to differentiates preprocessor directives that control "template application" from preprocessor directives that will end up in the generated code. So when **editing the template**, SA1119 is triggered on those "template-level" directives. Do you agree with this description @EdLichtman?
