### ISSUE TITLE
SA1313: False positive for records

### ISSUE THREAD

**Issue by konrad-gora** [DotNetAnalyzers/StyleCopAnalyzers#3718]
I have some simple record.
`public record Node(Node? Left, Node? Right, int Value);`
StyleCop shows warnings for it SA1313 (ParameterNamesMustBeginWithLowerCaseLetter)
But in this case, these names are also property names. So they should be in upper case. I think there should be a warning in the opposite case (when they begin with lowercase)

**Comment by konrad-gora** [comment]
It is a duplicate of #3604

**Comment by sharwell** [comment]
Duplicate of #3181
