### ISSUE TITLE
SA1513 triggered on object initializer inside collection expression

### ISSUE THREAD

**Issue by jnyrup** [DotNetAnalyzers/StyleCopAnalyzers#3720]
Changing an array initializer containing an object initializer to using collection expression triggers SA1513.
Using  StyleCopAnalyzer 1.2.0-beta.507

```cs
public class MyClass
{
    public int Value { get; set; }

    public static MyClass[] Foo() => new[]
    {
        new MyClass
        {
            Value = 42
        }
    };

    public static MyClass[] Bar() =>
    [
        new MyClass
        {
            Value = 42
        } // <-- triggers SA1513
    ];
}
```

![image](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/assets/919634/1affb4a4-bf0c-4908-9b5e-c400dab6f276)

**Comment by bjornhellander** [comment]
Sorry for the delay!

There is currently no way of adding tests for c# 12 constructs in this repository, so this will have to wait for a while. It should be trivial to fix once that is in place, though.
