### ISSUE TITLE
New feature: Support for Inline-SQL with Verbatim String Literals as a Formatting Indicator

### ISSUE THREAD

**Issue by urmel9** [DotNetAnalyzers/StyleCopAnalyzers#3722]
### Background

Our team (and many other teams) use SQL queries in C# source code. We use verbatim string literals (prefixed with the `@` symbol) for writing inline SQL queries. Normally, we use StyleCop in order to ensure a standardized way of writing. 

Sadly, Inline-SQL isn't supported yet. This leads to the problem is that inline SQL queries are often hard to read and poorly formatted, leading to a negative code-quality. Some developers completely resist formatting their SQL-Code. 

### New feature we suggest

The formatter is able to mark inconvenient formatting and can autofix them. For example, could you use the verbatim string literal as an indicator and searching for SQL-Keywords in the string.

### Example

An example of using verbatim string literals for inline SQL in C#:

```csharp
string sqlQuery = @"select * from instances.productcosthistory PC JOIN instances.products P ON P.ProductId = PC.ProductId JOIN definitions.products PD ON PD.DefinitionId = P.DefinitionId WHERE PC.postedtimestamp > '2022-01-01'";

```csharp
string sqlQuery = @"SELECT * 
                    FROM instances.productcosthistory PC 
                    JOIN instances.products P 
                        ON P.ProductId = PC.ProductId
                    JOIN definitions.products PD
                        ON PD.DefinitionId = P.DefinitionId
                    WHERE PC.postedtimestamp > '2022-01-01'";

**Comment by sharwell** [comment]
I believe this would be better suited to a separate project, since only a small subset of StyleCop Analyzers users will be interested in using verbatim string literals for specific formatting of a different (non-C#) language.

**Comment by urmel9** [comment]
We are using inline SQL only in our C# projects and I know among other teams they do too.

Which independent project are you thinking about? :)

**Comment by sharwell** [comment]
StyleCop Analyzers has more than 100M downloads, so I would expect it is being used by many thousands of projects.

**Comment by urmel9** [comment]
Hello @sharwell ,
I still don't understand. I opened the issue here because _it is_ StyleCop for the .NET-Compiler.
So it's the correct project and will only affect C# -programmers who are using the .NET-Compiler.
Also, SQL is a very common language that is widely used.

Can you explain to me why it doesn't belong here and which other project would be the best one?

Also, I searched for another Plugin, but mostly they are deprecated nor are for VS 2022. So I decided to open an issue for Style Cop.

**Comment by sharwell** [comment]
C# programmers can use more than one set of C# analyzers at the same time. I would recommend creating a new (completely independent) project for this, and then installing _both_ that new project and StyleCop Analyzers in your projects for use.
