### ISSUE TITLE
SA1009 triggers when having the closing parenthesis on a single line

### ISSUE THREAD

**Issue by urmel9** [DotNetAnalyzers/StyleCopAnalyzers#3726]
SA1009 shouldn't trigger when the closing parenthesis is on a single line because in most cases it's intended. Also the rules is for cases like this: `cond2 )` not for a whole line - Even the autofix is firing.

After autofix:
![grafik](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/assets/67114570/20d5b861-06d0-4c5a-9cd7-972ce8686125)

This would be better:
![grafik](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/assets/67114570/bae85a71-4492-4623-b8d5-ee3a90675bd4)

**Comment by bjornhellander** [comment]
I don't see any StyleCop warnings on your original code when I try it. What version are you using?

**Comment by sharwell** [comment]
This is certainly the expected behavior of SA1009, as shown in #1206 and #2155. We have tests for it here:
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/1dd5ced072d7d870f6dd698a6c02ad509a122452/StyleCop.Analyzers/StyleCop.Analyzers.Test/SpacingRules/SA1009UnitTests.cs#L485-L515
