### ISSUE TITLE
StyleCop schema file URL is getting timed out

### ISSUE THREAD

**Issue by arunchandrapant** [DotNetAnalyzers/StyleCopAnalyzers#3727]
Following URL is getting timed out

https://raw.githubusercontent.com/DotNetAnalyzers/StyleCopAnalyzers/master/StyleCop.Analyzers/StyleCop.Analyzers/Settings/stylecop.schema.json

This URL is used in 'schema' property of 'stylecop.json' file.

Due to this issue, a warning is generated during project build.

![image](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/assets/38681653/1c3e3fc4-8aa4-47d9-9849-0848eb334e43)

![image](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/assets/38681653/3eab8786-028b-4f4d-a419-3f3f62a09b14)

![image](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/assets/38681653/54d969cb-f165-4e93-8466-0ea6e916b44d)

**Comment by sharwell** [comment]
> Following URL is getting timed out

This was a transient problem with GitHub, and not something specific with this project.

> Due to this issue, a warning is generated during project build.

The schema file is not used during a build. The warning is purely cosmetic by an editor, and not by the build.
