### ISSUE TITLE
SA1516 Elements should be separated by blank line - Razor Class Library - csproj file

### ISSUE THREAD

**Issue by roysurles** [DotNetAnalyzers/StyleCopAnalyzers#3738]
"SA1516 Elements should be separated by blank line" shows warnings for csproj file of a "Razor Class Library " project
<Project Sdk="Microsoft.NET.Sdk.Razor">

This does not occur for regular Blazor project or xUnit Test project.

Cannot find a way to suppress this warning for just the csproj file and/or prevent Stylecop from firig this warning against the csproj file in a "Razor Class Library " project

**Comment by bjornhellander** [comment]
I am having difficulty understanding what it is you want. Could you try to explain more what you experience and what it is you would like to achieve? Maybe post some screenshots and/or a link to a repo to show the problem?

**Comment by roysurles** [comment]
Please see screenshots below...
- Poolcorp.PointOfSale.csproj is a csproj file that is firing the SA1516 rule as Warning
- this is razor class library project --> <Project Sdk="Microsoft.NET.Sdk.Razor">
- This rule does not fire warning in our Blazor csproj file or our xUnit csproj file
- We have resolved this rule's warning in all places in c# code
- Is there a way we can suppress SA1516, just for the file:  Poolcorp.PointOfSale.csproj

![image](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/assets/37274814/6e9e2d3f-d954-4306-ad6c-e09b9deaf7db)

**Comment by bjornhellander** [comment]
These rules/anlyzers should only execute on what the compiler thinks is c# code, so they should **never** fire inside csproj files. Can you provide a link to a repository where this happens?

**Comment by bjornhellander** [comment]
One hypothesis could be that Visual Studio uses the project file name in the error list if SA1516 is reported without a location. Don't know why that would happen, though. If you rebuild and look in the output view, what does it look like when the warning is reported? Can you post a part of the output?

**Comment by bjornhellander** [comment]
Regarding suppressing it, if the diagnostic is reported without a location as I speculated above, then I don't think that you can suppress those warnings without turning off the entire rule in that project. This can be done in an .editorconfig file or a ruleset file, if you would like. But this behaviour is caused by something weird, so it would be good if we could find the root cause instead, so you don't have to turn it off.

**Comment by roysurles** [comment]
Yes, the 1.2.0-beta.507 "fixed" it.  I need to check with our architect if he will allow a beta package.

Do you have an ETA of an official release of this latest beta?

Thank you very much!

**Comment by bjornhellander** [comment]
Unfortunately not. See for example #3500 and https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3420#issuecomment-1058215862, but the general reasoning is that beta releases should not be a problem since this is only a development dependency.

**Comment by sharwell** [comment]
Duplicate of #3242
