### ISSUE TITLE
New Analyzer: Use File Scoped Namespaces

### ISSUE THREAD

**Issue by DavidMartynWood** [DotNetAnalyzers/StyleCopAnalyzers#3739]
I am considering the possibility of a new analyzer to enforce the usage of file scoped namespaces.

Is this something that StyleCop would consider accepting, or are there considerations which make such a rule not viable for inclusion in the project?

**Comment by sharwell** [comment]
This rule already exists as part of the built-in analyzers for the .NET SDK.

**Comment by DavidMartynWood** [comment]
So it is! Thanks Sam.
