### ISSUE TITLE
Remove ConfigureAwait(false) in tests?

### ISSUE THREAD

**Issue by bjornhellander** [DotNetAnalyzers/StyleCopAnalyzers#3742]
@martyix asked why we have ConfigureAwait(false) in the test projects: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/pull/3719#discussion_r1390220618

In later xUnit versions, there is an analyzer which warns about this due to potential parallelization issues (https://xunit.net/xunit.analyzers/rules/xUnit1030), so it seems to be a valid question.

**Comment by bjornhellander** [comment]
I found this which contained some background to xUnit1130: https://github.com/xunit/xunit/issues/2628

I kind of "hoped" that running too many tests in parallel could have a negative impact on execution time etc, but after benchmarking a bit on my laptop with and without ConfigureAwait I don't see any clear differences. Will try it on github for a while too, in case it behaves differently there.

**Comment by bjornhellander** [comment]
Ok, then I misunderstood the reasoning behind it. Thanks for clarifying! I am pretty sure there is no correctness issue related to it in this repository at this moment, but it seems like a good idea to follow their analyzers. A decision will need to be taken when xunit is updated, at the latest.

**Comment by sharwell** [comment]
We will likely have to disable xUnit1030, because there are many places in Roslyn where `ConfigureAwait(false)` is used and we don't have control over those.
