### ISSUE TITLE
SA1313 Allow underscore for primary constructors C# 12

### ISSUE THREAD

**Issue by madhusameena** [DotNetAnalyzers/StyleCopAnalyzers#3752]
```
public class DemoClass(IUnitOfWork _unitOfWork)
{
	//
}


```
  `DemoClass.cs(14, 81): [SA1313] Parameter '_unitOfWork' should begin with lower-case letter (https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1313.md)`
  
 Any way we can solve this ?

**Comment by cpriestland** [comment]
+1 Would like this, Have noticed that the linked issue is also closed? Having to define the injection as a separate backing field is not an acceptable solution and would mean that most people wouldn't use primary constructors.

**Comment by sharwell** [comment]
@cpriestland There is no action for this project to take at this time. There would need to be a new (altered) resolution for https://github.com/dotnet/roslyn/issues/68743 before any change would be made here.
