### ISSUE TITLE
SA1102 documentation should include a working C# snippet example

### ISSUE THREAD

**Issue by arphox** [DotNetAnalyzers/StyleCopAnalyzers#3754]
Hi!

I'm reading https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1102.md and I got confused while reading the code example for the rule. It does not seem compilable C# for me.

I created a fully working example, feel free to use it as you wish.
```cs
int[] c = { 1, 2, 3, 4, 5 };
int a = 2;

IEnumerable<int> query = from item in c
                         where item == a

                         select item;
```

**Comment by sharwell** [comment]
I'm not sure we need to include a complete example that compiles, but we should definitely fix the cases where `from` and `select` were reversed.
