### ISSUE TITLE
SA1010: Opening square brackets should not be preceded by a space conflicts with IDE0305

### ISSUE THREAD

**Issue by mggrand** [DotNetAnalyzers/StyleCopAnalyzers#3757]
With C# 12, new [Collection Expressions](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/collection-expressions) are introduced. This simplification is provided with the Stylefix [IDE0305](https://learn.microsoft.com/de-de/dotnet/fundamentals/code-analysis/style-rules/ide0305). When this is applied, it conflicts with the SA1010 analyzer.

**Comment by sharwell** [comment]
Duplicate of #3687
