### ISSUE TITLE
Unexpected SA1131

### ISSUE THREAD

**Issue by bjornhellander** [DotNetAnalyzers/StyleCopAnalyzers#3759]
I updated this repository to 1.2.0-beta.553 and got lots of unexpected SA1131.
Triggers for example on these cases:
`x + 1 < y`
`a() < y`

The common denominator seems to be that the left side or the operator is not just a variable, so this is probably a very common problem.

**Comment by bjornhellander** [comment]
Investigating...

**Comment by sharwell** [comment]
Likely caused by #3710

**Comment by bjornhellander** [comment]
Indeed it is. Sorry.

I pushed a fix. If you feel the slightest bit unsure about this, you could revert dfd5ed2e454d71a563dac50ca7bed57a37d31e9f instead.

**Comment by sharwell** [comment]
Were you planning to submit a PR here?

**Comment by bjornhellander** [comment]
Done now.
