### ISSUE TITLE
SA1009 and SA1024 cannot both be satisfied in case of a record with an interface

### ISSUE THREAD

**Issue by ahofland** [DotNetAnalyzers/StyleCopAnalyzers#3771]
SA1024: Colon should be preceded by a space
SA1009: Closing parenthesis should not be followed by a space.

Consider the following code:

public record struct MyRecord(string MyValue) : IInterface<MyType>
{ }

If I remove the space, I get SA1024. If I keep the space, I get SA1009. This does not seem intended. I expect to have a space in this particular instance.

**Comment by bjornhellander** [comment]
I cannot verify your case right now, but start by checking which version you are using.
Specifically, the latest official release (1.1.118) is too old for modern c# like record structs, so you need to use a later beta version to not get this kind of problem. This could be a new problem as well, but I suspect that you just need to change version.

**Comment by ahofland** [comment]
You are correct, I updated to a beta version and the problem resolved itself. Thank you!

**Comment by sharwell** [comment]
Duplicate of #3248
