### ISSUE TITLE
Alternative brace placement

### ISSUE THREAD

**Issue by bjornhellander** [DotNetAnalyzers/StyleCopAnalyzers#3776]
I have a client which uses this package but insists on a slightly different code style, so they disable some rules that does not fit their style. Specifically SA1500, since they want the braces on the same line. How would you feel about an alternative rule to instead enforce that style?

**Comment by sharwell** [comment]
No.

**Comment by sharwell** [comment]
I would recommend either the formatting analyzer from Roslyn for handling this case, or creating a new analyzer in a separate package. Braces on the same line is not a standard pattern for C# code and should be avoided the same way braces on a separate line should be avoided in Java or Go code.
