### ISSUE TITLE
How to distinguish between array access/indexer call

### ISSUE THREAD

**Issue by macpak** [DotNetAnalyzers/StyleCopAnalyzers#378]
For [SA1111] (http://stylecop.soyuz5.com/SA1111.html) I need to analyze an indexer call. Indexer call is represented by ElementAccessExpression. Unfortunately, ElementAccessExpression also represents an array access. Actually I can't find a way to distinguish between indexer call / array access. The only way I found is by checking if the type being accessed is array. However, it requires a lot of coding because there are many cases for that (like local variable access, field access, parameter access ...).
Maybe you know a better way to distinguish between array access / indexer call ?

**Comment by pdelvo** [comment]
Can't you just get the symbol info for for Expression of the ElementAccessExpression? This should give you the type of it

**Comment by macpak** [comment]
Yes, but you will have many type of symbols (depending on the context you are in, like method parameter, local variable, field, property etc) so you need to implement a kind of strategy to solve that. It's the second option I proposed and requires a lot of coding, that's why I created this issue to ask you if it can be done in a better/shorter way :)

**Comment by pdelvo** [comment]
If you call GetTypeInfo this should not matter

**Comment by macpak** [comment]
Thanks. I will test it.

**Comment by macpak** [comment]
Works fine.
Thank you very much :)
