### ISSUE TITLE
`SA1629` should ignore `<example>` since a trailing period is often not valid input.

### ISSUE THREAD

**Issue by EraYaN** [DotNetAnalyzers/StyleCopAnalyzers#3805]
When using the `<example>` element, `SA1629` fires when it does not contain a period.

it wants to turn this
```cs
/// <summary>
/// The date
/// </summary>
/// <example>2021-04-28</example>
public DateOnly? Date { get; set; }
```
into this
```cs
/// <summary>
/// The date
/// </summary>
/// <example>2021-04-28.</example>
public DateOnly? Date { get; set; }
```

Which is not correct since we do not actually want that period in the input.

**Comment by sharwell** [comment]
I believe this is a duplicate of #3804

**Comment by EraYaN** [comment]
Ooh it is, such a shame the GitHub search system didn't bring it up. Never mind this issue.
