### ISSUE TITLE
Rules contradicting C# naming conventions

### ISSUE THREAD

**Issue by urielginsburg** [DotNetAnalyzers/StyleCopAnalyzers#3806]
More than a few violations contradict official Microsoft recommendations and coding conventions and I was wondering why.

Few examples:

* SA1200 contradicts [Microsoft C# Coding Conventions](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#place-the-using-directives-outside-the-namespace-declaration)
* SA1309 contradicts [Microsoft C# Naming Conventions](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#place-the-using-directives-outside-the-namespace-declaration), specifically "Private instance fields start with an underscore (_)."
* SA1101 contradicts [.Net Runtime Coding Guidelines](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/coding-style.md), specifically "4. We avoid `this.` unless absolutely necessary".

And the list goes on...

**Comment by sharwell** [comment]
The StyleCop rules predate the pages you linked to. We try to avoid making changes to the default behavior of the rules so existing users don't experience large numbers of breaking changes during updates.

**Comment by urielginsburg** [comment]
@sharwell 
Understood. However, the opposite is also true - for example, when coding in C# I tend to follow Microsoft's guidelines. I added StyleCop to a solution with several projects and got 1000s of warnings, right off the bat. Perhaps it would be beneficial to add configuration "Presets"? The default one could stay the same as today and a "Microsoft-guidelines" preset would reflect the more recent guidelines? 
I would be happy to contribute.

cheers,
Uriel

**Comment by sharwell** [comment]
Note that the pages you listed above are specific to individual repositories (one being the samples for the documentation site). Another rule listed on the page for the documentation site is:

> Limit lines to 65 characters to enhance code readability on docs, especially on mobile screens.

We don't currently have one single set of rules that applies to all repositories. The **stylecop.json** file allows many items to be customized to fit different rules. It would be nice to futher consolidate SA1101/SX1101, and SA1309/SX1309/SX1309S by adding options, but we never ended up doing that.
