### ISSUE TITLE
SA1010 false positive when instantiating empty array

### ISSUE THREAD

**Issue by riley211** [DotNetAnalyzers/StyleCopAnalyzers#3821]
See screenshot. Removing the space then raises SA1003.

![image](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/assets/108871396/a79d51b3-9981-4443-abd2-8f88b9dfc851)

**Comment by bjornhellander** [comment]
This should go away if you switch to the latest beta.

**Comment by bjornhellander** [comment]
Duplicate of  #3687

**Comment by nolme** [comment]
We're nearly in 2025, is there a release coming soon ?
