### ISSUE TITLE
SA1010	Opening square brackets should not be preceded by a space

### ISSUE THREAD

**Issue by daleao** [DotNetAnalyzers/StyleCopAnalyzers#3824]
This rule doesn't make sense with collection initialization.
E.g. `int[] array = [1, 2, 3, 4];`

According to this rule, we should instead use
`int[] array =[1, 2, 3, 4];` or
`int[] array = { 1, 2, 3, 4 };`

**Comment by bjornhellander** [comment]
This should go away if you switch to the latest beta.

**Comment by bjornhellander** [comment]
Duplicate of #3687

**Comment by daleao** [comment]
I am using Latest prerelease 1.2.0-beta.435.

**Comment by bjornhellander** [comment]
1.2.0-beta.556 is the latest. It's fixed in that.
