### ISSUE TITLE
Add option to detect unused using

### ISSUE THREAD

**Issue by Sebastriani** [DotNetAnalyzers/StyleCopAnalyzers#3860]
It would be really nice, at least to me, if it were possible to detect the unused using directives, I'm tired of seeing lots of unused usings in the projects I work with and I would like to force the rule on the PRs...

**Comment by bjornhellander** [comment]
This is already built in to the compiler as diagnostic IDE0005, but is normally only reported while editing in Visual Studio.
It is possible to enable during builds as well: https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview?tabs=net-8#enable-on-build

**Comment by Sebastriani** [comment]
@bjornhellander Yes, I have that activated in the IDE but our proyects are in .NET Framwork, I can not active it on build.
Thanks anyway.

**Comment by sharwell** [comment]
@Sebastriani I've worked on numerous .NET Framework targeted projects that have IDE0005 activated on build. I don't understand your comment.

**Comment by Sebastriani** [comment]
@sharwell The section of the article that Bjorn mentioned says:
 _**"With the .NET 5 SDK and later versions, you can enable code-style analysis when building from the command-line and in Visual Studio"**_ 

 And before that, it reads:
 _**"Starting in .NET 5, you can enable code-style analysis on build, both at the command line and inside Visual Studio. Code style violations appear as warnings or errors with an "IDE" prefix. This enables you to enforce consistent code styles at build time."**_

Since we are using .NET Framework I didn't even bother to try what the article says. Why should I if the official documentation explicity says "starting in .NET5"? 

If it works for you in .NET Framework, then the documentation is wrong, I'll try.

**Comment by manfred-brands** [comment]
There is a difference between the TargetFramework and the SDK used to compile the code.

like @sharwell our product targets .net framework, but we use the .NET 8 SDK to compile it. The latter allows us to use newer C# language features.

**Comment by sharwell** [comment]
@Sebastriani both of those cases are supposed to read ".NET 5 SDK". There is no limit I'm aware of regarding the target framework of the project itself.

**Comment by Sebastriani** [comment]
@manfred-brands @sharwell I didn't know about the SDK being the responsable for compiling or that Rosylin was part of the SDK, I know nothing about Rosylin actually other than it's the compiler... I'll get it working then, thanks.
