### ISSUE TITLE
NullReferenceException in SA1112 ClosingParenthesisMustBeOnLineOfOpeningParenthesis

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#389]
Currently SA1112 is throwing exceptions for `ObjectCreationExpressionSyntax` when the `ArgumentList` property returns `null`. The following field declaration should reproduce this situation:

```csharp
Dictionary<int, int> cache = new Dictionary<int, int> { { 3, 3 } };
```

**Comment by sharwell** [comment]
@macpak I assigned this to you since you implemented the initial diagnostic.

**Comment by macpak** [comment]
Allright, I reproduced the problem.
