### ISSUE TITLE
SA1024 conflicting with SA1003 when using primary constructors

### ISSUE THREAD

**Issue by natashalysakova** [DotNetAnalyzers/StyleCopAnalyzers#3901]
When using class declaration with primary constructor and interface (or base class) like this 
```
public class MyClass(int value) : ITest { }
```
I getting SA1009 A closing parenthesis within a C# statement is not spaced correctly.

But If I change to
```
public class MyClass(int value): ITest { }
``` 
I getting SA1024 A colon within a C# element is not spaced correctly.

I think, in this case SA1009 should not be applied at all.

**Comment by bjornhellander** [comment]
Looks like a duplicate of #3248. Are you using the latest beta?

**Comment by natashalysakova** [comment]
You are right, this is the same. I'am not using beta, I',m on 1.1.118.
