### ISSUE TITLE
SA1001 conflicts with SA1008 for tuples in case

### ISSUE THREAD

**Issue by LinAGKar** [DotNetAnalyzers/StyleCopAnalyzers#3903]
```C#
switch ((1, 2), (3, 4))
{
    case ((1, 2), (3, 4)):
        break;
}
```

Keeping the space after the second comma in the case triggers SA1008, and removing the case triggers SA1001.

**Comment by bjornhellander** [comment]
Version?

**Comment by LinAGKar** [comment]
Sorry, the project was using an old version, it's fixed in the latest one
