### ISSUE TITLE
Analyzer Settings

### ISSUE THREAD

**Issue by pdelvo** [DotNetAnalyzers/StyleCopAnalyzers#410]
Any thoughts on how we are going to implement rules that require configuration like [SA1636](http://www.stylecop.com/docs/SA1636.html)?

**Comment by sharwell** [comment]
Not a clue :grinning: 

Actually that's a lie. I plan on using the [`AdditionalFiles`](http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalyzerOptions.cs,7197d586b9314062,references) property to feed the necessary configuration files into the analyzer.

**Comment by sharwell** [comment]
As mentioned in #422, we can use a **.targets** file to automatically locate the configuration file and add it as an additional file for the analyzers.
