### ISSUE TITLE
SA1642 (constructor summary text) special case for structures

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#418]
Currently SA1642 always enforces the use of the word "class" in the documentation for constructors. Should the constructors for a `struct` type "prefer" the use of another word here, in the same sense as #413 handled the wording for private constructors?

**Comment by AArnott** [comment]
Yes. "struct' should be the last word of the mandatory leading text for structure constructors.

**Comment by sharwell** [comment]
@AArnott I guess the other question is should it be 'struct' or 'structure'?

**Comment by AArnott** [comment]
struct.
My answers are based on the behavior of the original StyleCop. I have several very large codebases that are migrating from stylecop to stylecop.analyzers, and I'd love for it to go smoothly.
Also, I've noticed that a lot of the text StyleCop rules require to appear in xml doc comments to match MSDN docs, which I think has value to preserve as well.

**Comment by sharwell** [comment]
> I have several very large codebases that are migrating from stylecop to stylecop.analyzers

BTW, just saw this part. That's pretty cool! :dancers:
