### ISSUE TITLE
CI System

### ISSUE THREAD

**Issue by pdelvo** [DotNetAnalyzers/StyleCopAnalyzers#419]
What do you think about adding a CI system for building the master branch and/or pull requests?

**Comment by sharwell** [comment]
I'm not opposed to it. The project is [already configured for AppVeyor](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/f5d7e316b309b4cf50c43c7a90cc3135c67cb3c8/StyleCop.Analyzers/StyleCop.Analyzers.Vsix/StyleCop.Analyzers.Vsix.csproj#L27-L30).

**Comment by pdelvo** [comment]
I do have a server we could use.

**Comment by sharwell** [comment]
Here we go:

[![Build status](https://ci.appveyor.com/api/projects/status/8jw2lq431kgg44jl/branch/master?svg=true)](https://ci.appveyor.com/project/sharwell/stylecopanalyzers/branch/master)

Just need to update the readme to include that.

**Comment by sharwell** [comment]
And now it's actually [configured to build with Visual Studio 2015 CTP 5](http://www.appveyor.com/blog/2015/01/20/visual-studio-2015-ctp-image).

**Comment by sharwell** [comment]
1. Need to set OS to Visual Studio 2015 CTP
2. Need to set install script to:

   > set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

3. Need to set before build script to:

   > nuget restore

4<sup>th</sup> times' the charm?

**Comment by sharwell** [comment]
:smiley:

**Comment by pdelvo** [comment]
:dancer: What do you think about building PR's? I think this would be very usefull to see if the author forgot to enable the diagnostic by default, so that tests fail when you compile in Release config. But I also have some security concerns. Because running unit tests is part of the build someone can possibly run millicious code in it by just creating a PR. So maybe a whitelist system would be a good idea like the one used in corefx

**Comment by sharwell** [comment]
It should already be configured to build pull requests.

You can read more about the [Build Environment](http://www.appveyor.com/docs/build-configuration) on AppVeyor's support page.

**Comment by sharwell** [comment]
All that's left is a pull request to add the following at an appropriate location in the readme:

```
[![Build status](https://ci.appveyor.com/api/projects/status/8jw2lq431kgg44jl/branch/master?svg=true)](https://ci.appveyor.com/project/sharwell/stylecopanalyzers/branch/master)
```
