### ISSUE TITLE
SA1108: BlockStatementsMustNotContainEmbeddedComments

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#42]
http://www.stylecop.com/docs/SA1108.html

**Comment by macpak** [comment]
grabbed

**Comment by macpak** [comment]
Ok, one thing to discuss. Originally, this diagnostic is not reported for declarations (method, class, namespace etc). So this code is valid (tested on stylecop 4.7.49.0):
 
       public class IndexTests
    //aa
    {
        public int Prop
        //aa
        {
            get
            //bb
            {
                return 0;
            }

            set
            //cc
            {
                
            }
        }
      }

I think we need to decide whether we are going to follow StyleCop understanding of this diagnostic or we are going to extend it, so declarations are also included.

**Comment by sharwell** [comment]
For this I suggest implementing it the way it's written, and following the pattern of #536 for the extension.
