### ISSUE TITLE
build.ps1 does not return correct error code

### ISSUE THREAD

**Issue by pdelvo** [DotNetAnalyzers/StyleCopAnalyzers#421]
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/build/build.ps1#L48

If Im not mistaken it should return `$LASTEXITCODE` instead. Where is `$p` defined at?

**Comment by sharwell** [comment]
You are correct. It should actually look something like this:

```powershell
If (-not $?) {
	echo 'Failed to build Solution.sln, aborting!'
	exit $LASTEXITCODE
}
```

**Comment by sharwell** [comment]
Reopening since this is still not fixed here :snail:
