### ISSUE TITLE
Code fix: SA1303 (ConstFieldNamesMustBeginWithUpperCaseLetter)

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#432]
Implement a code fix for #79.

**Comment by macpak** [comment]
grabbed

**Comment by sharwell** [comment]
Someone's going to town with the `Renamer` :+1:

**Comment by macpak** [comment]
For SAs "*WithUpperCaseLetter" I can use codefix from #429 :)

**Comment by pdelvo** [comment]
If @macpak is okay with it im grabbing this
