### ISSUE TITLE
SA1110: OpeningParenthesisMustBeOnDeclarationLine

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#44]
http://www.stylecop.com/docs/SA1110.html

**Comment by macpak** [comment]
grabbed

**Comment by macpak** [comment]
I am wondering about this diagnostic. Maybe you can help.
Let's consider an example:

    class Program
    {
        private List<int> items;

        static void Main(string[] args)
        {
        }

        public string JoinName(string first, string last)
        {
            return JoinStrings(
                first, last);
        }

        private string JoinStrings(string first, string last)
        {
            return first + last;
        }

        public int this[int x]
        {
            get 
            { 
                return this.items
                [x]; 
            }
        }
    }

According to the description of this diagnostic, we should report SA1110 violation on the line:
    
    return this.items
                [x]; 

However, Stylecop doesn't report this.
Moreover, if I test a method:
        
        public int TestIndexer()
        {
            return this
                [0];
        }

Stylecop reports SA1110 on indexer call.
So I am not sure whether this is a bug or description is incorrect/misleading.

**Comment by HowardvanRooijen** [comment]
Not a direct response to you question - but a wider question about the project? Have you thought about migrating the existing tests (or at lease test examples) from the stylecop project?

**Comment by macpak** [comment]
Good point! 
I think it'd be very valuable.

**Comment by HowardvanRooijen** [comment]
I spent a huge amount of time building StyleCop for ReSharper, before StyleCop was OSS'd - I wish I had access to the tests. Figuring out how to test that a quick fix alters the code structure and testing it against a "gold" image was the approach I used - so essentially you have a before and after snapshot of the code. I'm not sure with VS if the dev team have figured out a better approach for testing this API - but that certainly worked for me.

**Comment by sharwell** [comment]
@macpak In your example, SA1110 should be reported regardless of where the call appears (you showed cases within a property accessor and a method body, but other locations are possible as well).

**Comment by macpak** [comment]
Of course, but my question is different.
One of the violations of SA1110 is when an open bracket of indexer call is not placed at the same line as the indexer. My example contains code:

    return this.items
            [x];

where the open bracket is not placed at the same line as indexer call. However, in my opinion it seems that in this example, we actually don't see "the indexer" because indexer call is a simple usage of brackets. So maybe, SA1110 should only be reported for incorrect indexer declarations or incorrect indexer calls that use "this" like:

      public int TestIndexer()
        {
            return this
                [0];
        }

I am trying to find if it's possible to write code, that (for example) calls List<T>'s indexer in a way that violates SA1110.

**Comment by sharwell** [comment]
I'm not sure I understand what you are asking. Can you reword the above comment into one or more specific questions?

**Comment by macpak** [comment]
Sure.
Let me ask this way: can you find a violation of SA1110 when calling an indexer of List<T> ?

**Comment by sharwell** [comment]
The `List<T>` indexer is no different than any other indexer. If `items` is a field in the current class and has type `List<int>`, then the following should result in SA1110:

    return this.items
      [0];

**Comment by macpak** [comment]
So please test it using Stylecop. I did the test and I didn't get SA1110.

**Comment by sharwell** [comment]
For better or worse, I haven't been cross-testing any of these rules against the reference StyleCop implementation. :stuck_out_tongue_winking_eye:

I'm open to suggestions regarding the behavior of this diagnostic for the cases you mentioned, though my instinct is to implement the intuitive behavior regardless of what StyleCop does here.

**Comment by macpak** [comment]
Hehe, yeah, I think we should report SA1110 here, so we have consistent behavior.
