### ISSUE TITLE
Figure out how to test custom fix all providers

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#452]
This issue is currently affecting #450 and work being done separately by @giggio.

**Comment by giggio** [comment]
It is working now. Checkout the testing infrastructure on CodeCracker:
https://github.com/code-cracker/code-cracker/blob/f28ec4c16982cd2db3485cb65f56f27d770d2730/test/CSharp/CodeCracker.Test/Verifiers/CodeFixVerifier.cs#L132-L222
And related files.

I got Document and Project fix all changes to work, I did not go into Solution as it is mostly foreach on the projects, as far as I noticed.

**Comment by sharwell** [comment]
Fixed in #1126.
