### ISSUE TITLE
Make sure code fixes are properly exported

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#480]
The `ExportCodeFixProvider` for a code fix provider `T` should always use `nameof(T)` for the name. There are several cases in the current code where this is not the case.

**Comment by macpak** [comment]
Will fix it.

**Comment by sharwell** [comment]
Tempting to create an analyzer specifically for this project to catch these things early.

**Comment by macpak** [comment]
Just wondering if we can have "an internal analyzer" ?? ;)

**Comment by pdelvo** [comment]
The StyleCopAnalyzers analyzers analyzer
