### ISSUE TITLE
Update dependencies to 1.0.0rc1

### ISSUE THREAD

**Issue by pdelvo** [DotNetAnalyzers/StyleCopAnalyzers#487]
Im currently updating roslyn to 1.0.0rc1. Has a bunch of api changes

**Comment by sharwell** [comment]
Does this work with CTP 5? Or is this a preparation item for the next release?

**Comment by pdelvo** [comment]
It does not work in CTP 5. So this is preparation. After fixing all the api changes I am left with some weird broken unit tests because of syntax node actions not being called.

**Comment by sharwell** [comment]
Fixed in #488
