### ISSUE TITLE
Code fix: SA1212 (PropertyAccessorsMustFollowOrder)

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#495]
Implement a code fix for #72.

**Comment by macpak** [comment]
grabbed

**Comment by macpak** [comment]
Just thinking about one case. Let's say we have code like the one below:

    public string Prop
    {
        set
        {
               myField = value;
        }

        get
        {
             return "";
        }
    }

If we swap get with set, and take leading/trailing trivias, the empty line between get and set will be taken with get. which will result in code similar to:

    public string Prop
    {

        get
        {
             return "";
        }
        set
        {
               myField = value;
        }
    }

which in my opinion introduces incorrect code formatting. 
So the fix provider should be intelligent and catch a situation where set starts with a new line trivia, take this trivia and add it to get.
