### ISSUE TITLE
Duplicated diagnostic in SA1102 test

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#506]
The test `SA1102UnitTests.TestQueryInsideQuery` is reporting a duplicate diagnostic.

This was expected to be resolved in the recent update to CTP 6. It is not yet determined whether this is a bug in the analyzer implementation or in the reporting.

**Comment by macpak** [comment]
I am the author of the diagnostic, so if @pdelvo doesn't have anything againts, I can look at it.

**Comment by pdelvo** [comment]
Go ahead ;)
