### ISSUE TITLE
Problems with Roslyn reference ?

### ISSUE THREAD

**Issue by macpak** [DotNetAnalyzers/StyleCopAnalyzers#511]
Hi,

Looking at the build (for instance at my pull request #510), we can see that we get a bunch of warnings like: 

*CSC : warning CS8032: An instance of analyzer StyleCop.Analyzers.OrderingRules.SA1215InstanceReadonlyElementsMustAppearBeforeInstanceNonReadonlyElements cannot be created from C:\projects\stylecopanalyzers\packages\StyleCop.Analyzers.1.0.0-alpha004\tools\analyzers\StyleCop.Analyzers.dll : Could not find file 'C:\projects\stylecopanalyzers\packages\Microsoft.CodeAnalysis.Analyzers.1.0.0-rc1\tools\analyzers\System.Collections.Immutable.dll'..*

Any idea what's going on ?

**Comment by sharwell** [comment]
It's because we're building the code with an older version of Roslyn (CTP 5), which has an older version of System.Collections.Immutable loaded in the app domain.

**Comment by sharwell** [comment]
AppVeyor supports CTP 6 now. Feel free to send a pull request changing the `os` line in **appveyor.yml**:

```
os: Visual Studio 2015 CTP 6
```

**Comment by macpak** [comment]
The pull request solves the problem described here.
