### ISSUE TITLE
Switch to XUnit and clean up test infrastructure

### ISSUE THREAD

**Issue by pdelvo** [DotNetAnalyzers/StyleCopAnalyzers#515]
I think switching our unit tests to XUnit would be a good idea. What annoys me the most is the execution time of the tests. It might not take that long, but they definitly take longer than neccesary. All our tests could run in parallel, but MSTest does not support that, XUnit does. Other than that you need to have visual studio installed to use mstest. So we would drop that requirement.

Other than that I think our test system could use a clean up. We use "CodeFixVerifier" in places where we dont have a code fix, we have methods to test vb code still in there. I personally really like the way Code cracker has its test. They are using generics to specify the analyzer and the code fix provider. So they are on top of the test class and they can be easily spotted.

**Comment by sharwell** [comment]
> I think switching our unit tests to XUnit would be a good idea.

You could have left out the rest and still get a :+1:

**Comment by sharwell** [comment]
Rather than tackle this all at once, I recommend you break this into a sequence of smaller steps, each of which can be evaluated individually and applied in sequence without breaking the build/tests.

**Comment by sharwell** [comment]
I think this is generally done.
