### ISSUE TITLE
SA1118: ParameterMustNotSpanMultipleLines

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#52]
http://www.stylecop.com/docs/SA1118.html

**Comment by macpak** [comment]
grabbed

**Comment by macpak** [comment]
Just wondering, why the first parameter can span more than one line ? For me that code like:

    Foo(1
         +2
         +3
         +5
         +6
         +7,
          8)

is as unreadable as 

    Foo(1
        +2
        +3,
         2
         +3
         +4
         +5)

but the first one is ok in terms of SA1118.

**Comment by Przemyslaw-W** [comment]
Probably to cover scenario where method call has exactly one argument. It
can span as many lines as needed. No idea why this exception was made also
for multi arguments call. It's in SC from the day 1, so maybe it comes from
MS. Wild guess - MS teams would have too much to fix when they started
using SC.

2015-04-28 13:59 GMT+02:00 Maciej Pakulski <notifications@github.com>:

**Comment by macpak** [comment]
Ok.
Another case, this code doesn't generate SA1118 (tested using old StyleCop):

    class Program
    {
        static void Main(string[] args)
        {
            var p = new Program();
            var i = p[0,
                2 +
                3];
        }

        public int this[int i, int j]
        {
            get { return 0; }
        }
    }

I guess SA1118 should be reported for the second parameter.

**Comment by Przemyslaw-W** [comment]
yes, imho it's bug

2015-04-28 16:31 GMT+02:00 Maciej Pakulski <notifications@github.com>:
