### ISSUE TITLE
Discussion: Disable SA1101 or IDE0003 for the project.

### ISSUE THREAD

**Issue by vweijsters** [DotNetAnalyzers/StyleCopAnalyzers#530]
There is a clash between SA1101 and IDE0003, where either one is suggesting to 'fix the code', thereby triggering the other one. I think we should disable one of them, in order to no longer have the highlighting and offered code fixes all the time.

My personal preference would be to disable SA1101, as I think it offers no benefit for anything but fields. 

I created this issue to hear your opinions on it.

**Comment by sharwell** [comment]
What is IDE0003?

**Comment by sharwell** [comment]
SA1101 is a "hallmark" StyleCop rule. Personally I would disable it in almost any project where StyleCop is used, but for *this* project we should enable all rules supported by the analyzer.

I submitted a pull request to disable IDE0003 when working on just this project in the IDE. Prior to investigating from this issue, I wasn't aware disabling this feature of the IDE for a particular project would be so easy.
