### ISSUE TITLE
Avoid placeholders in documentation

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#536]
I would like to propose the implementation and inclusion of a new StyleCop diagnostic.

**Category:** Documentation
**Rule:** Do not use placeholder elements
**Description:** See openstacknetsdk/OpenStackNetAnalyzers#10 (which even includes screenshots)

**Rationale:** Since the implementation of #534 involves inserting a "best guess" regarding the `<value>` text for a property, I would like to wrap the generated text in a `<placeholder></placeholder>` element for the user to review. As shown in the issue linked above, a new diagnostic which reports a warning for these elements encourages users to actively review the text which was inserted for the properties. Without this diagnostic, a code fix which automatically inserts documentation text has a high likelihood of producing incorrect results which are not easily recognized or corrected.

**Comment by grokys** [comment]
:+1:

**Comment by sharwell** [comment]
Welcome to the project @grokys :dancers:
