### ISSUE TITLE
Quick Fix not working on empty lines

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#544]
During some testing today, I noticed that the code fix for removing extra lines at the end of the file (SA1518) does not work with the <kbd>Ctrl</kbd>+<kbd>.</kbd> shortcut when the caret is placed on an empty line. The only way to use the code fix appears to be using the mouse to hover over the warning and click "Show potential fixes".

**Comment by vweijsters** [comment]
I have been trying a lot of things and it seems that Visual Studio has an issue with offering quick actions on empty lines. If I add even a single space to an empty line, the quick action is triggered properly. 
Don't really know how to pursue this further :confused:

**Comment by sharwell** [comment]
@vweijsters I recommend filing a bug on the Roslyn project. :+1:

**Comment by vweijsters** [comment]
Filed an issue with the Roslyn project (dotnet/roslyn#1353)

**Comment by vweijsters** [comment]
The code fix for SA1507 is also affected by this.

**Comment by pdelvo** [comment]
This was just fixed in Roslyn.

**Comment by sharwell** [comment]
:+1:

**Comment by pdelvo** [comment]
I think this issue can be closed
