### ISSUE TITLE
Analyzers will report in auto generated files

### ISSUE THREAD

**Issue by pdelvo** [DotNetAnalyzers/StyleCopAnalyzers#555]
As far as I know the only way to exclude them is to use something like [this](https://github.com/code-cracker/code-cracker/blob/08c1a01337964924eeed12be8b14c8ce8ec6b626/src/Common/CodeCracker.Common/Extensions/GeneratedCodeAnalysisExtensions.cs).

**Comment by sharwell** [comment]
StyleCop has other ways of excluding files from analysis too, which we should consider supporting.

**Comment by AArnott** [comment]
Is this an expensive work item to complete? It blocks adoption for our projects.

**Comment by AArnott** [comment]
I'm working on a pull request for this.

**Comment by sharwell** [comment]
:+1: Looking forward to it @AArnott :smile:
