### ISSUE TITLE
Reporting location for SA1516

### ISSUE THREAD

**Issue by vweijsters** [DotNetAnalyzers/StyleCopAnalyzers#562]
Opened this to continue the discussion started in #561.

We are deviating from the reference implementation with respect to reporting location for SA1516.
My opinion is that the position reported by StyleCop is the more intuitive one, as it reports to location where something is missing. Reporting it at the element location leads me to believe that something is wrong with the element itself, instead of just the layout around it.

**Comment by sharwell** [comment]
I vote for placing it on the first non-whitespace (or newline) token following the location where the new line needs to be inserted.

**Comment by pdelvo** [comment]
![location](https://cloud.githubusercontent.com/assets/1710209/6869417/1c12a866-d494-11e4-9d14-f5c4bc0e33e8.PNG)
I didnt like that the squiggles are so small, but I guess Im outvoted. Im going to create a PR to change that

**Comment by sharwell** [comment]
@pdelvo My vote for that image is placing it on the word "internal".

Even if you go with the whitespace, what about the *entire* leading whitespace instead of just the first character?

**Comment by pdelvo** [comment]
What about this:

If the node has leading trivia, put the diagnostic at the first leading trivia. If not put the diagnostic at the first token.
This would look like this:

![location2](https://cloud.githubusercontent.com/assets/1710209/6869885/87fdc5b6-d498-11e4-9a5c-ba845119fb03.PNG)

**Comment by sharwell** [comment]
:+1: :sparkles:

**Comment by vweijsters** [comment]
That looks very good :+1:
