### ISSUE TITLE
Tests dont verify location if the actual location is at line start

### ISSUE THREAD

**Issue by pdelvo** [DotNetAnalyzers/StyleCopAnalyzers#567]
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/c26d390a4f0963f279d06d5079d7448cfe8d92ee/StyleCop.Analyzers/StyleCop.Analyzers.Test/Verifiers/DiagnosticVerifier.cs#L210
Line start is at character = 0, so we got an off by one error here. The same thing aplies for line = 0

**Comment by pdelvo** [comment]
We have 3 unit tests that are broken but werent detected because of this.

**Comment by sharwell** [comment]
Very nice catch; assigning to you.

Consider reporting this to the Roslyn project so they can update their templates.

**Comment by pdelvo** [comment]
Thanks. Will do.
