### ISSUE TITLE
Code fix: SA1201 (ElementsMustAppearInTheCorrectOrder)

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#573]
Implement a code fix for #61.

My initial recommendation is a stable lexicographical sorting algorithm.

It may further be possible to implement a single code fix that corrects #61, #62, #63, #64, #67, #74, and #75. See code-cracker/code-cracker#76 for more information.

**Comment by Noryoko** [comment]
Grabbing this. I'm thinking we can modify the code fix added in #1167 to make a single code fix for all the element ordering rules. SA1201, SA1202, SA1204, and SA1215 would be added to the existing code fix.
