### ISSUE TITLE
Accessible readonly fields are reported twice

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#574]
Currently an externally-accessible `readonly` fields is reported as both SA1304 and SA1307. In this case, only SA1307 should be reported (see #557 for more information).

I'm marking this as enhancement instead of bug because the reference implementation of StyleCop reports both warnings for this case. We are only reporting one to simplify the presentation and code fix for users.

**Comment by pdelvo** [comment]
Im working on this

**Comment by vweijsters** [comment]
@pdelvo Have a look at #861 and use the same mechanism when disabling part of SA1304 please.
