### ISSUE TITLE
SA1306 Unit tests are missing some cases

### ISSUE THREAD

**Issue by vweijsters** [DotNetAnalyzers/StyleCopAnalyzers#592]
(text copied from remarks made in #586)

I expected to see `public const`, `public readonly`, and `protected internal` test for `TestThatDiagnosticIsNotReported` as well, or am I missing something?

I'm missing test cases for static fields, which should never trigger this diagnostic according to StyleCop documentation.

**Comment by Noryoko** [comment]
Grabbing this.
