### ISSUE TITLE
SA1513 (ClosingCurlyBracketMustBeFollowedByBlankLine) not reported when followed by `break`

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#599]
The current implementation of the SA1513 diagnostic (#596) does not report a diagnostic when the line after a closing brace is a `break;` statement. I don't consider this case special enough to warrant a deviation from the documented behavior of the rule.

**Comment by vweijsters** [comment]
Fair point, I'll fix it. 

I guess you've found out by now that it is one of the major annoyances of the original StyleCop for me :smile:
