### ISSUE TITLE
"Alternative" rules

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#600]
This proposal is based on two things:

1. StyleCop is "opinionated", and not all teams share those opinions
2. The Rule Set Editor does not currently support custom configurations for a rule - they are either enabled or disabled

I propose allowing variants of certain rules to be added with identifiers starting with **SX**, which offer a different interpretation for the same situation. For example, a rule **SX1309** could be implemented which *requires* an underscore prefix for private, non-constant, instance fields. **SX** rules would always be disabled by default due to a fundamental conflict with existing **SA** rules.

This would allow for the adoption of this project in a wider variety of existing projects.

The following table shows rules which I believe are the primary initial targets of this:

| Rule | "SA" Behavior | "SX" Behavior |
| --- | --- | --- |
| 1101 | Always prefix locals calls with `this.` | Prefix local calls with `this.` only when necessary for disambiguation |
| 1121 | Use built-in type alias | Use framework name when accessing static members¹ |
| 1309 | Never prefix fields with `_` | Prefix private non-`const` instance fields with `_`² |

¹ An extended rule to cover *all* references would be a separate SX rule.
² An extended rule to cover other fields would be a separate SX rule.

**Comment by AArnott** [comment]
You're absolutely right. I have written some of my own alternative rules for the original StyleCop myself. Having an "off by default" set of alternative rules sounds great. I think in some cases there will be more than just one alternative, so if SX is the alternative rules' prefix, will it start from 1000 and not require a one-to-one mapping to the "standard" rule?

**Comment by sharwell** [comment]
I was planning to keep the 1-1 mapping so it's easy for users to go from "no I want the opposite" to "oh, yes that's what I want". Perhaps a suffix could be added if more than one alternative makes sense.

**Comment by AArnott** [comment]
I think most of the time there's an opposite, ya. And that would certainly improve discoverability. I think in corefx they have more complex rules for fields, involving static and threadlocal fields too. Enforcing those rules probably should be separate from the underscore rule.
