### ISSUE TITLE
Place text in paragraphs

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#601]
I would like to propose the implementation and inclusion of a new StyleCop diagnostic.

**Category:** Documentation
**Rule:** Place text in paragraphs
**Description:** Text within certain documentation elements should be placed within `<para>` tags. This includes all blocks of text within a `<remarks>` or `<note>` element.

**Rationale:** This rule ensures these elements appear consistently when rendered to a variety of output media, including HTML.

**Comment by AArnott** [comment]
I like this rule, so long as it doesn't require `<remarks>` with only a single paragraph to be surrounded in `<para>` tags.

**Comment by sharwell** [comment]
It does. The `<remarks>` element is the most frequently included element (using `inheritdoc`) which is then extended to include additional content. Placing even a single paragraph in these tags ensures consistent formatting across the board.

Keep in mind a code fix is already implemented that can wrap every single-paragraph `<remarks>` element in `<para>` tags across the solution with no effort from the developer, and these can be used at any time. Users will not be required to type the tags, and the barrier to adoption is minimized.

**Comment by sharwell** [comment]
@DotNetAnalyzers/members This rule really helps ensure consistent formatting when using tools like Sandcastle Help File Builder to publish documentation, and manually checking for these cases is tiresome. Since the rule includes a code fix that can correct existing violations, I believe it would be a great help to developers if we could include it.

**Comment by AArnott** [comment]
> The  <remarks>  element is the most frequently included element (using  inheritdoc ) which is then extended to include additional content. Placing even a single paragraph in these tags ensures consistent formatting across the board.

I've never seen `<inheritdoc />` used in combination with any other docs. How does that look? 

That might be the compelling reason. But as I've never seen it so far, I'm still leaning toward not wanting this rule since adding `<para>` tags to a single paragraph (even a few word sentence) of a doc section hurts readability where it matters most (in the code). Document formatting tools should be able to do whatever is necessary when tags are missing from a single paragraph. Adding `<para>` when multiple paragraphs are in use makes sense though.

**Comment by Noryoko** [comment]
:+1:

**Comment by sharwell** [comment]
@AArnott It would make sense to update the output formatting to automatically wrap inline text into paragraphs, without having to make them explicit in code. I use this rule because the tools currently do *not* behave this way, and far more people are consuming the published documentation than are looking at the source code. Most other documentation markup languages do require inline content be explicitly placed in a block-level element, so technical writers and such would already be used to seeing the additional structure.

For the reference, `<inheritdoc/>` with augmentation works like the following.

> :memo: I haven't needed to do this.

```csharp
public interface ISomeType
{
  /// <summary>Summary</summary>
  /// <remarks>
  /// <para>Additional commentary.</para>
  /// </remarks>
  void Method();
}

public abstract class SomeType
{
  /// <inheritdoc/>
  /// <remarks>
  /// <inheritdoc/>
  /// <note type="implement">
  /// <para>When implementing this method, some special consideration...</para>
  /// </note>
  /// </remarks>
  public abstract void Method() { }
}

public class SpecializedType
{
  /// <inheritdoc/>
  /// <remarks>
  /// <!-- Include everything except for the note to implementers. -->
  /// <inheritdoc select="*[not(self::note and @type='implement')]"/>
  /// </remarks>
  public abstract void Method() { }
}
```

**Comment by sharwell** [comment]
@AArnott  What about marking this rule as disabled by default? The rule is intended to help with producing high-quality final output; teams that aren't running the XML files through a tool like Sandcastle wouldn't need to be so particular about use of paragraph tags for elements that only contain a single paragraph. But for teams that do render their documentation, the rule is a huge help.

**Comment by AArnott** [comment]
Sure. Disabled would be fine. In fact, "hidden" would also be fine. I asked the Roslyn team a while back what the difference between disabled and hidden was, and they said "hidden" was for non-warnings where code fixes can be useful. It sounds like just what you're aiming at.

That's pretty neat stuff what `<inheritdoc>` can do. I had no idea. Where is this documented?

**Comment by otac0n** [comment]
I'm actually :-1: in having this rule in the main StyleCop.Analyzers.  Perhaps Sandcastle.Analyzers, but I don't think the majority of developers would benefit from this rule.

**Comment by sharwell** [comment]
I'm going to move this to a new project.
