### ISSUE TITLE
SA1201 Exception for EventFieldDeclarationSyntax

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#611]
I get a `KeyNotFoundException` when evaluating the parameters for a call to `ReportDiagnostic` when `members[i].Kind()` or `members[i + 1].Kind()` is `EventFieldDeclaration`.

**Comment by pdelvo** [comment]
StyleCops documentation doesnt include information about where event fields should be placed. The easiest way to fix that is to give event fields a fixed place in a class (maybe after regular fields?). Or should I tread them as if they are fields?

**Comment by sharwell** [comment]
They are just events.
