### ISSUE TITLE
Consider testing complete diagnostic span instead of just start

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#625]
The purpose of this is preventing regressions on issues like #618.

Currently the test framework does not support this, and we would need it to be relatively straightforward. I'm thinking an interesting possibility would be a `.WithSingleTokenSpan()` method for `DiagnosticResult` (expanding on #526).

**Comment by vweijsters** [comment]
The more generic `.WithSpan(startLine, startColumn, endLine, endColumn)` would also be nice for diagnostics covering more than 1 token.
