### ISSUE TITLE
Code Fixes For Naming Rules SA1308 and SA1309 Do Not Always Fix The Name Entirely

### ISSUE THREAD

**Issue by johnkoerner** [DotNetAnalyzers/StyleCopAnalyzers#627]
If a violation contains multiple prefixes, then only the first prefix is fixed, which would result in the user having to run the fix multiple times to fix the violation.  

Example:

    private static string __x = string.Empty;

This code violates SA1309 and the current fix results in a single underscore being removed from the variable name:

    private static string _x = string.Empty;

This new code still violates SA1309 and applying another fix will remove the final underscore and the final result will be no violations.

The same type of issue occurs with SA1308 if the user prefixes a variable with `m_m_` or `s_s_` (or any permutations.)

I think for these cases we should attempt to get the variable name into a known good state such that there are no violations for that particular rule after the code fix is applied.

**Comment by johnkoerner** [comment]
Note, when trying to test the running the fix multiple times, be aware that depending on what version of roslyn you are running, you may encounter an error if you do not close the rename dialog.

This issue is tracked on the Roslyn repo: https://github.com/dotnet/roslyn/issues/554

**Comment by sharwell** [comment]
Did you want to work on this?

**Comment by johnkoerner** [comment]
Yes, I will take this.
