### ISSUE TITLE
Using Static directives must be ordered alphabetically

### ISSUE THREAD

**Issue by vweijsters** [DotNetAnalyzers/StyleCopAnalyzers#652]
I would like to propose a new diagnostic that covers a new language feature of C# 6:

**Category:** Ordering
**Rule:** Using Static directives must be ordered alphabetically
**Description:** A violation of this rule occurs when `using static` directives are not sorted alphabetically by the fully qualifier class name. Sorting the `using static` directives alphabetically can make the code cleaner and easier to read, and can help make it easier to identify the namespaces that are being used by the code.

**Rationale:** This proposed rule is an extension in line with rules SA1210 and SA1211 to cover a new language feature in C# 6

**Comment by Przemyslaw-W** [comment]
Also would be nice to order using groups respectively: first "regular"
usings, then usings which introduce aliases, and new using static last

2015-04-09 20:42 GMT+02:00 Vincent Weijsters <notifications@github.com>:

**Comment by AArnott** [comment]
#653 talks about the grouping. Within the grouping, sorting sounds like a good idea.

**Comment by sharwell** [comment]
I agree on this as well. It's obviously non-breaking since it's a new language feature.

**Comment by vweijsters** [comment]
Grabbing this one for implementation
