### ISSUE TITLE
Using static directives must be placed after other using directives

### ISSUE THREAD

**Issue by vweijsters** [DotNetAnalyzers/StyleCopAnalyzers#653]
I would like to propose a new diagnostic that covers a new language feature of C# 6:

**Category:** Ordering
**Rule:** Using static directives must be placed after other using directives
**Description:** A violation of this rule occurs when a `using static` directive is placed before a normal or an alias using directive. Placing the `using static` directives together below all other using-directives can make the code cleaner and easier to read, and can help make it easier to identify the static members used throughout the code.

**Rationale:** This proposed rule is an extension in line with rules SA1208 and SA1209 to cover a new language feature in C# 6. My proposal is to put the `using static` directives after the existing using directives in order to have minimal disturbance to patterns that developers are used to.

**Comment by AArnott** [comment]
:+1: This seems consistent with where the C# language service adds them too, so it passes the "IDE default behavior" test.

**Comment by sharwell** [comment]
I agree on this as well. It's obviously non-breaking since it's a new language feature.

**Comment by vweijsters** [comment]
Grabbing this one for implementation
