### ISSUE TITLE
SA1207: ProtectedMustComeBeforeInternal

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#67]
http://www.stylecop.com/docs/SA1207.html

**Comment by EdwinEngelen** [comment]
grabbed

**Comment by EdwinEngelen** [comment]
Analyzer and tests seem to be ready. If possible, I want a review on Monday or Tuesday. But I first need to figure out how to do it without merging all the way up.

**Comment by sharwell** [comment]
@EdwinEngelen don't worry about merging; most of the time I can deal with merging after your work is complete. Just push your branch to your fork at its current location and we can review it there.

**Comment by EdwinEngelen** [comment]
The analyzer is ready for review at my fork. The code fix is still to be implemented.

**Comment by sharwell** [comment]
@EdwinEngelen Can you send a pull request? That is where we do the review. :smile:

**Comment by EdwinEngelen** [comment]
You said "Just push your branch to your fork at its current location and we can review it there.". But no problem, I'll send the pull request.

**Comment by sharwell** [comment]
@EdwinEngelen Sometimes it's hard for me to see the difference in wording because I've done it so many times. The pull request flags a specific branch in your fork as ready for review, and also does the following:

* Triggers an automated build and test cycle
* Creates a place where we can add comments
* Allows us to merge your changes into the code base when it is complete
