### ISSUE TITLE
SA1013 (ClosingCurlyBracketsMustBeSpacedCorrectly) reported at end of file

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#685]
Currently SA1013 is reported on the last `}` of a file, if it is not followed by a trailing newline.

This is not correct. *If* we report a diagnostic at this location, it should be SA1513.

**Comment by AArnott** [comment]
More generally than end of file, the rule docs provides several exceptions:

> A closing curly bracket should always be followed by a single space, unless it is the last character on the line, or unless it is followed by a closing parenthesis, a comma, or a semicolon.

I would also add a period as one of the punctuations that are allowed to immediately follow, to allow for such syntax as:

    return new[] { new object() }.GetEnumerator();

**Comment by sharwell** [comment]
@AArnott That is actually issue #687, which has not yet reached a consensus regarding the expected behavior.
