### ISSUE TITLE
SA1513 (ClosingCurlyBracketMustBeFollowedByBlankLine) is not reported on the last character of a file

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#686]
Currently SA1513 is not reported if the last character of the file is a `}`, and the file does not end with a trailing newline. I believe one of the following actions should be taken, especially considering the fact that cross-platform considerations dictate that including the trailing newline is a best practice.

1. Report SA1513 at this location.
2. Create a new diagnostic to report at this location.

My preference would probably be to go with the first option, and possibly split the rule in the future.

**Comment by vweijsters** [comment]
I don't think that it is logical to report SA1513 here, as SA1513 is all about having an blank lines after closing curly brackets, something which should not happen at the end of the file as it will then trigger SA1518.

I would like to add a third option:
3. Do not report any diagnostic when a closing curly bracket is the last character of a file.

I really see no benefit in reporting a diagnostic for not having a newline after the last closing curly bracket. It will not improve readability, in fact you have to explicitly move the cursor there to see if it is present all. My preference would therefore be the third option.

**Comment by sharwell** [comment]
Option 3 would also be supported in Option 2, (by disabling the new diagnostic).

**Comment by vweijsters** [comment]
Fair point, that would change my preference to option 2.

**Comment by sharwell** [comment]
This was addressed by #1800.
