### ISSUE TITLE
Consider updating SA1308 (VariableNamesMustNotBePrefixed) to handle 't_'

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#688]
Currently the prefix `t_` (used by some projects for thread-local variables) is not treated as a "special prefix" for rule SA1308. It is instead reported as SA1310 (FieldNamesMustNotContainUnderscore). I believe we should update rule SA1308 to handle this special case in addition to its current treatment of `m_` and `s_`.

**Comment by vweijsters** [comment]
I agree, `t_` should trigger SA1308, not SA1310.
