### ISSUE TITLE
SA1509 (OpeningCurlyBracketsMustNotBePrecededByBlankLine) reported for consecutive blocks

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#689]
Currently SA1509 is reported for the following code. If the space is removed, SA1513 (ClosingCurlyBracketMustBeFollowedByBlankLine) is reported.

```csharp
{
    var target = new int[s_manyElements.Length];
    s_manyElements.CopyTo(target);
    Assert.Equal(target, s_manyElements);
}

{
    var target = new int[0];
    Assert.Throws<NullReferenceException>(() => s_emptyDefault.CopyTo(target));
}
```

:question: What is the expected behavior in this situation?

**Comment by Przemyslaw-W** [comment]
Original SC special cased this - blank line was required

**Comment by sharwell** [comment]
Oh good. :+1: I think it makes sense for us to do the same.

**Comment by macpak** [comment]
So to sum up, if you have consecutive blocks, original SC requires a blank line between the blocks, so in @sharwell's example SA1509 should not be reported. However, if I have code like (two blank lines)

    {
        var target = new int[s_manyElements.Length];
       s_manyElements.CopyTo(target);
       Assert.Equal(target, s_manyElements);
    }
    

    {
        var target = new int[0];
        Assert.Throws<NullReferenceException>(() => s_emptyDefault.CopyTo(target));
    } 

the SA1509 should be reported ?

**Comment by sharwell** [comment]
@macpak In that case SA1507 (CodeMustNotContainMultipleBlankLinesInARow) would be reported.

**Comment by macpak** [comment]
Allright, so is there a situation where SA1509 is reported for  consecutive blocks? Of we can assume that SA1509 is not checked for blocks (I mean the blocks which are not connected to for/foreach etc)  at all. Because this code is valid as well (from SA1509 point of view):

    var s = 2;
     
    {
         //inside block
    }

    for(var i=0; i < 5; i++)
    {
         //inside for
    }

    {
         //inside block 2
    }

**Comment by sharwell** [comment]
It sounds like we need to disable SA1509 when:

* The `{` is part of a `BlockSyntax` (call this one *child*)
* The parent of a `BlockSyntax` is another `BlockSyntax` (call this one *parent*)
* *child* is not the first child of *parent*

**Comment by Przemyslaw-W** [comment]
Modulo open bracket leading trivia:

```
    {
      // comment

      {
      }
    }
```

should report SA1509 and SA1512

**Comment by sharwell** [comment]
@Przemyslaw-W In that case we would only report SA1512, which means the rules I included in the preceding comment would still work.

**Comment by Przemyslaw-W** [comment]
What about case when user disables one of them - here SA1512? StyleCop used to report all issues to target such use case

**Comment by sharwell** [comment]
> What about case when user disables one of them - here SA1512? StyleCop used to report all issues to target such use case

Probably a good item to create a new issue for. Ideally we will eventually suppress diagnostics using conditionals (i.e. suppress SA1509 only if SA1512 is disabled). But for now I wouldn't worry about it. The key for this particular issue is the conditions I listed above are particularly easy to detect.
