### ISSUE TITLE
SA1504 (AllAccessorsMustBeSingleLineOrMultiLine) should always be reported on the single-line accessor

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#690]
Currently SA1504 is always reported on the *second* accessor, which results in the bizarre behavior shown in dotnet/roslyn#2199. This analyzer should be updated to report the diagnostic on whichever accessor is the single-line accessor, even if it appears first. This change in behavior will simplify the implementation of the quick fix, because the quick fix behavior will need to change the single-line accessor to be multi-line.

**Comment by macpak** [comment]
grabbed ;)
