### ISSUE TITLE
SA1513 and SA1516 reported for the same situation

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#692]
Currently the following code produces SA1513 after the closing `}` of the `get` accessor, and `SA1516` on the whitespace preceding the `set` keyword.

```csharp
get
{
    var self = this;
    self.ThrowInvalidOperationIfNotInitialized();
    return self[index];
}
set { throw new NotSupportedException(); }
```

If you press <kbd>Ctrl</kbd>+<kbd>.</kbd> on the line containing `set`, you get two code fix proposals (one for SA1513 and one for SA1516) which have exactly the same result. One of these two diagnostics should be suppressed in this situation, and my initial suggestion is for only SA1516 to be reported.

**Comment by vweijsters** [comment]
Seems logical to only report SA1516 as that is the more specific diagnostic.

Assign this one to me please, I'll work on a change for SA1513.
