### ISSUE TITLE
SA1405 (DebugAssertMustProvideMessageText) exception for user-defined Debug.Assert

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#705]
If the user defines their own `Debug.Assert` method as follows, and then calls it with one argument, an `ArgumentOutOfRangeException` is thrown. This is caused by an assumption in `SystemDiagnosticsDebugDiagnosticBase.HandleMethodCall` that `symbolInfo.Parameters.Length` equals `invocationExpressionSyntax.ArgumentList.Arguments.Count`.

```csharp
namespace System.Diagnostics
{
    internal static class Debug
    {
        public static void Assert(bool condition, string message = null)
        {
        }
    }

    internal static class ClassName
    {
        public void Method()
        {
            Debug.Assert(false);
        }
    }
}
```

:memo: This [actually happened](https://github.com/dotnet/roslyn/blob/master/src/ExpressionEvaluator/Core/Source/ResultProvider/SystemHelpers.cs#L5-L18).

**Comment by pdelvo** [comment]
grabbed
