### ISSUE TITLE
Cannot install alpha005

### ISSUE THREAD

**Issue by AArnott** [DotNetAnalyzers/StyleCopAnalyzers#713]
I can install alpha004 into my class library just fine. But updating to alpha005, or installing it fresh, always yields this error:

> update-package : Missing dependency information for package: StyleCop.Analyzers
At line:1 char:1
+ update-package StyleCop.Analyzers -version 1.0.0-alpha005
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
 
I'm using a prerelease of VS2015. Is anyone else seeing this? Is there perhaps a flaw in the StyleCop.Analyzers nuspec file?

**Comment by sharwell** [comment]
What package source are you using? I'm using **nuget.org**, and not **api.nuget.org**.

**Comment by AArnott** [comment]
I'm using api.nuget.org

**Comment by AArnott** [comment]
Interestingly, it started working after I manually removed alpha004 by removing all traces of it from the project file and packages.config file myself. Hmm.. not sure what to make of it.

**Comment by sharwell** [comment]
Weird. Should we assume it's a bug in NuGet that will work itself out?

Also you still have a message from me in Gitter. :wink:

**Comment by AArnott** [comment]
Quite possibly. I'll file a bug over at http://github.com/nuget/home

I'll visit gitter.

**Comment by pdelvo** [comment]
Can this issue be closed @AArnott?

**Comment by sharwell** [comment]
I'm going to assume it's been fixed since this is the only report, and all relevant components (NuGet, Visual Studio, and this project) have received numerous improvements since.
