### ISSUE TITLE
SA1205 (PartialElementsMustDeclareAccess) underlines entire partial class instead of just the 1-line declaration

### ISSUE THREAD

**Issue by AArnott** [DotNetAnalyzers/StyleCopAnalyzers#714]
Give a very large class that is missing an access modifier, this rule squiggles the entire class definition (methods, bodies, everything).

```csharp
partial class Foo
{
}
```

It should only squiggle the first line, or just part of the first line.

**Comment by sharwell** [comment]
In your example, it should underline only `Foo`.

**Comment by sharwell** [comment]
@vweijsters Do you want to take this one?

**Comment by vweijsters** [comment]
Yup, I'll grab this one

**Comment by vweijsters** [comment]
Having #625 would really help for testing this
