### ISSUE TITLE
New rule proposal: Use braces consistently

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#716]
This rule is an intentional subset of the behavior of SA1503 (CurlyBracketsMustNotBeOmitted) targeting the behavior used by me in my own projects and now adopted by CoreFX.

**Category:** Layout
**Rule:** Use braces consistently
**Description:** For a sequence of `if`/`else if`/`else` control flow statements, if any element of the sequence includes curly braces for the block, then *all* elements of the sequence should include curly braces. Note that `else if` is a special case here - if `else` is immediately followed by `if`, then the `else` does not need braces.

**Comment by vweijsters** [comment]
:+1: its nice to give people a bit more flexibility with regards to curly braces.

**Comment by Przemyslaw-W** [comment]
+1

2015-05-20 17:32 GMT+02:00 Vincent Weijsters <notifications@github.com>:
