### ISSUE TITLE
SA1509 misfires due to #pragma line

### ISSUE THREAD

**Issue by AArnott** [DotNetAnalyzers/StyleCopAnalyzers#725]
After suppressing SA1302, SA1509 started complaining about a supposed blank line preceding the opening curly bracket. There isn't a blank line. And the #pragma's are where the auto-fix put them. So this should Just Work.

```csharp
#pragma warning disable SA1302 // Interface names must begin with I
    public interface ActiveConfiguredProject<out T>
#pragma warning restore SA1302 // Interface names must begin with I
    {
        /// <summary>
        /// Gets the ConfiguredProject exported value.
        /// </summary>
        T Value { get; }
    }
```

**Comment by sharwell** [comment]
As a workaround you should be able to move the `{` inside the `#pragma` block.

**Comment by AArnott** [comment]
Yes, that works.
