### ISSUE TITLE
SA1101 batch autofix fixed 2 out of 3 errors on 1 line

### ISSUE THREAD

**Issue by AArnott** [DotNetAnalyzers/StyleCopAnalyzers#727]
In the following sample, `tokenizer` is an instance field. As part of a large project-wide autofix from SA1101, the following method was updated, but only 2 out of 3 references to the field were updated with the `this.` prefix

```diff
    private bool Top()
    {
        var r = this.OrTerm();
-        Requires.Argument(tokenizer.Peek() == null, CapabilityExpressionParameterName, UtilityStrings.InvalidCapabilityExpressionWithPosition, tokenizer.Input.Length, tokenizer.Input);
+        Requires.Argument(this.tokenizer.Peek() == null, CapabilityExpressionParameterName, UtilityStrings.InvalidCapabilityExpressionWithPosition, this.tokenizer.Input.Length, tokenizer.Input);
        return r;
    }
```

**Comment by sharwell** [comment]
This is still the batch fixer merge algorithm causing us problems. We're going to be seeing them until we either write our own `FixAllProvider` (and somehow manage to do it better??), or a more reliable algorithm is implemented in Roslyn.

**Comment by mavasani** [comment]
@AArnott Do you have a small repro case?

**Comment by AArnott** [comment]
@mavasani Yes. [Here you go](https://onedrive.live.com/redir?resid=63d0c265f96e43d%212468080)

**Comment by mavasani** [comment]
Thanks, this should be fixed with https://github.com/dotnet/roslyn/pull/2286

**Comment by sharwell** [comment]
This is now fixed.
