### ISSUE TITLE
SA1110 mis-fires for generic methods

### ISSUE THREAD

**Issue by AArnott** [DotNetAnalyzers/StyleCopAnalyzers#728]
The SA1110 fires claiming that the opening parenthesis must be on the declaration line, referring to the very first line in the sample below.

```csharp
return new ExportLifetimeContext<object>(
    tcs.Task, // can be anything really.
    () => tcs.TrySetResult(null));
```

Obviously, it *is* on the declaration line.

**Comment by sharwell** [comment]
@macpak Would you like this one?

**Comment by macpak** [comment]
Yes.

**Comment by tommymonk** [comment]
I'm seeing this issue occur in 1.0.0-beta002 with the generic call in this example;

```cs
int productId = _client.Cypher
                       .Match("p: Product")
                       .Return<int>("p.Id")
                       .Results
                       .SingleOrDefault();

**Comment by sharwell** [comment]
@tommymonk Thanks for taking the time to follow up on this issue. Do you mind opening a new issue with your example?

**Comment by tommymonk** [comment]
Thanks, See: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/1079
