### ISSUE TITLE
Rule proposal: NoSpacesBeforeTabs

### ISSUE THREAD

**Issue by AArnott** [DotNetAnalyzers/StyleCopAnalyzers#731]
As found [here](https://github.com/AArnott/nerdbank.stylecop.rules/blob/master/src/NerdBank.StyleCop.Rules/NerdBankRules.cs) and described [here](http://blog.nerdbank.net/2008/09/notrailingwhitespace-stylecop-rule-and.html).

Sometimes when one person is using tabs with size 4 and another has size 3 tabs, extra spaces can make formatted code look wrong.  This rule just makes sure you don't have a tab, a space, and another tab or something strange like that. 

The NoSpacesBeforeTabs rule is about preventing this:

```csharp
<SPACE><TAB>int foo;
<TAB>string bar;
```

This is visibly equivalent so long as the leading spaces are fewer than the width of a tab. But it's noise that Format Document would clean up and therefore a StyleCop rule keeps the noise down and the indentation at its simplest form. 

This issue tracks porting the rule from the legacy StyleCop style implementation to StyleCop.Analyzers. You may assign it to me.

**Comment by sharwell** [comment]
I'm going to vote against this one, at least for now. This rule would only apply to users that disable both SA1027 (use spaces) and SX1027 (use tabs). If a team doesn't feel strongly one way or the other regarding tabs, I'm not sure this rule would provide much benefit for them either.

**Comment by vweijsters** [comment]
I'm undecided yet. It would very much depend on the implementation of SX1027 to see if it is useful at all. If SX1027 would accept `<tab><tab><space><space>`, which is a sequence generated by Visual Studio when having tab size 3 and indentation size 4, then this rule would make sense.

**Comment by AArnott** [comment]
@sharwell I wonder if you're misunderstanding the use case here. It *is* for use in combination with SX1027. Consider the following code, and imagine tab width + indent are set to 5 characters for sake of conveniently making these characters "visible" in the below snippet:

```csharp
<TAB>var foobar = select a
<TAB><TAB><TAB>   from source;
```

This is roughly what VS would do by default when using tabs. It uses as many tabs as possible to intend the second line then falls back to spaces for the remainder of the indent in order for the LINQ query to line up with the previous line. While this looks good with tabs set to 5 characters wide it will *not* look good when the IDE on another user's machine is configured for 3 characters:

```csharp
TABvar foobar = select a
TABTABTAB   from source;
```

This of course is one of the chief arguments against using tabs. But this is a fault of the language service's use of mixed tabs and spaces rather than a fundamental flaw with tabs. If instead the original characters were:

```csharp
<TAB>var foobar = select a
<TAB>             from source;
```

Then again when 5 column tabs are changed to 3 column, the appearance is still good:

```csharp
TABvar foobar = select a
TAB             from source;
```

This proposed rule is to enforce and preserve the optimal combination of tabs and spaces so that it looks good at any tab width.

I actually had convinced the Roslyn team to fix their default behavior for indentation to produce the correct combination of tabs and spaces since they were writing it from scratch, although I haven't confirmed whether they do it or not this close to RTM.

**Comment by vweijsters** [comment]
That's a really nice explanation. I'm changing my vote to :+1:

**Comment by sharwell** [comment]
Why would we not just say this *is* SX1027?

**Comment by AArnott** [comment]
Hmm.... You know I think I just explained a different rule. "NoSpacesBeforeTabs" doesn't seem to fit my scenarios since there are never any spaces before tabs. Sorry. The NoSpacesBeforeTabs rule is about preventing this:

```csharp
<SPACE><TAB>int foo;
<TAB>string bar;
```

This is visibly equivalent so long as the leading spaces are fewer than the width of a tab. But it's noise that Format Document would clean up and therefore a StyleCop rule keeps the noise down and the indentation at its simplest form. 

I shouldn't have gotten these two confused. Sorry for that. 

As for whether my earlier representation about proper indentation with various tab widths should be merged into SX1027, we could. Since it helps make tab use better that makes sense to me. I'll copy my earlier comments into the spec for SX1027 and we'll consider that the NoSpacesBeforeTabs proposal is just the simple one I described just now. Sound good?

**Comment by AArnott** [comment]
Ya, my discussion about changing tab widths is my [OneTabIndent rule](https://github.com/AArnott/nerdbank.stylecop.rules/blob/master/src/NerdBank.StyleCop.Rules/NerdBankRules.cs#L39).

**Comment by AArnott** [comment]
OK. I've updated this issue's description to keep it focused on the original proposal and updated #730 with the description from my earlier comment

**Comment by sharwell** [comment]
> Sound good?

Sure. But now I'm back to not understanding why we would need this rule. The case you described is mixed indentation, and both SA1027 and SX1027 would report it as such.

**Comment by AArnott** [comment]
As long as they do report it as such, sure. We can close this. It might be interesting to add tests for each one to confirm.

**Comment by sharwell** [comment]
Remember if we ever find out that this isn't working out for some users, we can always revisit the issue :smile:

**Comment by sharwell** [comment]
Verified that we are testing this case in SA1027: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers.Test/SpacingRules/SA1027UnitTests.cs#L76
