### ISSUE TITLE
IDE very sluggish with StyleCop.Analyzers on a large solution

### ISSUE THREAD

**Issue by AArnott** [DotNetAnalyzers/StyleCopAnalyzers#732]
In migrating a large 400K+ line solution to StyleCop.Analyzers, the IDE feels quite sluggish. Most text changes can hang the IDE for several seconds. We should take ETL traces of the process and find out which rules are contributing to this and what can be done to make them much more efficient.

**Comment by AArnott** [comment]
I've filed a bug against Roslyn based on an ETL trace I took that suggests most of the problem lies with them. 
But among StyleCop.Analyzer offenders, the worst was this frame, which was responsible for about 6% of the time during the 20+ second delay.

    StyleCop.Analyzers!StyleCop.Analyzers.AnalyzerExtensions+<>c__DisplayClass1_0`1[Microsoft.CodeAnalysis.CSharp.SyntaxKind].<RegisterSyntaxNodeActionHonorExclusions>b__0(value class Microsoft.CodeAnalysis.Diagnostics.SyntaxNodeAnalysisContext)

I'll follow up with Roslyn and also study the trace to see if we can make our own HonorExclusions extension method any faster.

**Comment by sharwell** [comment]
I'm not seeing that behavior in my installation. To test, I opened **RoslynLight.sln** (which I assume is a reasonably big project) and started making changes to it manually typing in code from pull requests. During the test run, the IDE remained responsive.

That said, among the StyleCopAnalyzers rules, the following are the biggest culprits:

* SA1405 (15.45%)
* SA1513 (14.04%)
* SA1121 (9.10%)
* SA1001 (4.30%)
* SA1406 (3.60%)

**Comment by AArnott** [comment]
I restarted my IDE and now I'm not seeing it either. I suspect there's a 'leak' somewhere, perhaps of event handlers or analyzer registrations, such that over time it gets progressively worse. I've seen plenty of these in my time dogfooding roslyn.

Do our SA analyzers register and fail to deregister somewhere?

**Comment by sharwell** [comment]
There's a deregister?

**Comment by AArnott** [comment]
I don't know. But given the perf degradation I saw over time, we should look for one.

**Comment by sharwell** [comment]
The biggest issues I saw have now been addressed separately.
