### ISSUE TITLE
Rewrite SA1513ClosingCurlyBracketMustBeFollowedByBlankLine.IsOnSameLineAsOpeningBrace for performance

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#734]
The line to `currentToken = currentToken.GetPreviousToken();` in this method is currently responsible for over 12% of the overall cost of running the currently available StyleCopAnalyzers analyzers. This issue was found while investigating #732.

**Comment by vweijsters** [comment]
Grabbing this one
