### ISSUE TITLE
SA1516 should require a line before attributes

### ISSUE THREAD

**Issue by Przemyslaw-W** [DotNetAnalyzers/StyleCopAnalyzers#737]
If attribute is added to type or member, there should be blank line enforced above it, unless 
* there is another attribute or xml doc comment in the line above
* element decorated with attribute is first element of its parent (e.g. first member in the type, or first type in a namespace)
* attribute is added inline - e.g. attributes added for parameters should not trigger this rule

Rationale - currently SC enforces blank line before element if there are no attributes and xml doc comments at all. It also enforces blank line above xml doc comment. Attributes feel like missing piece in the whole puzzle

**Comment by vweijsters** [comment]
:+1: Good suggestion, I think we should treat attributes the same as the other stuff indeed.

**Comment by sharwell** [comment]
This is a bug in SA1516.

**Comment by Przemyslaw-W** [comment]
IMHO it would be strange to fix it within SA1516 scope, since xml doc comments do have separate dedicated rule - SA1514
