### ISSUE TITLE
Implement SA1314: TypeParameterNamesMustBeginWithT

### ISSUE THREAD

**Issue by Przemyslaw-W** [DotNetAnalyzers/StyleCopAnalyzers#739]
I'd like to propose new naming rule for generic parameters. Name should start with "T", second character (if it exists) should be upper case letter or digit. AFAIK Whole BCL follows this convention. 

Few valid names: "T", "T1", "TKey", "TValue" 

Few invalid names: "t", "Tkey", "Key" 

This rule was originally proposed by Andy Reeves here:
http://stylecop.codeplex.com/workitem/6891

**Comment by sharwell** [comment]
I think this makes sense. It's certainly in line with the existing rule that applies to interface names.

**Comment by GregReddick** [comment]
:+1:

**Comment by nbarbettini** [comment]
Grabbing this one
