### ISSUE TITLE
Rule proposal: Naming rule - disallow use of @ in identifiers

### ISSUE THREAD

**Issue by Przemyslaw-W** [DotNetAnalyzers/StyleCopAnalyzers#745]
Using a character like @ (and possibly any other special characters, if C# allows them) in a variable name is most commonly done to avoid conflicts with reserved keywords and such. For example, one might have a variable declaration like: 
string @string = string.Empty; 

Worse yet, as is currently the case in the StyleCop codebase itself, one might create several misleading side-effects with a single poor styling choice: 
CsToken @string = stringNode.Value; 
... @string.SomeCall() A reasonable individual might think here:
* Whoa, what application of the @ operator, aside from string-literal, am I not aware of here?
* Whoa, is that a method of the string class, or an extension method of string?

However, there is Always a more descriptive, or at least different, name one can use. Banning the usage of '@' in variable names prevents at least the above issues. In ALL cases, banning the usage of '@' in variable names serves only to clarify the code, and will never make code less clear as it will force non-conflicting names and can't be mistaken for another operator.

Originally posted by Karak http://stylecop.codeplex.com/workitem/6757

**Comment by Przemyslaw-W** [comment]
I personally don't have strong opinion regarding this. But I am closer to 'no' as @ is known and widely used way to escape keywords.

**Comment by sharwell** [comment]
I lean against this one. The clumsiness of using `@` is already a discouragement.

**Comment by AArnott** [comment]
:-1: 
Like @sharwell said, folks won't tend to do this unless they need to (and if they do, then they evidently would disapprove of the rule anyway). Sometimes you *need* to, and StyleCop shouldn't get in the way.

**Comment by sharwell** [comment]
I'm moving this to **wontfix** since two avid StyleCop users are leaning against it so far and it doesn't have any backers. If someone wants to advocate for this rule in the future, we can always reopen this to take a closer look.
