### ISSUE TITLE
Rule proposal - Spacing rule - Check indentation

### ISSUE THREAD

**Issue by Przemyslaw-W** [DotNetAnalyzers/StyleCopAnalyzers#749]
Stylecop doesn't check the indentation of lines. I think it should. 

There is a problem: lambda expressions. How should they be indented? I've seen AT LEAST three styles:
the same indent as line above: 
```
Action a = () => 
{ 
}; 
```
the same indent as line above + 1 additional indent
```
Action b = () => 
    { 
    }; 
```
indent with => operator + 1 additional indent
```
Action c = () => 
                   { 
                   }; 
```
(technically the third style is used with the "java notation" of curly brackets, and with "MS" Notation it isn't very beautiful): 
```
Action c = () => { 
                    }; 
```

For lambda expressions the VS by default "suggests" the second solution (if you write => and new line the new line is indented), but if you change the indentation the VS won't reformat that block. 

A similar "problem" is with switch/case+curly brackets as for example: switch (t) { case 1: { // } } 
In this situation the VS forcibly reformats the curly brackets using the "second style".

Originally posted by xanatos http://stylecop.codeplex.com/workitem/6792

follow up discussion:

andyr wrote Feb 4, 2011 at 11:51 AM
Jason, please comment and I'll fix accordingly.

xanatos wrote Feb 4, 2011 at 1:15 PM
When I say "Stylecop doesn't check the indentation of lines" I mean even the "standard" indentation, for example this is legit:
```
if (true)
{
func()
}
```
(where the func() isn't indented)

Everything else in the comment was about two "special" cases (lambda and switch).

andyr wrote Mar 15, 2011 at 5:32 PM
From Jason, "This would be a great new rule to have"

berntie wrote Jan 12, 2013 at 6:30 PM
I think this is a duplicate of http://stylecop.codeplex.com/workitem/7337. Please delete one of the two. If possible, add the votes of the deleted to the remaining item.

**Comment by Przemyslaw-W** [comment]
IMHO rules for indentation would be nice, especially around "gray area" - formatting lamdas and wrapped arguments. I personally align ```{``` for statement lambda to ```(``` in its parameters. This way it looks like embedded method.

On the other hand, I indent wrapped arguments as per "line above + one indent" rule

**Comment by sharwell** [comment]
I'm closing this rule, not because it's a bad idea but because it's too broad and doesn't present a specific rule which can be discussed and later implemented. I've already opened two new rules related to indentation; I encourage you (or anyone) to do the same if you feel strongly about some aspect.
