### ISSUE TITLE
Rule proposal: Readability rule - Require class name before static call

### ISSUE THREAD

**Issue by Przemyslaw-W** [DotNetAnalyzers/StyleCopAnalyzers#755]
If, in a method of a class/obect, I call another method, I have to do this:
```
this.AnotherMethod();
```
One of the reasons is that in this way the syntax completion activates and helps me. Another is to solve ambiguities. 

The question is: should the same be true for "static" methods/properties? 

So, for example, should I prefix the static method/property with the class/struct name?
```
MyObject.MyStaticMethod();
```
(in this way the syntax completion would activate, the same as this., and this would clearly mark my method/field/... as "static" in the eye of the observer. This would even solve the ambiguity between static fields and local fields with the same name) 

I think we should use the name of the "current" class as the prefix, like this:
```
    public class A1
    {
        public static void Method1()
        {   
        }
    }

    public class A2 : A1
    {
        public void MyMethod2()
        {
            A2.Method1();
        }
    }
```
This to "mimic" the use of this (and for another problem: if we used the name of the class where Method1 is defined, moving Method1 from A1 to A2 would break all)

Originally proposed by Xanatos http://stylecop.codeplex.com/workitem/6809

**Comment by Przemyslaw-W** [comment]
I vote no. It looks like this rule complements SA1101, but:
* SA1101 requires usage of this. So all not qualified calls are known to be static anyway
* it actively acts against usage of ```using static```

**Comment by sharwell** [comment]
I don't like it. There are cases where you *can't* prefix an item, such as invoking a static event.

**Comment by sharwell** [comment]
I'm moving this to **wontfix** since two users are leaning against it so far and it doesn't have any backers. If someone wants to advocate for this rule in the future, we can always reopen this to take a closer look.
