### ISSUE TITLE
SA1301: ElementMustBeginWithLowerCaseLetter

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#77]
http://www.stylecop.com/docs/SA1301.html

**Comment by johnkoerner** [comment]
The documentation states 

>There are currently no situations in which this rule will fire.

So that begs the question, do we need an analyzer for this?

**Comment by Przemyslaw-W** [comment]
In the original SC this was "placeholder" rule reserved for future use - so
that it is next to SA1300 in the list

2015-04-07 5:47 GMT+02:00 John Koerner <notifications@github.com>:

**Comment by pdelvo** [comment]
I would leave it in for completion sake. Just remove the todos, enable it by default (so it is maked as "done"), add a nocodefix attribute and that should be it.
