### ISSUE TITLE
SA1209 (UsingAliasDirectivesMustBePlacedAfterOtherUsingDirectives) efficiency improvement

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#776]
Currently SA1209 is implemented by registering a handler for using directives. This could be improved by instead registering a handler for compilation unit and namespaces, similar to the way SA1201 is implemented.

**Comment by vweijsters** [comment]
Maybe extend this with SA1208, SA1210, SA1211, since they are using similar constructions?

**Comment by sharwell** [comment]
Created issues #777, #778, and #779 for those.

**Comment by baks** [comment]
I recently worked on #777 and this looks similiar so if possible I would like to grab this one :+1:
