### ISSUE TITLE
SA1208 (SystemUsingDirectivesMustBePlacedBeforeOtherUsingDirectives) efficiency improvement

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#777]
Currently SA1208 is implemented by registering a handler for using directives. This could be improved by instead registering a handler for compilation unit and namespaces, similar to the way SA1201 is implemented.

**Comment by baks** [comment]
I could try do this and I'll also add some tests for SA1208 rule.

**Comment by sharwell** [comment]
Hi @baks, and welcome to the project.

I've removed the **up for grabs** tag; you can send a pull request any time. :+1: 

If you'd like me to make you the "Assignee" for the issue, you can accept my invitation to join the DotNetAnalyzers organization here on GitHub. :smile:

**Comment by baks** [comment]
@sharwell of course and thanks for invitation :+1:
