### ISSUE TITLE
SA1302: InterfaceNamesMustBeginWithI

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#78]
http://www.stylecop.com/docs/SA1302.html

**Comment by macpak** [comment]
grabbed

**Comment by macpak** [comment]
Can it be closed ? The implementation is merged (#357). We just need to add code fix (probably a separate issue ?).

**Comment by sharwell** [comment]
:bulb: If you add a line like `Fixed #xxx` to the description in your pull request, it will close the associated issue automatically when the pull request is merged. :+1:
