### ISSUE TITLE
SA1642SA1643CodeFixProvider fails (and crashes VS)

### ISSUE THREAD

**Issue by AArnott** [DotNetAnalyzers/StyleCopAnalyzers#780]
In a project with StyleCop.Analyzers.1.0.0-alpha005 installed, define this class:

```csharp
    internal abstract class CustomizableBlockSubscriberBase<TSource, TTarget, TSubscribedElement>
        where TSource : class
        where TTarget : class
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProjectBuildSnapshotService"/> class.
        /// </summary>
        protected CustomizableBlockSubscriberBase()
        {
        }
    }
```

Press Ctrl+. on the xml doc comment that gets a diagnostic for having a bad constructor message.

VS crashes, after throwing the exception below. Note that I have filed no less than 3 bugs with VS since we shouldn't be crashing anyway (including dotnet/roslyn#2496 and 2 more internally) but we should of course get StyleCop.Analyzers itself fixed as well.

> $exception	{"separatorToken"}	System.Exception {System.ArgumentException}
    Microsoft.CodeAnalysis.dll!Microsoft.CodeAnalysis.SeparatedSyntaxList<Microsoft.CodeAnalysis.CSharp.Syntax.TypeSyntax>.ReplaceSeparator(Microsoft.CodeAnalysis.SyntaxToken separatorToken, Microsoft.CodeAnalysis.SyntaxToken newSeparator) Line 529	C#
    StyleCop.Analyzers!StyleCop.Analyzers.DocumentationRules.SA1642SA1643CodeFixProvider.ParameterToArgumentListSyntax(Microsoft.CodeAnalysis.CSharp.Syntax.TypeParameterListSyntax typeParameters)	Unknown
    StyleCop.Analyzers!StyleCop.Analyzers.DocumentationRules.SA1642SA1643CodeFixProvider.BuildStandardText(Microsoft.CodeAnalysis.SyntaxToken identifier, Microsoft.CodeAnalysis.CSharp.Syntax.TypeParameterListSyntax typeParameters, string preText, string postText)	Unknown
    StyleCop.Analyzers!StyleCop.Analyzers.DocumentationRules.SA1642SA1643CodeFixProvider.GetTransformedDocumentAsync(Microsoft.CodeAnalysis.Document document, Microsoft.CodeAnalysis.SyntaxNode root, Microsoft.CodeAnalysis.CSharp.Syntax.XmlElementSyntax node)	Unknown
    StyleCop.Analyzers!StyleCop.Analyzers.DocumentationRules.SA1642SA1643CodeFixProvider.RegisterCodeFixesAsync.AnonymousMethod__0(System.Threading.CancellationToken token)	Unknown
    Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.CodeActions.CodeAction.DocumentChangeAction.GetChangedDocumentAsync(System.Threading.CancellationToken cancellationToken) Line 308	C#
    Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(System.Threading.CancellationToken cancellationToken) Line 111	C#
    Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(System.Threading.CancellationToken cancellationToken) Line 87	C#
    Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(System.Threading.CancellationToken cancellationToken) Line 102	C#
    Microsoft.CodeAnalysis.Workspaces.dll!Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(System.Threading.CancellationToken cancellationToken) Line 72	C#
    Microsoft.CodeAnalysis.EditorFeatures.dll!Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewOperationsAsync.AnonymousMethod__0()	C#
    mscorlib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.Task<System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.CodeActions.CodeActionOperation>>>.InnerInvoke() Line 680	C#
    mscorlib.dll!System.Threading.Tasks.Task.Execute() Line 2498	C#
    mscorlib.dll!System.Threading.Tasks.Task.ExecutionContextCallback(object obj) Line 2861	C#
    mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954	C#
    mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902	C#
    mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot) Line 2827	C#
    mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution) Line 2767	C#
    mscorlib.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() Line 2704	C#
    mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch() Line 820	C#
    mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() Line 1161	C#

**Comment by sharwell** [comment]
There is a very high likelihood that this is fixed by #609.

**Comment by sharwell** [comment]
Reported as a Roslyn bug and fixed by both working around the issue and adding a test that will alert us when we upgrade to a version of Roslyn which no longer suffers from the bug.

**Comment by AArnott** [comment]
Can you link to the Roslyn bug?

**Comment by sharwell** [comment]
I already did above :wink:

**Comment by AArnott** [comment]
Oh, right. whoops. I thought that was the bug [*I* had filed](roslyn/issues#2496) on another argument validation bug in that same method. But I see you filed this one and it tracks something different.
