### ISSUE TITLE
Local StyleCop builds should be identical to public builds

### ISSUE THREAD

**Issue by AArnott** [DotNetAnalyzers/StyleCopAnalyzers#793]
StyleCop.Analyzers on dev boxes builds to 1.0.0-dev while the publicly released builds take the form of 1.0.0-alpha000. This makes it difficult or impossible to make a fix locally and publish the package to some internal package store, repeatedly, and have the consuming projects track which private build they're using at the time.

One pattern that we use in some places internally at Microsoft that I think would be beneficial here is for the package versions to take this form:

1.0.0-pre-ga1f23cd3

The idea here is that the version spec includes the git commit id (after the -g for 'git') allowing folks to immediately identify the version of source code in git that went behind a build (even without producing tags for every single one) and most importantly, allows a local build to exactly reproduce what the public build will be if the commit is the same. 

We could of course make this more friendly to nuget upgrades by adding the alpha000 back:

1.0.0-alpha008-ga1f23cd3

But we'd need some file in SCC to name the alpha000 number being built so that anyone who builds the commit can reproduce the package without any special global properties, etc. When I've done this myself, my pattern is that the version.txt file will have 'alpha008' in it as soon as alpha007 ships. So that all subsequent builds claim to be alpha008 to match the next public release.

What do you think? If you agree, I can prepare a pull request to add this.

**Comment by vweijsters** [comment]
Sounds like a solid idea. There is a slim chance to have a collision on git commit id (assuming that the shorthand version is used), but for internal repositories that is not a problem. 

As the git commit id are not monotone increasing, you cannot simply grab the latest package from the package source, but again for internal repositories that should not pose a real problem. 

A potential fix would be to include a date/time stamp in the package version as well (in international format), but I'm not convinced that such a measure is really necessary.

**Comment by AArnott** [comment]
Thanks, @vweijsters 
The git commit id collision chance is negligible even for public repositories. The math on that [has been done](http://stackoverflow.com/a/29146396/46926) by the git community and generally accepted.

Yes, since the id's don't increase in alphanumeric order they alone can't answer the "which one is newer than another" question. And yes, for internal repositories at Microsoft so far it's tolerable as-is, although considering developing tools to solve that problem too. 

Adding any kind of timestamp in the package version destroys the reproducibility of it between dev and official builds. The reason this is so important in some scenarios is that if I produce a fix and plan to ship it, I can build it locally and then update another source tree to depend on it even before the official build comes out. I can push both the update and the dependency at once and be confident that the official build will produce the exact version that the other one needs to do nuget package restore. 

Is this relevant to this project? Yes. Because in adopting this project within several projects at Microsoft (quite possibly many, if I can persuade more folks to use it), we'll probably maintain a fork of stylecop.analyzers at least while it's still relatively young and growing fast so that we can use patched versions while we wait for the next alpha release to include those fixes. But we'll want our fork to match the official version as closely as possible so we'd rather the official project produce version specs the same way we would internally too.

**Comment by sharwell** [comment]
I'm still thinking about this, but wanted to add a few comments:

* For the assemblies themselves, the only difference is the `AssemblyInformationalVersion`, so this is not an issue with binding or strong names.
* Within the bounds of deterministic compilation (which the compiler doesn't support), if you check out a tag from this repository your build will be identical to the release corresponding to the tag. No other commit in the repository, for any tag, will do this.
* The release after a tag is functionally identical to the release, but uses the **-dev** suffix for the package. If you anticipate consuming intermediate builds (non-tagged builds), start with a build from this commit instead of a build from the tag.

**Comment by vweijsters** [comment]
@AArnott thank for the detailed explaination! It took me a few minutes to understand it all, but I see now that the timestamp stuff would indeed not work.

So I understand the issue correcty, when I say it has to do with NuGet package references in other projects, and not the binary stuff? I assume that the full package version (incl. dev suffix) used in the hint path within .csproj files is the main culprit. That would imply that if @sharwell was infinitely fast with producing official builds, the problem would not exist. Is this the correct line of reasoning?

**Comment by AArnott** [comment]
@vweijsters Yes, if we had a nuget release every day and all my pull requests were accepted same day, we probably wouldn't need this.
@sharwell Ya, I'm not worried at all about binary compatibility because nothing references the analyzer assembly. It's all about the nuget package dependency my projects take on "-dev" not meaning anything. I didn't realize until you mentioned it that you actually change the source code itself to produce your 'alpha006' build. That being the case, it would be impossible for me to maintain a fork with from which I could build and consume packages without dealing with merge conflicts or extra care to keep certain branches clean of my code changes or clean of my version file changes to avoid those conflicts. Whereas if the project itself always produced repeatable, and unique versions with each commit, the only touching of version.txt would be when you're about to release an official update.

**Comment by sharwell** [comment]
Would it be a working solution to publish AppVeyor builds to the [project feed](https://ci.appveyor.com/nuget/stylecopanalyzers-jqg4a6mt0hgj)? For this I would use the "build version" from AppVeyor to identify the build (e.g. you would have **1.0.565-dev** for [this build](https://ci.appveyor.com/project/sharwell/stylecopanalyzers/build/1.0.565)). Each time a commit is merged to the **master** branch, a new build would appear on that stream.

**Comment by AArnott** [comment]
That would certainly help, but it doesn't suffice. For example internally VS2015 post RC has already moved to a newer reference assembly for System.Collections.Immutable.dll so we have to have a private build of StyleCopAnalyzers until that version of VS goes public. I'll need to track the public version but still produce that same variation on it. AppVeyor on your repo won't help me with that.

**Comment by sharwell** [comment]
Please see my [detailed comment](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/pull/847#issuecomment-102915465) in the pull request associated with this issue for an explanation on closing the issue and marking it as **wontfix**.
