### ISSUE TITLE
SA1028 (CodeMustNotContainTrailingWhitespace) code fix does not support documentation comments

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#795]
This is a problem for the following reasons:

* Documentation comments are already analyzed, so warnings will be reported.
* The default smart indent implementation in Visual Studio for documentation comments includes trailing whitespace on new lines, as opposed to most other cases where virtual space is used to avoid these spaces.

**Comment by AArnott** [comment]
I don't yet understand the problem. We want trailing whitespace to be reported even in comments and doc comments, don't we?

**Comment by sharwell** [comment]
The problem is we are adding a new rule that is likely to trigger a large number of new warnings in existing projects, but we have not implemented the code fix for one particularly common case where the IDE itself is known to violate the rule (by inserting trailing whitespace in documentation comments). We need to provide a code fix that works within documentation comments at the same time we initially ship this analyzer.

While this could be seen as a bug or an enhancement, I marked it as a bug due to the number of people likely to be immediately affected by this and the amount of work it will save if we provide a fully-functional code fix for this case.

**Comment by AArnott** [comment]
I'm curious why you say the IDE itself violates the rule a lot. When I ran the rule in a decent sized codebase it only found 4 violations and they were all cases where *I* had added a space at the end of a sentence.

But regardless, yes a code fix for this is very valuable.

**Comment by AArnott** [comment]
I'm going to work on this today.
