### ISSUE TITLE
Move SA1028 (NoTrailingWhitespace) documentation to repository

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#798]
Currently the documentation for new rule SA1028 is located in the wiki. This file should be moved into the repository in the manner shown in #786, so users can more easily access it and pull requests can be submitted to update its content.

**Comment by AArnott** [comment]
Sorry for putting it in the wrong place. During the pull request someone directed me to another pull request saying "do it like this" and they were using the wiki.

**Comment by sharwell** [comment]
There wasn't a right or wrong place at the time. Most people use a wiki for it, but I've found that the wiki can be hard to maintain and is definitely harder for users to contribute to through a code review process. I just copied what you wrote there into the repository and then disabled the wiki so everything is clear. :+1:
