### ISSUE TITLE
SA1304: NonPrivateReadonlyFieldsMustBeginWithUpperCaseLetter

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#80]
http://www.stylecop.com/docs/SA1304.html

**Comment by macpak** [comment]
grabbed

**Comment by macpak** [comment]
Can it be closed ? The implementation is in #362. I think we just need code fix.

**Comment by sharwell** [comment]
Fixed in #362.
