### ISSUE TITLE
Implement SA1134 (AttributesMustNotShareLine)

### ISSUE THREAD

**Issue by vweijsters** [DotNetAnalyzers/StyleCopAnalyzers#809]
**Category:** ~~Layout~~ Readability
**Title:** Attribute must be on separate line
**Description:** C# allows attributes to be specified on the same line of code, like:
```C#
[Export] [Shared]
public class Foo
{
}
```
The form makes it more difficult to determine which attributes are present, especially when the attributes also have a (long) list op parameters. Each attribute should therefore be placed on its own line. 
```C#
[Export]
[Shared]
public class Foo
{
}
```

An exception to this rule would be inline attributes for parameters.

**Comment by sharwell** [comment]
This rule complements #805.

**Comment by Przemyslaw-W** [comment]
+1

**Comment by sharwell** [comment]
With 3 "+1" votes and no negative comments so far, I'm moving this forward but it remains blocked on #805.

**Comment by sharwell** [comment]
I changed this to be a **readability** rule as well, which seems in line with the other readability rules.

**Comment by vweijsters** [comment]
Grabbing this
