### ISSUE TITLE
SA1114 (Parameter list must follow declaration): Should ignore #pragma directives

### ISSUE THREAD

**Issue by oatkins** [DotNetAnalyzers/StyleCopAnalyzers#830]
The following code is *not* reported by legacy SC, but fails the new version of SA1114:

    using System;

    public class SomeOtherClass
    {
        private void SomeMethod()
        {
            this.SomeOtherMethod(
    #pragma warning disable 618
                    this.SomeObsoleteMethod());
    #pragma warning restore 618
        }

        [Obsolete("Don't use me!")]
        private int SomeObsoleteMethod()
        {
            return 0;
        }

        private void SomeOtherMethod(int someParameter)
        {
        }
    }

Lines that contain `#pragma` directives should generally be ignored by SC rules.

Warning 618 relates to the use of a member marked obsolete. The `#pragma` line can be moved to resolve the warning. However, it would be better not to have to move it. (Doing so might unintentionally suppress other errors.)

**Comment by macpak** [comment]
Ok, I will look at it.
