### ISSUE TITLE
<autogenerated/> not accepted as indicator for auto generated files

### ISSUE THREAD

**Issue by vweijsters** [DotNetAnalyzers/StyleCopAnalyzers#833]
A file starting with `// <autogenerated/>` is not accepted as an auto generated file by the '...HonorExclusions' extension methods. 

Stylecop was accepting both `<autogenerated/>` and `<auto-generated/>`.

**Comment by sharwell** [comment]
@AArnott @vweijsters Do we need this?

**Comment by AArnott** [comment]
Yes, [it's true](http://stylecop.codeplex.com/SourceControl/latest#Project/Src/AddIns/CSharp/Parser/FileHeader.cs). I'll send a pull request.
