### ISSUE TITLE
SX1309: FieldNamesMustBeginWithUnderscore

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#837]
This is the standard alternative rule to SA1309 (FieldNamesMustNotBeginWithUnderscore).

A violation of this rule occurs when a field name does not begin with an underscore. This rule only examines fields which are *all* of the following:

* `private`
* Instance (not `static`)
* Not `const`

**Comment by pakdev** [comment]
Would you accept a modification to your logic that excludes read-only fields as well? If not, could I add a setting to stylecop.json that would allow read-only fields to be excluded?

**Comment by vweijsters** [comment]
hi @pakdev, please create a new issue for your proposal, so that we can properly tag and track it.

**Comment by pakdev** [comment]
[Done](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2281)
