### ISSUE TITLE
Remove '*.g.cs' and '*.g.i.cs' from the list of files which are considered generated

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#851]
This issue relates to the exclusion of *particular* files from analysis according to their filenames (see #836). It specifically covers the following patterns:

* *.g.cs
* *.g.i.cs

The filename-based exclusion is not necessary because the code generators which produce these files include `<auto-generated>` in a comment at the top of the file.

**Comment by AArnott** [comment]
It makes sense that we can remove these. 
The only possible reason I can think of to remove them is that a filename check is faster than searching the document header for a substring inside it. But I think our design hinges on that header check being fast anyway, so it's probably a non-issue. I support your goal of reducing the list of filename patterns.

**Comment by sharwell** [comment]
For now, this exclusion has been removed. If it's reported as necessary in the future, we can easily add it back and we'll also have the advantage of having a record of the reasons each exclusion exists.
