### ISSUE TITLE
SA1612 (ElementParameterDocumentationMustMatchElementParameters) Does not take parameter order into account

### ISSUE THREAD

**Issue by ymor** [DotNetAnalyzers/StyleCopAnalyzers#867]
SA1612 (ElementParameterDocumentationMustMatchElementParameters) Is not checking the order of the param documentation is in the same order as the method parameters.

The following fails to report SA1612:	

    /// <summary>
    /// foo
    /// </summary>
    /// <param name="bar"></param>
    /// <param name="foo"></param>
    public bool Method(string foo, string bar)
    {
	    return true;
    }

**Comment by sharwell** [comment]
Definitely a bug! Thanks for taking the time to report it. :+1:

**Comment by pdelvo** [comment]
Im grabbing this.
