### ISSUE TITLE
stylecop configure use of rules

### ISSUE THREAD

**Issue by ltd65** [DotNetAnalyzers/StyleCopAnalyzers#868]
Comming from the original stylecop I am used to configure if rules should be used or not within a settings file. So far I only see the posibility to disable rules project global via annotations in a project global c# file.
Is there no settings file anymore or am I too blind to find it?
Other than that I am glad that "stylecop" is back.

**Comment by vweijsters** [comment]
You can create a rule set file (From the menu: `File > New > File...`, pick the `Code Analysis Rule Set`) and use this to define a set of analyzer that you want active. You can then reference this file from the different projects in your solution, or define the behavior via the solution properties.

**Comment by ltd65** [comment]
Thanks. That was exactly what I was looking for.

**Comment by sharwell** [comment]
@ltd65 If you have suggestions for improving the user documentation surrounding this issue, they would be welcome. :+1:
