### ISSUE TITLE
Proposal: Settings file

### ISSUE THREAD

**Issue by vweijsters** [DotNetAnalyzers/StyleCopAnalyzers#892]
### Scope
This issue describes a proposal for settings files for the StyleCopAnalyzers analyzers. It is similar to the original StyleCop settings files, but deliberately different, to signify the differences between the two projects. 

The settings files for the StyleCopAnalyzers analyzers will only feature settings that can be used to configure certain diagnostics. There will be no mechanism to disable analyzers, the standard rule set mechanism from Visual Studio can be used for that.

The settings file for the StyleCopAnalyzers will be stored using the JSON data-interchange format.

### Example
The example below shows the content of a possible settings file. This example also shows all currently identified settings.

```JSON
{
  "mergeMode" : "parentFolder",
  "settings" :
  {
    "documentationRules" :
    {
      "companyName" : "FooBar Inc.",
      "copyrightText" : "Copyright (c) 2015 FooBar Inc. All rights reserved.",
      "ignorePrivateDeclarations" : true,
      "ignoreInternalDeclarations" : true,
      "ignoreFields" : true
    }
  }
}
```
### Naming
The settings file shall be named `Settings.StyleCopAnalyzers`. This name was chosen to be similar to the original StyleCop name, to indicate to developers its intended use, but also different to signify that the contents are not compatible.

### Locating the settings file
When analyzing a source file, the analyzer will look in the folder where the source file resides for a `Settings.StyleCopAnalyzers` file. If no settings file is present, the parent folder is searched for a settings file. If no settings file is present there, the parent of the parent folder is searched, and so on.
(See the section on merging for more details)

If no settings files are found, the default settings are used.

### Validation
The settings file shall be validated as being proper JSON and a diagnostic must be produced to signal an invalid settings file. Whenever an invalid settings file is encountered, all valid settings from already parsed (and merged) settings files must be retained. The merge process must stop immediately when an invalid settings file is encountered.

If the settings file contains unknown name/value pairs, they shall be silently ignored.

### Merging
To allow reuse of settings files, it is useful to have a merging scheme available, where multiple settings files will be combined into a single set of settings. When merging the current set of  settings with another settings file, the current set of settings will override any settings defined in the file being merged.

The proposed merge scheme is similar to the one that StyleCop is using. It will however not have a 'master' settings file in the installation folder.

The merge process will be controlled by the optional `<merge>` element within each settings file. One (and only one) of three merge modes can be specified:
* Do not merge this settings file. This will stop the merge process. 
```JSON
  "mergeMode" : "none"
```
* Merge with a settings file present in a parent folder. This does not have to be the direct parent folder, the entire tree towards the root of the filesystem is traversed until a settings file is found. This is the default option, if no merge element is specified.
```JSON
  "mergeMode" : "parentFolder"
```
* Merge with a specified settings file, and continue the merge process from there. 
```JSON
  "mergeMode" : "file"
  "mergeFile" : "D:\\GitHub\\Settings.StyleCopAnalyzers"
```

### Related issues
This would be used for implementing the following issues: #156, #161, and #789.
It is related to #410 and #422
It would also influence pull request #832

**Comment by sharwell** [comment]
Between XML and JSON, I think JSON is the way to go. It gets rid of the problems typically associated with versioning and reduces our overall maintenance cost in the long term.

**Comment by vweijsters** [comment]
JSON would be ok with me, I just picked XML because the StyleCop stuff was in XML.
I would say we use [Json.NET](https://github.com/JamesNK/Newtonsoft.Json/) for reading the file.
I'll update the proposal to use JSON later.

**Comment by vweijsters** [comment]
Given the limited amount of available settings, it might also be wise to leave out the merge mechanism for now, as that will be quite some work and have an impact on performance.

**Comment by sharwell** [comment]
* I think we should name the file **stylecop.json**. The extension ensures it will open in the correct mode for editing, and also matches the naming used by **project.json**.

* JSON is easily extended in the future. For now, let's omit the ability to merge multiple configurations.

* Locating the settings file should be done by way of the `AdditionalFiles` functionality in Roslyn. This supports both regular and linked documents.

**Comment by sharwell** [comment]
For the initial implementation, let's make `companyName` the only setting. The copyright text would read as follows:

> Copyright (c) {companyName}. All rights reserved.

**Comment by vweijsters** [comment]
I agree with the comments above. I'll update #893 to reflect that.

**Comment by otac0n** [comment]
Considering you are planning on using CodeAnalysis settings files, I would also consider using the `<CodeAnalysisDictionary Include="CustomDictionary.xml" />` for things like Hungarian notation and spelling.  Maintaining two dictionaries will not be fun.

**Comment by otac0n** [comment]
> Copyright (c) {companyName}. All rights reserved.

This doesn't really work for Open Source.  e.g.

    // -----------------------------------------------------------------------
    // <copyright file="Program.cs" company="(none)">
    //   Copyright © 2015 John Gietzen.  All Rights Reserved.
    //   This source is subject to the MIT license.
    //   Please see license.md for more information.
    // </copyright>
    // -----------------------------------------------------------------------

I think you should allow custom copyright text.  I want to require MIT licensing on some of my files, I want to require the ASCII copyright symbol, and I don't want a company name.

**Comment by sharwell** [comment]
> Maintaining two dictionaries will not be fun.

The spelling rule was permanently disabled as part of #1057. The Hungarian notation rule has not yet been implemented, but I still lean towards using a blacklist instead of a whitelist to avoid false positives. Either way, these prefixes would not be duplicated in a spelling dictionary.

> This doesn't really work for Open Source

#1243 deals with this.

**Comment by otac0n** [comment]
In light of #1243, why include `companyName` in the JSON format?

**Comment by sharwell** [comment]
It's the minimum piece of configuration necessary to support all of the file header rules, and is particularly useful for SA1641 (FileHeaderCompanyNameTextMustMatch).

**Comment by alaendle** [comment]
@sharwell How does the analyzer is locating the settings file? Can I share the settings across multiple projects/solutions. With the old StyleCop.settings this could easily be done by just putting the file in the root of the source code repository.

**Comment by pdelvo** [comment]
The path to the settings file is written in the [csproj file](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers/StyleCop.Analyzers.csproj#L400). So you can point it to a central location and share it across projects. You could also share it across multiple solutions but if those solutions are not in the same repository I dont think that this is a good idea.

**Comment by alaendle** [comment]
@pdelvo If already seen this possibility, but I find this somehow inconvenient to add the configuration file to more than 300 projects in our repository. So thought it might be wise to have some fallback as described in this proposal. It also seems to be more "convention over configuration" like if I could just place a file in the root folder and everything is configured ;-)

**Comment by sharwell** [comment]
@alaendle Currently there is only one "official" way to add an additional file into the build process for an analyzer. However, the Roslyn team is reconsidering this approach *right now*. If you are interested in additional ways to add a common file into the build for multiple projects, I highly recommend you provide feedback in dotnet/roslyn#5096, since the solution derived from that issue is almost certainly the one you will be stuck using. :smile:
