### ISSUE TITLE
SA1602 is this intended or a bug

### ISSUE THREAD

**Issue by ltd65** [DotNetAnalyzers/StyleCopAnalyzers#909]
When looking at the following code I get a SA1602.
Not sure if that is intended or not.
I think as this is a private element which does not require a xml documentation the elements should also not need a documentation.

private enum AckError
{
  AckerrOk = 0,
  AckerrInvalidCounter,
  AckerrPackageTooShort
}

**Comment by ltd65** [comment]
Can be ignored. Too late I found that there is already a report about this.

**Comment by sharwell** [comment]
Either way, welcome to the project! :+1: :smile:
