### ISSUE TITLE
SA1402: FileMayOnlyContainASingleClass

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#91]
http://www.stylecop.com/docs/SA1402.html

**Comment by pdelvo** [comment]
grabbed.

The diagnostic also enforces the file name to match the class name. If the class is called 'Foo' should file names like Foo.bar.cs be allowed? This pattern is ofden used when a partial class is split up into multiple files

**Comment by sharwell** [comment]
I wouldn't check the file name itself as part of this diagnostic. That feature could be implemented as another diagnostic.

**Comment by pdelvo** [comment]
I thought so too. I implemented it but it would make much more sense to split it. I will do that

**Comment by sharwell** [comment]
For the name check, see DotNetAnalyzers/Proposals#13.
