### ISSUE TITLE
New rule proposal: Non-private elements must be documented

### ISSUE THREAD

**Issue by oatkins** [DotNetAnalyzers/StyleCopAnalyzers#912]
This is a follow-up to discussion on #832.

The proposal is for a rule that is the equivalent of SA1600, SA1602 and SA1602 for non-private, non-public elements only.

This is the equivalent of [CS1591](https://msdn.microsoft.com/en-us/library/zk18c1w9.aspx) but for non-private, non-public elements.

The existing SA160x rules will continue to report violations for elements with *any* visibility, unless the same violation is reported by this new rule or CS1591. This will require modifying the SA160x rules to check whether CS1591 and this new rule is enabled.

**Comment by sharwell** [comment]
I don't think all the details of this rue have been finalized (in particular the relation between this rule and CS1591 when one or the other is disabled), but overall this is a big :+1: from me. I believe it provides a meaningful "stepping stone" for people working to increase the overall documentation in their product.

**Comment by sharwell** [comment]
Addressed by a configuration approach in #1278.
