### ISSUE TITLE
SA1405: DebugAssertMustProvideMessageText

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#94]
http://www.stylecop.com/docs/SA1405.html

**Comment by pdelvo** [comment]
grabbed

**Comment by sharwell** [comment]
:sunglasses: Thanks for working on so many of these. I'm still on vacation (or "staycation" :expressionless:) but I'm trying to put in a few minutes here and there to review your contributions.

**Comment by pdelvo** [comment]
No problem. I just think that this is a very cool project I like to contribute to a bit. Unfortunatly starting next week I will not have as much time because I have to get back studying
