### ISSUE TITLE
Command line tool to run StyleCopAnalyzers on a solution

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#952]
It would be nice to have a command line utility that runs the StyleCopAnalyzers analyzers on a solution (code fixes considered later).

```
StyleCopTester [options] <Solution>
```

By default, all analyzers which are enabled by default run. The following options are avaliable for `[options]`:

| Option | Meaning |
| --- | --- |
| `/all` | Run all StyleCopAnalyzers analyzers, including ones that are disabled by default |
| `/id:<id>` | Enable analyzer with diagnostic ID `<id>` (when this is specified, only this analyzer is enabled) |

:memo: A primary purpose of this tool is testing performance with both the sampling and instrumenting profilers. The Test Explorer in Visual Studio 2015 does not currently provide enough ability to configure profiling methods for unit tests, and running inside the IDE introduces significant variance due to the editor environment, hence the need to create this as a command line tool.

**Comment by pdelvo** [comment]
I thought this was already assigned to me. *grabbed*
