### ISSUE TITLE
SA1003 should not be reported for operator ++ when followed by a closing bracket

### ISSUE THREAD

**Issue by oatkins** [DotNetAnalyzers/StyleCopAnalyzers#955]
The `i++` wrongly has SA1003 reported in the following code:

    for (int i = 0; i < this.OutputFiles.Length; i++)
    {
    }

**Comment by vweijsters** [comment]
Grabbing this

**Comment by sharwell** [comment]
@vweijsters Assigned, and marked for the upcoming release because it would be a pretty major annoyance if this bug made its way into the wild. :smile:
