### ISSUE TITLE
SA1001 reported for multidimensional array declaration

### ISSUE THREAD

**Issue by roadz99** [DotNetAnalyzers/StyleCopAnalyzers#958]
Declaring a multidimensional array raises SA1001 with seemingly no valid way to get rid of the warning. Old StyleCop accepts the following:

byte[,] myArray;

Adding the following unit tests show the error, but I'm not sure how to fix it.

        [Fact]
        public async Task TestCommaFollowedBySquareBracketInArrayDeclAsync()
        {
            string statement = @"int[,] myArray";
            await this.TestCommaInStatementOrDeclAsync(statement, EmptyDiagnosticResults, statement).ConfigureAwait(false);
        }

        [Fact]
        public async Task TestSpaceBeforeCommaFollowedBySquareBracketInArrayDeclAsync()
        {
            string statement = @"int[, ,] myArray";
            string fixedStatement = @"int[,,] myArray";

            DiagnosticResult expected = this.CSharpDiagnostic().WithArguments(" not", "preceded").WithLocation(7, 41);

            await this.TestCommaInStatementOrDeclAsync(statement, expected, fixedStatement).ConfigureAwait(false);
        }

**Comment by pdelvo** [comment]
The if statement in SA1001CommasMustBeSpacedCorrectly.cs line 90 should have another exception if the next token is a CloseBracketToken. Then we dont want to enforce a whitespace. @roadz99 Do you want to fix this?

**Comment by roadz99** [comment]
Will do. Thanks.

**Comment by pdelvo** [comment]
In the code fix provider line 77 you have to make the same change. Otherwise your second test will fail

**Comment by pdelvo** [comment]
This issue can be closed
