### ISSUE TITLE
Special case SA1001 for multi-dimensional array declarations

### ISSUE THREAD

**Issue by grokys** [DotNetAnalyzers/StyleCopAnalyzers#966]
Currently SA1001 flags `int[,]` as requiring a space after the comma. This shouldn't be required in this case. 

This is already a special case for `typeof(Func<,,,>)`. It would make sense to do the same thing for `int[,,,]`.

**Comment by pdelvo** [comment]
This bug has been fixed yesterday with #960.

**Comment by grokys** [comment]
Oops, didn't see that. Thanks!
