### ISSUE TITLE
SA1600: Auto-create documentation for overridden/interface impl members.

### ISSUE THREAD

**Issue by grokys** [DotNetAnalyzers/StyleCopAnalyzers#968]
When SA1600 detects no documentation for an overridden member or a member defined in an interface, it could provide a code fix to copy the documentation for the member from the base class or interface.

Particularly when implementing interfaces i end up doing a lot of copy/pasing (implementing collection interfaces arrgh :ambulance:).

These could be wrapped in `<placeholder>`.

**Comment by JohanLarsson** [comment]
Nice.

**Comment by vweijsters** [comment]
:+1: Good suggestion

I would prefer it without the `<placeholder>` tag, as in most cases the copied documentation is correct and it should not have to be changed.

It would be nice if IntelliSense would support `<inheritdoc/>`, but until that happens, having a code fix for copying the documentation is the next best thing.

**Comment by sharwell** [comment]
I disagree with copying the documentation for the following reasons:

1. Copied documentation is more likely to become incomplete and/or incorrect over time. Changes made to documentation at the interface level are not automatically propagated without `<inheritdoc/>`.
2. Copied documentation requires more effort to read during development. Users need to look at both the class documentation and the inherited documentation to ensure they are consistent, and to understand the differences (if any) between them.
3. Sandcastle Help File Builder supports rewriting the XML file produced by the C# compiler to replace `<inheritdoc/>` tags in the documentation with the actual inherited documentation. Last year, an "IntelliSense-only" mode was added to that tool which disables the full documentation output generation if this is the only feature you need.

For documenting methods which override or implement another member, my vote is in favor of adding an `<inheritdoc/>` comment, whether or not the other member is currently documented. We can then continue to put pressure on issues like dotnet/roslyn#67 or work to expand SHFB's editor extensions to augment QuickInfo and Signature Help functionality to expand these tags automatically while working in Visual Studio.

**Comment by vweijsters** [comment]
> Copied documentation requires more effort to read during development. Users need to look at both the class documentation and the inherited documentation to ensure they are consistent, and to understand the differences (if any) between them.

This seems like a candidate for an analyzer, regardless of what we do with this issue

**Comment by sharwell** [comment]
> This seems like a candidate for an analyzer, regardless of what we do with this issue

Differences in documentation are sometime desired. I would prefer to not have to suppress a warning every time I override documentation to add additional information. :smile:

**Comment by vweijsters** [comment]
Good point. Guess I'm usually too lazy to do stuff like that :wink:

**Comment by grokys** [comment]
FWIW after reading @sharwell's thoughts, I agree with him.
