### ISSUE TITLE
SA1008 (Opening parenthesis must not be preceded by a space) triggered after named parameter

### ISSUE THREAD

**Issue by Noryoko** [DotNetAnalyzers/StyleCopAnalyzers#973]
example:

string.Concat(arg0: "test", arg1: ("A" + "B") + "C");

**Comment by sharwell** [comment]
Hi @Noryoko! Thank you for taking the time to try out this project and report the issue. I've labeled this as **up for grabs** for now; if you'd like to try getting your hands dirty (to fix it), just let us know. Otherwise one of the regulars will pick it up. :+1:

**Comment by Noryoko** [comment]
I can work on this over the weekend. Seems like a good starter.

**Comment by sharwell** [comment]
:+1: I sent you an invitation to join the [DotNetAnalyzers](https://github.com/DotNetAnalyzers) organization, which will allow be to assign the issue to you. Feel free to ask questions here or in Gitter if you get stuck.

**Comment by Noryoko** [comment]
Thanks! This should make for an interesting weekend.
