### ISSUE TITLE
SA1009 (ClosingParenthesisMustBeSpacedCorrectly) fails with any method declaration

### ISSUE THREAD

**Issue by roadz99** [DotNetAnalyzers/StyleCopAnalyzers#974]
Sample code fails unless you add a trailing space after the closing parenthesis

    using System;

    public class Foo
    {
        public void Method()
        {
        }
    }

**Comment by sharwell** [comment]
I marked this **up for grabs**. Did you want to work on it? :smile:

**Comment by roadz99** [comment]
There is no test class for this rule so I'm a little scared to change it!

**Comment by sharwell** [comment]
You could fix #194. :smile:

**Comment by Maxwe11** [comment]
I also saw this earlier but was confused because [this diagnostic disabled](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/StyleCop.Analyzers/StyleCop.Analyzers/SpacingRules/SA1009ClosingParenthesisMustBeSpacedCorrectly.cs#L37).

**Comment by sharwell** [comment]
@Maxwe11 the disabled diagnostics are enabled in debug builds, and you can also enable them manually (via ruleset files and/or the Code Analysis UI).

**Comment by roadz99** [comment]
I'll take this one too. Looks like a simple fix but I'll try to add a good number of unit tests too.
