### ISSUE TITLE
Rename 'bracket' to 'brace' when referring to { and }

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#989]
StyleCop generally refers to `{` and `}` as "curly brackets". However, Roslyn in general refers to these as "curly braces". In my experience (which is admittedly biased by working in parsing for so long), braces seems to be the more widely used term.

I propose changing all uses (code and documentation) of 'bracket' to 'brace' when referring to curly braces.

**Comment by Maxwe11** [comment]
:+1: for consistency with Roslyn

**Comment by vweijsters** [comment]
:+1:

**Comment by EdwinEngelen** [comment]
:+1: I almost never use the term 'bracket'. Let's use the Roslyn name.

**Comment by GregReddick** [comment]
:+1:
