### ISSUE TITLE
New rule proposal: Comments must not share lines

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#993]
**Category:** Readability
**Rule:** Comments must not share lines
**Description:** A line comment must not appear on the same line as non-whitespace tokens.
**Rationale:** Comments appearing at the end of a line containing code make it burdensome to deal with wrapping in both the commented code and inside the comment text itself, and it's especially inconvenient when you later want to move the comment before the line to deal with this. Comments on lines by themselves are easier to read, easier to maintain, and are least likely to interfere with analysis and code fixes.

:memo: This was split from #992.

**Comment by vweijsters** [comment]
:+1:

**Comment by alxyr** [comment]
This rule would deny the ability to annotate lists like this:
```C#
dataStore.Select(
	"Field1",	// for header
	"Field2",	// for footer
	"Field3",	// for summary
	"Field4");	// for summary
```
Of course, I would prefer to write it like this:
```C#
dataStore.Select(
	// for header
	"Field1",
	// for footer
	"Field2",
	// for summary
	"Field3",
	// for summary
	"Field4");
```
but this is denied by SA1114:ParameterListMustFollowDeclaration, SA1115:ParameterMustFollowComma, and SA1515:SingleLineCommentMustBePrecededByBlankLine.

**Comment by sharwell** [comment]
@alxyr There are two better solutions for this. The first is preferred when available because it results in a compile-time error if your are mistaken about the parameters.

Named parameters:

```csharp
dataStore.Select(
    header: "Field1",
    footer: "Field2",
    summary1: "Field3",
    summary2: "Field4");
```

Named constants:

```csharp
string headerField = "Field1";
string footerField = "Field2";
string summaryField1 = "Field3";
string summaryField2 = "Field4";
dataStore.Select(
    headerField,
    footerField,
    summaryField1,
    summaryField2);
```

**Comment by alxyr** [comment]
In my example, the purpose of the annotations is to explain *why* we included a field in the select list. The signature of the Select method is `Select(params string[] fields)`.

A better example would be:
```C#
var fieldsToSelect = new string[]
{
    // for header
    "Field1",
    // for footer
    "Field2",
    // for summary
    "Field3",
    // for summary
    "Field4"
};

dataStoreSelect(fieldsToSelect);
```
Now we have only SA1515:SingleLineCommentMustBePrecededByBlankLine and, to get rid of this warning, we have to insert extra blank lines which looks somewhat unusual:
```C#
var fieldsToSelect = new string[]
{
    // for header
    "Field1",

    // for footer
    "Field2",

    // for summary
    "Field3",

    // for summary
    "Field4"
};

dataStoreSelect(fieldsToSelect);
```

**Comment by GregReddick** [comment]
:+1: I'm fine with there being no exceptions. The SA1515 requirement is just fine in the initialization of array in alxyr's example.

**Comment by sharwell** [comment]
Closing this in favor of adding an option to **stylecop.json** to control the behavior of the existing rule.
