### ISSUE TITLE
Proposal: Permanently disable rule SA1109

### ISSUE THREAD

**Issue by sharwell** [DotNetAnalyzers/StyleCopAnalyzers#998]
All violations of rule SA1109 (BlockStatementsMustNotContainEmbeddedRegions) are also violations of rule SA1123 (DoNotPlaceRegionsWithinElements). I propose disabling SA1109 the same way we disabled SA1126 (in #997) for the following reasons:

1. Rule SA1109 is a subset of another rule; disabling the rule still leaves users with a warning *and* a code fix for less computational work.
2. Violations of SA1109 are rare; special-casing this rule is unlikely to ever provide significant benefits to users.

**Comment by Noryoko** [comment]
:+1:

**Comment by pdelvo** [comment]
:+1

**Comment by JohanLarsson** [comment]
:+1:
